### ISSUE TITLE
Cannot display PDFs

### ISSUE THREAD

**Issue by ssantichaivekin** [James-Yu/LaTeX-Workshop#1142]
**Describe the bug**
I cannot view any pdfs on latex workshop. The link provided (supposedly by pdf.js) also did not work. The pdf opens just fine in other apps. It worked yesterday, Jan 23.

**To Reproduce**
Open pdf in vscose using latex workshop extension, or, while on a tex file, open a pdf preview.

**Expected behavior**
Display a pdf.

**Logs**
Extension:
```
[09:02:40] Initializing LaTeX Workshop.
[09:02:40] Creating LaTeX Workshop http and websocket server.
[09:02:40] LaTeX Workshop initialized.
[09:02:40] Found root file from active editor: /Users/santisantichaivekin/Desktop/college/Discrete Math/tex/math55-hw1-list-and-sets.tex
[09:02:40] Root file changed from: undefined. Find all dependencies.
[09:02:40] Instatiating new file watcher for /Users/santisantichaivekin/Desktop/college/Discrete Math/tex/math55-hw1-list-and-sets.tex
[09:02:40] Parsing /Users/santisantichaivekin/Desktop/college/Discrete Math/tex/math55-hw1-list-and-sets.tex
[09:02:40] Server created on 127.0.0.1:50155
[09:02:40] Snippet data loaded.
[09:02:40] LaTeX Workshop version: 5.21.0
[09:02:42] VIEW command invoked.
[09:02:42] Found root file from active editor: /Users/santisantichaivekin/Desktop/college/Discrete Math/tex/math55-hw1-list-and-sets.tex
[09:02:42] Root file remains unchanged from: /Users/santisantichaivekin/Desktop/college/Discrete Math/tex/math55-hw1-list-and-sets.tex.
[09:02:42] Serving PDF file at http://127.0.0.1:50155/viewer.html?file=/pdf:%25252FUsers%25252Fsantisantichaivekin%25252FDesktop%25252Fcollege%25252FDiscrete%252520Math%25252Ftex%25252Fmath55-hw1-list-and-sets.pdf
[09:02:42] Open PDF tab for /Users/santisantichaivekin/Desktop/college/Discrete Math/tex/math55-hw1-list-and-sets.pdf
```

Developer JS Console:
Here thing looks more sketchy. I think the main problems are the `Cannot read property 'typeset' of undefined` and the `cannot find module tough-cookie` error.
```js
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3268 [Extension Host] debugger listening on port 35612
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3266 Extension Host
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3266 Debugger listening on ws://127.0.0.1:35612/d5f7de12-8eb2-4cf8-b00f-8586f51cec77
For help see https://nodejs.org/en/docs/inspector

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1504  INFO no standard startup: panel is active
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] rejected promise not handled within 1 second
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:303
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5725 [James-Yu.latex-workshop]Cannot find module 'tough-cookie'
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5725
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5725 Error: Cannot find module 'tough-cookie'
	at Function.Module._resolveFilename (module.js:543:15)
	at Function.Module._load (module.js:473:25)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:767:268)
	at Function.t.getExtensionPathIndex.then.s._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:538)
	at Function.t.getExtensionPathIndex.then.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:692:883)
	at Module.require (module.js:586:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:738)
	at Object.<anonymous> (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/node_modules/jsdom/lib/api.js:5:21)
	at Object.<anonymous> (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/node_modules/jsdom/lib/api.js:353:3)
	at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:963)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:767:268)
	at Function.t.getExtensionPathIndex.then.s._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:538)
	at Function.t.getExtensionPathIndex.then.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:692:883)
	at Module.require (module.js:586:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:738)
	at Object.<anonymous> (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/node_modules/mathjax-node/lib/main.js:33:13)
	at Object.<anonymous> (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/node_modules/mathjax-node/lib/main.js:995:3)
	at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:963)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:767:268)
	at Function.t.getExtensionPathIndex.then.s._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:538)
	at Function.t.getExtensionPathIndex.then.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:692:883)
	at Module.require (module.js:586:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:738)
	at Object.module.exports.Object.defineProperty.value (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/out/src/main.js:371:173689)
	at n (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/out/src/main.js:1:279)
	at module.exports.t.HoverProvider.constructor.Promise.resolve.then (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/out/src/main.js:371:161214)
	at <anonymous>
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5725
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5725 [James-Yu.latex-workshop]Cannot read property 'typeset' of undefined
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5725
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5725 TypeError: Cannot read property 'typeset' of undefined
	at module.exports.t.HoverProvider.<anonymous> (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/out/src/main.js:371:164300)
	at Generator.next (<anonymous>)
	at module.exports.r (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/out/src/main.js:371:160987)
	at new Promise (<anonymous>)
	at module.exports.r (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/out/src/main.js:371:160764)
	at module.exports.t.HoverProvider.provideHoverOnTex (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/out/src/main.js:371:164098)
	at module.exports.t.HoverProvider.provideHover.Promise (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/out/src/main.js:371:161862)
	at new Promise (<anonymous>)
	at module.exports.t.HoverProvider.provideHover (/Users/santisantichaivekin/.vscode/extensions/james-yu.latex-workshop-5.21.0/out/src/main.js:371:161592)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:554:595
	at t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:141:941)
	at new Promise (<anonymous>)
	at Object.t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:141:909)
	at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:554:554)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:570:950
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:567:513)
	at e.$provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:570:912)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:60)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)
	at Socket.n._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Screenshots**
<img width="601" alt="screen shot 2019-01-24 at 9 10 38 am" src="https://user-images.githubusercontent.com/19219105/51695447-edc38200-1fb7-11e9-8692-6af03efc02b0.png">

**Desktop:**
 - OS: Mojave 10.14.2
 - VS Code version: November 2018 (version 1.30)
 - Extension version: [5.21.0] - 2019-01-24

**Comment by ssantichaivekin** [comment]
Doing so solves the problem.

**Comment by mskamara** [comment]
I can't see any PDF at all and I keep getting this message:

[10:35:59] Initializing LaTeX Workshop.
[10:35:59] Cannot run pdflatex to determine if we are using MiKTeX
[10:35:59] Creating LaTeX Workshop http and websocket server.
[10:35:59] LaTeX Workshop initialized.
[10:36:05] Server created on 127.0.0.1:51306
[10:36:05] Snippet data loaded.
[10:36:05] LaTeX Workshop version: 8.2.0
[10:36:11] BUILD command invoked.
[10:36:11] Cannot find LaTeX root file.
[10:36:13] VIEW command invoked.
[10:36:13] Active document is not a TeX file.
[10:36:19] Found root file from active editor: c:\Users\Panasonic\Documents\Test2.tex
[10:36:19] Root file changed from: undefined to c:\Users\Panasonic\Documents\Test2.tex. Find all dependencies.
[10:36:19] Instantiating a new file watcher for c:\Users\Panasonic\Documents\Test2.tex
[10:36:19] Creating file watcher for .bib files.
[10:36:19] Parsing c:\Users\Panasonic\Documents\Test2.tex
[10:36:19] Adding c:\Users\Panasonic\Documents\Test2.tex to file watcher.
[10:36:27] VIEW command invoked with mode: file:///c%3A/Users/Panasonic/Documents/Test2.tex.
[10:36:27] Found root file from active editor: c:\Users\Panasonic\Documents\Test2.tex
[10:36:27] Root file remains unchanged from: c:\Users\Panasonic\Documents\Test2.tex.
[10:36:27] Cannot find PDF file c:\Users\Panasonic\Documents\Test2.pdf
[10:36:31] VIEW command invoked with mode: file:///c%3A/Users/Panasonic/Documents/Test2.tex.
[10:36:31] Found root file from active editor: c:\Users\Panasonic\Documents\Test2.tex
[10:36:31] Root file remains unchanged from: c:\Users\Panasonic\Documents\Test2.tex.
[10:36:31] Cannot find PDF file c:\Users\Panasonic\Documents\Test2.pdf

**Comment by mskamara** [comment]
I have reinstalled the extension and it's the same problem.

**Comment by dwrh** [comment]
Same problem
Have removed the extension files three times - no change.
