### ISSUE TITLE
Add ability to jump to cursor position

### ISSUE THREAD

**Issue by Zaph-x** [James-Yu/LaTeX-Workshop#1304]
**Is your feature request related to a problem? Please describe.**
When writing long research papers, it is frustrating having to find your way back to the segment you were working on. This happens to me when I need to check something I have written somewhere else in my LaTeX document.

**Describe the solution you'd like**
When a build has finished, it would be nice to be able to jump to the location of the cursor, in the PDF, when viewing it in the VSCode tab. It would also be neat to have the feature, but in reverse, where you click twice on a segment in the PDF, and VSCode jumps to the location of that segment. Overleaf (An online LaTeX editor) already does this, but it would be nice to see it in LaTeX Workshop as well. This should also work accross multiple tex files.

**Describe alternatives you've considered**
If it is not possible to jump FROM a location in the PDF it would at least be nice to jump TO a location in the PDF.

**Additional context**

**Comment by James-Yu** [comment]
Try ctrl+click

**Comment by James-Yu** [comment]
Please post your log

**Comment by Spenhouet** [comment]
Which log? And after I tried `ctrl + click`?

**Comment by Spenhouet** [comment]
I did take a look at the LaTeX Workshop log.

On performing a `ctrl + click` in a `.tex` file just nothing happens. It doesn't jump to the position in the PDF and it doesn't print any log.
This is what I want to be able to do.

If performing a `ctrl + click` in a `.pdf` file, the following error log comes up:

```
[12:21:41] Handle data type: click
[12:21:41] SyncTexJsError: synctex file, .synctex and .synctex.gz, not found in the file system.
	at c (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:371:338955)
	at Object.module.exports.t.syncTexJsBackward (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:371:342003)
	at module.exports.t.Locator.<anonymous> (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:371:335622)
	at Generator.next (<anonymous>)
	at module.exports.n (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:371:330940)
	at new Promise (<anonymous>)
	at module.exports.n (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:371:330717)
	at module.exports.t.Locator.locate (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:371:335456)
	at module.exports.t.Viewer.handler (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:371:322163)
	at w.module.exports.t.Server.constructor.wsServer.on.e.on.t (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:371:323563)
	at w.emit (events.js:182:13)
	at module.exports.e.exports.T (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:137:34110)
	at module.exports.e.exports.emit (events.js:182:13)
	at module.exports.e.exports.dataMessage (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:137:42641)
	at module.exports.e.exports.getData (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:137:41755)
	at module.exports.e.exports.startLoop (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:137:39144)
	at module.exports.e.exports._write (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:137:38526)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at module.exports.e.exports.Writable.write (_stream_writable.js:294:11)
	at Socket.L (C:\Users\spenh\.vscode\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:137:34640)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by Spenhouet** [comment]
@James-Yu I know found out that there is in fact a keyboard shortcut:

```
{
  "key": "ctrl+alt+j",
  "command": "latex-workshop.synctex",
  "when": "editorTextFocus && !config.latex-workshop.bind.altKeymap.enabled"
}
```

I did not expect the keyboard shortcut to be `ctrl+alt+j`.
I did expect to `ctrl+click` on text to jump to the position in the PDF.

Currently it doesn't seem possible to change this shortcut to `ctrl+click`, see:
https://github.com/Microsoft/vscode/issues/38849
https://github.com/microsoft/vscode/issues/3130

Is it documented anywhere that this jump to PDF position is only possible via a strange shortcut?
Documenting this might help to prevent confusion.

**Comment by tamuratak** [comment]
https://github.com/James-Yu/LaTeX-Workshop/wiki/View#usage

**Comment by janosh** [comment]
I agree with @Spenhouet that <kbd>ctrl</kbd> + left click would be a better default binding for this once [vscode#3130](https://github.com/microsoft/vscode/issues/3130) is addressed.

**Comment by James-Yu** [comment]
As you have referenced, the shortcut cannot be created currently in vscode.

**Comment by chaselweng** [comment]
Hi, ctrl+click worked fine, but I encounter another problem.
iMac with Catalina: lock screen and then login, the pdf viewer cannot jump back to .tex file. 
I must open a new pdf viewer tab to make this function work. Any idea?

**Comment by jlelong** [comment]
I also experiment this issue with `synctex` being broken from time to time when the computer wakes up from suspend. I use Mojave. I will open a new issue on this
