### ISSUE TITLE
forward-search and inverse-search not working with external synctex

### ISSUE THREAD

**Issue by views63** [James-Yu/LaTeX-Workshop#1462]
vscode setting
``` json
  "latex-workshop.view.pdf.external.synctex": {
    "command": "C:/SumatraPDF/SumatraPDF.exe",
    "args": [
      "-forward-search",
      "%TEX%",
      "%LINE%",
      "-reuse-instance",
      "-inverse-search",
      "\"C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe\" \"C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\cli.js\" -r -g \"%f:%l\"",
      "%PDF%",
    ]
  }
```
log
```
[14:44:31] SyncTeX failed.
[14:44:31] TypeError: Cannot convert undefined or null to object
	at Function.keys (<anonymous>)
	at l (C:\Users\user\.vscode-insiders\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:371:339733)
	at Object.module.exports.t.syncTexJsForward (C:\Users\user\.vscode-insiders\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:371:340482)
	at module.exports.t.Locator.syncTeX (C:\Users\user\.vscode-insiders\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:371:333056)
	at module.exports.t.Commander.<anonymous> (C:\Users\user\.vscode-insiders\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:137:99090)
	at Generator.next (<anonymous>)
	at s (C:\Users\user\.vscode-insiders\extensions\james-yu.latex-workshop-7.0.2\out\src\main.js:137:93609)
```
Desktop (please complete the following information):
    OS: [Windows 10 1903]
    VS Code version: [1.36.0]
    Extension version: [7.0.2]

**Comment by views63** [comment]
change to VS Code version: [1.35.1]，can use inverse-search，but forward-search also not working
log
```
[16:57:32] SYNCTEX command invoked.
[16:57:32] Found root file from active editor: d:\Probability_and_Statistics\probability_and_statistics.tex
[16:57:32] Root file remains unchanged from: d:\Probability_and_Statistics\probability_and_statistics.tex.
[16:57:32] Executing synctex with args view,-i,43:17:d:\Probability_and_Statistics\probability_and_statistics.tex,-o,d:\Probability_and_Statistics\probability_and_statistics.pdf
[16:57:32] PDF is not viewed: d:\Probability_and_Statistics\probability_and_statistics.pdf
```
the SumatraPDF nothing hanpen.

**Comment by tamuratak** [comment]
Please use the default internal pdf viewer, and check whether SyncTeX works with the internal pdf viewer at first.

If everything works fine, let's look into issues of external pdf viewers.

**Comment by tamuratak** [comment]
Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

**Comment by tamuratak** [comment]
Please disable `latex-workshop.synctex.synctexjs.enabled` in your configuration, and check whether SyncTeX works well.

**Comment by views63** [comment]
> 
> 
> Please use the default internal pdf viewer, and check whether SyncTeX works with the internal pdf viewer at first.
> 
> If everything works fine, let's look into issues of external pdf viewers.
use the default internal pdf viewer is working. `latex-workshop.synctex.synctexjs.enabled` is disable.
in the log said `[16:57:32] PDF is not viewed`  so I change vscode setting ` "latex-workshop.view.pdf.viewer": "tab",`  to ` "latex-workshop.view.pdf.viewer": "external",` is works. how can  keep the default pdf viewer with tab and use external with SumatraPDF.

**Comment by tamuratak** [comment]
It seems that there is not much I can help.

**Comment by jlelong** [comment]
Is this issue solved? If not, please provide more information (including logs).

**Comment by views63** [comment]
> including

log:
```
[14:52:09] Initializing LaTeX Workshop.
[14:52:09] Creating LaTeX Workshop http and websocket server.
[14:52:09] LaTeX Workshop initialized.
[14:52:10] Server created on 127.0.0.1:63744
[14:52:10] Snippet data loaded.
[14:52:11] Try root file in root directory: d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:11] Parsing d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:11] Parsing d:\Probability_and_Statistics\format\new-command.tex
[14:52:11] Parsing d:\Probability_and_Statistics\chapters\total-prob-bayes.tex
[14:52:11] Parsing d:\Probability_and_Statistics\chapters\normal-dist.tex
[14:52:11] Parsing d:\Probability_and_Statistics\chapters\expectation.tex
[14:52:11] Parsing d:\Probability_and_Statistics\chapters\mle.tex
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm.tex
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm-diff-mu.tex
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm-diff-mu-seperate.tex
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm-prob-dist.tex
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm32.tex
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm-diff-sigma.tex
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm-diff-sigma-separate.tex
[14:52:11] Cannot find file d:\Probability_and_Statistics\probability_and_statistics.fls
[14:52:11] Found root file in root directory: d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:11] Root file changed from: undefined. Find all dependencies.
[14:52:11] Instantiating a new file watcher for d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:11] Parsing d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:11] Adding d:\Probability_and_Statistics\format\new-command.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\format\new-command.tex
[14:52:11] Adding d:\Probability_and_Statistics\chapters\total-prob-bayes.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\chapters\total-prob-bayes.tex
[14:52:11] Adding d:\Probability_and_Statistics\chapters\normal-dist.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\chapters\normal-dist.tex
[14:52:11] Adding d:\Probability_and_Statistics\chapters\expectation.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\chapters\expectation.tex
[14:52:11] Adding d:\Probability_and_Statistics\chapters\mle.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\chapters\mle.tex
[14:52:11] Adding d:\Probability_and_Statistics\tikz\mle_norm.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm.tex
[14:52:11] Adding d:\Probability_and_Statistics\tikz\mle_norm-diff-mu.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm-diff-mu.tex
[14:52:11] Adding d:\Probability_and_Statistics\tikz\mle_norm-diff-mu-seperate.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm-diff-mu-seperate.tex
[14:52:11] Adding d:\Probability_and_Statistics\tikz\mle_norm-prob-dist.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm-prob-dist.tex
[14:52:11] Adding d:\Probability_and_Statistics\tikz\mle_norm32.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm32.tex
[14:52:11] Adding d:\Probability_and_Statistics\tikz\mle_norm-diff-sigma.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm-diff-sigma.tex
[14:52:11] Adding d:\Probability_and_Statistics\tikz\mle_norm-diff-sigma-separate.tex to file watcher.
[14:52:11] Parsing d:\Probability_and_Statistics\tikz\mle_norm-diff-sigma-separate.tex
[14:52:11] Found .bib file d:\Probability_and_Statistics\prob-stat-ouyang.bib
[14:52:11] Creating file watcher for .bib files.
[14:52:11] Adding .bib file d:\Probability_and_Statistics\prob-stat-ouyang.bib to bib file watcher.
[14:52:11] Parsing .bib entries from d:\Probability_and_Statistics\prob-stat-ouyang.bib
[14:52:11] Parsed 4 .bib entries from d:\Probability_and_Statistics\prob-stat-ouyang.bib.
[14:52:11] Cannot find file d:\Probability_and_Statistics\probability_and_statistics.fls
[14:52:11] LaTeX Workshop version: 7.0.2
[14:52:45] VIEW command invoked.
[14:52:45] Try root file in root directory: d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:45] Parsing d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:45] Cannot find file d:\Probability_and_Statistics\probability_and_statistics.fls
[14:52:45] Found root file in root directory: d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:45] Root file remains unchanged from: d:\Probability_and_Statistics\probability_and_statistics.tex.
[14:52:45] Open external viewer for d:\Probability_and_Statistics\probability_and_statistics.pdf
[14:52:55] SYNCTEX command invoked.
[14:52:55] Try root file in root directory: d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:55] Parsing d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:55] Cannot find file d:\Probability_and_Statistics\probability_and_statistics.fls
[14:52:55] Found root file in root directory: d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:55] Root file remains unchanged from: d:\Probability_and_Statistics\probability_and_statistics.tex.
[14:52:55] Executing synctex with args view,-i,260:15:d:\Probability_and_Statistics\chapters\expectation.tex,-o,d:\Probability_and_Statistics\probability_and_statistics.pdf
[14:52:55] PDF is not viewed: d:\Probability_and_Statistics\probability_and_statistics.pdf
```

**Comment by jlelong** [comment]
From your logs, `synctex` complains that there is no PDF viewer opened
````
[14:52:55] PDF is not viewed: d:\Probability_and_Statistics\probability_and_statistics.pdf
````
, which is weird as `[14:52:45] VIEW command invoked.`

**Comment by views63** [comment]
> 
> 
> From your logs, `synctex` complains that there is no PDF viewer opened
> 
> ```
> [14:52:55] PDF is not viewed: d:\Probability_and_Statistics\probability_and_statistics.pdf
> ```
> 
> , which is weird as `[14:52:45] VIEW command invoked.`

```
[14:52:45] VIEW command invoked.
[14:52:45] Try root file in root directory: d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:45] Parsing d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:45] Cannot find file d:\Probability_and_Statistics\probability_and_statistics.fls
[14:52:45] Found root file in root directory: d:\Probability_and_Statistics\probability_and_statistics.tex
[14:52:45] Root file remains unchanged from: d:\Probability_and_Statistics\probability_and_statistics.tex.
[14:52:45] Open external viewer for d:\Probability_and_Statistics\probability_and_statistics.pdf
[14:52:55] SYNCTEX command invoked.
```
I have use left panel `view in external viewer` open the pdf file befor  `SYNCTEX `

**Comment by jlelong** [comment]
To make forward synctex work with an external viewer, you need define the configuration variable `latex-workshop.view.pdf.external.synctex`. See the [synctex page on the wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#using-synctex-with-an-external-viewer).

**Comment by views63** [comment]
> 
> 
> To make forward synctex work with an external viewer, you need define the configuration variable `latex-workshop.view.pdf.external.synctex`. See the [synctex page on the wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#using-synctex-with-an-external-viewer).

already set `latex-workshop.view.pdf.external.synctex`.
```
  "latex-workshop.view.pdf.external.synctex": {
    "command": "C:/SumatraPDF/SumatraPDF.exe",
    "args": [
      "-forward-search",
      "%TEX%",
      "%LINE%",
      "-reuse-instance",
      "-inverse-search",
      "\"C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe\" \"C:\\Program Files\\Microsoft VS Code Insiders\\resources\\app\\out\\cli.js\" -r -g \"%f:%l\"",
      "%PDF%",
    ]
  }
```

**Comment by jlelong** [comment]
Do you still have issues with LaTeX-Workshop 7.1? If things were working with VSCode 1.35.1, your problems may be related to #1477.

**Comment by views63** [comment]
> 
> 
> Do you still have issues with LaTeX-Workshop 7.1? If things were working with VSCode 1.35.1, your problems may be related to #1477.

There are still problems.  info:
OS: [Windows 10 1903]
VS Code version: [1.36.0]
Extension version: [7.1.0]

**Comment by jlelong** [comment]
I cannot reproduce your issue under Mac OSX using `Skim` as an external PDF viewer and I do not use Windows. This is issue must be related to your configuration and how you call `SumatraPDF`.
