### ISSUE TITLE
Inverse Search not working in Browser with vscode 1.36

### ISSUE THREAD

**Issue by VadimSokolov** [James-Yu/LaTeX-Workshop#1477]
Inverse search suddenly stopped working when `"latex-workshop.view.pdf.viewer": "browser"`. However when `"latex-workshop.view.pdf.viewer": "tab"` it is working just fine. 

**To Reproduce**
1. Build using the following recipe
```
  {
    "name": "pdflatex",
    "command": "pdflatex",
    "args": [
      "-synctex=1",
      "-interaction=nonstopmode",
      "-file-line-error",
      "--output-directory=build",
      "%DOC%"
    ],
    "env": {}
  },
```
2. View pdf in the browser
3. When I Comment + click on a text, it does not do inverse search

**Logs [Required]**
```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(/Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson.tex
LaTeX2e <2018-12-01>
(/usr/local/texlive/2019basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/usr/local/texlive/2019basic/texmf-dist/tex/latex/base/size12.clo)) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/psnfss/mathpazo.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/graphics/graphicx.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/graphics/keyval.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/graphics/graphics.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/graphics/trig.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/graphics-cfg/graphics.cfg) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/graphics-def/pdftex.def))) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/amsfonts/amsfonts.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/setspace/setspace.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/amsfonts/amssymb.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/amscls/amsthm.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/float/float.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2019basic/texmf-dist/tex/latex/amsmath/amstext.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/amsmath/amsgen.sty)) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/amsmath/amsbsy.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/amsmath/amsopn.sty)) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/caption/subcaption.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/caption/caption.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/caption/caption3.sty))) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/graphics/color.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/graphics-cfg/color.cfg)) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/soul/soul.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/marginnote/marginnote.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/hyperref/hyperref.sty (/usr/local/texlive/2019basic/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty (/usr/local/texlive/2019basic/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty)) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/ifxetex/ifxetex.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/oberdiek/auxhook.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/oberdiek/kvoptions.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/hyperref/pd1enc.def) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/latexconfig/hyperref.cfg) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/url/url.sty)) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/hyperref/hpdftex.def (/usr/local/texlive/2019basic/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty)) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/utilities/pgfutil-common-lists.tex)) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def (/usr/local/texlive/2019basic/texmf-dist/tex/latex/ms/everyshi.sty)) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/pgf.revision.tex))) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.tex)) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-pdftex.def (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.def))) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.tex)) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/xcolor/xcolor.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/graphics-cfg/color.cfg)) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonometric.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerarithmetics.code.tex))) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex)) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformations.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.tex)) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex))) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18.sty)) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/pgf/utilities/pgffor.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex)) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/pgf/math/pgfmath.sty (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex)) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex))) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex) (/usr/local/texlive/2019basic/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarytopaths.code.tex))) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/natbib/natbib.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/geometry/geometry.sty) (build/deep-poisson.aux) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/psnfss/ot1ppl.fd) (/usr/local/texlive/2019basic/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty (/usr/local/texlive/2019basic/texmf-dist/tex/latex/oberdiek/grfext.sty) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg)) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/hyperref/nameref.sty (/usr/local/texlive/2019basic/texmf-dist/tex/generic/oberdiek/gettitlestring.sty)) (build/deep-poisson.out) (build/deep-poisson.out) ABD: EveryShipout initializing macros
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(/usr/local/texlive/2019basic/texmf-dist/tex/latex/psnfss/omlzplm.fd) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/psnfss/omszplm.fd) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/psnfss/omxzplm.fd) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/psnfss/ot1zplm.fd) (/usr/local/texlive/2019basic/texmf-dist/tex/latex/psnfss/omsppl.fd) [1{/usr/local/texlive/2019basic/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] [2 <./fig/rnn.pdf>]
Overfull \hbox (26.41199pt too wide) in paragraph at lines 150--151
\OT1/ppl/m/n/12 We will use MM al-go-rithm to train the model []$\OT1/cmtt/m/n/12 https : / / en . wikipedia . org / wiki / MM _ algorithm$[] 
(build/deep-poisson.bbl [3 <./fig/lstm.pdf>]) [4] (build/deep-poisson.aux) )
(see the transcript file for additional information){/usr/local/texlive/2019basic/texmf-dist/fonts/enc/dvips/base/8r.enc}</usr/local/texlive/2019basic/texmf-dist/fonts/type1/public/amsfonts/cm/cmex10.pfb></usr/local/texlive/2019basic/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb></usr/local/texlive/2019basic/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb></usr/local/texlive/2019basic/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy10.pfb></usr/local/texlive/2019basic/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy8.pfb></usr/local/texlive/2019basic/texmf-dist/fonts/type1/public/amsfonts/cm/cmtt12.pfb></usr/local/texlive/2019basic/texmf-dist/fonts/type1/public/mathpazo/fplmri.pfb></usr/local/texlive/2019basic/texmf-dist/fonts/type1/urw/palatino/uplb8a.pfb></usr/local/texlive/2019basic/texmf-dist/fonts/type1/urw/palatino/uplr8a.pfb></usr/local/texlive/2019basic/texmf-dist/fonts/type1/urw/palatino/uplri8a.pfb>
Output written on build/deep-poisson.pdf (4 pages, 130146 bytes).
SyncTeX written on build/deep-poisson.synctex.gz.
Transcript written on build/deep-poisson.log.
```

<details>
<summary>LaTeX Workshop Output [Required]</summary>

````
[10:01:47] Initializing LaTeX Workshop.
[10:01:47] Creating LaTeX Workshop http and websocket server.
[10:01:47] LaTeX Workshop initialized.
[10:01:47] Found root file from active editor: /Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson.tex
[10:01:47] Root file changed from: undefined. Find all dependencies.
[10:01:47] Instantiating a new file watcher for /Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson.tex
[10:01:47] Parsing /Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson.tex
[10:01:47] Found .bib file /Users/vsokolov/Dropbox/papers/deep-poisson/paper/ref.bib
[10:01:47] Creating file watcher for .bib files.
[10:01:47] Adding .bib file /Users/vsokolov/Dropbox/papers/deep-poisson/paper/ref.bib to bib file watcher.
[10:01:47] Parsing .bib entries from /Users/vsokolov/Dropbox/papers/deep-poisson/paper/ref.bib
[10:01:47] Parsed 2 .bib entries from /Users/vsokolov/Dropbox/papers/deep-poisson/paper/ref.bib.
[10:01:47] Cannot find file /Users/vsokolov/Dropbox/papers/deep-poisson/paper/build/deep-poisson.fls
[10:01:47] Server created on 127.0.0.1:50889
[10:01:47] Snippet data loaded.
[10:01:47] LaTeX Workshop version: 7.0.2
[10:01:59] RECIPES command invoked.
[10:02:00] BUILD command invoked.
[10:02:00] Found root file from active editor: /Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson.tex
[10:02:00] Root file remains unchanged from: /Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson.tex.
[10:02:00] Building root file: /Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson.tex
[10:02:00] Build root file /Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson.tex
[10:02:00] Recipe step 1: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,--output-directory=build,/Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson
[10:02:00] LaTeX build process spawned. PID: 3989.
[10:02:00] LaTeX log parsed with 1 messages.
[10:02:00] A step in recipe finished. PID: 3989.
[10:02:00] Recipe step 2: bibtex, ./build/deep-poisson
[10:02:00] LaTeX build process spawned. PID: 3990.
[10:02:00] A step in recipe finished. PID: 3990.
[10:02:00] Recipe step 3: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,--output-directory=build,/Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson
[10:02:00] LaTeX build process spawned. PID: 3991.
[10:02:01] LaTeX log parsed with 1 messages.
[10:02:01] A step in recipe finished. PID: 3991.
[10:02:01] Recipe step 4: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,--output-directory=build,/Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson
[10:02:01] LaTeX build process spawned. PID: 3992.
[10:02:01] LaTeX log parsed with 1 messages.
[10:02:01] Recipe of length 4 finished. PID: 3992.
[10:02:01] Successfully built /Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson.tex.
[10:02:01] No PDF viewer connected for /Users/vsokolov/Dropbox/papers/deep-poisson/paper/build/deep-poisson.pdf
[10:02:01] Cannot find file /Users/vsokolov/Dropbox/papers/deep-poisson/paper/build/deep-poisson.fls
[10:02:01] SyncTex after build invoked.
[10:02:01] PDF is not viewed: /Users/vsokolov/Dropbox/papers/deep-poisson/paper/build/deep-poisson.pdf
[10:02:03] VIEW command invoked.
[10:02:03] Found root file from active editor: /Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson.tex
[10:02:03] Root file remains unchanged from: /Users/vsokolov/Dropbox/papers/deep-poisson/paper/deep-poisson.tex.
[10:02:03] Serving PDF file at http://localhost:50889/viewer.html?file=/pdf:%252FUsers%252Fvsokolov%252FDropbox%252Fpapers%252Fdeep-poisson%252Fpaper%252Fbuild%252Fdeep-poisson.pdf
[10:02:03] Open PDF viewer for /Users/vsokolov/Dropbox/papers/deep-poisson/paper/build/deep-poisson.pdf
[10:02:03] Handle data type: open
[10:02:03] Preview PDF file: /Users/vsokolov/Dropbox/papers/deep-poisson/paper/build/deep-poisson.pdf
[10:02:03] Handle data type: loaded
````
</details>

<details>
<summary>Developer Tools Console [Required]</summary>

````
mainThreadExtensionService.ts:60 [[object Object]]i is not iterable
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
mainThreadExtensionService.ts:61 TypeError: i is not iterable
	at module.exports.t.Viewer.handler (/Users/vsokolov/.vscode/extensions/james-yu.latex-workshop-7.0.2/out/src/main.js:371)
	at w.module.exports.t.Server.constructor.wsServer.on.e.on.t (/Users/vsokolov/.vscode/extensions/james-yu.latex-workshop-7.0.2/out/src/main.js:371)
	at w.emit (events.js:182)
	at module.exports.e.exports.T (/Users/vsokolov/.vscode/extensions/james-yu.latex-workshop-7.0.2/out/src/main.js:137)
	at module.exports.e.exports.emit (events.js:182)
	at module.exports.e.exports.dataMessage (/Users/vsokolov/.vscode/extensions/james-yu.latex-workshop-7.0.2/out/src/main.js:137)
	at module.exports.e.exports.getData (/Users/vsokolov/.vscode/extensions/james-yu.latex-workshop-7.0.2/out/src/main.js:137)
	at module.exports.e.exports.startLoop (/Users/vsokolov/.vscode/extensions/james-yu.latex-workshop-7.0.2/out/src/main.js:137)
	at module.exports.e.exports._write (/Users/vsokolov/.vscode/extensions/james-yu.latex-workshop-7.0.2/out/src/main.js:137)
	at doWrite (_stream_writable.js:410)
	at writeOrBuffer (_stream_writable.js:394)
	at module.exports.e.exports.Writable.write (_stream_writable.js:294)
	at Socket.L (/Users/vsokolov/.vscode/extensions/james-yu.latex-workshop-7.0.2/out/src/main.js:137)
	at Socket.emit (events.js:182)
	at addChunk (_stream_readable.js:283)
	at readableAddChunk (_stream_readable.js:264)
	at Socket.Readable.push (_stream_readable.js:219)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:61
log.ts:173   ERR Invalid guestInstanceId: null: Error: Invalid guestInstanceId: null
    at Object.getGuestForWebContents (/Applications/Visual Studio Code.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:430:11)
    at /Applications/Visual Studio Code.app/Contents/Resources/electron.asar/browser/rpc-server.js:449:34
    at EventEmitter.ipcMain.on.args (/Applications/Visual Studio Code.app/Contents/Resources/electron.asar/browser/rpc-server.js:278:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/electron.asar/browser/api/web-contents.js:370:21)
    at WebContents.emit (events.js:182:13)
````
</details>

**Desktop [Required]:**
 - OS: MacOS Mojave
 - VS Code version: 1.36.0
 - Extension version: 7.0.2

**Comment by jlelong** [comment]
I do think browsers have ever been able to trigger `synctex` by `ctrl+click`.

**Comment by VadimSokolov** [comment]
@jlelong It has always worked in my browser (safari) until this morning. Something has happened although I did not modify any settings or install any new plugins.

**Comment by trevorgunn** [comment]
Could it be the VSCode 1.36 update?

**Comment by jlelong** [comment]
Probably as the current published version of the extension is already a month old.
Do you have nay relevant logs that could help identifying the problem? It seems that vscode 1.36 has broken a few things but it is hard to know if it is because of a bug on their side or because we have always been doing something wrong but it was working anyway.

**Comment by VadimSokolov** [comment]
@jlelong My original bug report has PDFLatex output, LaTeX Workshop Output  and Developer Tools Console output. What other logs would be logs would be relevant?

**Comment by trevorgunn** [comment]
I think this is the same issue that we are seeing in #1472. The [patch](https://github.com/James-Yu/LaTeX-Workshop/issues/1472#issuecomment-508329801) mentioned there fixes it.

**Comment by VadimSokolov** [comment]
@trevorgunn The patch did fix the issue! Thank you!
