### ISSUE TITLE
Catch/Resolve Error on Save

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1565]
In the debug console, every time a `.tex` file is saved I see the following
````
stack trace: Error: 
	at UnknownErrorExceptionClosure (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:1103:37)
	at Object._typeof (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:1106:2)
	at __w_pdfjs_require__ (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:52:30)
	at Object.defineProperty.value (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:147:13)
	at __w_pdfjs_require__ (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:52:30)
	at Object.defineProperty.value (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:128:23)
	at __w_pdfjs_require__ (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:52:30)
	at pdfjsVersion (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:116:18)
	at /home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:119:10
	at webpackUniversalModuleDefinition (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:25:20)
	at Object.<anonymous> (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:32:3)
	at Object.<anonymous> (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.worker.js:47058:3)
	at Module._compile (internal/modules/cjs/loader.js:693:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.load (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:33564:37)
	at Function.Module._load (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47276:33)
	at Function.load [as _load] (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43810:37)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Immediate.<anonymous> (/home/tec/.vscode/extensions/james-yu.latex-workshop-7.3.0/node_modules/pdfjs-dist/build/pdf.js:7876:20)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)
```

could we resolve this somehow?

**Comment by tamuratak** [comment]
I cannot reproduce this issue. Please fill out the information required in the issue template.

**Comment by tecosaur** [comment]
Sure. I'll copy the bug template and overwrite my original post.

**Comment by tamuratak** [comment]
Execute `npm install` at first. Feel free to reopen when you can reproduce this problem.

**Comment by tecosaur** [comment]
Sorry about the bogus issue, I think it was probably introduced by me when checking out different versions. If I find it happening again I'll do a better job reporting it :sweat_smile:
