### ISSUE TITLE
Auto build stops working after encountering error if latex-workshop.latex.clean.fileTypes is not set 

### ISSUE THREAD

**Issue by FrankDrop** [James-Yu/LaTeX-Workshop#1576]
Disabled all other extensions, still see the problem.

If I disable the automatic removal of build-generated files by renaming or removing the field "latex-workshop.latex.clean.fileTypes" in settings.json, the auto build function upon saving a file stops working after a build encounters an error. For example, i rename the field into "latex-workshop.latex.clean.fileTypes.no".

**To Reproduce**
1. Remove/rename the field latex-workshop.latex.clean.fileTypes
2. Open a building project.
3. Modify a file and save. Autobuild should now run and complete successfully.
4. Modify a file and save. Autobuild should now run again and complete successfully.
5. Introduce an error into one of the .tex files and save. Autobuild runs and returns an error.
6. Fix the error and save. Expected behavior: autobuild runs again and all is good. Actual behavior: nothing happens. VSCode needs to be restarted for the autobuild to work again.

If "latex-workshop.latex.clean.fileTypes" is now renamed back to its actual name, or added to settings.json again, everything works as expected.
I do not always want the clean step to run. Perhaps I am using the wrong method to prevent the clean step from running, but I wouldn't expect this behavior.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>
[09:43:12] Initializing LaTeX Workshop.
[09:43:12] Creating LaTeX Workshop http and websocket server.
[09:43:12] LaTeX Workshop initialized.
[09:43:12] Server created on 127.0.0.1:46687
[09:43:12] Snippet data loaded.
[09:43:12] Try root file in root directory: /project_folder/main.tex
[09:43:12] Parsing /project_folder/main.tex
[09:43:12] Parsing /project_folder/introduction.tex
[09:43:12] Parsing /project_folder/main.fls to compute dependencies
[09:43:12] Found root file in root directory: /project_folder/main.tex
[09:43:12] Root file changed from: undefined. Find all dependencies.
[09:43:12] Instantiating a new file watcher for /project_folder/main.tex
[09:43:12] Parsing /project_folder/main.tex
[09:43:12] Adding /project_folder/introduction.tex to file watcher.
[09:43:12] Parsing /project_folder/introduction.tex
[09:43:12] Parsing /project_folder/main.fls to compute dependencies
[09:43:12] Adding /usr/share/texmf/tex/latex/lm/lmodern.sty to file watcher.
[09:43:12] Adding /project_folder/optidef.sty to file watcher.
[09:43:12] Adding /project_folder/environ.sty to file watcher.
[09:43:12] LaTeX Workshop version: 7.3.0
[09:43:34] Parsing /project_folder/introduction.tex
[09:43:34] File watcher: responding to change in /project_folder/introduction.tex
[09:43:34] /project_folder/introduction.tex changed. Auto build project.
[09:43:34] BUILD command invoked.
[09:43:34] Building root file: /project_folder/main.tex
[09:43:34] Build root file /project_folder/main.tex
[09:43:34] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-halt-on-error,-pdf,/project_folder/main
[09:43:34] LaTeX build process spawned. PID: 7563.
[09:43:35] LaTeX log parsed with 5 messages.
[09:43:35] Recipe of length 1 finished. PID: 7563.
[09:43:35] Successfully built /project_folder/main.tex.
[09:43:35] No PDF viewer connected for /project_folder/main.pdf
[09:43:35] Parsing /project_folder/main.fls to compute dependencies
[09:43:35] Auto Clean invoked.
[09:43:44] Parsing /project_folder/introduction.tex
[09:43:44] File watcher: responding to change in /project_folder/introduction.tex
[09:43:44] /project_folder/introduction.tex changed. Auto build project.
[09:43:44] BUILD command invoked.
[09:43:44] Building root file: /project_folder/main.tex
[09:43:44] Build root file /project_folder/main.tex
[09:43:44] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-halt-on-error,-pdf,/project_folder/main
[09:43:44] LaTeX build process spawned. PID: 7581.
[09:43:45] LaTeX log parsed with 5 messages.
[09:43:45] Recipe of length 1 finished. PID: 7581.
[09:43:45] Successfully built /project_folder/main.tex.
[09:43:45] No PDF viewer connected for /project_folder/main.pdf
[09:43:45] Parsing /project_folder/main.fls to compute dependencies
[09:43:45] Auto Clean invoked.
[09:43:53] Parsing /project_folder/introduction.tex
[09:43:53] File watcher: responding to change in /project_folder/introduction.tex
[09:43:53] /project_folder/introduction.tex changed. Auto build project.
[09:43:53] BUILD command invoked.
[09:43:53] Building root file: /project_folder/main.tex
[09:43:53] Build root file /project_folder/main.tex
[09:43:53] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-halt-on-error,-pdf,/project_folder/main
[09:43:53] LaTeX build process spawned. PID: 7593.
[09:43:53] LaTeX log parsed with 5 messages.
[09:43:53] Recipe returns with error: 12/null. PID: 7593. message: Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'introduction.tex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -halt-on-error -recorder  "/project_folder/main.tex"'
------------
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
.
[09:43:53] Cleaning auxillary files and retrying build after toolchain error.
[09:44:20] Parsing /project_folder/introduction.tex
[09:44:20] File watcher: responding to change in /project_folder/introduction.tex
[09:44:20] /project_folder/introduction.tex changed. Auto build project.
[09:44:20] BUILD command invoked.
[09:44:20] Building root file: /project_folder/main.tex
[09:44:35] Parsing /project_folder/introduction.tex
[09:44:35] File watcher: responding to change in /project_folder/introduction.tex
[09:44:35] /project_folder/introduction.tex changed. Auto build project.
[09:44:35] BUILD command invoked.
[09:44:35] Building root file: /project_folder/main.tex
[09:44:35] Another LaTeX build processing is already waiting for the current LaTeX build to finish. Exit.
</details>

<details>
<summary>Developer Tools Console [Required]</summary>
[Extension Host] rejected promise not handled within 1 second: TypeError: globs.map is not a function
t.log @ console.ts:134
console.ts:134 [Extension Host] stack trace: TypeError: globs.map is not a function	at Cleaner.<anonymous> (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:38:19)	at Generator.next (<anonymous>)	at __awaiter (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:7:71)	at new Promise (<anonymous>)	at __awaiter (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:3:12)	at Cleaner.clean (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:20:16)	at Builder.buildFinished (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/builder.js:311:36)	at ChildProcess.buildStep.currentProcess.on (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/builder.js:280:30)	at ChildProcess.emit (events.js:182:13)	at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
t.log @ console.ts:134
mainThreadExtensionService.ts:60 [[object Object]]globs.map is not a function
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
mainThreadExtensionService.ts:61 TypeError: globs.map is not a function
	at Cleaner.<anonymous> (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:38)
	at Generator.next (<anonymous>)
	at __awaiter (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:7)
	at new Promise (<anonymous>)
	at __awaiter (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:3)
	at Cleaner.clean (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:20)
	at Builder.buildFinished (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/builder.js:311)
	at ChildProcess.buildStep.currentProcess.on (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/builder.js:280)
	at ChildProcess.emit (events.js:182)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:240)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:61
console.ts:134 [Extension Host] rejected promise not handled within 1 second: TypeError: globs.map is not a function
t.log @ console.ts:134
console.ts:134 [Extension Host] stack trace: TypeError: globs.map is not a function	at Cleaner.<anonymous> (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:38:19)	at Generator.next (<anonymous>)	at __awaiter (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:7:71)	at new Promise (<anonymous>)	at __awaiter (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:3:12)	at Cleaner.clean (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:20:16)	at ChildProcess.buildStep.currentProcess.on (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/builder.js:245:48)	at ChildProcess.emit (events.js:182:13)	at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
t.log @ console.ts:134
mainThreadExtensionService.ts:60 [[object Object]]globs.map is not a function
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
mainThreadExtensionService.ts:61 TypeError: globs.map is not a function
	at Cleaner.<anonymous> (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:38)
	at Generator.next (<anonymous>)
	at __awaiter (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:7)
	at new Promise (<anonymous>)
	at __awaiter (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:3)
	at Cleaner.clean (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/cleaner.js:20)
	at ChildProcess.buildStep.currentProcess.on (/home/fdrop/.vscode/extensions/james-yu.latex-workshop-7.3.0/out/src/components/builder.js:245)
	at ChildProcess.emit (events.js:182)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:240)
</details>

**Desktop [Required]:**
 - OS: Ubuntu 18.04
 - VS Code version: 1.36.1
 - Extension version: 7.3.0

**Are you using LaTeX Workshop with VS Code Remote?**
No

**Additional context**
Perhaps my way of disabling the autoclean is just wrong (renaming the field into "latex-workshop.latex.clean.fileTypes.no"...? But I would've expected it to work.

**Comment by tamuratak** [comment]
If you want to disable the autoclean completely, set an empty array `[]` to `latex-workshop.latex.clean.fileTypes`. See [link](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#cleaning-generated-files).

**Comment by tamuratak** [comment]
If you want auxiliary files remained only when compilation succeed, set `onFailed` to `latex-workshop.latex.autoClean.run`.

**Comment by FrankDrop** [comment]
I see. I was just thinking that the (possibly accidental) misspelling of a json setting should not result in hard to comprehend unexpected behavior.

**Comment by tamuratak** [comment]
We do not accept such reports. Do not send us any more. Please open an issue only if you really need help. Thank you for your cooperation.
