### ISSUE TITLE
Intellisense not working with `\cite`

### ISSUE THREAD

**Issue by ShuCaiMonkaS** [James-Yu/LaTeX-Workshop#1643]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.**

**Describe the bug [Required]**
With `$BIBINPUTS`, I have my `.bib` files store outside.
![Screen Shot 2019-08-26 at 11 28 07 AM](https://user-images.githubusercontent.com/43042885/63706642-96a7b900-c7f5-11e9-949b-3ae6ad9331be.jpg)

After setting up the `latex-workshop.latex.bibDirs`,
![Screen Shot 2019-08-26 at 11 28 17 AM](https://user-images.githubusercontent.com/43042885/63706703-b9d26880-c7f5-11e9-98de-10d15aa562be.jpg)
with `latex-workshop.intellisense.citation.maxfilesizeMB` 20.

However, there's no Intellisense when I use `\cite{}`
![Screen Shot 2019-08-26 at 11 27 23 AM](https://user-images.githubusercontent.com/43042885/63706847-0cac2000-c7f6-11e9-8983-a107b6cfbfae.jpg)

The 
**To Reproduce**
Compile this 
```
\documentclass[12pt,letterpaper]{report}
\usepackage{hyperref}

\begin{document}
\cite{}
%-----Bibliography
\bibliography{references}
\bibliographystyle{plain}
\end{document}
```
with `$BIBINPUTS` and `latex-workshop.latex.bibDirs` set to be the same the same, `latex-workshop.intellisense.citation.maxfilesizeMB` set to 20.

**Expected behavior**
Intellisense recommending related reference

**Logs [Required]**
I don't know how to get it.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

```
[11:31:07] Initializing LaTeX Workshop.
[11:31:07] Creating LaTeX Workshop http and websocket server.
[11:31:07] LaTeX Workshop initialized.
[11:31:07] Linter for root file started.
[11:31:07] No root file found for linting.
[11:31:12] Found root file from active editor: /Users/shengchao/Desktop/test/main.tex
[11:31:12] Root file changed from: undefined to /Users/shengchao/Desktop/test/main.tex. Find all dependencies.
[11:31:12] Instantiating a new file watcher for /Users/shengchao/Desktop/test/main.tex
[11:31:12] Creating file watcher for .bib files.
[11:31:12] Parsing /Users/shengchao/Desktop/test/main.tex
[11:31:12] Found .bib file /Users/shengchao/Documents/RiceUniversity/references.bib
[11:31:12] Adding .bib file /Users/shengchao/Documents/RiceUniversity/references.bib to bib file watcher.
[11:31:12] Parsing .bib entries from /Users/shengchao/Documents/RiceUniversity/references.bib
[11:31:12] Server created on 127.0.0.1:62630
[11:31:12] Adding /Users/shengchao/Desktop/test/main.tex to file watcher.
[11:31:13] Snippet data loaded.
[11:31:13] LaTeX Workshop version: 8.0.7
[11:38:51] Found root file from active editor: /Users/shengchao/Desktop/test/main.tex
[11:38:51] Root file remains unchanged from: /Users/shengchao/Desktop/test/main.tex.
[11:39:44] Found root file from active editor: /Users/shengchao/Desktop/test/main.tex
[11:39:44] Root file remains unchanged from: /Users/shengchao/Desktop/test/main.tex.
[11:39:46] Found root file from active editor: /Users/shengchao/Desktop/test/main.tex
[11:39:46] Root file remains unchanged from: /Users/shengchao/Desktop/test/main.tex.
[11:39:53] Found root file from active editor: /Users/shengchao/Desktop/test/main.tex
[11:39:53] Root file remains unchanged from: /Users/shengchao/Desktop/test/main.tex.
[11:40:24] Found root file from active editor: /Users/shengchao/Desktop/test/main.tex
[11:40:24] Root file remains unchanged from: /Users/shengchao/Desktop/test/main.tex.
```
</details>

<details>
<summary>Developer Tools Console [Required]</summary>

[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/theme-seti/icons/seti.woff
actionbar.ts:639 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/base/browser/ui/octiconLabel/octicons/octicons.ttf?1b0f2a9535896866c74dd24eedeb4374
extensionHost.ts:293 [Extension Host] debugger listening on port 49653
console.ts:137 [Extension Host] parse /Users/shengchao/Desktop/test/main.tex: 9.602ms
console.ts:137 [Extension Host] rejected promise not handled within 1 second: SyntaxError: Expected "\"", "\r\n", "{", [ \t\n], [0-9], or [a-zA-Z0-9_:\-] but "[" found.
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: SyntaxError: Expected "\"", "\r\n", "{", [ \t\n], [0-9], or [a-zA-Z0-9_:\-] but "[" found.	at peg$buildStructuredError (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_js.js:365:12)	at Object.peg$parse [as parse] (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_js.js:2006:11)	at Citation.parseBibFile (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/providers/completer/citation.js:137:39)	at Manager.watchBibFile (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:695:47)	at Manager.parseBibFiles (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:438:22)	at Manager.<anonymous> (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:301:18)	at Generator.next (<anonymous>)	at __awaiter (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:7:71)	at new Promise (<anonymous>)	at __awaiter (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:3:12)	at Manager.parseFileAndSubs (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:289:16)	at Manager.<anonymous> (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:130:26)	at Generator.next (<anonymous>)	at fulfilled (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:4:58)
t.log @ console.ts:137
mainThreadExtensionService.ts:64 [[object Object]]Expected "\"", "\r\n", "{", [ \t\n], [0-9], or [a-zA-Z0-9_:\-] but "[" found.
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
mainThreadExtensionService.ts:65 SyntaxError: Expected "\"", "\r\n", "{", [ \t\n], [0-9], or [a-zA-Z0-9_:\-] but "[" found.
	at peg$buildStructuredError (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_js.js:365)
	at Object.peg$parse [as parse] (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_js.js:2006)
	at Citation.parseBibFile (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/providers/completer/citation.js:137)
	at Manager.watchBibFile (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:695)
	at Manager.parseBibFiles (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:438)
	at Manager.<anonymous> (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:301)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:7)
	at new Promise (<anonymous>)
	at __awaiter (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:3)
	at Manager.parseFileAndSubs (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:289)
	at Manager.<anonymous> (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:130)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/shengchao/.vscode/extensions/james-yu.latex-workshop-8.0.7/out/src/components/manager.js:4)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
</details>

**Desktop [Required]:**
 - OS: macOS Catalina Version 10.15 Beta (19A536g)
 - VS Code version: 1.37.1
 - Extension version: 8.0.7

**Are you using LaTeX Workshop with VS Code Remote?**

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 5.0.0]

**Additional context**

**Comment by jlelong** [comment]
I cannot reproduce the issue, please provide a MWE.

**Comment by jlelong** [comment]
We cannot do much if the `.bib` file has typos.

**Comment by lockejan** [comment]
```
@misc{arm2016bag,
% personal comment about ref
	archiveprefix = {arXiv},
	author        = {Armand Joulin and Edouard Grave and Piotr Bojanowski and Tomas Mikolov},
	eprint        = {1607.01759},
	primaryclass  = {cs.CL},
	title         = {Bag of Tricks for Efficient Text Classification},
	year          = {2016}
}
```

@jlelong I totally get your point, but shouldn't the user get some sort of feedback by the linter that the bib-file isn't valid?
Please see my example here.
I need to put my comments somewhere so I put them one line above the bib entry, but when the sort script is invoked the comments are ignored and therefore out of place afterwards, so i started to put them inside.
The compilation passes in my case, but because of the comment line intellisense doesn't work anymore.

Where else should such problem be adressed then?

**Comment by tamuratak** [comment]
Please open a new issue.
