### ISSUE TITLE
Unable to configure makeglossaries with -d option and outDir

### ISSUE THREAD

**Issue by lagru** [James-Yu/LaTeX-Workshop#1690]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**

I'm trying to use `makeglossaries` together with a custom output directory. I've configured the tool and recipe as show in the section below. However the recipe fails with the message

```
Unable to chdir to ' /home/lg/Desktop/test/build' No such file or directory
makeglossaries version 4.41 (2018-07-23)
```

I've looked into the log message and tried the command as invoked by latex-workshop in a terminal where it works fine.

**To Reproduce**
On manjaro with texlive installed:

1. Use the following configuration:

<details>
<summary>settings.json</summary>

```json
{
    "latex-workshop.latex.outDir": "%DIR%/build",
    "latex-workshop.latex.tools": [
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-recorder",
                "-output-directory=%OUTDIR%",
                "%DOC%"
            ],
            "env": {}
        },
        {
            "name": "makeglossaries",
            "command": "makeglossaries",
            "args": [
                "-d %OUTDIR%",
                "%DOCFILE%",
            ],
            "env": {}
        },
    ],
    "latex-workshop.latex.recipes": [
        {
            "name": "pdflatex ➞ makeglossaries",
            "tools": [
                "pdflatex",
                "makeglossaries",
            ]
        }
    ]
}
```

</details>
2. Create the following minimal tex file:

```latex
\documentclass{article}
\usepackage[xindy]{glossaries}
\makeglossaries
\newglossaryentry{sample}{name={sample},
description={an example}}
\begin{document}
A \gls{sample}.
\printglossaries
\end{document}
```

3. Invoke the recipe `pdflatex ➞ makeglossaries`.

**Expected behavior**

The recipe behaves the same way as if invoked with the same configuration options in a separate terminal.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

```
[16:13:57] Initializing LaTeX Workshop.
[16:13:57] Creating LaTeX Workshop http and websocket server.
[16:13:57] LaTeX Workshop initialized.
[16:13:58] Found root file from active editor: /home/lg/Desktop/test/test.tex
[16:13:58] Root file changed from: undefined to /home/lg/Desktop/test/test.tex. Find all dependencies.
[16:13:58] Instantiating a new file watcher for /home/lg/Desktop/test/test.tex
[16:13:58] Creating file watcher for .bib files.
[16:13:58] Parsing /home/lg/Desktop/test/test.tex
[16:13:58] Server created on 127.0.0.1:36907
[16:13:58] Adding /home/lg/Desktop/test/test.tex to file watcher.
[16:13:58] Snippet data loaded.
[16:13:58] LaTeX Workshop version: 8.1.0
[16:14:00] RECIPES command invoked.
[16:14:01] BUILD command invoked.
[16:14:01] Found root file from active editor: /home/lg/Desktop/test/test.tex
[16:14:01] Root file remains unchanged from: /home/lg/Desktop/test/test.tex.
[16:14:01] Building root file: /home/lg/Desktop/test/test.tex
[16:14:01] Build root file /home/lg/Desktop/test/test.tex
[16:14:01] Recipe step 1: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,-recorder,-output-directory=/home/lg/Desktop/test/build,/home/lg/Desktop/test/test
[16:14:01] LaTeX build process spawned. PID: 29016.
[16:14:02] LaTeX log parsed with 0 messages.
[16:14:02] A step in recipe finished. PID: 29016.
[16:14:02] Recipe step 2: makeglossaries, -d /home/lg/Desktop/test/build,test
[16:14:02] LaTeX build process spawned. PID: 29021.
[16:14:02] Recipe returns with error: 2/null. PID: 29021. message: Unable to chdir to ' /home/lg/Desktop/test/build' No such file or directory
.
[16:14:12] LOG command invoked.
```

</details>

<details>
<summary>Developer Tools Console [Required]</summary>

```
[Extension Host] debugger listening on port 21378
notificationsAlerts.ts:40 Recipe terminated with error.
onDidNotificationChange @ notificationsAlerts.ts:40
console.ts:137 [Extension Host] rejected promise not handled within 1 second: MissingPDFException: Missing PDF "/home/lg/Desktop/test/build/test.pdf".
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: 	at MissingPDFExceptionClosure (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:686:35)	at Object._typeof (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:689:2)	at __w_pdfjs_require__ (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:52:30)	at Object.defineProperty.value (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:129:23)	at __w_pdfjs_require__ (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:52:30)	at pdfjsVersion (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:116:18)	at /home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:119:10	at webpackUniversalModuleDefinition (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:25:20)	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:32:3)	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:23600:3)	at Module._compile (internal/modules/cjs/loader.js:693:30)	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)	at Module.load (internal/modules/cjs/loader.js:602:32)	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)	at Function.Module._load (internal/modules/cjs/loader.js:533:3)	at Function.define._installInterceptor.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)	at Function.t._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)	at Function.t.getExtensionPathIndex.then.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)	at Module.require (internal/modules/cjs/loader.js:640:17)	at require (internal/modules/cjs/helpers.js:20:18)	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/out/src/components/builder.js:8:18)	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/out/src/components/builder.js:478:3)	at Module._compile (internal/modules/cjs/loader.js:693:30)	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)	at Module.load (internal/modules/cjs/loader.js:602:32)	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)	at Function.Module._load (internal/modules/cjs/loader.js:533:3)	at Function.define._installInterceptor.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)	at Function.t._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)	at Function.t.getExtensionPathIndex.then.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)	at Module.require (internal/modules/cjs/loader.js:640:17)	at require (internal/modules/cjs/helpers.js:20:18)	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/out/src/main.js:11:19)	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/out/src/main.js:417:3)	at Module._compile (internal/modules/cjs/loader.js:693:30)	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)	at Module.load (internal/modules/cjs/loader.js:602:32)	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)	at Function.Module._load (internal/modules/cjs/loader.js:533:3)	at Function.define._installInterceptor.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)	at Function.t._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)	at Function.t.getExtensionPathIndex.then.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)	at Module.require (internal/modules/cjs/loader.js:640:17)	at require (internal/modules/cjs/helpers.js:20:18)	at Function.i [as __$__nodeRequire] (/usr/lib/code/out/vs/loader.js:31:639)	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:60	at I._doActivateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:168)	at I._activateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:762:6)	at I.<anonymous> (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:758:868)	at Generator.next (<anonymous>)	at n (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:979)	at new Promise (<anonymous>)	at n (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:756)	at Object.actualActivateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:758:570)	at p._activateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:144)	at define._activateExtensions.r.length.Promise.all.s.map.e (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:814)	at Array.map (<anonymous>)	at p._activateExtensions (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:802)	at p.activateByEvent (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:494:635)	at I._activateByEvent (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:680)	at define.$activateByEvent._readyToRunExtensions.wait.then.t (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:769:470)	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ console.ts:137
log.ts:173   ERR Missing PDF "/home/lg/Desktop/test/build/test.pdf".: Error: 
	at MissingPDFExceptionClosure (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:686:35)
	at Object._typeof (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:689:2)
	at __w_pdfjs_require__ (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:52:30)
	at Object.defineProperty.value (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:129:23)
	at __w_pdfjs_require__ (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:52:30)
	at pdfjsVersion (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:116:18)
	at /home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:119:10
	at webpackUniversalModuleDefinition (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:25:20)
	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:32:3)
	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:23600:3)
	at Module._compile (internal/modules/cjs/loader.js:693:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)
	at Function.t._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/out/src/components/builder.js:8:18)
	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/out/src/components/builder.js:478:3)
	at Module._compile (internal/modules/cjs/loader.js:693:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)
	at Function.t._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/out/src/main.js:11:19)
	at Object.<anonymous> (/home/lg/.vscode-oss/extensions/james-yu.latex-workshop-8.1.0/out/src/main.js:417:3)
	at Module._compile (internal/modules/cjs/loader.js:693:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)
	at Function.t._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (/usr/lib/code/out/vs/loader.js:31:639)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:60
	at I._doActivateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:168)
	at I._activateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:762:6)
	at I.<anonymous> (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:758:868)
	at Generator.next (<anonymous>)
	at n (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:979)
	at new Promise (<anonymous>)
	at n (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:756)
	at Object.actualActivateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:758:570)
	at p._activateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:144)
	at define._activateExtensions.r.length.Promise.all.s.map.e (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:814)
	at Array.map (<anonymous>)
	at p._activateExtensions (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:802)
	at p.activateByEvent (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:494:635)
	at I._activateByEvent (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:680)
	at define.$activateByEvent._readyToRunExtensions.wait.then.t (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:769:470)
	at process._tickCallback (internal/process/next_tick.js:68:7)
console.ts:137 [Extension Host] Error when JSON.parse theme files.
console.ts:137 [Extension Host] Unexpected token } in JSON at position 2473
```

</details>

**Desktop [Required]:**
 - OS: Manjaro Linux
 - VS Code version: 1.37.1
 - Extension version: 8.1.0

**Are you using LaTeX Workshop with VS Code Remote?**
No

**Additional context**

- It seems like `makeglossaries` is not able to change the working directory when invoked by latex-workshow in contrast to invoking the script directly inside a shell. Sadly I'm not versed enough in JS or TypeScript to find the related code that invokes tools. Is the way latex-workshop invokes these commands perhaps prohibiting or missing an environment variable for the perl script to properly change the directory?
- Related: #238
- [Code](https://github.com/BetterCrypto/Applied-Crypto-Hardening/blob/615604e3cef24373d35dffd9aa12faf589f98ab3/src/texmf/scripts/glossaries/makeglossaries#L154-L167) handling the `-d` option in `makeglossaries`
- Installed texlive packages:
```
local/texlive-bibtexextra 2019.50908-1 (texlive-most)
local/texlive-bin 2019.51075-3
local/texlive-core 2019.50917-1 (texlive-most)
local/texlive-fontsextra 2019.50876-1 (texlive-most)
local/texlive-formatsextra 2019.50602-1 (texlive-most)
local/texlive-latexextra 2019.50920-1 (texlive-most)
local/texlive-pictures 2019.50872-1 (texlive-most)
local/texlive-pstricks 2019.50587-1 (texlive-most)
local/texlive-publishers 2019.50915-1 (texlive-most)
local/texlive-science 2019.50760-1 (texlive-most)
```
---

Despite encountering this bug I'm impressed with your extension. Thank you for all the impressive work! If you can think of information that's missing feel free to ask!

**Comment by jlelong** [comment]
From 

> `Unable to chdir to ' /home/lg/Desktop/test/build' No such file or directory`

It seems that there is an extra leading white space in your path (look at the quotes). This is probably coming from 
```
 { "name": "makeglossaries", 
   "command": "makeglossaries", 
   "args": [ "-d %OUTDIR%", "%DOCFILE%", ], 
   "env": {} }
```
Try to remove the space after `-d` in the arguments.

**Comment by lagru** [comment]
Removing the space like this "-d%OUTDIR%" indeed works! Thank you for the quick and helpful reply. I feel a little stupid now for missing that. :smile: 

I'm just surprised that this whitespace is critical. When using a shell the whitespace is fine.
