### ISSUE TITLE
Brackets in Directory Name mess up problem and warning tracking.

### ISSUE THREAD

**Issue by ericrbg** [James-Yu/LaTeX-Workshop#1764]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.**

**Describe the bug [Required]**
When there is brackets in the directory name, problems and warnings (not errors!) don't file correctly. Here's an example:

![image](https://user-images.githubusercontent.com/37984851/67474414-51b0cf00-f64c-11e9-9275-db19d997d1e2.png)

**To Reproduce**
1. Make a file as I've done, with brackets in any directory name in its path.
2. Cause an error/warning in it.

**Expected behavior**
Actually mark the correct file, so that I can double click on the warning to go straight to it and also so that it gets underlined in TeX.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>
```
Latexmk: Log file says output to 'example.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'c:/Working(Example)/example.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
C:\texlive\2019\bin\win32\runscript.tlu:907: command failed with exit code 12:
perl.exe c:\texlive\2019\texmf-dist\scripts\latexmk\latexmk.pl -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=c:/Working(Example) c:/Working(Example)/example
.
[10:45:26] Parsing c:\Working(Example)\example.tex
[10:45:26] File watcher: responding to change in c:\Working(Example)\example.tex
[10:45:26] c:\Working(Example)\example.tex changed. Auto build project.
[10:45:26] BUILD command invoked.
[10:45:26] Building root file: c:\Working(Example)\example.tex
[10:45:26] Build root file c:\Working(Example)\example.tex
[10:45:26] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=c:/Working(Example),c:/Working(Example)/example
[10:45:26] LaTeX build process spawned. PID: 10420.
[10:45:27] LaTeX log parsed with 2 messages.
[10:45:27] Recipe of length 1 finished. PID: 10420.
[10:45:27] Successfully built c:\Working(Example)\example.tex.
[10:45:27] Refresh PDF viewer for c:\Working(Example)\example.pdf
[10:45:27] Handle data type: position
[10:45:28] Preview PDF file: c:\Working(Example)\example.pdf
[10:45:28] Handle data type: loaded
```
</details>

<details>
<summary>Developer Tools Console [Required]</summary>
```
mainThreadExtensionService.ts:65 [[object Object]]Can't Display Progress for non-Started build - see BuildInfo.buildStarted()
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
mainThreadExtensionService.ts:66 Error: Can't Display Progress for non-Started build - see BuildInfo.buildStarted()
	at BuildInfo.newStdoutLine (c:\Users\Eric\.vscode\extensions\james-yu.latex-workshop-8.2.0\out\src\components\buildinfo.js:56:19)
	at Socket.currentProcess.stdout.on.newStdout (c:\Users\Eric\.vscode\extensions\james-yu.latex-workshop-8.2.0\out\src\components\builder.js:223:38)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
</details>

**Desktop [Required]:**
 - OS: Win 10
 - VS Code version: 1.39.2
 - Extension version: 8.2.0

**Are you using LaTeX Workshop with VS Code Remote?** 

No

**Comment by trevorgunn** [comment]
Filenames for warnings are reported by the compiler in parentheses with spaces on either end. For example: `/home/Trevor/folder.tex) /file.tex` is a valid path on Linux, and the compiler would report the warning as `... (/home/Trevor/folder.tex) /file.tex) ...`. If one doesn't allow spaces in file URIs then you could tell where the end of the file is by where the first space is. But many people do put spaces in their URIs so instead we rely on the parentheses to find the file name. This requires that we can't allow parentheses in URIs.

**Comment by ericrbg** [comment]
What does a full example log line look like? Obviously this can't be done
with regex but surely there must be further structure in how the log lines
are structured?

**Comment by trevorgunn** [comment]
This produces several example warnings:

```latex
%%% main.tex %%%
\documentclass{article}
\usepackage{thmtools}
\usepackage{hyperref}

\newtheorem{theorem}{Theorem}

\begin{document}

\section{$e^x$}

\input{subfile.tex}

\begin{theorem}
    overfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfull
\end{theorem}

\end{document}

%%% subfile.tex %%%
\fontsize{15}{18}\selectfont Hello world.
```


```
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(/home/trevor/Documents/LaTeX-Test/main.tex
LaTeX2e <2018-12-01>
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo)) (/usr/share/texmf-dist/tex/latex/thmtools/thmtools.sty (/usr/share/texmf-dist/tex/latex/thmtools/thm-patch.sty (/usr/share/texmf-dist/tex/latex/thmtools/parseargs.sty)) (/usr/share/texmf-dist/tex/latex/thmtools/thm-kv.sty (/usr/share/texmf-dist/tex/latex/graphics/keyval.sty) (/usr/share/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty (/usr/share/texmf-dist/tex/generic/oberdiek/infwarerr.sty) (/usr/share/texmf-dist/tex/generic/oberdiek/etexcmds.sty (/usr/share/texmf-dist/tex/generic/oberdiek/ifluatex.sty)))) (/usr/share/texmf-dist/tex/latex/thmtools/thm-autoref.sty (/usr/share/texmf-dist/tex/latex/thmtools/aliasctr.sty (/usr/share/texmf-dist/tex/latex/carlisle/remreset.sty

Package remreset Warning: The remreset package is obsolete:
(remreset)                \@removefomresset is defined.

))) (/usr/share/texmf-dist/tex/latex/thmtools/thm-listof.sty) (/usr/share/texmf-dist/tex/latex/thmtools/thm-restate.sty)) (/usr/share/texmf-dist/tex/latex/hyperref/hyperref.sty (/usr/share/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty (/usr/share/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty)) (/usr/share/texmf-dist/tex/generic/ifxetex/ifxetex.sty) (/usr/share/texmf-dist/tex/latex/oberdiek/auxhook.sty) (/usr/share/texmf-dist/tex/latex/oberdiek/kvoptions.sty) (/usr/share/texmf-dist/tex/latex/hyperref/pd1enc.def) (/usr/share/texmf-dist/tex/latex/latexconfig/hyperref.cfg) (/usr/share/texmf-dist/tex/latex/url/url.sty)) (/usr/share/texmf-dist/tex/latex/hyperref/hpdftex.def (/usr/share/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty)) (/home/trevor/Documents/LaTeX-Test/main.aux) (/usr/share/texmf-dist/tex/latex/hyperref/nameref.sty (/usr/share/texmf-dist/tex/generic/oberdiek/gettitlestring.sty)) (/home/trevor/Documents/LaTeX-Test/main.out) (/home/trevor/Documents/LaTeX-Test/main.out)

Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `math shift' on input line 9.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `superscript' on input line 9.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `math shift' on input line 9.

(/home/trevor/Documents/LaTeX-Test/subfile.tex

LaTeX Font Warning: Font shape `OT1/cmr/m/n' in size <15> not available
(Font)              size <14.4> substituted on input line 1.

)

LaTeX Font Warning: Font shape `OT1/cmr/bx/n' in size <15> not available
(Font)              size <14.4> substituted on input line 14.


LaTeX Font Warning: Font shape `OT1/cmr/m/it' in size <15> not available
(Font)              size <14.4> substituted on input line 14.


Overfull \hbox (746.57552pt too wide) in paragraph at lines 14--15
[]\OT1/cmr/m/it/14.4 overfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfulloverfull 
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (/home/trevor/Documents/LaTeX-Test/main.aux)

LaTeX Font Warning: Size substitutions with differences
(Font)              up to 0.6pt have occurred.

 )
(see the transcript file for additional information)</usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx12.pfb></usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb></usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi12.pfb></usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb></usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr12.pfb></usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmti12.pfb>
Output written on /home/trevor/Documents/LaTeX-Test/main.pdf (1 page, 48132 bytes).
SyncTeX written on /home/trevor/Documents/LaTeX-Test/main.synctex.gz.
Transcript written on /home/trevor/Documents/LaTeX-Test/main.log.
```

Also pdflatex will add page numbers in square brackets after the file names if there is more than one page in the document.

Changing the log parser is very delicate for us because we don't have a list of all possible warnings and errors to test against. As far as I know, nobody provides such a list anywhere on the web.

**Comment by jlelong** [comment]
As @trevorgunn pointed out, the syntax of LaTeX log files is not fully specified and I really doubt these files are generated to be parsed. It is virtually impossible to implement a log parser for every possible situation and we have already spent a lot of energy trying to improve the current parser. Allowing spaces in filenames makes parsing far more complicated. Ideally, filenames should only contain ascii characters and no space but unfortunately it is not the case.

As spaces are so common (especially under Windows), we have chosen to correctly deal with spaces. I am afraid we cannot do better. You can have a look at the [parser](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/parser/log.ts) and feel free to ask for reopening the issue or even make a PR if you come up with a new idea.
