### ISSUE TITLE
PDF Preview not working

### ISSUE THREAD

**Issue by jschneider92** [James-Yu/LaTeX-Workshop#181]
Hello!
I have unfortunately some issues with the PDF preview of the LaTeX Workshop plugin for VS Code.

The latex-workshop plugin output reads as (I have shortened the path for readability and privacy):

```
[15:57:48] Initializing LaTeX Workshop.
[15:57:48] Creating LaTeX Workshop http and websocket server.
[15:57:48] LaTeX Workshop initialized.
[15:57:48] Found root file by magic comment: [...]/Notes/notes.tex
[15:57:48] Root file changed from: undefined. Find all dependencies.
[15:57:48] Instatiating new file watcher for [...]/Notes/notes.tex
[15:57:48] Parsing [...]/Notes/notes.tex
[15:57:48] Adding [...]/Notes/structure.tex to file watcher.
[15:57:48] Parsing [...]/Notes/structure.tex
[15:57:48] Adding [...]/Notes/chapters/chapter1.tex to file watcher.
[15:57:48] Parsing [...]/Notes/chapters/chapter1.tex
[15:57:48] Adding [...]/Notes/chapters/chapter2.tex to file watcher.
[15:57:48] Parsing [...]/Notes/chapters/chapter2.tex
[15:57:48] Found .bib file [...]/Notes/references.bib
[15:57:48] Creating file watcher for .bib files.
[15:57:48] Parsing .bib entries from [...]/Notes/references.bib
[15:57:48] Parsed 8 .bib entries from [...]/Notes/references.bib.
[15:57:48] Linter for root file started.
[15:57:48] Linter for root file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-f%f:%l:%c:%d:%k:%n:%m
,[...]/Notes/notes.tex
[15:57:48] Linter for root file failed with exit code 1 and error:
  
[15:57:48] Linter log parsed with 88 messages.
[15:57:48] Default environments loaded
[15:57:48] Parsing [...]/Notes/notes.tex
[15:57:48] Parsing [...]/Notes/structure.tex
[15:57:48] Parsing [...]/Notes/chapters/chapter1.tex
[15:57:48] Parsing [...]/Notes/chapters/chapter2.tex
[15:57:48] Default commands loaded
[15:57:48] Default unimathsymbols loaded
[15:57:51] BUILD command invoked.
[15:57:51] Found root file by magic comment: [...]/Notes/notes.tex
[15:57:51] Root file remains unchanged from: [...]/Notes/notes.tex.
[15:57:51] Building root file: [...]/Notes/notes.tex
[15:57:51] Build root file [...]/Notes/notes.tex
[15:57:51] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,[...]/Notes/notes
[15:57:56] LaTeX log parsed with 1 messages.
[15:57:56] Toolchain of length 1 finished.
[15:57:56] Successfully built [...]/Notes/notes.tex
[15:57:56] No PDF viewer connected for [...]/Notes/notes.pdf
[15:57:56] Found root file by magic comment: [...]/Notes/notes.tex
[15:57:56] Root file remains unchanged from: [...]/Notes/notes.tex.
[15:57:56] File cleaned: [...]/Notes/notes.aux
[15:57:56] File cleaned: [...]/Notes/notes.bbl
[15:57:56] File cleaned: [...]/Notes/notes.blg
[15:57:56] File cleaned: [...]/Notes/notes.out
[15:57:56] File cleaned: [...]/Notes/notes.toc
[15:57:56] File cleaned: [...]/Notes/notes.fls
[15:57:56] File cleaned: [...]/Notes/notes.log
[15:57:56] File cleaned: [...]/Notes/notes.fdb_latexmk

[15:58:00] ACTIONS command invoked.
[15:58:03] VIEW command invoked.
[15:58:03] Found root file by magic comment: [...]/Notes/notes.tex
[15:58:03] Root file remains unchanged from: [...]/Notes/notes.tex.
[15:58:03] No PDF viewer connected for [...]/Notes/notes.pdf
[15:58:03] Cannot establish server connection.

[15:58:05] ACTIONS command invoked.
[15:58:07] TAB command invoked.
[15:58:07] Found root file by magic comment: [...]/Notes/notes.tex
[15:58:07] Root file remains unchanged from: [...]/Notes/notes.tex.
[15:58:07] No PDF viewer connected for [...]/Notes/notes.pdf
[15:58:07] Cannot establish server connection.
```

**Comment by James-Yu** [comment]
My speculation is on your firewall settings. Does it work for in-browser viewer?

**Comment by jschneider92** [comment]
I would have guessed that, too! However, I deactivated my firefall and it was still not working.

In fact, if you mean by in-browser viewer the action "preview in new tab", then I am sorry to say that it does not work either:
```
[15:58:05] ACTIONS command invoked.
[15:58:07] TAB command invoked.
[15:58:07] Found root file by magic comment: [...]/Notes/notes.tex
[15:58:07] Root file remains unchanged from: [...]/Notes/notes.tex.
[15:58:07] No PDF viewer connected for [...]/Notes/notes.pdf
[15:58:07] Cannot establish server connection.
```

**Comment by James-Yu** [comment]
It's preview in browser tab, not new tab.

**Comment by jschneider92** [comment]
Both do not work, as you can read up in the latex-workshop output in OP:

>` [15:58:00] ACTIONS command invoked.`
> `[15:58:03] VIEW command invoked.`
> `[15:58:03] Found root file by magic comment: [...]/Notes/notes.tex`
>`[15:58:03] Root file remains unchanged from: [...]/Notes/notes.tex.`
> `[15:58:03] No PDF viewer connected for [...]/Notes/notes.pdf`
> `[15:58:03] Cannot establish server connection.`
> 
> `[15:58:05] ACTIONS command invoked.`
> `[15:58:07] TAB command invoked.`
> `[15:58:07] Found root file by magic comment: [...]/Notes/notes.tex`
> `[15:58:07] Root file remains unchanged from: [...]/Notes/notes.tex.`
> `[15:58:07] No PDF viewer connected for [...]/Notes/notes.pdf`
> `[15:58:07] Cannot establish server connection.`

**Comment by James-Yu** [comment]
The extension cannot create a websocket server at `localhost`. Code as follows:
```
        this.httpServer.listen(0, "localhost", undefined, (err: Error) => {
            if (err) {
                this.extension.logger.addLogMessage(`Error creating LaTeX Workshop http server: ${err}.`)
            } else {
                const {address, port} = this.httpServer.address()
                this.address = `${address}:${port}`
                this.root = path.resolve(`${this.extension.extensionRoot}/viewer`)
                this.extension.logger.addLogMessage(`Server created on ${this.address}`)
            }
        })
```
Please check if the development console has anything suspicious. Other than firewall things, I cannot come up with anything else that may cause the trouble.

**Comment by jschneider92** [comment]
I believe I have adapted all firewal rules for the VS Code app appropiately. 
Is there another process for which I have to adapt my firewall rules in order for this to work?

**Comment by James-Yu** [comment]
It really depends on your local pc configurations. On Windows, there are too many things that may control your firewall, e.g., anti-virus. On linux, I believe the system rules matter.

**Comment by jschneider92** [comment]
> Please check if the development console has anything suspicious.

Could you perhaps guide me through this? I have no idea what you mean by that...  😔

**Comment by James-Yu** [comment]
You can access it through `Help` -> `Toggle Develop Tools`. If no console-like things show up, press `ESC`.

**Comment by jschneider92** [comment]
This is what the development console throws when trying to use the preview

```
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at context.subscriptions.push.vscode.window.onDidChangeActiveTextEditor (/Users/===/.vscode/extensions/James-Yu.latex-workshop-2.9.1/out/src/main.js:124:42)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:14715)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:53565)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:390025
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:14715)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:53565)
    at t.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:346353)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:312304)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:176531)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:177208)
e.onUnexpectedError @ shell.ts:445
(anonymous) @ shell.ts:405
e.onUnexpectedError @ errors.ts:68
o @ errors.ts:88
t.onUnexpectedExtHostError @ mainThreadErrors.ts:13
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by James-Yu** [comment]
Seems uncorrelated. This error is thrown due to the empty pane created by the extension, which should have a pdf viewer `document`.

If this is the only error, I would assume that the websocket server takes too long time to listen on a given port. However, reasons causing that remain unknown to me. I only have very general suggestions, such as re-install, re-boot, or try on another computer. 😭

**Comment by jschneider92** [comment]
Indeed, you might be right: Everytime I right-click in a latex file and hit `Latex-Workshop: All Actions`
the console throws a violation:
`[Violation] Long running JavaScript task took 3630ms`

What might be causing this?!? 😭

**Comment by James-Yu** [comment]
It's reaaally strange. The server is created on initializing the extension, instead of openning the dropdown menu. I would temporarily close this issue for now and wait for more reports on this problem. Up to now, still no idea why it happens.

**Comment by AllanWang** [comment]
I'm having this issue as well at times:

```
[17:10:10] Root file remains unchanged from: /home/...tex.
[17:10:17] Found root file from active editor: /home/...tex
[17:10:17] Root file remains unchanged from: /home/...tex.
[17:10:17] Linter for active file started.
```

This works on and off, and is the embedded viewer.

**Comment by James-Yu** [comment]
@AllanWang It seems to be unrelated with this issue. Can you please open a new one and provide a minimal working example for me to debug?

**Comment by haasdo95** [comment]
Encountering the same issue...
"Cannot connect to server" & "No PDF Viewer Connected"

**Comment by TAGC** [comment]
Same issue with me. Server seems to be created fine on `127.0.0.1:52359` but `No PDF viewer connected for: ...`

**Comment by TAGC** [comment]
Actually, it works viewing it in browser, but not in VS Code (browser tab or new VS Code tab).

**Comment by TAGC** [comment]
I run this action:

`LaTeX Workshop: All Action -> View LaTeX PDF -> View in VS Code tab -> Browser Tab`

I get this message: "By default, PDF will be viewed with browser. This setting can be changed at "latex-workshop.view.pdf.viewer"." and nothing else happens.

I then run `LaTeX Workshop: View PDF file`. I don't see any PDF file display.

These two actions generate this output in `LaTeX Workshop` console:

```
[09:39:35] Found root file from active editor: ...\Documents\CV\src\CV.tex
[09:39:35] Root file remains unchanged from: ...\Documents\CV\src\CV.tex.
[09:39:37] ACTIONS command invoked.
[09:39:47] PDF command invoked.
```

The developer console output only consists of warnings that I think are unrelated:

![firefox_2018-04-16_09-43-11](https://user-images.githubusercontent.com/1588951/38798856-bbc9f356-415a-11e8-8aac-84e05612a444.png)

**Comment by TAGC** [comment]
However, if I right-click the generated PDF file in the sidebar and select `View PDF file`, then it opens the PDF in a new tab and keeps it synchronized with the changes I make to the TeX file, which is exactly what I'm after.

**Comment by James-Yu** [comment]
Should be fixed in the above commit.
