### ISSUE TITLE
BUILD / VIEW command invoked, but nothing happened

### ISSUE THREAD

**Issue by zhuyuming96** [James-Yu/LaTeX-Workshop#1900]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

There is no response for BUILD and VIEW command.

I have just installed mactex (mactex-no-gui) from homebrew. I just installed the workshop. It is my first time writing LaTex on vscode on Mac. 

### To Reproduce

1. Create a simple file.
2. Click BUILD, VIEW
3. See error

### Expected behavior

Build LaTex project, view PDF in tab.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[11:49:55] BUILD command invoked.
[11:50:21] VIEW command invoked.
```

### Developer Tools Console [Required]

```
  ERR Cannot read property 'uri' of undefined: TypeError: Cannot read property 'uri' of undefined
	at Manager.findWorkspace (/Users/yumingz/.vscode/extensions/james-yu.latex-workshop-8.5.0/out/src/components/manager.js:108:70)
	at Manager.findRoot (/Users/yumingz/.vscode/extensions/james-yu.latex-workshop-8.5.0/out/src/components/manager.js:116:14)
	at Commander.build (/Users/yumingz/.vscode/extensions/james-yu.latex-workshop-8.5.0/out/src/commander.js:64:53)
	at /Users/yumingz/.vscode/extensions/james-yu.latex-workshop-8.5.0/out/src/main.js:57:87
	at v._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:538:925)
	at v.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:539:295)
	at p._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:663:275)
	at p._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:662:971)
	at p._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:661:639)
	at p._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:660:468)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:658:691
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:820:285
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)
	at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:193:629)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:190:824
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:737)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:89
	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:195:68)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
(This is the console error for `[11:49:55] BUILD command invoked.`, VIEW command returns the same error.)

## Screenshots

<img width="1440" alt="Screen Shot 2020-01-11 at 11 52 54 AM" src="https://user-images.githubusercontent.com/47201935/72208498-eb786300-3468-11ea-9ea2-76dcc0d2daee.png">

## Desktop [Required]
 - OS: macOS Catalina Version 10.15.2
 - VS Code version: 1.14.1
 - Extension version: 8.5.0
 - TeX distribution version: (I installed cask `mactex-no-gui` from homebrew. Here is the info page.
```
% brew cask info mactex-no-gui

mactex-no-gui: 2019.0508
https://www.tug.org/mactex/
/usr/local/Caskroom/mactex-no-gui/2019.0508 (3.8GB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mactex-no-gui.rb
==> Name
MacTeX
==> Artifacts
mactex-20190508.pkg (Pkg)
```

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
Closed by 8121339d4190bde70b5e2c4b0c687e9264857607
