### ISSUE TITLE
Math preview dont work with my big document

### ISSUE THREAD

**Issue by ezalorpro** [James-Yu/LaTeX-Workshop#1926]
## Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

You still see this issue?: Yes

## Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug

Hover math preview dont work on my current document, but it work for a MWE.

### To Reproduce:

unfortunately, no idea

### Host extension Log:

```cmd
[2020-01-31 21:22:52.103] [exthost] [error] [James-Yu.latex-workshop] provider FAILED
[2020-01-31 21:22:52.119] [exthost] [error] Error: 
	at c:\Users\PC\.vscode\extensions\james-yu.latex-workshop-8.7.1\node_modules\workerpool\dist\workerpool.min.js:25:9316
	at ChildProcess.<anonymous> (c:\Users\PC\.vscode\extensions\james-yu.latex-workshop-8.7.1\node_modules\workerpool\dist\workerpool.min.js:25:9391)
	at ChildProcess.emit (events.js:200:13)
	at emit (internal/child_process.js:876:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

### LaTeX workshop Log:

```cmd
[21:21:00] Initializing LaTeX Workshop.
[21:21:03] pdflatex is provided by MiKTeX
[21:21:03] Creating LaTeX Workshop http and websocket server.
[21:21:04] LaTeX Workshop initialized.
[21:21:04] Found root file from active editor: c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\principalTesis.tex
[21:21:04] Root file changed from: undefined to c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\principalTesis.tex. Find all dependencies.
[21:21:04] Instantiating a new file watcher for c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\principalTesis.tex
[21:21:04] Creating file watcher for .bib files.
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\principalTesis.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\dependencias.tex
[21:21:04] Found .bib file c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\referencias.bib
[21:21:04] Adding .bib file c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\referencias.bib to bib file watcher.
[21:21:04] Parsing .bib entries from c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\referencias.bib
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\configurationFile.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\portada.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContentTesis.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContent\contraPortada.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContent\cartaAprobacion.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContent\Agradecimiento.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContent\Resumen.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContent\Introduccion.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\capitulo1.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\capitulo2.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\capitulo3.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\capitulo4.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\capitulo5.tex
[21:21:04] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\anexos.tex
[21:21:04] Server created on 127.0.0.1:62689
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\principalTesis.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\dependencias.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\configurationFile.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\portada.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContentTesis.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContent\contraPortada.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContent\cartaAprobacion.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContent\Agradecimiento.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContent\Resumen.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\FrontContent\Introduccion.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\capitulo1.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\capitulo2.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\capitulo3.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\capitulo4.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\capitulo5.tex to file watcher.
[21:21:04] Adding c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\anexos.tex to file watcher.
[21:21:05] Parsed 40 bib entries from c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\referencias.bib.
[21:21:05] Snippet data loaded.
[21:21:05] LaTeX Workshop version: 8.7.1
[21:22:35] Found root file from active editor: c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\principalTesis.tex
[21:22:35] Root file remains unchanged from: c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\principalTesis.tex.
[21:22:39] File watcher: responding to change in c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\principalTesis.tex
[21:22:39] Parsing c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\principalTesis.tex
[21:25:32] Found root file from active editor: c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\principalTesis.tex
[21:25:32] Root file remains unchanged from: c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\Archivos latex - tesis\principalTesis.tex.
[21:26:45] LOG command invoked.
```

## Desktop
 - OS: Windows 10
 - VS Code version: 1.41.1
 - Extension version: 8.7.1
 - TeX distribution version: MiKTeX 2.9.7076

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

Folder tree:
```cmd
C:.
│   anexos.tex
│   bibliografia.bib
│   capitulo1.tex
│   capitulo2.tex
│   capitulo2propuesta.tex
│   capitulo3.tex
│   capitulo4.tex
│   capitulo5.tex
│   configurationFile.tex
│   dependencias.tex
│   frontContentTesis.tex
│   Plantillas.tex
│   portada.tex
│   principalTesis.fls
│   principalTesis.pdf
│   principalTesis.synctex.gz
│   principalTesis.tex (My main file)
│   print.txt
│   referencias.bib
│
├───FrontContent
│       Agradecimiento.tex
│       cartaAprobacion.tex
│       contraPortada.tex
│       Dedicatoria.tex
│       Introduccion.tex
│       Resumen.tex
│
├───imagenes
│   │   analisis.pdf
│   │   analisisSS.pdf
│   │   bodeG1.pdf
│   │   bodeG2.pdf
│   │   ConfAvz.pdf
│   │   ConfBloques.pdf
│   │   ConfControlador.pdf
│   │   ConfGeneral.pdf
│   │   entonacionCSV.pdf
│   │   entonacionPID.pdf
│   │   esquemaLazoAbierto.pdf
│   │   esquemaLazoCerrado.pdf
│   │   esquemaPID.pdf
│   │   estructuraMain.pdf
│   │   FuzzyFront.pdf
│   │   FuzzyIO.pdf
│   │   FuzzyPrueba.pdf
│   │   FuzzyRespuesta.pdf
│   │   FuzzyRules.pdf
│   │   FuzzySet.pdf
│   │   GainScheduler.pdf
│   │   GainschedulerTomo.pdf
│   │   gaussmf.pdf
│   │   gbellmf.pdf
│   │   nyquistPlot.pdf
│   │   pdDifuso.pdf
│   │   pdFuzzyTomo.pdf
│   │   pdplusIDifuso.pdf
│   │   pFuzzyTomo.pdf
│   │   pidDifuso.pdf
│   │   pidFuzzyTomo.pdf
│   │   piDifuso.pdf
│   │   pidplusDifuso.pdf
│   │   pidplusFuzzyTomo.pdf
│   │   piFuzzyTomo.pdf
│   │   pipdDifuso.pdf
│   │   piplusDDifuso.pdf
│   │   pzmap.pdf
│   │   rootLocus.pdf
│   │   sigmf.pdf
│   │   SimulacionGeneral.pdf
│   │   SimulacionPlot.pdf
│   │   smf.pdf
│   │   trapmf.pdf
│   │   trimf.pdf
│   │   UML.pdf
│   │   unet.jpg
│   │   ZieglerN.pdf
│   │   zmf.pdf
│   │
│   ├───LV
│   │       inputGraph.pdf
│   │       outputGraph.pdf
│   │       Pc.pdf
│   │       Pd.pdf
│   │       PDGc1.pdf
│   │       PDGc2.pdf
│   │       PDGd.pdf
│   │       PDmasIc.pdf
│   │       PDmasId.pdf
│   │       PIc.pdf
│   │       PIcf1.pdf
│   │       PIcf2.pdf
│   │       PId.pdf
│   │       PIDc.pdf
│   │       PIDcf1.pdf
│   │       PIDcf2.pdf
│   │       PIDd.pdf
│   │       PIDdf.pdf
│   │       PIdf.pdf
│   │       PIDmasfc.pdf
│   │       PIDmasfd.pdf
│   │       PImasDc.pdf
│   │       PImasDd.pdf
│   │       TomoC1.pdf
│   │       TomoC21.pdf
│   │       TomoC22.pdf
│   │
│   ├───MATLAB
│   │       Set1Bode.png
│   │       Set1DBode.png
│   │       Set1DImp.png
│   │       Set1DNichols.png
│   │       Set1DNyquist.png
│   │       Set1DRlocus.png
│   │       Set1DStep.png
│   │       Set1Imp.png
│   │       Set1Nichols.png
│   │       Set1Nyquist.png
│   │       Set1Rlocus.png
│   │       Set1Step.png
│   │       Set2Bode.png
│   │       Set2DBode.png
│   │       Set2DImp.png
│   │       Set2DNichols.png
│   │       Set2DNyquist.png
│   │       Set2DRlocus.png
│   │       Set2DStep.png
│   │       Set2Imp.png
│   │       Set2Nichols.png
│   │       Set2Nyquist.png
│   │       Set2Rlocus.png
│   │       Set2Step.png
│   │       Set3Bode.png
│   │       Set3DBode.png
│   │       Set3DImp.png
│   │       Set3DNichols.png
│   │       Set3DNyquist.png
│   │       Set3DRlocus.png
│   │       Set3DStep.png
│   │       Set3Imp.png
│   │       Set3Nichols.png
│   │       Set3Nyquist.png
│   │       Set3Rlocus.png
│   │       Set3Step.png
│   │       TomoC1.pdf
│   │       TomoC21.pdf
│   │       TomoC22.pdf
│   │
│   └───SciLab
│           ScSet1Bode.png
│           ScSet1DBode.png
│           ScSet1DImp.png
│           ScSet1DNichols.png
│           ScSet1DNyquist.png
│           ScSet1DStep.png
│           ScSet1Imp.png
│           ScSet1Nichols.png
│           ScSet1Nyquist.png
│           ScSet1Step.png
│           ScSet2Bode.png
│           ScSet2Imp.png
│           ScSet2Nichols.png
│           ScSet2Nyquist.png
│           ScSet2Step.png
│           TomoC1.pdf
│           TomoC21.pdf
│           TomoC22.pdf
│
└───tobedeleted
    │   configurationFile.aux
    │   dependencias.aux
    │   FrontContentTesis.aux
    │   portada.aux
    │   principalTesis.aux
    │   principalTesis.bbl
    │   principalTesis.bcf
    │   principalTesis.blg
    │   principalTesis.lof
    │   principalTesis.log
    │   principalTesis.lol
    │   principalTesis.lot
    │   principalTesis.out
    │   principalTesis.run.xml
    │   principalTesis.toc
    │
    └───_minted-principalTesis
            08EFA9ADD77725A09D5A2DB0373565A12006DD731FD6FAF559ABDC4D555BC951.pygtex
            1EA971D09BE72498C68D8D998F2ECFF8FC7D727240977648714AFC6841A6D2A0.pygtex
            2A0475FA3A668F44E25DD5AB1958ED952006DD731FD6FAF559ABDC4D555BC951.pygtex
            357D24AA171B655DB0AE03EAEFE20B262006DD731FD6FAF559ABDC4D555BC951.pygtex
            3E0789AB22D6FCAEDD16CFB76AB110E4FC7D727240977648714AFC6841A6D2A0.pygtex
            5A5DCDC416A6C512B9D332C987EE5E542006DD731FD6FAF559ABDC4D555BC951.pygtex
            73FB0C2B426489CDB0E5EFD2CA21568BFC7D727240977648714AFC6841A6D2A0.pygtex
            79353262D26125C7C78C99F3FB65AFB82006DD731FD6FAF559ABDC4D555BC951.pygtex
            8026F4BDA1672C0F91CB03714248595F2006DD731FD6FAF559ABDC4D555BC951.pygtex
            8297C6715D4E573A57326B93F1A16EC02006DD731FD6FAF559ABDC4D555BC951.pygtex
            86430C062F397784D35E75EBFF29DD832006DD731FD6FAF559ABDC4D555BC951.pygtex
            870120E11963AAFC6E45EFA82ACECD612006DD731FD6FAF559ABDC4D555BC951.pygtex
            93CB327E04493E5F2C70ABBF7A20A665FC7D727240977648714AFC6841A6D2A0.pygtex
            94840C523B6942BEEACFE57E15E73D6DFC7D727240977648714AFC6841A6D2A0.pygtex
            9FC5071F2B0EBE68E5803A400DE949EFFC7D727240977648714AFC6841A6D2A0.pygtex
            AF8C6DA93A3F761111770FFF51DD68592006DD731FD6FAF559ABDC4D555BC951.pygtex
            B0AC058245E1D203168F8875CBAF1BB2FC7D727240977648714AFC6841A6D2A0.pygtex
            BBB57A9DE207D528D59176FB8DCE86012006DD731FD6FAF559ABDC4D555BC951.pygtex
            C3AB969FEF33774BFF45FAECEBBD27842006DD731FD6FAF559ABDC4D555BC951.pygtex
            default-pyg-prefix.pygstyle
            default.pygstyle
            E4F6E1141FF4E994AEF57513851DDE662006DD731FD6FAF559ABDC4D555BC951.pygtex
            EBBB5C2EDDFD878D79A2616C1E394B9D2006DD731FD6FAF559ABDC4D555BC951.pygtex
            F32EE7CC6B55D073B8E01D76B2C40599FC7D727240977648714AFC6841A6D2A0.pygtex
            FFCE319BD4C14656A08929096578CF9EFC7D727240977648714AFC6841A6D2A0.pygtex
```

**Comment by tamuratak** [comment]
Setting `latex-workshop.hover.preview.newcommand.parseTeXFile.enabled` to false might be a workaround.

https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewnewcommandparseTeXFileenabled

**Comment by ezalorpro** [comment]
Indeed, that solves the problem. So, every use of \newcommand causes this problem? even if they are not math related? i read a couple closed issues on the matter, but i though that was a problem with \newcommand exclusively with math functions.

**Comment by jlelong** [comment]
We cannot know if a `\newcommand` is related to maths or not. So we inject all of them into mathjax, but unfortunately mathjax cannot understand all TeX constructions. Hence your problem. 
A workaround is 
- set `latex-workshop.hover.preview.newcommand.parseTeXFile.enabled` to `false``
- put the required math newcommands in a dedicated file and let mathjax know about the file by setting `latex-workshop.hover.preview.newcommand.newcommandFile`.
