### ISSUE TITLE
"Auto Focus" setting keeps re-enabling

### ISSUE THREAD

**Issue by jamerst** [James-Yu/LaTeX-Workshop#1970]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

Upon opening a .tex file, the Auto Focus (latex-workshop.view.autoFocus.enabled) re-enables itself.

### To Reproduce

1. Open a .tex file
2. Disable auto focus setting
3. Click on the PDF preview
4. Sidebar is not changed
5. Re-open .tex file
6. Click on PDF preview
7. LaTeX sidebar is shown and auto focus setting is re-enabled

### Expected behavior

Setting should not be reset

## Logs [Required]

Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[19:26:50] Initializing LaTeX Workshop.
[19:26:50] Creating file watcher for .pdf files.
[19:26:50] Creating LaTeX Workshop http and websocket server.
[19:26:50] LaTeX Workshop initialized.
[19:26:50] Server created on 127.0.0.1:43995
[19:26:50] Snippet data loaded.
[19:26:50] LaTeX Workshop version: 8.7.2
[19:26:50] Found files that might be root, choose the first one: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex,/home/james/src/warwick-cs355/labs/report1/cs355-lab-report-1.tex
[19:26:50] Root file changed from: undefined to /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex. Find all dependencies.
[19:26:50] Instantiating a new file watcher for /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:26:50] Creating file watcher for .bib files.
[19:26:50] Parsing /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:26:50] Adding /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex to file watcher.
[19:27:02] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:02] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:02] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:02] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:04] VIEW command invoked with mode: file:///home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:04] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:04] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:04] Serving PDF file at http://localhost:43995/viewer.html?file=pdf..JTJGaG9tZSUyRmphbWVzJTJGc3JjJTJGd2Fyd2ljay1jczM1NSUyRmxhYnMlMkZyZXBvcnQyJTJGY3MzNTUtbGFiLXJlcG9ydC0yLnBkZg
[19:27:04] The encoded path is /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.pdf
[19:27:04] Open PDF tab for /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.pdf
[19:27:04] Handle data type: open
[19:27:05] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:05] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:05] Preview PDF file: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.pdf
[19:27:05] Handle data type: request_params
[19:27:05] Handle data type: loaded
[19:27:10] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:10] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:25] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:25] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:26] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:26] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:26] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:26] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:27] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:27] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:29] Handle data type: close
[19:27:31] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:31] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:31] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:31] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:33] VIEW command invoked with mode: file:///home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:33] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:33] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:33] Serving PDF file at http://localhost:43995/viewer.html?file=pdf..JTJGaG9tZSUyRmphbWVzJTJGc3JjJTJGd2Fyd2ljay1jczM1NSUyRmxhYnMlMkZyZXBvcnQyJTJGY3MzNTUtbGFiLXJlcG9ydC0yLnBkZg
[19:27:33] The encoded path is /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.pdf
[19:27:33] Open PDF tab for /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.pdf
[19:27:34] Handle data type: open
[19:27:34] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:34] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:34] Preview PDF file: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.pdf
[19:27:34] Handle data type: request_params
[19:27:34] Handle data type: loaded
[19:27:37] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:37] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:54] LOG command invoked.
[19:27:54] Found root file from active editor: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex
[19:27:54] Root file remains unchanged from: /home/james/src/warwick-cs355/labs/report2/cs355-lab-report-2.tex.
[19:27:57] LOG command invoked.
```

### Developer Tools Console [Required]

```
ERR Unable to write to User Settings because latex-workshop.view.autoActivateLatex.enabled is not a registered configuration.: Error: Unable to write to User Settings because latex-workshop.view.autoActivateLatex.enabled is not a registered configuration.
    at k.reject (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4735:465)
    at k.resolveAndValidate (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4738:243)
    at k.doWriteConfiguration (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4732:722)
    at Object.factory (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4732:498)
    at u.consume (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:149:609)
    at u.consumed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:149:770)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:149:651
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
console.ts:137 [Extension Host] Found no documents
log.ts:197   ERR Unable to write to User Settings because latex-workshop.view.autoActivateLatex.enabled is not a registered configuration.: Error: Unable to write to User Settings because latex-workshop.view.autoActivateLatex.enabled is not a registered configuration.
    at k.reject (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4735:465)
    at k.resolveAndValidate (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4738:243)
    at k.doWriteConfiguration (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4732:722)
    at Object.factory (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4732:498)
    at u.consume (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:149:609)
    at u.consumed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:149:770)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:149:651
webviewElement.ts:241 [Embedded Page] PDF 233b350f926c40226fa96539a982c8bd [1.5 pdfTeX-1.40.20 / LaTeX with hyperref] (PDF.js: 2.2.228)
log.ts:197   ERR Unable to write to User Settings because latex-workshop.view.autoActivateLatex.enabled is not a registered configuration.: Error: Unable to write to User Settings because latex-workshop.view.autoActivateLatex.enabled is not a registered configuration.
    at k.reject (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4735:465)
    at k.resolveAndValidate (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4738:243)
    at k.doWriteConfiguration (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4732:722)
    at Object.factory (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4732:498)
    at u.consume (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:149:609)
    at u.consumed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:149:770)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:149:651
webviewElement.ts:241 [Embedded Page] PDF 233b350f926c40226fa96539a982c8bd [1.5 pdfTeX-1.40.20 / LaTeX with hyperref] (PDF.js: 2.2.228)
```
## Desktop [Required]
 - OS: Linux (Fedora 31)
 - VS Code version: 1.42.1
 - Extension version: 8.7.2
 - TeX distribution version: N/A

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
From the _Developer Tools Console_, you have a `latex-workshop.view.autoActivateLatex.enabled` configuration causing some issue. It was renamed some time ago into `latex-workshop.view.autoFocus.enabled`. Check your global and workspace settings for the culprit `latex-workshop.view.autoActivateLatex.enabled`.

**Comment by jamerst** [comment]
Removing that old setting fixed it. Thanks.
