### ISSUE TITLE
Activating extension `James-Yu.latex-workshop` failed:  Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by Philip-Trettner** [James-Yu/LaTeX-Workshop#208]
### Description

Sometimes Latex Workshop works, but most of the time no command works.
Please see log.

### LaTeX Workshop log messages

<details>
<summary>Log messages</summary>

LaTeX Workshot Output:

```
[15:28:09] Initializing LaTeX Workshop.
[15:28:09] Creating LaTeX Workshop http and websocket server.
[15:28:09] LaTeX Workshop initialized.
[15:28:09] Server created on 127.0.0.1:6996
[15:28:09] Default environments loaded
[15:28:09] Default commands loaded
[15:28:09] Default unimathsymbols loaded
[15:29:14] ACTIONS command invoked.
[15:29:21] ACTIONS command invoked.
[15:35:25] ACTIONS command invoked.
```

Developer Console (Startup):

```
[Extension Host] Here is the error stack:  TypeError: Cannot read property 'on' of undefined
    at new SectionNodeProvider (C:\Users\ArtificialMind\.vscode\extensions\James-Yu.latex-workshop-3.0.0\out\src\providers\outline.js:21:38)
    at C:\Users\ArtificialMind\.vscode\extensions\James-Yu.latex-workshop-3.0.0\out\src\main.js:191:92
    at Generator.next (<anonymous>)
    at C:\Users\ArtificialMind\.vscode\extensions\James-Yu.latex-workshop-3.0.0\out\src\main.js:7:71
    at __awaiter (C:\Users\ArtificialMind\.vscode\extensions\James-Yu.latex-workshop-3.0.0\out\src\main.js:3:12)
    at activate (C:\Users\ArtificialMind\.vscode\extensions\James-Yu.latex-workshop-3.0.0\out\src\main.js:111:12)
    at Function.t._callActivateOptional (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:418005)
    at Function.t._callActivate (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:417790)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:417565
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:41973)
```

Developer Console (Clicking Show Workshop Actions)

```
Running the contributed command:'latex-workshop.actions' failed.: Error: Running the contributed command:'latex-workshop.actions' failed.
    at t.$executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:328177)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308956)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189275)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189930)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ shell.ts:443
(anonymous) @ shell.ts:403
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:139
(anonymous) @ errors.ts:49
(anonymous) @ errors.ts:44
```

VS Code:
* Version 1.14.2
* Shell 1.6.6
* Node 7.4.0
* Windows 10 64Bit

</details>

**Comment by James-Yu** [comment]
Hmm.. This is because that the extension cannot find the root file. My guess is that you opened a `.tex` file without `\begin{document}`. Please confirm if I am right.

**Comment by James-Yu** [comment]
Fixed

**Comment by Philip-Trettner** [comment]
Oh yeah you're right, I thought it would find it in the same folder but only does so if I have it open. Thanks!
