### ISSUE TITLE
Synctex problem with Docker building

### ISSUE THREAD

**Issue by Syndlex** [James-Yu/LaTeX-Workshop#2107]
## Preliminary questions [Required]
How do i get Synctex working with Docker  when I have multiple files in subdirectories

### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.
You visited the wiki?: Yes

## Describe the bug [Required]

Synctex does not work on tex files that are in a sub folder 
Build with Docker
Multiple files in Subdirectories

### To Reproduce

1. Build File
2. Navigate to tex file in sub dir.
3. use `Synctex from cursor`
4. nothing is heppening

### Expected behavior

Pdf in internal viewer is navigating to cursor

## Logs [Required]
Using External Synctex - 
[15:24:55] SYNCTEX command invoked.
[15:24:55] Executing synctex with args view,-i,39:1:expose.tex,-o,thesis.pdf

Using Internal Synctexjs
```
SyncTexJsError: no relevant entry of tex file found in the synctex file.
	at Object.syncTexJsForward (/run/media/marcel/Linux2/home/marcel/.vscode-oss/extensions/james-yu.latex-workshop-8.9.0/out/src/components/synctex.js:51:15)
	at Locator.syncTeX (/run/media/marcel/Linux2/home/marcel/.vscode-oss/extensions/james-yu.latex-workshop-8.9.0/out/src/components/locator.js:133:42)
	at Commander.synctex (/run/media/marcel/Linux2/home/marcel/.vscode-oss/extensions/james-yu.latex-workshop-8.9.0/out/src/commander.js:220:32)
	at /run/media/marcel/Linux2/home/marcel/.vscode-oss/extensions/james-yu.latex-workshop-8.9.0/out/src/main.js:66:89
	at e._executeContributedCommand (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:220)
	at e.$executeContributedCommand (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:595)
	at e._doInvokeHandler (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:683)
	at e._invokeHandler (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:375)
	at e._receiveRequest (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:14)
	at e._receiveOneMessage (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:749:832)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:748:34
	at e.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at v.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:206:615)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:919:744
	at e.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at v.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:206:615)
	at t.PersistentProtocol._receiveMessage (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:211:17)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:208:155
	at e.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at p.acceptChunk (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:204:129)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:203:483
	at Socket.t (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:212:565)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
### Developer Tools Console [Required]

```
Empty
```
## Desktop [Required]
 - OS: Linux Manjaro 5.6.12-1
 - VS Code version: 1.41.2
 - Extension version: 8.9.0
 - TeX distribution version: The normal Dockerfile

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. It should start with `Initializing LaTeX Workshop.`

**Comment by tamuratak** [comment]
Try setting `latex-workshop.synctex.synctexjs.enabled: false`. See https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopsynctexsynctexjsenabled

**Comment by Syndlex** [comment]
@tamuratak Here is the full log

I tryed it with and without the buildin synctexjs option.

```
[16:03:24] Initializing LaTeX Workshop.
[16:03:24] Creating file watcher for .pdf files.
[16:03:24] Creating LaTeX Workshop http and websocket server.
[16:03:24] LaTeX Workshop initialized.
[16:03:24] Found root file by magic comment: /home/syndlex/repo/f/workdir/thesis.tex
[16:03:24] Linter for root file started.
[16:03:24] No root file found for linting.
[16:03:24] Root file changed from: undefined to /home/syndlex/repo/f/workdir/thesis.tex. Find all dependencies.
[16:03:24] Instantiating a new file watcher for /home/syndlex/repo/f/workdir/thesis.tex
[16:03:24] Creating file watcher for .bib files.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/thesis.tex
[16:03:24] Parsing /home/syndlex/repo/f/workdir/hdathesis-config.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/classicthesis-config.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/frontbackmatter/Titlepage.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/frontbackmatter/Titleback.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/frontbackmatter/Declaration.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/frontbackmatter/AbstractEN.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/frontbackmatter/AbstractDE.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/frontbackmatter/Contents.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/frontbackmatter/Figures.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/frontbackmatter/Tables.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/frontbackmatter/Listings.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/frontbackmatter/Acronyms.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/chapters/einleitung/expose.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/chapters/grundlagen/Grundlagen.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/chapters/architektur/Architektur.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/chapters/technologie/Technologie.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/chapters/implementierung/Implementierung.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/chapters/fazit/Fazit.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Parsing /home/syndlex/repo/f/workdir/frontbackmatter/Bibliography.tex
[16:03:24] Parse fls file.
[16:03:24] Cannot find fls file.
[16:03:24] Found .bib file /home/syndlex/repo/f/workdir/Bib/bibliography.bib
[16:03:24] Adding .bib file /home/syndlex/repo/f/workdir/Bib/bibliography.bib to bib file watcher.
[16:03:24] Parsing .bib entries from /home/syndlex/repo/f/workdir/Bib/bibliography.bib
[16:03:24] Parse fls file.
[16:03:24] Found .bib file /home/syndlex/repo/f/workdir/thesis-blx.bib
[16:03:24] Adding .bib file /home/syndlex/repo/f/workdir/thesis-blx.bib to bib file watcher.
[16:03:24] Parsing .bib entries from /home/syndlex/repo/f/workdir/thesis-blx.bib
[16:03:24] Found .bib file /home/syndlex/repo/f/workdir/Bib/bibliography.bib
[16:03:24] Server created on 127.0.0.1:41643
[16:03:24] Adding /home/syndlex/repo/f/workdir/thesis.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/hdathesis-config.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/classicthesis-config.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/frontbackmatter/Titlepage.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/frontbackmatter/Titleback.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/frontbackmatter/Declaration.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/frontbackmatter/AbstractEN.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/frontbackmatter/AbstractDE.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/frontbackmatter/Contents.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/frontbackmatter/Figures.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/frontbackmatter/Tables.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/frontbackmatter/Listings.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/frontbackmatter/Acronyms.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/chapters/einleitung/expose.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/chapters/grundlagen/Grundlagen.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/chapters/architektur/Architektur.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/chapters/technologie/Technologie.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/chapters/implementierung/Implementierung.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/chapters/fazit/Fazit.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/frontbackmatter/Bibliography.tex to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/hdathesis.sty to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/classicthesis.sty to file watcher.
[16:03:24] Adding /home/syndlex/repo/f/workdir/gfx/logo_h-da_rot.pdf to file watcher.
[16:03:24] Snippet data loaded.
[16:03:24] LaTeX Workshop version: 8.9.0
[16:03:24] Parsed 15 bib entries from /home/syndlex/repo/f/workdir/Bib/bibliography.bib.
[16:03:24] Parsed 1 bib entries from /home/syndlex/repo/f/workdir/thesis-blx.bib.
[16:03:25] VIEW command invoked with mode: file:///home/syndlex/repo/f/workdir/chapters/einleitung/expose.tex.
[16:03:25] Found root file by magic comment: /home/syndlex/repo/f/workdir/thesis.tex
[16:03:25] Root file remains unchanged from: /home/syndlex/repo/f/workdir/thesis.tex.
[16:03:25] Serving PDF file at http://localhost:41643/viewer.html?file=pdf..JTJGaG9tZSUyRm1hcmNlbCUyRnJlcG8lMkZmZWl4JTJGTWFzdGVyYXJiZWl0JTJGdGhlc2lzLnBkZg
[16:03:25] The encoded path is /home/syndlex/repo/f/workdir/thesis.pdf
[16:03:25] Open PDF tab for /home/syndlex/repo/f/workdir/thesis.pdf
[16:03:26] Handle data type: open
[16:03:26] Preview PDF file: /home/syndlex/repo/f/workdir/thesis.pdf
[16:03:26] Handle data type: request_params
[16:03:26] Found root file by magic comment: /home/syndlex/repo/f/workdir/thesis.tex
[16:03:26] Root file remains unchanged from: /home/syndlex/repo/f/workdir/thesis.tex.
[16:03:26] Handle data type: loaded
[16:03:26] SyncTex after build invoked.
[16:03:26] Executing synctex with args view,-i,44:8:expose.tex,-o,thesis.pdf
[16:03:28] SYNCTEX command invoked.
[16:03:28] Executing synctex with args view,-i,44:8:expose.tex,-o,thesis.pdf
[16:03:57] Found root file by magic comment: /home/syndlex/repo/f/workdir/thesis.tex
[16:03:57] Root file remains unchanged from: /home/syndlex/repo/f/workdir/thesis.tex.
[16:04:00] SYNCTEX command invoked.
[16:04:01] SyncTeX failed.
[16:04:01] no relevant entry of tex file found in the synctex file.
[16:04:01] SyncTexJsError: no relevant entry of tex file found in the synctex file.
	at Object.syncTexJsForward (/run/media/syndlex/Linux2/home/syndlex/.vscode-oss/extensions/james-yu.latex-workshop-8.9.0/out/src/components/synctex.js:51:15)
	at Locator.syncTeX (/run/media/syndlex/Linux2/home/syndlex/.vscode-oss/extensions/james-yu.latex-workshop-8.9.0/out/src/components/locator.js:133:42)
	at Commander.synctex (/run/media/syndlex/Linux2/home/syndlex/.vscode-oss/extensions/james-yu.latex-workshop-8.9.0/out/src/commander.js:220:32)
	at /run/media/syndlex/Linux2/home/syndlex/.vscode-oss/extensions/james-yu.latex-workshop-8.9.0/out/src/main.js:66:89
	at e._executeContributedCommand (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:220)
	at e.$executeContributedCommand (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:595)
	at e._doInvokeHandler (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:683)
	at e._invokeHandler (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:375)
	at e._receiveRequest (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:14)
	at e._receiveOneMessage (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:749:832)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:748:34
	at e.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at v.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:206:615)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:919:744
	at e.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at v.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:206:615)
	at t.PersistentProtocol._receiveMessage (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:211:17)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:208:155
	at e.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at p.acceptChunk (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:204:129)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:203:483
	at Socket.t (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:212:565)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by tamuratak** [comment]
Please describe your configuration in detail. 

- How do you compile your document with Docker? Are you setting `latex-workshop.docker.enabled: true`?
- Why are `/home/syndlex/` and `/run/media/syndlex/Linux2/home/syndlex/` different?
- Please show the whole log when you build the Tex file.

**Comment by Syndlex** [comment]
How do you compile your document with Docker? Are you setting latex-workshop.docker.enabled: true? 
YES i use this setting.

Why are /home/syndlex/ and /run/media/syndlex/Linux2/home/syndlex/ different?

That was the problem.
/home/ is a symlink to /run/media/syndlex/Linux2/home/

Moved the folder Repo away from the home folder. its working now.
Sems like Synctexjs is resolving the Symlink while the latex compiler in Docker leaves the Path unsolved.

Make sure that thesis.synxtex or thesis.synctex.gz exists. Please show us the content of the file with gunzip. 
[thesis.synctex.gz](https://github.com/James-Yu/LaTeX-Workshop/files/4672899/thesis.synctex.gz)

**Comment by Syndlex** [comment]
@tamuratak  Thank you this is looking nice.
