### ISSUE TITLE
keyword typed is automatically removed when pressing return

### ISSUE THREAD

**Issue by zhyiyu** [James-Yu/LaTeX-Workshop#2113]
## Describe the bug
I type in `\item` by hand and click <kbd>return</kbd> to continue to next line, but the `\item` I type is removed automatically.

### Screenshots

![disappear](https://user-images.githubusercontent.com/26550166/82857908-55f1e300-9ee0-11ea-87c2-84dd0ce3a6a2.gif)

### Expected behavior

I understand if an automatically generated `\item` is removed, but I typed that `\item`, I think it makes more sense to keep it.

### LaTeX Workshop Output [Required]

```
[23:18:58] Initializing LaTeX Workshop.
[23:18:58] Creating file watcher for .pdf files.
[23:18:58] Creating LaTeX Workshop http and websocket server.
[23:18:58] LaTeX Workshop initialized.
[23:18:58] Found root file from active editor: /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/log.tex
[23:18:58] Root file changed from: undefined to /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/log.tex. Find all dependencies.
[23:18:58] Instantiating a new file watcher for /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/log.tex
[23:18:58] Creating file watcher for .bib files.
[23:18:58] Parsing /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/log.tex
[23:18:58] Found .bib file /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/biber.bib
[23:18:58] Adding .bib file /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/biber.bib to bib file watcher.
[23:18:58] Parsing .bib entries from /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/biber.bib
[23:18:58] Parse fls file.
[23:18:58] Cannot find fls file.
[23:18:58] Server created on 127.0.0.1:49349
[23:18:58] Adding /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/log.tex to file watcher.
[23:18:58] Snippet data loaded.
[23:18:58] LaTeX Workshop version: 8.9.0
[23:18:59] Error parsing BibTeX: line 29 in /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/biber.bib.
[23:21:22] LOG command invoked.
[23:21:53] Found root file from active editor: /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/log.tex
[23:21:53] Root file remains unchanged from: /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/log.tex.
[23:21:53] Found root file from active editor: /Users/zyy/Dropbox/应用/Overleaf/annual review/presentation/main.tex
[23:21:53] Found root file from active editor: /Users/zyy/Dropbox/应用/Overleaf/annual review/presentation/main.tex
[23:21:53] Root file changed from: /Users/zyy/Dropbox/work/working/jefferson lab/scholarship/monte carlo/note/log/log.tex to /Users/zyy/Dropbox/应用/Overleaf/annual review/presentation/main.tex. Find all dependencies.
[23:21:53] Root file changed -> cleaning up old file watcher.
[23:21:53] Instantiating a new file watcher for /Users/zyy/Dropbox/应用/Overleaf/annual review/presentation/main.tex
[23:21:53] Parsing /Users/zyy/Dropbox/应用/Overleaf/annual review/presentation/main.tex
[23:21:53] Parse fls file.
[23:21:53] Cannot find fls file.
[23:21:53] Root file remains unchanged from: /Users/zyy/Dropbox/应用/Overleaf/annual review/presentation/main.tex.
[23:21:53] Adding /Users/zyy/Dropbox/应用/Overleaf/annual review/presentation/main.tex to file watcher.
[23:22:09] LOG command invoked.
[23:24:34] Found root file from active editor: /Users/zyy/Dropbox/应用/Overleaf/annual review/presentation/main.tex
[23:24:34] Root file remains unchanged from: /Users/zyy/Dropbox/应用/Overleaf/annual review/presentation/main.tex.
```

### Developer Tools Console [Required]

```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: SyntaxError: Expected "=", "\r\n", or [ \t\n] but "j" found.
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: SyntaxError: Expected "=", "\r\n", or [ \t\n] but "j" found.    at peg$buildStructuredError (/Users/zyy/.vscode/extensions/james-yu.latex-workshop-8.9.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:366:12)    at Object.peg$parse [as parse] (/Users/zyy/.vscode/extensions/james-yu.latex-workshop-8.9.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:2011:11)    at Object.parse (/Users/zyy/.vscode/extensions/james-yu.latex-workshop-8.9.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser.js:24:30)    at Function.parseBibtex (/Users/zyy/.vscode/extensions/james-yu.latex-workshop-8.9.0/out/src/components/parser/syntax_worker.js:12:42)    at process.<anonymous> (/Users/zyy/.vscode/extensions/james-yu.latex-workshop-8.9.0/node_modules/workerpool/dist/workerpool.min.js:25:16221)    at process.emit (events.js:203:13)    at emit (internal/child_process.js:876:12)    at processTicksAndRejections (internal/process/task_queues.js:77:11)
  ERR Expected "=", "\r\n", or [ \t\n] but "j" found.: SyntaxError: Expected "=", "\r\n", or [ \t\n] but "j" found.
    at peg$buildStructuredError (/Users/zyy/.vscode/extensions/james-yu.latex-workshop-8.9.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:366:12)
    at Object.peg$parse [as parse] (/Users/zyy/.vscode/extensions/james-yu.latex-workshop-8.9.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:2011:11)
    at Object.parse (/Users/zyy/.vscode/extensions/james-yu.latex-workshop-8.9.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser.js:24:30)
    at Function.parseBibtex (/Users/zyy/.vscode/extensions/james-yu.latex-workshop-8.9.0/out/src/components/parser/syntax_worker.js:12:42)
    at process.<anonymous> (/Users/zyy/.vscode/extensions/james-yu.latex-workshop-8.9.0/node_modules/workerpool/dist/workerpool.min.js:25:16221)
    at process.emit (events.js:203:13)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
2console.ts:137 [Extension Host] (node:20301) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
## Desktop
 - OS: macOS 10.15.4
 - VS Code version: 1.45.1
 - Extension version: 8.9.0
 - TeX distribution version: TeX Live 2018

**Comment by jlelong** [comment]
Unfortunately there is no way to know if `\item` was typed or inserted automatically. 

The complete behaviour is described on https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#Itemize-like-environments

**Comment by zhyiyu** [comment]
Thanks, I might just close automatic insertion with

```
"latex-workshop.bind.enter.key": false
```

Thanks for pointing out the error, I think it is fixed.
