### ISSUE TITLE
Error while parsing custom command file

### ISSUE THREAD

**Issue by tobiasdiez** [James-Yu/LaTeX-Workshop#2119]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Setting a custom file with latex commands breaks preview

### To Reproduce

1. Set "latex-workshop.hover.preview.newcommand.newcommandFile" to the attached file. 
[myMathHeader.txt](https://github.com/James-Yu/LaTeX-Workshop/files/4690238/myMathHeader.txt)
2. Hover over an existing equation
3. No preview shown, error logged in "Log (Window)".

The log in the developer console suggests that there is a problem with parsing the file (which should be a problem in the file parser since Latex has no problem with the file).

### Expected behavior

Preview shown, with commands rendered nicely. Or at least a proper error message that helps diagnosing the problem.

## Logs [Required]

```
[2020-05-27 17:43:11.997] [renderer1] [error] An unknown error occurred. Please consult the log for more details.: Error: 
	at c:\Users\Tobi\.vscode\extensions\james-yu.latex-workshop-8.9.0\node_modules\workerpool\dist\workerpool.min.js:25:9316
	at ChildProcess.<anonymous> (c:\Users\Tobi\.vscode\extensions\james-yu.latex-workshop-8.9.0\node_modules\workerpool\dist\workerpool.min.js:25:9391)
	at ChildProcess.emit (events.js:203:13)
	at emit (internal/child_process.js:876:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

### LaTeX Workshop Output [Required]

```
[18:23:53] Found root file from active editor: d:\Research\Publications and talks\2020 - Singular cotangent bundle reduction\DR-singular cotangent bundle.tex
[18:23:53] Root file remains unchanged from: d:\Research\Publications and talks\2020 - Singular cotangent bundle reduction\DR-singular cotangent bundle.tex.
```

### Developer Tools Console [Required]

```
Extension Host
extensionHost.ts:213 TeX parse error: Extra close brace or missing open brace
log.ts:197   ERR An unknown error occurred. Please consult the log for more details.: Error: 
	at c:\Users\Tobi\.vscode\extensions\james-yu.latex-workshop-8.9.0\node_modules\workerpool\dist\workerpool.min.js:25:9316
	at ChildProcess.<anonymous> (c:\Users\Tobi\.vscode\extensions\james-yu.latex-workshop-8.9.0\node_modules\workerpool\dist\workerpool.min.js:25:9391)
	at ChildProcess.emit (events.js:203:13)
	at emit (internal/child_process.js:876:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.45.1
 - Extension version: 8.9.0
 - TeX distribution version: TeX Live 2019

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
Your file contains LaTeX3 code and cannot be understood by `mathjax`, which is used by the extension to provide preview on hover. The  message `TeX parse error: Extra close brace or missing open brace` is raised by `mathjax` itself. There is not much we can do. See [`mathjax` documentation](http://docs.mathjax.org/en/latest/input/tex/extensions/newcommand.html).

**Comment by tobiasdiez** [comment]
Thanks for the quick reply! In this case I would suggest to log the `TeX parse error` message at least to the normal console, maybe pointing to mathjax. The workerpool error message currently shown helps little in seeing whats wrong.
