### ISSUE TITLE
Go-to-symbol not working with \label

### ISSUE THREAD

**Issue by karljs** [James-Yu/LaTeX-Workshop#219]
### Description

When working with any new or old LaTeX project of mine, the go-to-symbol function accessed with `cmd-t` or `cmd-shift-o` is unable to find any symbols.  I am under the impression that it should find labels such as `\label{myLabel}`.

### How to reproduce

1. Create a new LaTeX document which contains the following code:
```
\documentclass{article}
\begin{document}
\section{Intro}
\label{sec:intro}
Lorem ipsum.
\end{document}
```
2. Press `cmd-t` and begin typing `sec:intro`
3. Notice that it is unable to find this symbol.
4. Try `cmd-shift-o` and begin typing `sec:intro`
5. Notice that this also fails

### Expected behavior

I expect the label `sec:intro` to be detected as a symbol I can navigate to, as briefly mentioned in #212

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>
[17:20:57] Initializing LaTeX Workshop.
[17:20:57] Creating LaTeX Workshop http and websocket server.
[17:20:57] LaTeX Workshop initialized.
[17:20:57] Found root file from active editor: Untitled-1
[17:20:57] Root file changed from: undefined. Find all dependencies.
[17:20:57] Instatiating new file watcher for Untitled-1
[17:20:57] Parsing Untitled-1
[17:20:57] Server created on 127.0.0.1:61387
[17:20:57] Default environments loaded
[17:20:57] Default commands loaded
[17:20:57] Default unimathsymbols loaded
[17:20:57] BUILD command invoked.
[17:20:57] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:20:57] Root file changed from: Untitled-1. Find all dependencies.
[17:20:57] Root file changed -> cleaning up old file watcher.
[17:20:57] Instatiating new file watcher for /Users/karl/workspace/textest/test.tex
[17:20:57] Parsing /Users/karl/workspace/textest/test.tex
[17:21:06] BUILD command invoked.
[17:21:06] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:21:06] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:21:06] Building root file: /Users/karl/workspace/textest/test.tex
[17:21:06] Build root file /Users/karl/workspace/textest/test.tex
[17:21:06] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:21:06] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:21:06] Parsing /Users/karl/workspace/textest/test.tex
[17:21:06] Refresh outline.
[17:21:06] Parsing /Users/karl/workspace/textest/test.tex
[17:21:07] LaTeX log parsed with 2 messages.
[17:21:07] Toolchain returns with error: 12/null.
[17:21:10] BUILD command invoked.
[17:21:10] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:21:10] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:21:10] Building root file: /Users/karl/workspace/textest/test.tex
[17:21:10] Build root file /Users/karl/workspace/textest/test.tex
[17:21:10] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:21:11] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:21:11] Parsing /Users/karl/workspace/textest/test.tex
[17:21:11] Refresh outline.
[17:21:11] Parsing /Users/karl/workspace/textest/test.tex
[17:21:11] Toolchain returns with error: 12/null.
[17:21:13] ACTIONS command invoked.
[17:21:31] BUILD command invoked.
[17:21:31] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:21:31] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:21:31] Building root file: /Users/karl/workspace/textest/test.tex
[17:21:31] Build root file /Users/karl/workspace/textest/test.tex
[17:21:31] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:21:31] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:21:31] Parsing /Users/karl/workspace/textest/test.tex
[17:21:31] Refresh outline.
[17:21:31] Parsing /Users/karl/workspace/textest/test.tex
[17:21:31] Toolchain returns with error: 12/null.
[17:22:19] BUILD command invoked.
[17:22:19] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:22:19] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:22:19] Building root file: /Users/karl/workspace/textest/test.tex
[17:22:19] Build root file /Users/karl/workspace/textest/test.tex
[17:22:19] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:22:19] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:22:19] Parsing /Users/karl/workspace/textest/test.tex
[17:22:19] Refresh outline.
[17:22:19] Parsing /Users/karl/workspace/textest/test.tex
[17:22:19] Toolchain returns with error: 12/null.
[17:22:32] BUILD command invoked.
[17:22:32] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:22:32] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:22:32] Building root file: /Users/karl/workspace/textest/test.tex
[17:22:32] Build root file /Users/karl/workspace/textest/test.tex
[17:22:32] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:22:32] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:22:32] Parsing /Users/karl/workspace/textest/test.tex
[17:22:32] Refresh outline.
[17:22:32] Parsing /Users/karl/workspace/textest/test.tex
[17:22:33] LaTeX log parsed with 0 messages.
[17:22:33] Toolchain of length 1 finished.
[17:22:33] Successfully built /Users/karl/workspace/textest/test.tex
[17:22:33] No PDF viewer connected for /Users/karl/workspace/textest/test.pdf
[17:22:58] BUILD command invoked.
[17:22:58] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:22:58] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:22:58] Building root file: /Users/karl/workspace/textest/test.tex
[17:22:58] Build root file /Users/karl/workspace/textest/test.tex
[17:22:58] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:22:58] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:22:58] Parsing /Users/karl/workspace/textest/test.tex
[17:22:58] Refresh outline.
[17:22:58] Parsing /Users/karl/workspace/textest/test.tex
[17:22:59] LaTeX log parsed with 0 messages.
[17:22:59] Toolchain of length 1 finished.
[17:22:59] Successfully built /Users/karl/workspace/textest/test.tex
[17:22:59] No PDF viewer connected for /Users/karl/workspace/textest/test.pdf
[17:23:00] BUILD command invoked.
[17:23:00] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:23:00] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:23:00] Building root file: /Users/karl/workspace/textest/test.tex
[17:23:00] Build root file /Users/karl/workspace/textest/test.tex
[17:23:00] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:23:00] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:23:00] Parsing /Users/karl/workspace/textest/test.tex
[17:23:00] Refresh outline.
[17:23:00] Parsing /Users/karl/workspace/textest/test.tex
[17:23:01] LaTeX log parsed with 0 messages.
[17:23:01] Toolchain of length 1 finished.
[17:23:01] Successfully built /Users/karl/workspace/textest/test.tex
[17:23:01] No PDF viewer connected for /Users/karl/workspace/textest/test.pdf
[17:25:02] BUILD command invoked.
[17:25:02] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:25:02] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:25:02] Building root file: /Users/karl/workspace/textest/test.tex
[17:25:02] Build root file /Users/karl/workspace/textest/test.tex
[17:25:02] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:25:02] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:25:02] Parsing /Users/karl/workspace/textest/test.tex
[17:25:02] Refresh outline.
[17:25:02] Parsing /Users/karl/workspace/textest/test.tex
[17:25:03] LaTeX log parsed with 0 messages.
[17:25:03] Toolchain of length 1 finished.
[17:25:03] Successfully built /Users/karl/workspace/textest/test.tex
[17:25:03] No PDF viewer connected for /Users/karl/workspace/textest/test.pdf
[17:25:11] BUILD command invoked.
[17:25:11] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:25:11] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:25:11] Building root file: /Users/karl/workspace/textest/test.tex
[17:25:11] Build root file /Users/karl/workspace/textest/test.tex
[17:25:11] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:25:11] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:25:11] Parsing /Users/karl/workspace/textest/test.tex
[17:25:11] Refresh outline.
[17:25:11] Parsing /Users/karl/workspace/textest/test.tex
[17:25:12] LaTeX log parsed with 0 messages.
[17:25:12] Toolchain of length 1 finished.
[17:25:12] Successfully built /Users/karl/workspace/textest/test.tex
[17:25:12] No PDF viewer connected for /Users/karl/workspace/textest/test.pdf
[17:27:07] BUILD command invoked.
[17:27:07] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:27:07] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:27:07] Building root file: /Users/karl/workspace/textest/test.tex
[17:27:07] Build root file /Users/karl/workspace/textest/test.tex
[17:27:07] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:27:07] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:27:07] Parsing /Users/karl/workspace/textest/test.tex
[17:27:07] Refresh outline.
[17:27:07] Parsing /Users/karl/workspace/textest/test.tex
[17:27:08] LaTeX log parsed with 0 messages.
[17:27:08] Toolchain of length 1 finished.
[17:27:08] Successfully built /Users/karl/workspace/textest/test.tex
[17:27:08] No PDF viewer connected for /Users/karl/workspace/textest/test.pdf
[17:27:13] TAB command invoked.
[17:27:13] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:27:13] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:27:13] No PDF viewer connected for /Users/karl/workspace/textest/test.pdf
[17:27:13] Serving PDF file at http://127.0.0.1:61387/viewer.html?file=/pdf:%2FUsers%2Fkarl%2Fworkspace%2Ftextest%2Ftest.pdf
[17:27:13] Open PDF tab for /Users/karl/workspace/textest/test.pdf
[17:27:15] BUILD command invoked.
[17:27:15] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:27:15] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:27:15] Building root file: /Users/karl/workspace/textest/test.tex
[17:27:15] Build root file /Users/karl/workspace/textest/test.tex
[17:27:15] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:27:15] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:27:15] Parsing /Users/karl/workspace/textest/test.tex
[17:27:15] Refresh outline.
[17:27:15] Parsing /Users/karl/workspace/textest/test.tex
[17:27:15] LaTeX log parsed with 0 messages.
[17:27:15] Toolchain of length 1 finished.
[17:27:15] Successfully built /Users/karl/workspace/textest/test.tex
[17:27:15] No PDF viewer connected for /Users/karl/workspace/textest/test.pdf
[17:27:16] BUILD command invoked.
[17:27:16] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:27:16] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:27:16] Building root file: /Users/karl/workspace/textest/test.tex
[17:27:16] Build root file /Users/karl/workspace/textest/test.tex
[17:27:16] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/karl/workspace/textest/test
[17:27:16] File watcher: responding to change in /Users/karl/workspace/textest/test.tex
[17:27:16] Parsing /Users/karl/workspace/textest/test.tex
[17:27:16] Refresh outline.
[17:27:16] Parsing /Users/karl/workspace/textest/test.tex
[17:27:17] LaTeX log parsed with 0 messages.
[17:27:17] Toolchain of length 1 finished.
[17:27:17] Successfully built /Users/karl/workspace/textest/test.tex
[17:27:17] No PDF viewer connected for /Users/karl/workspace/textest/test.pdf
[17:27:29] VIEW command invoked.
[17:27:29] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:27:29] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:27:29] No PDF viewer connected for /Users/karl/workspace/textest/test.pdf
[17:27:29] Serving PDF file at http://127.0.0.1:61387/viewer.html?file=/pdf:%2FUsers%2Fkarl%2Fworkspace%2Ftextest%2Ftest.pdf
[17:27:29] Open PDF viewer for /Users/karl/workspace/textest/test.pdf
[17:27:30] Preview PDF file: /Users/karl/workspace/textest/test.pdf
[17:29:20] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:29:21] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:29:21] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:30:26] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:30:27] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:30:27] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:30:29] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:30:29] Found root file from active editor: /Users/karl/workspace/textest/test.tex
[17:30:29] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
[17:30:49] Root file remains unchanged from: /Users/karl/workspace/textest/test.tex.
</details>

I believe the following tools log is not relevant to this issue, but rather something else to do with previewing the PDF.

<details>
<summary>Developer Tools Console</summary>
[Extension Host] Activating extension `James-Yu.latex-workshop` failed: ENOENT: no such file or directory, open 'Untitled-1'.
h.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:29 [Extension Host] Activating extension `James-Yu.latex-workshop` failed:  ENOENT: no such file or directory, open 'Untitled-1'
h.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:29 [Extension Host] Here is the error stack:  Error: ENOENT: no such file or directory, open 'Untitled-1'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Manager.findDependentFiles (/Users/karl/.vscode/extensions/James-Yu.latex-workshop-3.1.1/out/src/components/manager.js:137:28)
    at Manager.findAllDependentFiles (/Users/karl/.vscode/extensions/James-Yu.latex-workshop-3.1.1/out/src/components/manager.js:126:18)
    at Manager.findRoot (/Users/karl/.vscode/extensions/James-Yu.latex-workshop-3.1.1/out/src/components/manager.js:32:26)
    at /Users/karl/.vscode/extensions/James-Yu.latex-workshop-3.1.1/out/src/main.js:186:27
    at Generator.next (<anonymous>)
    at /Users/karl/.vscode/extensions/James-Yu.latex-workshop-3.1.1/out/src/main.js:7:71
workbench.main.js:28 Activating extension `James-Yu.latex-workshop` failed: ENOENT: no such file or directory, open 'Untitled-1'.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:29 Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at context.subscriptions.push.vscode.window.onDidChangeActiveTextEditor (/Users/karl/.vscode/extensions/James-Yu.latex-workshop-3.1.1/out/src/main.js:164:42)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:55860)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:57651)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:388682
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:55860)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:57651)
    at t.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:345325)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:308956)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189275)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189930)
e.onUnexpectedError @ workbench.main.js:29
workbench.main.js:28 Running the contributed command:'latex-workshop.actions' failed.
e.doShow @ workbench.main.js:28
workbench.main.js:29 Running the contributed command:'latex-workshop.actions' failed.: Error: Running the contributed command:'latex-workshop.actions' failed.
    at t.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:328177)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:308956)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189275)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189930)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ workbench.main.js:29
workbench.main.js:28 WARNING: Promise with no error callback:110
workbench.main.js:28 Object
workbench.main.js:29 Unable to open 'latex-workshop-pdf:/Users/karl/workspace/textest/test.pdf' resource is not available.
(anonymous) @ workbench.main.js:29
index.js:41 [uncaught exception]: Error: resource is not available
onError @ index.js:41
index.js:44 Error: resource is not available
    at workbench.main.js:29
    at n.Class.define.cancel.then (workbench.main.js:28)
    at t.resolveTextModelContent (workbench.main.js:29)
    at t.createReferencedObject (workbench.main.js:29)
    at t.e.acquire (workbench.main.js:4)
    at e._createModelReference (workbench.main.js:29)
    at e.createModelReference (workbench.main.js:29)
    at workbench.main.js:28
    at n.Class.define.cancel.then (workbench.main.js:28)
    at t.setInput (workbench.main.js:28)
onError @ index.js:44
workbench.main.js:28 Uncaught Error: resource is not available
    at workbench.main.js:29
    at n.Class.define.cancel.then (workbench.main.js:28)
    at t.resolveTextModelContent (workbench.main.js:29)
    at t.createReferencedObject (workbench.main.js:29)
    at t.e.acquire (workbench.main.js:4)
    at e._createModelReference (workbench.main.js:29)
    at e.createModelReference (workbench.main.js:29)
    at workbench.main.js:28
    at n.Class.define.cancel.then (workbench.main.js:28)
    at t.setInput (workbench.main.js:28)
workbench.main.js:28 Unable to open 'test.pdf': resource is not available.: Error: Unable to open 'test.pdf': resource is not available.
    at t.doHandleSetInputError (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:424033)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:423639
    at n.Class.derive._creator.then (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:58966)
    at t.doSetInput (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:423409)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:421497
    at n.Class.derive._creator.then (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:59590)
    at t.doOpenEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:421469)
    at t.openEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:420759)
    at e.doOpenEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:3175984)
    at e.openEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:3175454)
e.doShow @ workbench.main.js:28
</details>

**Comment by James-Yu** [comment]
Previously implemented symbol support focuses on mouse activities, i.e., hover, right-click, and ctrl-click. The two symbol menus will be implemented a bit later.
