### ISSUE TITLE
comment in bib breaks intellisense for citation auto completion

### ISSUE THREAD

**Issue by lockejan** [James-Yu/LaTeX-Workshop#2196]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]
already commented here: https://github.com/James-Yu/LaTeX-Workshop/issues/1643
Comments inside citation in bib file are breaking intellisense for citation

### To Reproduce

1. Go to your example.bib file
2. Insert some comment in a reference block like so:
```
@misc{arm2016bag,
% personal comment about ref
	archiveprefix = {arXiv},
	author        = {Armand Joulin and Edouard Grave and Piotr Bojanowski and Tomas Mikolov},
	eprint        = {1607.01759},
	primaryclass  = {cs.CL},
	title         = {Bag of Tricks for Efficient Text Classification},
	year          = {2016}
}
```
3. Save the file.
4. Go in one of your tex-files and try to use intellisense for citation -> stays empty

### Expected behavior

I expect this feature to not break on comments inside references.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[19:37:14] Initializing LaTeX Workshop.
[19:37:14] Creating PDF file watcher.
[19:37:14] Creating LaTeX Workshop http and websocket server.
[19:37:14] LaTeX Workshop initialized.
[19:37:14] Linter for root file started.
[19:37:14] No root file found for linting.
[19:37:14] Server created on 127.0.0.1:63883
[19:37:14] LaTeX Workshop version: 8.11.1
[19:37:15] Snippet data loaded.
[19:37:15] Found files that might be root, choose the first one: /Users/smittie/Downloads/ma-expose/expose.tex,/Users/smittie/Downloads/ma-expose/content/tablehack.tex
[19:37:15] Root file changed: from undefined to /Users/smittie/Downloads/ma-expose/expose.tex
[19:37:15] Start to find all dependencies.
[19:37:15] Instantiating a new file watcher for /Users/smittie/Downloads/ma-expose/expose.tex
[19:37:15] Creating Bib file watcher.
[19:37:15] Parsing a file and its subfiles: /Users/smittie/Downloads/ma-expose/expose.tex
[19:37:15] Parsing a file and its subfiles: /Users/smittie/Downloads/ma-expose/content/abstract.tex
[19:37:15] Parse fls file.
[19:37:15] Cannot find fls file: /Users/smittie/Downloads/ma-expose/content/abstract.fls
[19:37:15] Parsing a file and its subfiles: /Users/smittie/Downloads/ma-expose/content/motivation.tex
[19:37:15] Parse fls file.
[19:37:15] Cannot find fls file: /Users/smittie/Downloads/ma-expose/content/motivation.fls
[19:37:15] Parsing a file and its subfiles: /Users/smittie/Downloads/ma-expose/content/statusQuo.tex
[19:37:15] Parse fls file.
[19:37:15] Cannot find fls file: /Users/smittie/Downloads/ma-expose/content/statusQuo.fls
[19:37:15] Parsing a file and its subfiles: /Users/smittie/Downloads/ma-expose/content/solution.tex
[19:37:15] Parse fls file.
[19:37:15] Cannot find fls file: /Users/smittie/Downloads/ma-expose/content/solution.fls
[19:37:15] Parsing a file and its subfiles: /Users/smittie/Downloads/ma-expose/content/scope.tex
[19:37:15] Parse fls file.
[19:37:15] Cannot find fls file: /Users/smittie/Downloads/ma-expose/content/scope.fls
[19:37:15] Found .bib file: /Users/smittie/Downloads/ma-expose/literature/lit.bib
[19:37:15] Added to bib file watcher: /Users/smittie/Downloads/ma-expose/literature/lit.bib
[19:37:15] Parsing .bib entries from /Users/smittie/Downloads/ma-expose/literature/lit.bib
[19:37:15] Parse fls file.
[19:37:15] Fls file found: /Users/smittie/Downloads/ma-expose/expose.fls
[19:37:15] Parse aux file: /Users/smittie/Downloads/ma-expose/expose.aux
[19:37:15] Added to file watcher: /Users/smittie/Downloads/ma-expose/expose.tex
[19:37:15] Added to file watcher: /Users/smittie/Downloads/ma-expose/content/abstract.tex
[19:37:15] Added to file watcher: /Users/smittie/Downloads/ma-expose/content/motivation.tex
[19:37:15] Added to file watcher: /Users/smittie/Downloads/ma-expose/content/statusQuo.tex
[19:37:15] Added to file watcher: /Users/smittie/Downloads/ma-expose/content/solution.tex
[19:37:15] Added to file watcher: /Users/smittie/Downloads/ma-expose/content/scope.tex
[19:37:15] Error parsing BibTeX: line 243 in /Users/smittie/Downloads/ma-expose/literature/lit.bib.
[19:37:16] Handle data type: open
[19:37:17] Preview PDF file: /Users/smittie/Downloads/ma-expose/expose.pdf
[19:37:17] Handle data type: request_params
[19:37:17] Handle data type: loaded```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
console.ts:137 [Extension Host] rejected promise not handled within 1 second: SyntaxError: Expected "=", "\r\n", or [ \t\n] but "p" found.
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: SyntaxError: Expected "=", "\r\n", or [ \t\n] but "p" found.    at peg$buildStructuredError (/Users/smittie/.vscode/extensions/james-yu.latex-workshop-8.11.1/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:366:12)    at Object.peg$parse [as parse] (/Users/smittie/.vscode/extensions/james-yu.latex-workshop-8.11.1/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:2011:11)    at Object.parse (/Users/smittie/.vscode/extensions/james-yu.latex-workshop-8.11.1/node_modules/latex-utensils/out/src/bibtex/bibtex_parser.js:32:30)    at Function.parseBibtex (/Users/smittie/.vscode/extensions/james-yu.latex-workshop-8.11.1/out/src/components/parser/syntax_worker.js:31:42)    at process.<anonymous> (/Users/smittie/.vscode/extensions/james-yu.latex-workshop-8.11.1/node_modules/workerpool/dist/workerpool.min.js:25:16559)    at process.emit (events.js:203:13)    at emit (internal/child_process.js:876:12)    at processTicksAndRejections (internal/process/task_queues.js:77:11)
t.log @ console.ts:137
log.ts:197   ERR Expected "=", "\r\n", or [ \t\n] but "p" found.: SyntaxError: Expected "=", "\r\n", or [ \t\n] but "p" found.
    at peg$buildStructuredError (/Users/smittie/.vscode/extensions/james-yu.latex-workshop-8.11.1/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:366:12)
    at Object.peg$parse [as parse] (/Users/smittie/.vscode/extensions/james-yu.latex-workshop-8.11.1/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:2011:11)
    at Object.parse (/Users/smittie/.vscode/extensions/james-yu.latex-workshop-8.11.1/node_modules/latex-utensils/out/src/bibtex/bibtex_parser.js:32:30)
    at Function.parseBibtex (/Users/smittie/.vscode/extensions/james-yu.latex-workshop-8.11.1/out/src/components/parser/syntax_worker.js:31:42)
    at process.<anonymous> (/Users/smittie/.vscode/extensions/james-yu.latex-workshop-8.11.1/node_modules/workerpool/dist/workerpool.min.js:25:16559)
    at process.emit (events.js:203:13)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```



## Screenshots

If applicable, add screenshots to help explain your problem.




## Desktop [Required]
 - OS: OSX Catalina 10.15.5
 - VS Code version: 1.46.1
 - Extension version: 8.11.1
 - TeX distribution version: 
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.02




## Additional questions

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

Add any other context about the problem here.

**Comment by jlelong** [comment]
This is because `%` is actually not a valid comment in bibtex.
See http://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html#comment and 
https://tex.stackexchange.com/questions/174555/bibtex-comment-out-lines?noredirect=1&lq=1 for instance.

**Comment by lockejan** [comment]
Ok, thanks for pointing that out.
I was coming from this post, which states that biber shouldn't have a problem with such:
https://tex.stackexchange.com/questions/93972/comment-out-sections-of-text-in-bib-file/93982#93982

I understand that it might be easier to keep ignoring it as is, but since biblatex and biber are under active development I would expect an increasing usage of it and therefore the possibility that it might will become relevant to ignore such lines when parsing bibfiles.
On the other hand I can understand that my approach isn't probably following best practices here and people might use something else to create such comments which then will break intellisense here as well.

So what would be a better and non-breaking approach to have custom comments inside references then?
The reason I started to put them inside the refs altogether was to prevent a disorder after invoking "sort bibliography".

**Comment by jlelong** [comment]
We rely on https://github.com/tamuratak/latex-utensils to parse bib files so we can nothing to handle `%` comments from the extension side. 

Using `@comment` (`@Comment`) declares a comment but it probably does not match your needs because it is an independent entry. Bibtex ignores non standard fields. If biber does the same, you could add a field `OPTComment` for instance. Let me know if it helps
