### ISSUE TITLE
Compilation not working when TeX file is place in directory root

### ISSUE THREAD

**Issue by UweZiegenhagen** [James-Yu/LaTeX-Workshop#2362]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

### To Reproduce

1. Create a new TeX file and place it in the top level directory, e.g. D:\ or R:\ depending on how your system is set up
2. Click on "Build LaTeX Project"
3. See error, the build symbol shows just a red X
4. Place the file in a sub directory of the drive
5. Click "Build LaTeX Project"
6. The file is compiled without error 

### Expected behavior

Building the LaTeX file works without errors.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[19:11:32] Initializing LaTeX Workshop.
[19:11:32] Extension root: c:\Users\Uwe\.vscode\extensions\james-yu.latex-workshop-8.13.2
[19:11:32] Creating PDF file watcher.
[19:11:33] Creating LaTeX Workshop http and websocket server.
[19:11:33] LaTeX Workshop initialized.
[19:11:33] Current workspace folders: undefined
[19:11:33] Current workspaceRootDir: 
[19:11:33] Found root file from active editor: o:\vsc\aaaa.tex
[19:11:33] Root file changed: from undefined to o:\vsc\aaaa.tex
[19:11:33] Start to find all dependencies.
[19:11:33] Instantiating a new file watcher for o:\vsc\aaaa.tex
[19:11:33] Creating Bib file watcher.
[19:11:33] Parsing a file and its subfiles: o:\vsc\aaaa.tex
[19:11:33] Parse fls file.
[19:11:33] Fls file found: o:\vsc\aaaa.fls
[19:11:33] Parse aux file: o:\vsc\aaaa.aux
[19:11:33] Server created on 127.0.0.1:58141
[19:11:33] Added to file watcher: o:\vsc\aaaa.tex
[19:11:33] Snippet data loaded.
[19:11:33] LaTeX Workshop version: 8.13.2
[19:11:37] BUILD command invoked.
[19:11:37] Current workspace folders: undefined
[19:11:37] Current workspaceRootDir: 
[19:11:37] Found root file from active editor: o:\vsc\aaaa.tex
[19:11:37] Keep using the same root file: o:\vsc\aaaa.tex.
[19:11:37] Building root file: o:\vsc\aaaa.tex
[19:11:37] Build root file o:\vsc\aaaa.tex
[19:11:37] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=o:/vsc,o:/vsc/aaaa
[19:11:37] cwd: o:\vsc
[19:11:37] LaTeX build process spawned. PID: 11384.
[19:11:38] Recipe of length 1 finished. PID: 11384.
[19:11:38] Successfully built o:\vsc\aaaa.tex.
[19:11:38] No PDF viewer connected for o:\vsc\aaaa.pdf
[19:11:38] Parse fls file.
[19:11:38] Fls file found: o:\vsc\aaaa.fls
[19:11:38] Parse aux file: o:\vsc\aaaa.aux
[19:11:41] LOG command invoked.
[19:11:41] Current workspace folders: undefined
[19:11:41] Current workspaceRootDir: 
[19:11:41] Found root file from active editor: o:\vsc\aaaa.tex
[19:11:41] Keep using the same root file: o:\vsc\aaaa.tex.
[19:11:48] Current workspace folders: undefined
[19:11:48] Current workspaceRootDir: 
[19:11:48] Found root file from active editor: o:\vsc\aaaa.tex
[19:11:48] Keep using the same root file: o:\vsc\aaaa.tex.
[19:11:54] Current workspace folders: undefined
[19:11:54] Current workspaceRootDir: 
[19:11:54] Found root file from active editor: o:\vsc\aaaa.tex
[19:11:54] Keep using the same root file: o:\vsc\aaaa.tex.
[19:11:54] Current workspace folders: undefined
[19:11:54] Current workspaceRootDir: 
[19:11:54] Found root file from active editor: o:\aaaaaaaa.tex
[19:11:54] Root file changed: from o:\vsc\aaaa.tex to o:\aaaaaaaa.tex
[19:11:54] Start to find all dependencies.
[19:11:54] Root file changed -> cleaning up old file watcher.
[19:11:54] Instantiating a new file watcher for o:\aaaaaaaa.tex
[19:11:54] Parsing a file and its subfiles: o:\aaaaaaaa.tex
[19:11:54] Parse fls file.
[19:11:54] Cannot find fls file: o:\aaaaaaaa.fls
[19:11:54] Added to file watcher: o:\aaaaaaaa.tex
[19:12:01] BUILD command invoked.
[19:12:01] Current workspace folders: undefined
[19:12:01] Current workspaceRootDir: 
[19:12:01] Found root file from active editor: o:\aaaaaaaa.tex
[19:12:01] Keep using the same root file: o:\aaaaaaaa.tex.
[19:12:01] Building root file: o:\aaaaaaaa.tex
[19:12:01] Build root file o:\aaaaaaaa.tex
[19:12:01] Unexpected Error: please see the console log of the Developer Tools of VS Code.
```

### Developer Tools Console [Required]

```
workbench.html:1 A cookie associated with a cross-site resource at https://visualstudio.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
log.ts:197   ERR EPERM: operation not permitted, mkdir 'o:\': Error: EPERM: operation not permitted, mkdir 'o:\'
	at mkdirSync (fs.js:823:3)
	at Object.fs.mkdirSync (electron/js2c/asar.js:718:16)
	at Object.module.exports.makeDirSync (c:\Users\Uwe\.vscode\extensions\james-yu.latex-workshop-8.13.2\node_modules\fs-extra\lib\mkdirs\make-dir.js:101:15)
	at c:\Users\Uwe\.vscode\extensions\james-yu.latex-workshop-8.13.2\out\src\components\builder.js:241:20
	at Array.forEach (<anonymous>)
	at Builder.build (c:\Users\Uwe\.vscode\extensions\james-yu.latex-workshop-8.13.2\out\src\components\builder.js:239:61)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Commander.build (c:\Users\Uwe\.vscode\extensions\james-yu.latex-workshop-8.13.2\out\src\commander.js:112:9)
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/semver-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/tas-client-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/main.js.map: 
```

## Desktop [Required]
 - OS: Windows 10 Pro
 - VS Code version: 1.50.1
 - Extension version: 8.13.2
 - TeX distribution version: TeX Live 2020

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

I had the same issue with TeX Works, therefore I decided to try this in VSC as well :-)

**Comment by jlelong** [comment]
The logs are pretty clear `mkdir 'o:\': Error: EPERM: operation not permitted`
Your cannot create a directory, which is actually the root of a filesystem. From [node.js documentation](https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback)

> On Windows, using fs.mkdir() on the root directory even with recursion will result in an error:
>
> ```
> fs.mkdir('/', { recursive: true }, (err) => {
>  // => [Error: EPERM: operation not permitted, mkdir 'C:\']
>});
> ```

**Comment by UweZiegenhagen** [comment]
But I am not trying to create the ``o:\``, I am just trying to compile the TeX file which happens to be in o:\
