### ISSUE TITLE
Recipe terminated with fatal error: spawn latexmk ENOENT.

### ISSUE THREAD

**Issue by mkarikom** [James-Yu/LaTeX-Workshop#2363]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

### To Reproduce

1. create new file test.tex
```
\documentclass{article}
\usepackage[mmddyyyy]{datetime}

\begin{document}

\begin{center}
    \today
\end{center}
\end{document}
```
2. Click on 'compile latex project'
3. See error: "Recipe terminated with fatal error: spawn latexmk ENOENT."

### Expected behavior

Should see output similar to `me$ pdflatex test.tex` (please see attached)

[test.pdf](https://github.com/James-Yu/LaTeX-Workshop/files/5496380/test.pdf)

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]
no output, only dialog pop up (please see above)

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'. this option is not available (run icon is just green arrow like normal run script and no dropdown)

[Paste the log here]
```

### Developer Tools Console [Required]

```
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:287 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, open 'Untitled-1'
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:287
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:287 [Extension Host] stack trace: Error: ENOENT: no such file or directory, open 'Untitled-1'	at Object.openSync (fs.js:440:3)	at Object.func [as openSync] (electron/js2c/asar.js:140:31)	at Object.readFileSync (fs.js:342:35)	at Object.fs.readFileSync (electron/js2c/asar.js:542:40)	at Manager.getDirtyContent (/home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/components/manager.js:385:52)	at Manager.parseFileAndSubs (/home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/components/manager.js:419:30)	at Manager.findRoot (/home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/components/manager.js:213:22)	at processTicksAndRejections (internal/process/task_queues.js:94:5)
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:287
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4640 [[object Object]]ENOENT: no such file or directory, open 'Untitled-1'
$onExtensionRuntimeError @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4640
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4641 Error: ENOENT: no such file or directory, open 'Untitled-1'
	at Object.openSync (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/fs.js:440)
	at Object.func [as openSync] (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/electron/js2c/asar.js:140)
	at Object.readFileSync (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/fs.js:342)
	at Object.fs.readFileSync (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/electron/js2c/asar.js:542)
	at Manager.getDirtyContent (/home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/components/manager.js:385)
	at Manager.parseFileAndSubs (/home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/components/manager.js:419)
	at Manager.findRoot (/home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/components/manager.js:213)
	at processTicksAndRejections (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/internal/process/task_queues.js:94)
$onExtensionRuntimeError @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4641
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4640 [[object Object]]ENOENT: no such file or directory, open 'Untitled-1'
$onExtensionRuntimeError @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4640
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4641 Error: ENOENT: no such file or directory, open 'Untitled-1'
	at Object.openSync (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/fs.js:440)
	at Object.func [as openSync] (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/electron/js2c/asar.js:140)
	at Object.readFileSync (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/fs.js:342)
	at Object.fs.readFileSync (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/electron/js2c/asar.js:542)
	at SectionNodeProvider.buildModel (/home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/providers/structure.js:83)
	at SectionNodeProvider.refresh (/home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/providers/structure.js:48)
	at /home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/main.js:162
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:713
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45)
	at b.acceptDocumentsAndEditorsDelta (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:718)
	at b.$acceptDocumentsAndEditorsDelta (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:716)
	at m._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:870)
	at m._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:870)
	at m._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:868)
	at m._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:867)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:865
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1059
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256)
	at t.PersistentProtocol._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:261)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:258
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45)
	at p.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253
	at Socket.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:263)
	at Socket.emit (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/events.js:223)
	at addChunk (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:309)
	at readableAddChunk (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:290)
	at Socket.Readable.push (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:224)
	at Pipe.onStreamRead (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/internal/stream_base_commons.js:181)
$onExtensionRuntimeError @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4641
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4640 [[object Object]]ENOENT: no such file or directory, open 'Untitled-1'
$onExtensionRuntimeError @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4640
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4641 Error: ENOENT: no such file or directory, open 'Untitled-1'
	at Object.openSync (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/fs.js:440)
	at Object.func [as openSync] (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/electron/js2c/asar.js:140)
	at Object.readFileSync (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/fs.js:342)
	at Object.fs.readFileSync (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/electron/js2c/asar.js:542)
	at SectionNodeProvider.buildModel (/home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/providers/structure.js:83)
	at SectionNodeProvider.refresh (/home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/providers/structure.js:48)
	at /home/me/.vscode/extensions/james-yu.latex-workshop-8.13.2/out/src/main.js:144
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45)
	at t.ExtHostDocuments.$acceptModelSaved (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:715)
	at m._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:870)
	at m._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:870)
	at m._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:868)
	at m._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:867)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:865
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1059
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256)
	at t.PersistentProtocol._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:261)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:258
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45)
	at p.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253
	at Socket.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:263)
	at Socket.emit (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/events.js:223)
	at addChunk (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:309)
	at readableAddChunk (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:290)
	at Socket.Readable.push (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:224)
	at Pipe.onStreamRead (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/internal/stream_base_commons.js:181)
$onExtensionRuntimeError @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4641
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98
addNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3154
notify @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4915
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4550
_showMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4550
$showMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4550
_doInvokeHandler @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4599
_invokeHandler @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4598
_receiveRequest @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4597
_receiveOneMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4596
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4594
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:454
_receiveMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:459
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:456
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98
acceptChunk @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:452
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:451
t @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:461
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98
addNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3154
notify @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4915
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4550
_showMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4550
$showMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4550
_doInvokeHandler @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4599
_invokeHandler @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4598
_receiveRequest @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4597
_receiveOneMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4596
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4594
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:454
_receiveMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:459
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:456
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98
acceptChunk @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:452
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:451
t @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:461
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98
addNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3154
notify @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4915
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4550
_showMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4550
$showMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4550
_doInvokeHandler @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4599
_invokeHandler @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4598
_receiveRequest @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4597
_receiveOneMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4596
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4594
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:454
_receiveMessage @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:459
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:456
fire @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:98
acceptChunk @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:452
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:451
t @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:461
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081 Recipe terminated with fatal error: spawn latexmk ENOENT.
onDidChangeNotification @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3081
DevTools failed to load SourceMap: Could not load content for file:///usr/share/code/resources/app/node_modules.asar/semver-umd/lib/semver-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/code/resources/app/node_modules.asar/xterm/lib/xterm.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/code/resources/app/node_modules.asar/xterm-addon-unicode11/lib/xterm-addon-unicode11.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/code/resources/app/node_modules.asar/xterm-addon-search/lib/xterm-addon-search.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/code/resources/app/node_modules.asar/node-pty/lib/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/code/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/code/resources/app/node_modules.asar/node-pty/lib/terminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/code/resources/app/node_modules.asar/node-pty/lib/eventEmitter2.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/code/resources/app/node_modules.asar/node-pty/lib/utils.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/code/resources/app/node_modules.asar/tas-client-umd/lib/tas-client-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js.map: 
```

## Screenshots

![errbox](https://user-images.githubusercontent.com/335091/98286075-4af3b200-1f58-11eb-830c-2b729ac232d2.png)

## Desktop [Required]
 - OS: Ubuntu 20.04
 - VS Code version: 1.50.1
 - Extension version: 8.13.2
 - TeX distribution version: TeX 3.14159265 (TeX Live 2019/Debian)

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by jlelong** [comment]
Please post the complete logs of the extension not just the compiler outputs. Do not truncate or alter them in particular if the paths contain non ascii characters.

![74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524](https://user-images.githubusercontent.com/2910140/77959270-98c77e00-72d6-11ea-8c58-4934a9fde39a.png)

**Comment by mkarikom** [comment]
Thanks, I have located it now:
```
[13:51:40] Initializing LaTeX Workshop.
[13:51:40] Extension root: /home/au/.vscode/extensions/james-yu.latex-workshop-8.13.2
[13:51:40] Creating PDF file watcher.
[13:51:40] Creating LaTeX Workshop http and websocket server.
[13:51:40] LaTeX Workshop initialized.
[13:51:41] Current workspace folders: ["file:///tmp/new"]
[13:51:41] Current workspaceRootDir: /tmp/new
[13:51:41] Found root file from active editor: /tmp/new/test.tex
[13:51:41] Root file changed: from undefined to /tmp/new/test.tex
[13:51:41] Start to find all dependencies.
[13:51:41] Instantiating a new file watcher for /tmp/new/test.tex
[13:51:41] Creating Bib file watcher.
[13:51:41] Parsing a file and its subfiles: /tmp/new/test.tex
[13:51:41] Parse fls file.
[13:51:41] Cannot find fls file: /tmp/new/test.fls
[13:51:41] Server created on 127.0.0.1:43583
[13:51:41] Added to file watcher: /tmp/new/test.tex
[13:51:41] Snippet data loaded.
[13:51:41] LaTeX Workshop version: 8.13.2
[13:51:45] BUILD command invoked.
[13:51:45] Current workspace folders: ["file:///tmp/new"]
[13:51:45] Current workspaceRootDir: /tmp/new
[13:51:45] Found root file from active editor: /tmp/new/test.tex
[13:51:45] Keep using the same root file: /tmp/new/test.tex.
[13:51:45] Building root file: /tmp/new/test.tex
[13:51:45] Build root file /tmp/new/test.tex
[13:51:45] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/tmp/new,/tmp/new/test
[13:51:45] cwd: /tmp/new
[13:51:45] LaTeX build process spawned. PID: undefined.
[13:51:45] LaTeX fatal error: spawn latexmk ENOENT, . PID: undefined.
[13:51:45] Does the executable exist? PATH: /home/au/.local/bin:/home/au/.local/bin:/home/au/anaconda3/bin:/home/au/anaconda3/condabin:/home/au/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[13:51:45] The current SHELL: /bin/bash
[13:51:58] LOG command invoked.
[13:52:00] LOG command invoked.
[13:52:00] Current workspace folders: ["file:///tmp/new"]
[13:52:00] Current workspaceRootDir: /tmp/new
[13:52:00] Found root file from active editor: /tmp/new/test.tex
[13:52:00] Keep using the same root file: /tmp/new/test.tex.
[13:52:01] LOG command invoked.
[13:52:01] Current workspace folders: ["file:///tmp/new"]
[13:52:01] Current workspaceRootDir: /tmp/new
[13:52:01] Found root file from active editor: /tmp/new/test.tex
[13:52:01] Keep using the same root file: /tmp/new/test.tex.

```

**Comment by mkarikom** [comment]
Here is extension manager showing no others are enabled:
![pkg](https://user-images.githubusercontent.com/335091/98300660-741f3d00-1f6e-11eb-9dee-15bfaa3e4a93.png)

**Comment by trevorgunn** [comment]
Do you have `latexmk` installed?

**Comment by tamuratak** [comment]
This issue is not related to LaTeX Workshop.

Please check whether `latexmk` and `perl` installed in one of directories of `PATH`.

```
[13:51:45] LaTeX fatal error: spawn latexmk ENOENT, . PID: undefined.
[13:51:45] Does the executable exist? PATH: /home/me/.local/bin:/home/me/.local/bin:/home/me/anaconda3/bin:/home/me/anaconda3/condabin:/home/me/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[13:51:45] The current SHELL: /bin/bash
```
