### ISSUE TITLE
Show PDF in browser not working

### ISSUE THREAD

**Issue by fkjogu** [James-Yu/LaTeX-Workshop#244]
I'd like to detach the PDF viewer from my window in order to use two monitors. This does not seem to be working with the internal viewer. I can't transplant it to another window of the editor. So I'd tried to look at it in the browser, which also fails with

```
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at context.subscriptions.push.vscode.window.onDidChangeActiveTextEditor (/uni-mainz.de/homes/fkoessel/.vscode/extensions/James-Yu.latex-workshop-3.3.2/out/src/main.js:166:42)
    at e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:55038)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:56829)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:392875
    at e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:55038)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:56829)
    at t.$acceptDocumentsAndEditorsDelta (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:348628)
    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:308751)
    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:188848)
    at h (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189503)
e.onUnexpectedError	@	shell.ts:423
webview.ts:150 [Embedded Page] The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
webview.ts:150 [Embedded Page] /pdf:<some filename>.pdf
webview.ts:150 [Embedded Page] loaded
webview.ts:150 [Embedded Page] PDF 59fc199c237e224695e978f7f7571772 [1.5 pdfTeX-1.40.17 / LaTeX with hyperref package] (PDF.js: 1.8.609)
webview.ts:150 [Embedded Page] PDFViewer_setScale: "undefined" is an unknown zoom value.

shell.ts:423 Running the contributed command:'latex-workshop.view' failed.: Error: Running the contributed command:'latex-workshop.view' failed.
    at t.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:328997)
    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:308751)
    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:188848)
    at h (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError	@	shell.ts:423
(anonymous)	@	shell.ts:383
e.onUnexpectedError	@	errors.ts:119
o	@	errors.ts:139
(anonymous)	@	errors.ts:49
(anonymous)	@	errors.ts:44
errors.ts:51 WARNING: Promise with no error callback:102
errors.ts:52 
Object

messageService.ts:125 Running the contributed command:'latex-workshop.view' failed.
e.doShow	@	messageService.ts:125
e.show	@	messageService.ts:104
e.resume	@	messageService.ts:63
(anonymous)	@	workbench.ts:995
e.invoke	@	callbackList.ts:63
e.fire	@	event.ts:123
```

Running on debian

**Comment by James-Yu** [comment]
Unfortunately, it seems that the error messages are not related with the extension. I also cannot reproduce the problem. More information and an minimal working example is required for any possible further investigation.

**Comment by fkjogu** [comment]
But the log in the dev console is the correct place to look for the extension's log?

If it helps, here are videos that show, what I'm trying to do.

Open in webbrowser:
https://imgur.com/WfPEerU

Detach tab:
https://imgur.com/Ksq5mW2

**Comment by James-Yu** [comment]
What is the log message of LaTeX Workshop? You can access that from the PROBLEM->OUTPUT panel at the bottom.

**Comment by will-hart** [comment]
I get this exception in the inspector if I open up a window that isn't an editor. For instance, if I go to the LaTeX Workshop page from the "Extensions" menu, then the error reliably appears when tabbing between a document and the non-editable tab.

**Comment by James-Yu** [comment]
@will-hart this information is quite important! Will try to reproduce and see where's the problem.

**Comment by James-Yu** [comment]
This commit can fix the issue described by @will-hart , however I'm not sure if pdf in browser will work for others. Please feel free to re-open if any problem exists.

**Comment by fkjogu** [comment]
@James-Yu The OUTPUT panel ist just empty. I've updated the extension today and it still does not work.

The only thing that appears in the developer console right after commiting the command, is this log:

```
hell.ts:423 Running the contributed command:'latex-workshop.view' failed.: Error: Running the contributed command:'latex-workshop.view' failed.
    at t.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:328997)
    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:308751)
    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:188848)
    at h (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ shell.ts:423
(anonymous) @ shell.ts:383
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:139
(anonymous) @ errors.ts:49
(anonymous) @ errors.ts:44
errors.ts:51 WARNING: Promise with no error callback:144
errors.ts:52 Objecterror: Error: Running the contributed command:'latex-workshop.view' failed.
    at t.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:328997)
    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:308751)
    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:188848)
    at h (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)exception: nullhandler: undefinedid: 144parent: undefinedpromise: n.Class.derive._oncancel__proto__: Object
messageService.ts:125 Running the contributed command:'latex-workshop.view' failed.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
e.resume @ messageService.ts:63
(anonymous) @ workbench.ts:995
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ quickOpenController.ts:517
```

**Comment by fkjogu** [comment]
By the way, it is impossible for a non collaborator of the repo to reopen an issue and collaborator has closed.

**Comment by James-Yu** [comment]
The log message is not meaningful for debug. However I cannot come up with other things that is helpful. Empty output seems unreasonable to me since initializing the extension itself also generates some log messages.

It looks like a local client-side problem.

**Comment by fkjogu** [comment]
Ah, missed the little tab to select this extension output. It says now after issuing the command

```
[10:51:15] VIEW command invoked.
[10:51:15] Found root file from active editor: /uni-mainz.de/homes/fkoessel/Documents/Paper/mtb_kinetic_bands/main.tex
[10:51:15] Root file remains unchanged from: /path/to/some.tex.
[10:51:15] No PDF viewer connected for /path/to/some.tex
[10:51:15] Serving PDF file at http://127.0.0.1:45269/viewer.html?file=/pdf:%2Fpath%2Fto%2Fsome%2Fsome.pdf
[10:51:22] Root file remains unchanged from: //path/to/some.tex.
```

**Comment by James-Yu** [comment]
What would it be if you copy/paste the `http://127.0.0.1:45269/viewer.html?file=/pdf:%2Fpath%2Fto%2Fsome%2Fsome.pdf` manually to a web browser, say Chrome?

**Comment by fkjogu** [comment]
That works fine. So it seems to be an issue opening the correct browser. I'm on Debian Stretch btw.

**Comment by James-Yu** [comment]
My 2c is that package `opn` won't work for the said OS. The problem exists between
https://github.com/James-Yu/LaTeX-Workshop/blob/54714ee869691173cab6505eb98d8d323ee8f47b/src/components/viewer.ts#L65
and
https://github.com/James-Yu/LaTeX-Workshop/blob/54714ee869691173cab6505eb98d8d323ee8f47b/src/components/viewer.ts#L72
And the only notable thing is `opn`.

A quick search gives https://github.com/sindresorhus/opn/issues/64 as a complaint of using `opn` on linux, but I'm not sure if you are facing the same issue. I will look into the issue, meanwhile you may try to copy the url manually as a dirty temporary workaround.

**Comment by fkjogu** [comment]
Thx. Since it auto-updates the page, it isn't that bad of a workaround right now. Ping me, if you need some testing.

**Comment by James-Yu** [comment]
Changing `opn` to other packages seems to be a bad solution. As an alternative, I'd proposed this one for you:
![image](https://user-images.githubusercontent.com/4210342/30019764-3b126cdc-9194-11e7-91b9-cc7a47afed36.png)

It should not be too disturbing, as only an extra step is required. The change will be published soon, and please have a test then.

**Comment by fkjogu** [comment]
I think this is a workable workaround until `opn` is fixed (if this is the culprit).
