### ISSUE TITLE
Reverse search fails when built with tectonic

### ISSUE THREAD

**Issue by coxackie** [James-Yu/LaTeX-Workshop#2467]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

I use tectonic (with default options provided by the extension). Documents build ok, but when I try to use reverse search via synctex (built-in pdf viewer) it does not work. (It works for latexmk, by the way.)

### To Reproduce

1. Use tectonic option to build
2. Control-click on the pdf for reverse search
3. Watch it fail.

### Expected behavior
3'. Watch it work.

## Desktop [Required]
 - OS: Arch Linux
 - VS Code version: 1.52.1
 - Extension version: 8.15.0
 - TeX distribution version: TeX Live 2019

### Are you using VSCodium?

No, but I am using Code - OSS

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
Please post the complete logs of the extension and of `tectonic` (compiler log). Do not truncate or alter them

![74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524](https://user-images.githubusercontent.com/2910140/77959270-98c77e00-72d6-11ea-8c58-4934a9fde39a.png)

**Comment by coxackie** [comment]
Latex compiler log:
```
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
note: Running TeX ...
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
note: Rerunning TeX because "test.aux" changed ...
note: Running xdvipdfmx ...
note: Writing `/home/coxackie/Test/test.log` (1.89 KiB)
note: Writing `/home/coxackie/Test/test.synctex.gz` (405 B)
note: Writing `/home/coxackie/Test/test.pdf` (2.58 KiB)
note: Skipped writing 1 intermediate files (use --keep-intermediates to keep them)
```

Latex Workshop log:
```
[12:00:49] Initializing LaTeX Workshop.
[12:00:49] Extension root: /home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0
[12:00:49] Creating PDF file watcher.
[12:00:49] Creating LaTeX Workshop http and websocket server.
[12:00:49] LaTeX Workshop initialized.
[12:00:49] Current workspace folders: ["file:///home/coxackie/Test"]
[12:00:49] Current workspaceRootDir: /home/coxackie/Test
[12:00:49] Found root file from active editor: /home/coxackie/Test/test.tex
[12:00:49] Root file changed: from undefined to /home/coxackie/Test/test.tex
[12:00:49] Start to find all dependencies.
[12:00:49] Root file languageId: latex
[12:00:49] Instantiating a new file watcher for /home/coxackie/Test/test.tex
[12:00:49] Creating Bib file watcher.
[12:00:49] Parsing a file and its subfiles: /home/coxackie/Test/test.tex
[12:00:49] Parse fls file.
[12:00:49] Cannot find fls file: /home/coxackie/Test/test.fls
[12:00:49] Server created on 127.0.0.1:36357
[12:00:49] Added to file watcher: /home/coxackie/Test/test.tex
[12:00:49] Snippet data loaded.
[12:00:49] LaTeX Workshop version: 8.15.0
[12:00:56] RECIPES command invoked.
[12:00:56] BUILD command invoked.
[12:00:56] The document of the active editor: file:///home/coxackie/Test/test.tex
[12:00:56] The languageId of the document: latex
[12:00:56] Current workspace folders: ["file:///home/coxackie/Test"]
[12:00:56] Current workspaceRootDir: /home/coxackie/Test
[12:00:56] Found root file from active editor: /home/coxackie/Test/test.tex
[12:00:56] Keep using the same root file: /home/coxackie/Test/test.tex
[12:00:56] Building root file: /home/coxackie/Test/test.tex
[12:00:56] Build root file /home/coxackie/Test/test.tex
[12:00:56] Recipe step 1: tectonic, --synctex,--keep-logs,/home/coxackie/Test/test.tex
[12:00:56] Recipe step env: {}
[12:00:56] cwd: /home/coxackie/Test
[12:00:56] LaTeX build process spawned. PID: 25481.
[12:00:56] Recipe of length 1 finished. PID: 25481.
[12:00:56] Successfully built /home/coxackie/Test/test.tex.
[12:00:56] No PDF viewer connected for /home/coxackie/Test/test.pdf
[12:00:56] Parse fls file.
[12:00:56] Cannot find fls file: /home/coxackie/Test/test.fls
[12:01:02] LOG command invoked: compiler
[12:01:10] LOG command invoked: default
[12:01:10] Current workspace folders: ["file:///home/coxackie/Test"]
[12:01:10] Current workspaceRootDir: /home/coxackie/Test
[12:01:10] Found root file from active editor: /home/coxackie/Test/test.tex
[12:01:10] Keep using the same root file: /home/coxackie/Test/test.tex
[12:01:14] Current workspace folders: ["file:///home/coxackie/Test"]
[12:01:14] Current workspaceRootDir: /home/coxackie/Test
[12:01:14] Found root file from active editor: /home/coxackie/Test/test.tex
[12:01:14] Keep using the same root file: /home/coxackie/Test/test.tex
[12:01:15] VIEW command invoked.
[12:01:15] Current workspace folders: ["file:///home/coxackie/Test"]
[12:01:15] Current workspaceRootDir: /home/coxackie/Test
[12:01:15] Found root file from active editor: /home/coxackie/Test/test.tex
[12:01:15] Keep using the same root file: /home/coxackie/Test/test.tex
[12:01:15] Serving PDF file at http://localhost:36357/viewer.html?file=pdf..JTJGaG9tZSUyRmNveGFja2llJTJGVGVzdCUyRnRlc3QucGRm
[12:01:15] The encoded path is /home/coxackie/Test/test.pdf
[12:01:15] Open PDF tab for /home/coxackie/Test/test.pdf
[12:01:15] Handle data type: open
[12:01:15] Preview PDF file: /home/coxackie/Test/test.pdf
[12:01:15] Handle data type: request_params
[12:01:15] Sending the settings of the PDF viewer for initialization: {"type":"params","scale":"auto","trim":2,"scrollMode":0,"spreadMode":0,"hand":false,"invertMode":{"enabled":false,"brightness":1,"grayscale":0.6,"hueRotate":180,"invert":0,"sepia":0},"bgColor":"#ffffff","keybindings":{"synctex":"ctrl-click"}}
[12:01:15] Handle data type: loaded
[12:01:16] Current workspace folders: ["file:///home/coxackie/Test"]
[12:01:16] Current workspaceRootDir: /home/coxackie/Test
[12:01:16] Found root file from active editor: /home/coxackie/Test/test.tex
[12:01:16] Keep using the same root file: /home/coxackie/Test/test.tex
[12:01:19] Handle data type: reverse_synctex
[12:01:19] Input file to jump to does not exist in the file system: test.tex
[12:01:19] SyncTexJsError: Input file to jump to does not exist in the file system: test.tex
	at SyncTexJs.convInputFilePath (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/synctex.js:226:15)
	at SyncTexJs.syncTexJsBackward (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/synctex.js:210:30)
	at Locator.locate (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/locator.js:283:41)
	at Viewer.handler (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/viewer.js:416:40)
	at WebSocket.<anonymous> (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/server.js:55:68)
	at WebSocket.emit (events.js:223:5)
	at Receiver.receiverOnMessage (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/websocket.js:720:20)
	at Receiver.emit (events.js:223:5)
	at Receiver.dataMessage (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:414:14)
	at Receiver.getData (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:346:17)
	at Receiver.startLoop (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:133:22)
	at Receiver._write (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:69:10)
	at doWrite (_stream_writable.js:435:12)
	at writeOrBuffer (_stream_writable.js:419:5)
	at Receiver.Writable.write (_stream_writable.js:309:11)
	at Socket.socketOnData (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/websocket.js:795:35)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[12:01:20] Handle data type: reverse_synctex
[12:01:20] Input file to jump to does not exist in the file system: test.tex
[12:01:20] SyncTexJsError: Input file to jump to does not exist in the file system: test.tex
	at SyncTexJs.convInputFilePath (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/synctex.js:226:15)
	at SyncTexJs.syncTexJsBackward (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/synctex.js:210:30)
	at Locator.locate (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/locator.js:283:41)
	at Viewer.handler (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/viewer.js:416:40)
	at WebSocket.<anonymous> (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/server.js:55:68)
	at WebSocket.emit (events.js:223:5)
	at Receiver.receiverOnMessage (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/websocket.js:720:20)
	at Receiver.emit (events.js:223:5)
	at Receiver.dataMessage (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:414:14)
	at Receiver.getData (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:346:17)
	at Receiver.startLoop (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:133:22)
	at Receiver._write (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:69:10)
	at doWrite (_stream_writable.js:435:12)
	at writeOrBuffer (_stream_writable.js:419:5)
	at Receiver.Writable.write (_stream_writable.js:309:11)
	at Socket.socketOnData (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/websocket.js:795:35)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[12:01:22] Handle data type: reverse_synctex
[12:01:22] Input file to jump to does not exist in the file system: test.tex
[12:01:22] SyncTexJsError: Input file to jump to does not exist in the file system: test.tex
	at SyncTexJs.convInputFilePath (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/synctex.js:226:15)
	at SyncTexJs.syncTexJsBackward (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/synctex.js:210:30)
	at Locator.locate (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/locator.js:283:41)
	at Viewer.handler (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/viewer.js:416:40)
	at WebSocket.<anonymous> (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/server.js:55:68)
	at WebSocket.emit (events.js:223:5)
	at Receiver.receiverOnMessage (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/websocket.js:720:20)
	at Receiver.emit (events.js:223:5)
	at Receiver.dataMessage (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:414:14)
	at Receiver.getData (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:346:17)
	at Receiver.startLoop (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:133:22)
	at Receiver._write (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:69:10)
	at doWrite (_stream_writable.js:435:12)
	at writeOrBuffer (_stream_writable.js:419:5)
	at Receiver.Writable.write (_stream_writable.js:309:11)
	at Socket.socketOnData (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/websocket.js:795:35)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[12:01:23] Handle data type: reverse_synctex
[12:01:23] Input file to jump to does not exist in the file system: test.tex
[12:01:23] SyncTexJsError: Input file to jump to does not exist in the file system: test.tex
	at SyncTexJs.convInputFilePath (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/synctex.js:226:15)
	at SyncTexJs.syncTexJsBackward (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/synctex.js:210:30)
	at Locator.locate (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/locator.js:283:41)
	at Viewer.handler (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/viewer.js:416:40)
	at WebSocket.<anonymous> (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/out/src/components/server.js:55:68)
	at WebSocket.emit (events.js:223:5)
	at Receiver.receiverOnMessage (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/websocket.js:720:20)
	at Receiver.emit (events.js:223:5)
	at Receiver.dataMessage (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:414:14)
	at Receiver.getData (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:346:17)
	at Receiver.startLoop (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:133:22)
	at Receiver._write (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/receiver.js:69:10)
	at doWrite (_stream_writable.js:435:12)
	at writeOrBuffer (_stream_writable.js:419:5)
	at Receiver.Writable.write (_stream_writable.js:309:11)
	at Socket.socketOnData (/home/coxackie/.vscode-oss/extensions/james-yu.latex-workshop-8.15.0/node_modules/ws/lib/websocket.js:795:35)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[12:01:30] LOG command invoked: default
[12:01:31] LOG command invoked: compiler
[12:02:18] LOG command invoked: default
```

**Comment by tamuratak** [comment]
Report to `tectonic`. Paths in `.synctex.gz` should be absolute.

**Comment by coxackie** [comment]
ok, I filed https://github.com/tectonic-typesetting/tectonic/issues/720 with them.
