### ISSUE TITLE
Cannot open external viewer when using settings with variable subsitution

### ISSUE THREAD

**Issue by supakorn-ras** [James-Yu/LaTeX-Workshop#2469]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When settings for external viewer uses variable substitution such as as `${env:ProgramFiles}`, the external viewer does not show up.

### To Reproduce

1. Set settings `latex-workshop.view.pdf.external.viewer.command` to `${env:ProgramFiles}\\SumatraPDF\\SumatraPDF.exe`
2. Execute "View LaTeX PDF File in external viewer"

### Expected behavior

SumatraPDF launches with the PDF file in question

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[17:07:40] Initializing LaTeX Workshop.
[17:07:40] Extension root: c:\Users\Supakorn\.vscode\extensions\james-yu.latex-workshop-8.15.0
[17:07:40] Creating PDF file watcher.
[17:07:40] Creating LaTeX Workshop http and websocket server.
[17:07:40] LaTeX Workshop initialized.
[17:07:40] Current workspace folders: ["file:///d:/Dropbox/Homework/m447/hw1"]
[17:07:40] Current workspaceRootDir: d:\Dropbox\Homework\m447\hw1
[17:07:41] Found root file from active editor: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:07:41] Root file changed: from undefined to d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:07:41] Start to find all dependencies.
[17:07:41] Root file languageId: latex
[17:07:41] Instantiating a new file watcher for d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:07:41] Creating Bib file watcher.
[17:07:41] Parsing a file and its subfiles: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:07:41] Parse fls file.
[17:07:41] Fls file found: d:\Dropbox\Homework\m447\hw1\m447hw1.fls
[17:07:41] Parsing a file and its subfiles: d:\Dropbox\Homework\base\mathPreamble.tex
[17:07:41] Cannot find .bib file: \basedir/bib/base.bib
[17:07:41] Parse fls file.
[17:07:41] Cannot find fls file: d:\Dropbox\Homework\base\mathPreamble.fls
[17:07:41] Parse aux file: d:\Dropbox\Homework\m447\hw1\m447hw1.aux
[17:07:41] Could not resolve included file undefined
[17:07:41] Server created on 127.0.0.1:49250
[17:07:41] Added to file watcher: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:07:41] Added to file watcher: d:\Dropbox\Homework\base\mathPreamble.tex
[17:07:41] Snippet data loaded.
[17:07:41] LaTeX Workshop version: 8.15.0
[17:08:01] Current workspace folders: ["file:///d:/Dropbox/Homework/m447/hw1"]
[17:08:01] Current workspaceRootDir: d:\Dropbox\Homework\m447\hw1
[17:08:01] Found root file from active editor: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:08:01] Keep using the same root file: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:08:43] VIEW command invoked with mode: external.
[17:08:43] Active document is not a TeX file.
[17:09:08] Current workspace folders: ["file:///d:/Dropbox/Homework/m447/hw1"]
[17:09:08] Current workspaceRootDir: d:\Dropbox\Homework\m447\hw1
[17:09:08] Found root file from active editor: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:09:08] Keep using the same root file: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:10:17] Current workspace folders: ["file:///d:/Dropbox/Homework/m447/hw1"]
[17:10:17] Current workspaceRootDir: d:\Dropbox\Homework\m447\hw1
[17:10:17] Found root file from active editor: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:10:17] Keep using the same root file: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:10:22] VIEW command invoked with mode: external.
[17:10:22] Current workspace folders: ["file:///d:/Dropbox/Homework/m447/hw1"]
[17:10:22] Current workspaceRootDir: d:\Dropbox\Homework\m447\hw1
[17:10:22] Found root file from active editor: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:10:22] Keep using the same root file: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:10:22] Open external viewer for d:\Dropbox\Homework\m447\hw1\m447hw1.pdf
[17:11:42] Current workspace folders: ["file:///d:/Dropbox/Homework/m447/hw1"]
[17:11:42] Current workspaceRootDir: d:\Dropbox\Homework\m447\hw1
[17:11:42] Found root file from active editor: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:11:42] Keep using the same root file: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:11:50] Current workspace folders: ["file:///d:/Dropbox/Homework/m447/hw1"]
[17:11:50] Current workspaceRootDir: d:\Dropbox\Homework\m447\hw1
[17:11:50] Found root file from active editor: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:11:50] Keep using the same root file: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:11:53] Current workspace folders: ["file:///d:/Dropbox/Homework/m447/hw1"]
[17:11:53] Current workspaceRootDir: d:\Dropbox\Homework\m447\hw1
[17:11:53] Found root file from active editor: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:11:53] Keep using the same root file: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:12:00] Current workspace folders: ["file:///d:/Dropbox/Homework/m447/hw1"]
[17:12:00] Current workspaceRootDir: d:\Dropbox\Homework\m447\hw1
[17:12:00] Found root file from active editor: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:12:00] Keep using the same root file: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:12:01] VIEW command invoked with mode: external.
[17:12:01] Current workspace folders: ["file:///d:/Dropbox/Homework/m447/hw1"]
[17:12:01] Current workspaceRootDir: d:\Dropbox\Homework\m447\hw1
[17:12:01] Found root file from active editor: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:12:01] Keep using the same root file: d:\Dropbox\Homework\m447\hw1\m447hw1.tex
[17:12:01] Open external viewer for d:\Dropbox\Homework\m447\hw1\m447hw1.pdf
```

### Developer Tools Console [Required]

```
mainThreadExtensionService.ts:66 Error: spawn ${env:ProgramFiles}\SumatraPDF\SumatraPDF.exe ENOENT
	at notFoundError (c:\Users\Supakorn\.vscode\extensions\james-yu.latex-workshop-8.15.0\node_modules\cross-spawn\lib\enoent.js:6:26)
	at verifyENOENT (c:\Users\Supakorn\.vscode\extensions\james-yu.latex-workshop-8.15.0\node_modules\cross-spawn\lib\enoent.js:40:16)
	at ChildProcess.cp.emit (c:\Users\Supakorn\.vscode\extensions\james-yu.latex-workshop-8.15.0\node_modules\cross-spawn\lib\enoent.js:27:25)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

## Screenshots

Not applicable

## Desktop [Required]
 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.41.0]
 - Extension version: [e.g. 8.5.0]
 - TeX distribution version: [e.g. TeX Live 2019/MiKTeX 2.9.7250]

Windows 10, VSCode 1.52.1, LaTeX Workshop 8.15.0, TexLive 2020.

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

Not applicable

**Comment by tamuratak** [comment]
Variable substitution `${env:ProgramFiles}` not supported.
