### ISSUE TITLE
'latex-workshop.build' failed

### ISSUE THREAD

**Issue by serkant** [James-Yu/LaTeX-Workshop#2567]
## Preliminary questions [Required]
I cannot compile any .tex file since it throws the following error: 'Running the contributed command: 'latex-workshop.build' failed.' It was working without any problem before, I have no idea why I suddenly started getting this error. I uninstalled Latex-Workshop and re-installed again, re-installed previous versions of the extension, and re-installed vscode as well but nothing solved it. 
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: I can compile the document using another tex editor (texmaker).

## Describe the bug [Required]

I cannot compile any .tex file within VS Code using LaTeX-Workshop extension.

### To Reproduce

The following .tex file fails to compile within VS Code while I can compile it using another .tex editor

\documentclass[12pt]{article}

\begin{document}
TEST

\end{document}

### Expected behavior

It should be able to compile it without any problem.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[19:26:58] Initializing LaTeX Workshop.
[19:26:58] Extension root: /Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1
[19:26:58] $PATH: /usr/local/opt/ruby/bin:/Users/serkantadiguzel/.pyenv/shims:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/serkantadiguzel/Library/Python/3.8/bin:/Users/serkantadiguzel/.local/bin:/Users/serkantadiguzel/Documents/chromedriver:/Library/TeX/texbin
[19:26:58] $SHELL: /bin/zsh
[19:26:58] Creating PDF file watcher.
[19:26:58] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[19:26:59] Creating LaTeX Workshop http and websocket server.
[19:26:59] LaTeX Workshop initialized.
[19:26:59] Trigger characters for intellisense of LaTeX documents: ["\\","{",",","(","["]
[19:26:59] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[]}
[19:26:59] Current workspace folders: undefined
[19:26:59] Current workspaceRootDir: 
[19:26:59] Server created on 127.0.0.1:49453
[19:26:59] Snippet data loaded.
[19:26:59] LaTeX Workshop version: 8.16.1
[19:26:59] Current workspace folders: undefined
[19:26:59] Current workspaceRootDir: 
[19:26:59] Found root file from active editor: /Users/serkantadiguzel/Desktop/test.tex
[19:26:59] Root file changed: from undefined to /Users/serkantadiguzel/Desktop/test.tex
[19:26:59] Start to find all dependencies.
[19:26:59] Root file languageId: latex
[19:26:59] Creating a new file watcher for /Users/serkantadiguzel/Desktop/test.tex
[19:26:59] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[19:26:59] Creating Bib file watcher.
[19:26:59] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[19:26:59] Parsing a file and its subfiles: /Users/serkantadiguzel/Desktop/test.tex
[19:26:59] Parse fls file.
[19:26:59] Cannot find fls file: /Users/serkantadiguzel/Desktop/test.fls
[19:26:59] Added to file watcher: /Users/serkantadiguzel/Desktop/test.tex
[19:26:59] Checking for duplicate labels: /Users/serkantadiguzel/Desktop/test.tex.
[19:27:02] BUILD command invoked.
[19:27:02] The document of the active editor: file:///Users/serkantadiguzel/Desktop/test.tex
[19:27:02] The languageId of the document: latex
[19:27:02] Current workspace folders: undefined
[19:27:02] Current workspaceRootDir: 
[19:27:02] Found root file from active editor: /Users/serkantadiguzel/Desktop/test.tex
[19:27:02] Keep using the same root file: /Users/serkantadiguzel/Desktop/test.tex
[19:27:02] Building root file: /Users/serkantadiguzel/Desktop/test.tex
[19:27:02] Build root file /Users/serkantadiguzel/Desktop/test.tex
[19:27:02] Recipe step 1: latexmk, -synctex=1,-file-line-error,-outdir=/Users/serkantadiguzel/Desktop,/Users/serkantadiguzel/Desktop/test
[19:27:02] Recipe step env: {}
[19:27:02] cwd: /Users/serkantadiguzel/Desktop
[19:27:02] Unexpected Error: please see the console log of the Developer Tools of VS Code.
[19:32:42] LOG command invoked: default
[19:34:02] File watcher - file changed: /Users/serkantadiguzel/Desktop/test.tex
[19:34:02] Parsing a file and its subfiles: /Users/serkantadiguzel/Desktop/test.tex
[19:34:02] Parse fls file.
[19:34:02] Cannot find fls file: /Users/serkantadiguzel/Desktop/test.fls
[19:34:02] Auto build started detecting the change of a file: /Users/serkantadiguzel/Desktop/test.tex
[19:34:02] BUILD command invoked.
[19:34:02] The document of the active editor: output:extension-output-%234
[19:34:02] The languageId of the document: Log
[19:34:02] Building root file: /Users/serkantadiguzel/Desktop/test.tex
[19:34:02] Build root file /Users/serkantadiguzel/Desktop/test.tex
[19:34:02] Checking for duplicate labels: /Users/serkantadiguzel/Desktop/test.tex.
[19:34:02] Recipe step 1: latexmk, -synctex=1,-file-line-error,-outdir=/Users/serkantadiguzel/Desktop,/Users/serkantadiguzel/Desktop/test
[19:34:02] Recipe step env: {}
[19:34:02] cwd: /Users/serkantadiguzel/Desktop
[19:34:02] Unexpected Error: please see the console log of the Developer Tools of VS Code.
[19:34:06] File watcher - file changed: /Users/serkantadiguzel/Desktop/test.tex
[19:34:06] Parsing a file and its subfiles: /Users/serkantadiguzel/Desktop/test.tex
[19:34:06] Parse fls file.
[19:34:06] Cannot find fls file: /Users/serkantadiguzel/Desktop/test.fls
[19:34:06] Auto build started detecting the change of a file: /Users/serkantadiguzel/Desktop/test.tex
[19:34:06] BUILD command invoked.
[19:34:06] The document of the active editor: output:extension-output-%234
[19:34:06] The languageId of the document: Log
[19:34:06] Building root file: /Users/serkantadiguzel/Desktop/test.tex
[19:34:06] Build root file /Users/serkantadiguzel/Desktop/test.tex
[19:34:06] Checking for duplicate labels: /Users/serkantadiguzel/Desktop/test.tex.
[19:34:06] Recipe step 1: latexmk, -synctex=1,-file-line-error,-outdir=/Users/serkantadiguzel/Desktop,/Users/serkantadiguzel/Desktop/test
[19:34:06] Recipe step env: {}
[19:34:06] cwd: /Users/serkantadiguzel/Desktop
[19:34:06] Unexpected Error: please see the console log of the Developer Tools of VS Code.
```

### Developer Tools Console [Required]

```
Error: Running the contributed command: 'latex-workshop.build' failed.
	at S._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87)
	at processTicksAndRejections (internal/process/task_queues.js:97)
onDidChangeNotification @ notificationsAlerts.ts:38
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: spawn ENOTDIR
v @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: spawn ENOTDIR	at ChildProcess.spawn (internal/child_process.js:407:11)	at Object.spawn (child_process.js:557:9)	at Object.spawn [as default] (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/node_modules/cross-spawn/index.js:12:24)	at Builder.buildStep (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:317:38)	at Builder.buildInitiator (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:197:14)	at Builder.build (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:259:18)	at processTicksAndRejections (internal/process/task_queues.js:97:5)	at async Commander.build (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/commander.js:115:9)
v @ console.ts:137
mainThreadExtensionService.ts:59 [[object Object]]spawn ENOTDIR
$onExtensionRuntimeError @ mainThreadExtensionService.ts:59
mainThreadExtensionService.ts:60 Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407)
	at Object.spawn (child_process.js:557)
	at Object.spawn [as default] (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/node_modules/cross-spawn/index.js:12)
	at Builder.buildStep (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:317)
	at Builder.buildInitiator (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:197)
	at Builder.build (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:259)
	at processTicksAndRejections (internal/process/task_queues.js:97)
	at async Commander.build (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/commander.js:115)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: spawn ENOTDIR
v @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: spawn ENOTDIR	at ChildProcess.spawn (internal/child_process.js:407:11)	at Object.spawn (child_process.js:557:9)	at Object.spawn [as default] (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/node_modules/cross-spawn/index.js:12:24)	at Builder.buildStep (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:317:38)	at Builder.buildInitiator (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:197:14)	at Builder.build (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:259:18)	at processTicksAndRejections (internal/process/task_queues.js:97:5)	at async Commander.build (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/commander.js:115:9)
v @ console.ts:137
mainThreadExtensionService.ts:59 [[object Object]]spawn ENOTDIR
$onExtensionRuntimeError @ mainThreadExtensionService.ts:59
mainThreadExtensionService.ts:60 Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407)
	at Object.spawn (child_process.js:557)
	at Object.spawn [as default] (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/node_modules/cross-spawn/index.js:12)
	at Builder.buildStep (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:317)
	at Builder.buildInitiator (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:197)
	at Builder.build (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:259)
	at processTicksAndRejections (internal/process/task_queues.js:97)
	at async Commander.build (/Users/serkantadiguzel/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/commander.js:115)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
```

## Desktop [Required]
 - OS: macOS Catalina Version 10.15.7 
 - VS Code version: 1.54.1
 - Extension version: 8.16.1
 - TeX distribution version: pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by tamuratak** [comment]
It might be related to microsoft/vscode/issues/118164.

**Comment by serkant** [comment]
Downgrading to v1.53.2 solved the problem. Thank you!

**Comment by tamuratak** [comment]
I cannot reproduce this issue. However, this issue might occur when the `PATH` environment variable includes a file, not a directory.

**Comment by tamuratak** [comment]
Related to https://github.com/microsoft/vscode/issues/118460#issuecomment-794469696.

**Comment by serkant** [comment]
> > [19:26:58] $PATH: /usr/local/opt/ruby/bin:/Users/serkantadiguzel/.pyenv/shims:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/serkantadiguzel/Library/Python/3.8/bin:/Users/serkantadiguzel/.local/bin:/Users/serkantadiguzel/Documents/chromedriver:/Library/TeX/texbin
> 
> > /Users/serkantadiguzel/Documents/chromedriver
> 
> I cannot reproduce this issue. However, this issue might occur when the `PATH` environment variable includes a file, not a directory. Other environment variables including a file, not a directory, might be the cause.

I removed it and upgraded vscode to the latest version but the problem appeared again. Downgrading vscode to v1.53.2  is still the only solution for me. Thank you.

**Comment by tamuratak** [comment]
microsoft/vscode/issues/118267

**Comment by tamuratak** [comment]
Updating to v1.54.2 might solve the issue. https://github.com/microsoft/vscode-remote-release/issues/4630#issuecomment-797143707

If not, please open a new issue filling out all the information required in the issue template.
