### ISSUE TITLE
PDF Preview Changes Focus on Refresh

### ISSUE THREAD

**Issue by gmarino2048** [James-Yu/LaTeX-Workshop#2631]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes/No
Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes/No
Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes/No

Yes, I am able to compile

## Describe the bug [Required]

When the PDF is compiled, the VSCode tab focus is automatically switched to the preview, meaning that all keystrokes are captured by the PDF viewer which prevents the user from typing anything.

### To Reproduce

1. Open the built-in PDF viewer in a new vscode tab
2. Edit the source LaTeX document
3. Wait for recompile
4. Attempt to type something more in the source document. You can't because the window focus changed.

### Expected behavior

The window focus does not change, allowing the user to continue typing with the source file uninterrupted.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[16:53:26] Initializing LaTeX Workshop.
[16:53:26] Extension root: /home/guy/.vscode-insiders/extensions/james-yu.latex-workshop-8.16.1
[16:53:26] $PATH: /home/guy/.jenv/shims:/home/guy/.jenv/bin:/home/guy/.cargo/bin:/home/guy/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-11.1/bin:/home/guy/.local/bin
[16:53:26] $SHELL: /usr/bin/zsh
[16:53:26] Creating PDF file watcher.
[16:53:26] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[16:53:26] Creating LaTeX Workshop http and websocket server.
[16:53:26] LaTeX Workshop initialized.
[16:53:26] Trigger characters for intellisense of LaTeX documents: ["\\","{",",","(","["]
[16:53:26] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[]}
[16:53:26] Current workspace folders: ["file:///home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5"]
[16:53:26] Current workspaceRootDir: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5
[16:53:26] Server created on 127.0.0.1:45971
[16:53:26] LaTeX Workshop version: 8.16.1
[16:53:26] Snippet data loaded.
[16:53:26] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q1/q1.fls
[16:53:26] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q7/q7.fls
[16:53:26] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q5/q5.fls
[16:53:26] Fls file found: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.fls
[16:53:26] Found root file from '.fls': /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:53:26] Root file changed: from undefined to /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:53:26] Start to find all dependencies.
[16:53:26] Root file languageId: latex
[16:53:26] Creating a new file watcher for /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:53:26] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[16:53:26] Creating Bib file watcher.
[16:53:26] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[16:53:26] Parsing a file and its subfiles: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:53:26] Parsing a file and its subfiles: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q1/q1.tex
[16:53:26] Parse fls file.
[16:53:26] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q1/q1.fls
[16:53:26] Parsing a file and its subfiles: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q2/q2.tex
[16:53:26] Parse fls file.
[16:53:26] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q2/q2.fls
[16:53:26] Parsing a file and its subfiles: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.tex
[16:53:26] Parse fls file.
[16:53:26] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.fls
[16:53:26] Parsing a file and its subfiles: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q4/q4.tex
[16:53:26] Parse fls file.
[16:53:26] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q4/q4.fls
[16:53:26] Parsing a file and its subfiles: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q5/q5.tex
[16:53:26] Parse fls file.
[16:53:26] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q5/q5.fls
[16:53:26] Parsing a file and its subfiles: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q6/q6.tex
[16:53:26] Parse fls file.
[16:53:26] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q6/q6.fls
[16:53:26] Parsing a file and its subfiles: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q7/q7.tex
[16:53:26] Parse fls file.
[16:53:26] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q7/q7.fls
[16:53:26] Parse fls file.
[16:53:26] Fls file found: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.fls
[16:53:26] Parse aux file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.aux
[16:53:26] Added to file watcher: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:53:26] Added to file watcher: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q1/q1.tex
[16:53:26] Added to file watcher: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q2/q2.tex
[16:53:26] Added to file watcher: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.tex
[16:53:26] Added to file watcher: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q4/q4.tex
[16:53:26] Added to file watcher: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q5/q5.tex
[16:53:26] Added to file watcher: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q6/q6.tex
[16:53:26] Added to file watcher: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q7/q7.tex
[16:53:26] Added to file watcher: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q2/q2.png
[16:53:26] Checking for duplicate labels: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex.
[16:53:26] Checking for duplicate labels: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q1/q1.tex.
[16:53:26] Checking for duplicate labels: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q2/q2.tex.
[16:53:26] Checking for duplicate labels: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.tex.
[16:53:26] Checking for duplicate labels: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q4/q4.tex.
[16:53:26] Checking for duplicate labels: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q5/q5.tex.
[16:53:26] Checking for duplicate labels: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q6/q6.tex.
[16:53:26] Checking for duplicate labels: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q7/q7.tex.
[16:53:29] VIEW command invoked with mode: file:///home/store/work/Spring%202021/Advanced%20Algorithms/Homework%20Assignments/HW5/Q3/q3.tex.
[16:53:29] Current workspace folders: ["file:///home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5"]
[16:53:29] Current workspaceRootDir: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5
[16:53:29] Keep using the same root file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:53:29] Serving PDF file at http://localhost:45971/viewer.html?file=pdf..JTJGaG9tZSUyRnN0b3JlJTJGd29yayUyRlNwcmluZyUyMDIwMjElMkZBZHZhbmNlZCUyMEFsZ29yaXRobXMlMkZIb21ld29yayUyMEFzc2lnbm1lbnRzJTJGSFc1JTJGZ3htMjYyLWh3NS5wZGY
[16:53:29] The encoded path is /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.pdf
[16:53:29] The internal PDF viewer url: http://localhost:45971/viewer.html?incode=1&file=pdf..JTJGaG9tZSUyRnN0b3JlJTJGd29yayUyRlNwcmluZyUyMDIwMjElMkZBZHZhbmNlZCUyMEFsZ29yaXRobXMlMkZIb21ld29yayUyMEFzc2lnbm1lbnRzJTJGSFc1JTJGZ3htMjYyLWh3NS5wZGY
[16:53:29] Open PDF tab for /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.pdf
[16:53:29] Handle data type: open
[16:53:29] Preview PDF file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.pdf
[16:53:29] Handle data type: request_params
[16:53:29] Sending the settings of the PDF viewer for initialization: {"type":"params","scale":"auto","trim":0,"scrollMode":0,"spreadMode":0,"hand":false,"invertMode":{"enabled":false,"brightness":1,"grayscale":0.6,"hueRotate":180,"invert":0,"sepia":0},"bgColor":"#ffffff","keybindings":{"synctex":"ctrl-click"}}
[16:53:29] Handle data type: loaded
[16:53:30] Current workspace folders: ["file:///home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5"]
[16:53:30] Current workspaceRootDir: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5
[16:53:30] Keep using the same root file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:53:34] File watcher - file changed: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.tex
[16:53:34] Parsing a file and its subfiles: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.tex
[16:53:34] Parse fls file.
[16:53:34] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.fls
[16:53:34] Auto build started detecting the change of a file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.tex
[16:53:34] BUILD command invoked.
[16:53:34] The document of the active editor: file:///home/store/work/Spring%202021/Advanced%20Algorithms/Homework%20Assignments/HW5/Q3/q3.tex
[16:53:34] The languageId of the document: latex
[16:53:34] Building root file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:53:34] Build root file /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:53:34] Checking for duplicate labels: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.tex.
[16:53:34] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5,/home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5
[16:53:34] Recipe step env: {}
[16:53:34] cwd: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5
[16:53:34] LaTeX build process spawned. PID: 90751.
[16:53:34] LaTeX log parsed with 0 messages.
[16:53:34] Recipe of length 1 finished. PID: 90751.
[16:53:34] Successfully built /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex.
[16:53:34] Refresh PDF viewer for /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.pdf
[16:53:34] Parse fls file.
[16:53:34] Fls file found: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.fls
[16:53:34] Parse aux file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.aux
[16:53:34] Preview PDF file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.pdf
[16:53:34] Handle data type: loaded
[16:58:12] BUILD command invoked.
[16:58:12] The document of the active editor: output:tasks
[16:58:12] The languageId of the document: Log
[16:58:12] Cannot find LaTeX root file.
[16:58:45] BUILD command invoked.
[16:58:45] The document of the active editor: output:tasks
[16:58:45] The languageId of the document: Log
[16:58:45] Cannot find LaTeX root file.
[16:58:46] BUILD command invoked.
[16:58:46] The document of the active editor: output:tasks
[16:58:46] The languageId of the document: Log
[16:58:46] Cannot find LaTeX root file.
[16:58:47] BUILD command invoked.
[16:58:47] The document of the active editor: output:tasks
[16:58:47] The languageId of the document: Log
[16:58:47] Cannot find LaTeX root file.
[16:58:47] BUILD command invoked.
[16:58:47] The document of the active editor: output:tasks
[16:58:47] The languageId of the document: Log
[16:58:47] Cannot find LaTeX root file.
[16:58:49] BUILD command invoked.
[16:58:49] The document of the active editor: output:tasks
[16:58:49] The languageId of the document: Log
[16:58:49] Cannot find LaTeX root file.
[16:58:51] Current workspace folders: ["file:///home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5"]
[16:58:51] Current workspaceRootDir: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5
[16:58:51] Keep using the same root file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:58:53] File watcher - file changed: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.tex
[16:58:53] Parsing a file and its subfiles: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.tex
[16:58:53] Parse fls file.
[16:58:53] Cannot find fls file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.fls
[16:58:53] Auto build started detecting the change of a file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.tex
[16:58:53] BUILD command invoked.
[16:58:53] The document of the active editor: file:///home/store/work/Spring%202021/Advanced%20Algorithms/Homework%20Assignments/HW5/Q3/q3.tex
[16:58:53] The languageId of the document: latex
[16:58:53] Building root file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:58:53] Build root file /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex
[16:58:53] Checking for duplicate labels: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/Q3/q3.tex.
[16:58:53] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5,/home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5
[16:58:53] Recipe step env: {}
[16:58:53] cwd: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5
[16:58:53] LaTeX build process spawned. PID: 92431.
[16:58:54] LaTeX log parsed with 0 messages.
[16:58:54] Recipe of length 1 finished. PID: 92431.
[16:58:54] Successfully built /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.tex.
[16:58:54] Refresh PDF viewer for /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.pdf
[16:58:54] Parse fls file.
[16:58:54] Fls file found: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.fls
[16:58:54] Parse aux file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.aux
[16:58:54] Preview PDF file: /home/store/work/Spring 2021/Advanced Algorithms/Homework Assignments/HW5/gxm262-hw5.pdf
[16:58:54] Handle data type: loaded
[16:59:12] LOG command invoked: default
[16:59:16] LOG command invoked: default

```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

electron/js2c/renderer_init.js:61 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:61
event.ts:487 [979] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ event.ts:487
event.ts:488     at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58523
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58:61006
    at new Promise (<anonymous>)
    at Object.F [as toPromise] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60987)
    at k.whenInitialized (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:4475)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:3211
    at w (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:68:11163)
    at Object.onFirstListenerAdd (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:3202)
    at _event._event (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:872)
    at l.set input [as input] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:4229)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:7162
check @ event.ts:488
viewer.js:268 webviewerloaded: SecurityError: Blocked a frame with origin "http://localhost:45971" from accessing a cross-origin frame.
webViewerLoad @ viewer.js:268
viewer.js:1375 PDF 883bdf64b3479ecc6befe87e85da7558 [1.5 pdfTeX-1.40.20 / LaTeX with hyperref] (PDF.js: 2.6.347)
VM8:25 Uncaught TypeError: Cannot set property 'type' of undefined
    at <anonymous>:25:36
viewer.js:1375 PDF 199761f06c3741d80f65450444fa28c9 [1.5 pdfTeX-1.40.20 / LaTeX with hyperref] (PDF.js: 2.6.347)
log.ts:290  WARN Exception when rerendering new tab widget Error: TreeError [TerminalTabsTree] Tree element not found: [object Object]
    at R.getElementLocation (objectTreeModel.ts:295)
    at R.rerender (objectTreeModel.ts:163)
    at C.rerender (objectTree.ts:65)
    at P._rerenderTabs (terminalTabbedView.ts:213)
    at P._addTabTree (terminalTabbedView.ts:207)
    at P._setupSplitView (terminalTabbedView.ts:180)
    at new P (terminalTabbedView.ts:142)
    at g._createInstance (instantiationService.ts:110)
    at g.createInstance (instantiationService.ts:76)
    at u._createTabsView (terminalView.ts:144)
    at u.renderBody (terminalView.ts:89)
    at u.render (paneview.ts:243)
    at u.render (viewPane.ts:276)
    at A.onDidAddViewDescriptors (viewPaneContainer.ts:767)
    at A.create (viewPaneContainer.ts:535)
    at M.create (panecomposite.ts:42)
    at li.showComposite (compositePart.ts:219)
    at li.doOpenComposite (compositePart.ts:150)
    at li.openComposite (compositePart.ts:114)
    at li.doOpenPanel (panelPart.ts:505)
    at li.openPanel (panelPart.ts:510)
    at y.openComposite (viewsService.ts:166)
    at y.openView (viewsService.ts:282)
    at N.showPanel (terminalService.ts:688)
    at Object.run (terminalActions.ts:1323)
    at handler (actions.ts:536)
    at g.invokeFunction (instantiationService.ts:61)
    at g._tryExecuteCommand (commandService.ts:84)
    at commandService.ts:73
    at async EventEmitter.<anonymous> (window.ts:154)
log.ts:296   ERR TreeError [TerminalTabsTree] Tree element not found: [object Object]: Error: TreeError [TerminalTabsTree] Tree element not found: [object Object]
    at R.getNode (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:61:57895)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:171:1186
    at Array.map (<anonymous>)
    at C.setSelection (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:171:1168)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1972:28336
    at d.fire (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at d.fire (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1856)
    at HTMLTextAreaElement.<anonymous> (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2621:102952)
    at t.focus (/usr/share/code-insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:42969)
    at e.focus (/usr/share/code-insiders/resources/app/node_modules.asar/xterm/lib/xterm.js:1:79503)
    at Xt.focus (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2621:108870)
    at Xt.focusWhenReady (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2621:108938)
viewer.js:1375 PDF 579f6deb764edf8d8ae8d60566edd173 [1.5 pdfTeX-1.40.20 / LaTeX with hyperref] (PDF.js: 2.6.347)
DevTools failed to load SourceMap: Could not load content for http://localhost:45971/out/viewer/latexworkshop.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:45971/out/viewer/components/synctex.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:45971/out/viewer/components/utils.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:45971/out/viewer/components/pagetrimmer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:45971/out/viewer/components/viewerhistory.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:45971/build/pdf.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:45971/viewer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:45971/build/pdf.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error

```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Kubuntu Linux 20.04
 - VS Code version: 1.56.0-insider
 - Extension version: 8.16.1
 - TeX distribution version: TeX Live 2019/Debian

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
Fixed in f0188ae4db663c6bd92a08bc36e01929cec6132d
