### ISSUE TITLE
Tex Root File Magic comment error handling

### ISSUE THREAD

**Issue by Siltyx** [James-Yu/LaTeX-Workshop#2659]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

If you give a wrong filepath for as root file the extension just shows this error and does nothing else:

_Command 'LaTeX Workshop: Build LaTeX project' resulted in an error (Running the contributed command: 'latex-workshop.build' failed.)_

### To Reproduce

Just give a non-existing file path xxx in the tex root command
% !TeX root = xxx.tex
For example, I had ./paper.tex instead of ./0_paper.tex

### Expected behavior

Clear error message that the given root file cannot be found.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[14:59:49] Initializing LaTeX Workshop.
[14:59:49] Extension root: /somepath/.vscode/extensions/james-yu.latex-workshop-8.17.0
[14:59:49] $PATH: /somepath/.local/bin:/somepath/miniconda2/bin:/somepath/miniconda2/condabin:/somepath/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/somepath/programms/context/tex/texmf-linux-64/bin:/usr/local/MATLAB/R2020b/bin:/somepath/scripts
[14:59:49] $SHELL: /bin/bash
[14:59:49] Creating PDF file watcher.
[14:59:49] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[14:59:49] Creating LaTeX Workshop http and websocket server.
[14:59:49] LaTeX Workshop initialized.
[14:59:49] Trigger characters for intellisense of LaTeX documents: ["\\","{",",","(","["]
[14:59:49] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[]}
[14:59:49] Current workspace folders: ["file:///somepath/somefolder"]
[14:59:49] Current workspaceRootDir: /somepath/somefolder
[14:59:49] Not found root file specified in the magic comment: /somepath/somefolder/tex_template/paper.tex
[14:59:49] Server created on 127.0.0.1:41253
[14:59:49] Snippet data loaded.
[14:59:55] BUILD command invoked.
[14:59:55] The document of the active editor: file:///somepath/somefolder/tex_template/0_paper.tex
[14:59:55] The languageId of the document: latex
[14:59:55] Current workspace folders: ["file:///somepath/somefolder"]
[14:59:55] Current workspaceRootDir: /somepath/somefolder
[14:59:55] Not found root file specified in the magic comment: /somepath/somefolder/tex_template/paper.tex
[15:00:02] LOG command invoked: default

```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[2021-05-05 14:27:56.667] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/testing-editor-contributions/dist/extension.js
[2021-05-05 14:28:03.765] [exthost] [error] Error: Not found root file specified in the magic comment: /somepath/somefolder/tex_template/paper.tex
	at FinderUtils.findRootFromMagic (/somepath/.vscode/extensions/james-yu.latex-workshop-8.17.0/out/src/components/managerlib/finderutils.js:44:23)
	at /somepath/.vscode/extensions/james-yu.latex-workshop-8.17.0/out/src/components/manager.js:194:36
	at Manager.findRoot (/somepath/.vscode/extensions/james-yu.latex-workshop-8.17.0/out/src/components/manager.js:200:36)
	at Commander.build (/somepath/.vscode/extensions/james-yu.latex-workshop-8.17.0/out/src/commander.js:94:53)
	at /somepath/.vscode/extensions/james-yu.latex-workshop-8.17.0/out/src/main.js:79:87
	at S._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106770)
	at S.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:107208)
	at u._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12794)
	at u._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12478)
	at u._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11145)
	at u._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:9931)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:8032
	at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at E.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:29750
	at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at E.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
	at t._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20754)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17640
	at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12861)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12209
	at Socket.w (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:13173)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23) latex-workshop.build
[2021-05-05 14:28:54.141] [exthost] [error] Error: Not found root file specified in the magic comment: /somepath/somefolder/tex_template/paper.tex
	at FinderUtils.findRootFromMagic (/somepath/.vscode/extensions/james-yu.latex-workshop-8.17.0/out/src/components/managerlib/finderutils.js:44:23)
	at /somepath/.vscode/extensions/james-yu.latex-workshop-8.17.0/out/src/components/manager.js:194:36
	at Manager.findRoot (/somepath/.vscode/extensions/james-yu.latex-workshop-8.17.0/out/src/components/manager.js:200:36)
	at Commander.view (/somepath/.vscode/extensions/james-yu.latex-workshop-8.17.0/out/src/commander.js:165:55)
	at /somepath/.vscode/extensions/james-yu.latex-workshop-8.17.0/out/src/main.js:81:90
	at S._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106770)
	at S.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:107208)
	at u._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12794)
	at u._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12478)
	at u._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11145)
	at u._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:9931)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:8032
	at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at E.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:29750
	at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at E.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
	at t._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20754)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17640
	at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12861)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12209
	at Socket.w (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:13173)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23) latex-workshop.view]
```

## Desktop [Required]

 - OS: [Ubuntu 18.04]
 - VS Code version: [1.55.2]
 - Extension version: [8.17.0]
 - TeX distribution version: [Version 3.14159265 (TeX Live 2017/Debian)]

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
> [14:59:55] Not found root file specified in the magic comment: /somepath/somefolder/tex_template/paper.tex

The log message is explaining well what went wrong. We expect users to read the log message when something went wrong.
