### ISSUE TITLE
Can't find tool "biber"

### ISSUE THREAD

**Issue by SandroMartens** [James-Yu/LaTeX-Workshop#2747]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: 
No

## Describe the bug [Required]
Biber is not found when compiling my project. I get the error:
` "Skipping undefined tool "biber" in recipe "pdflatex ➞ biber ➞ pdflatex × 2.""`
It is defined in  the settings.json: and also in the PATH (I can execute it  manually)

`        {
            "name": "biber",
            "command": "biber",
            "args": [
                "%DOCFILE%"
            ],
            "env": {}
        },
`

`        {
            "name": "pdflatex ➞ biber ➞ pdflatex × 2",
            "tools": [
                "pdflatex",
                "biber",
                "pdflatex",
                "pdflatex"
            ]
        },`

### To Reproduce

Click on "Build Project: pdflatex -> biber -> pdflatex*2"

### Expected behavior
A PDF file for my document

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[16:34:46] Initializing LaTeX Workshop.
[16:34:46] Extension root: c:\Users\Sandro\.vscode\extensions\james-yu.latex-workshop-8.18.0
[16:34:46] $PATH: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\GnuPG\bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\Program Files\dotnet\;C:\Program Files\MiKTeX\miktex\bin\x64\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\VSCodium\bin;C:\Program Files (x86)\GnuPG\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\Sandro\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Nmap;C:\Users\Sandro\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\texlive\2017\bin\win32;C:\Users\Sandro\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Sandro\AppData\Local\Programs\Microsoft VS Code Insiders\bin;C:\Program Files\Oracle\VirtualBox;C:\Users\Sandro\go\bin;C:\tools\NirLauncher\Nirsoft;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.1\bin;C:\Program Files\OpenJDK\jdk-16.0.1\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Go\bin;C:\Program Files\nodejs\;C:\tools\miniconda3\Library\mingw-w64\bin;C:\tools\miniconda3\Library\mingw-w64\lib;C:\tools\miniconda3\Library\bin\;C:\tools\miniconda3\pkgs\libblas-3.9.0-8_mkl\Library\bin;C:\tools\miniconda3\Lib\site-packages\jupyter_client;C:\tools\miniconda3\Scripts;C:\tools\miniconda3\;C:\Users\Sandro\AppData\Roaming\npm
[16:34:46] $SHELL: undefined
[16:34:46] latex-workshop.intellisense.update.aggressive.enabled: false
[16:34:46] latex-workshop.intellisense.update.delay: 1000
[16:34:46] Creating PDF file watcher.
[16:34:46] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[16:34:47] pdflatex is provided by MiKTeX
[16:34:47] Creating LaTeX Workshop http and websocket server.
[16:34:47] LaTeX Workshop initialized.
[16:34:47] Trigger characters for intellisense of LaTeX documents: ["\\","{",",","(","["]
[16:34:47] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[]}
[16:34:47] Current workspace folders: ["file:///f:/Dokumente/Studium/Master/Masterarbeit"]
[16:34:47] Current workspaceRootDir: file:///f:/Dokumente/Studium/Master/Masterarbeit
[16:34:47] Found root file from active editor: f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.tex
[16:34:47] Root file changed: from undefined to f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.tex
[16:34:47] Start to find all dependencies.
[16:34:47] Root file languageId: latex
[16:34:47] Creating a new file watcher for f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.tex
[16:34:47] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[16:34:47] Creating Bib file watcher.
[16:34:47] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[16:34:47] Parsing a file and its subfiles: f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.tex
[16:34:47] Found .bib file: F:\Dokumente\Studium\Master\Masterarbeit\Literatur\MA_neu.bib
[16:34:47] Added to bib file watcher: F:\Dokumente\Studium\Master\Masterarbeit\Literatur\MA_neu.bib
[16:34:47] Parsing .bib entries from F:\Dokumente\Studium\Master\Masterarbeit\Literatur\MA_neu.bib
[16:34:47] Parse fls file.
[16:34:47] Cannot find fls file: f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.fls
[16:34:47] Server created on 127.0.0.1:4750
[16:34:47] Added to file watcher: f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.tex
[16:34:47] Snippet data loaded.
[16:34:47] Parsed 53 bib entries from F:\Dokumente\Studium\Master\Masterarbeit\Literatur\MA_neu.bib.
[16:34:48] Checking for duplicate labels: f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.tex.
[16:34:56] BUILD command invoked.
[16:34:56] The document of the active editor: file:///f%3A/Dokumente/Studium/Master/Masterarbeit/Latex/Masterarbeit.tex
[16:34:56] The languageId of the document: latex
[16:34:56] Current workspace folders: ["file:///f:/Dokumente/Studium/Master/Masterarbeit"]
[16:34:56] Current workspaceRootDir: file:///f:/Dokumente/Studium/Master/Masterarbeit
[16:34:56] Found root file from active editor: f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.tex
[16:34:56] Keep using the same root file: f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.tex
[16:34:56] Building root file: f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.tex
[16:34:56] Build root file f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.tex
[16:34:56] Recipe step 1: pdflatex, --max-print-line=10000,-synctex=1,-interaction=nonstopmode,-file-line-error,-shell-escape,f:/Dokumente/Studium/Master/Masterarbeit/Latex/Masterarbeit
[16:34:56] Recipe step env: {}
[16:34:56] cwd: f:\Dokumente\Studium\Master\Masterarbeit\Latex
[16:34:56] LaTeX build process spawned. PID: 16844.
[16:35:25] KILL command invoked.
[16:35:25] Kill child processes of the current process. PPID: 16844
[16:35:25] Kill the current process. PID: 16844
[16:35:25] Recipe returns with error: 1/null. PID: 16844. message: .
[16:35:25] The environment variable $PATH: undefined
[16:35:25] The environment variable $SHELL: undefined
[16:35:25] Cleaning auxiliary files and retrying build after toolchain error.
[16:35:25] Cleaning file: f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.log
[16:35:25] Cleaning file: f:\Dokumente\Studium\Master\Masterarbeit\Latex\Masterarbeit.synctex(busy)
[16:35:25] Recipe step 1: pdflatex, --max-print-line=10000,-synctex=1,-interaction=nonstopmode,-file-line-error,-shell-escape,f:/Dokumente/Studium/Master/Masterarbeit/Latex/Masterarbeit
[16:35:25] Recipe step env: {}
[16:35:25] cwd: f:\Dokumente\Studium\Master\Masterarbeit\Latex
[16:35:25] LaTeX build process spawned. PID: 11956.
[16:36:08] KILL command invoked.
[16:36:08] Kill child processes of the current process. PPID: 11956
[16:36:08] Kill the current process. PID: 11956
[16:36:08] Recipe returns with error: 1/null. PID: 11956. message: .
[16:36:08] The environment variable $PATH: undefined
[16:36:08] The environment variable $SHELL: undefined

```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

electron/js2c/renderer_init.js:61 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:61
workbench.desktop.main.js:62 [Extension Host] (node:10900) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
S @ workbench.desktop.main.js:62
workbench.desktop.main.js:60 [375] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ workbench.desktop.main.js:60
workbench.desktop.main.js:60     at file:///C:/Users/Sandro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58523
    at file:///C:/Users/Sandro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:61006
    at new Promise (<anonymous>)
    at Object.N [as toPromise] (file:///C:/Users/Sandro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60987)
    at _.whenInitialized (file:///C:/Users/Sandro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:4475)
    at file:///C:/Users/Sandro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:2720
    at w (file:///C:/Users/Sandro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:11210)
    at file:///C:/Users/Sandro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:2710
    at new Promise (<anonymous>)
    at _.requestPromise (file:///C:/Users/Sandro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:2252)
    at Object.call (file:///C:/Users/Sandro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:1941)
    at file:///C:/Users/Sandro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:7092
check @ workbench.desktop.main.js:60
workbench.desktop.main.js:735 Skipping undefined tool "biber" in recipe "pdflatex ➞ biber ➞ pdflatex × 2."
onDidChangeNotification @ workbench.desktop.main.js:735
workbench.desktop.main.js:735 Recipe terminated with error.
onDidChangeNotification @ workbench.desktop.main.js:735
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/054a9295330880ed74ceaedda236253b4f39a335/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS:  Windows 10 Pro 10.0.19042 Build 19042
 - VS Code version: 1.56.2
 - Extension version: 8.18.0
 - TeX distribution version: Miktex 21.6.

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

It worked perfectly fine until yesterday. I tried to install minted when the error occured. I already reinstalled Miktex and the Latex Workshop extension.

**Comment by tamuratak** [comment]
```
Biber is not found when compiling my project. I get the error:
"Skipping undefined tool "biber" in recipe "pdflatex ➞ biber ➞ pdflatex × 2.""
It is defined in the settings.json: and also in the PATH (I can execute it manually)

{ "name": "biber", "command": "biber", "args": [ "%DOCFILE%" ], "env": {} },

{ "name": "pdflatex ➞ biber ➞ pdflatex × 2", "tools": [ "pdflatex", "biber", "pdflatex", "pdflatex" ] },
```

See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes
