### ISSUE TITLE
Synctex in file with \include 'd files is not searching for the correct directory.

### ISSUE THREAD

**Issue by ThunderSmotch** [James-Yu/LaTeX-Workshop#2923]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When building a project whose main file includes other files, Synctex throws an error when trying to reverse search.

### To Reproduce

1. Create a Latex Project
2. Create a subfolder where you will have other .tex files
3. Include said .tex files on the main .tex file.
4. Build and try to reverse search on the internal PDF viewer.

### Expected behavior

Synctex works.

### LaTeX Workshop Output [Required]

```
[15:22:17] Handle data type: reverse_synctex
[15:22:17] [SyncTexJs] Execute syncTexJsBackward: {"pdfPath":"d:\\Carlos\\Documents\\ThunderHub\\Matemática Estatística\\Apontamentos\\main.pdf","page":4,"x":327.81710883720933,"y":442.13882805362334}
[15:22:17] [SyncTexJs] Backward SyncTeX failed.
[15:22:17] Input file to jump to does not exist in the file system: d:/Carlos/Documents/ThunderHub/Matem?tica Estat?stica/Apontamentos/./TeX_files/intro.tex
[15:22:17] SyncTexJsError: Input file to jump to does not exist in the file system: d:/Carlos/Documents/ThunderHub/Matem?tica Estat?stica/Apontamentos/./TeX_files/intro.tex
	at SyncTexJs.convInputFilePath (c:\Users\carlo\.vscode\extensions\james-yu.latex-workshop-8.21.0\out\src\components\locatorlib\synctex.js:256:15)
	at SyncTexJs.syncTexJsBackward (c:\Users\carlo\.vscode\extensions\james-yu.latex-workshop-8.21.0\out\src\components\locatorlib\synctex.js:241:30)
	at Locator.locate (c:\Users\carlo\.vscode\extensions\james-yu.latex-workshop-8.21.0\out\src\components\locator.js:280:41)
	at Viewer.handler (c:\Users\carlo\.vscode\extensions\james-yu.latex-workshop-8.21.0\out\src\components\viewer.js:440:45)
	at WebSocket.<anonymous> (c:\Users\carlo\.vscode\extensions\james-yu.latex-workshop-8.21.0\out\src\components\server.js:92:68)
	at WebSocket.emit (events.js:315:20)
	at Receiver.receiverOnMessage (c:\Users\carlo\.vscode\extensions\james-yu.latex-workshop-8.21.0\node_modules\ws\lib\websocket.js:834:20)
	at Receiver.emit (events.js:315:20)
	at Receiver.dataMessage (c:\Users\carlo\.vscode\extensions\james-yu.latex-workshop-8.21.0\node_modules\ws\lib\receiver.js:437:14)
	at Receiver.getData (c:\Users\carlo\.vscode\extensions\james-yu.latex-workshop-8.21.0\node_modules\ws\lib\receiver.js:367:17)
	at Receiver.startLoop (c:\Users\carlo\.vscode\extensions\james-yu.latex-workshop-8.21.0\node_modules\ws\lib\receiver.js:143:22)
	at Receiver._write (c:\Users\carlo\.vscode\extensions\james-yu.latex-workshop-8.21.0\node_modules\ws\lib\receiver.js:78:10)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at Receiver.Writable.write (internal/streams/writable.js:303:10)
	at Socket.socketOnData (c:\Users\carlo\.vscode\extensions\james-yu.latex-workshop-8.21.0\node_modules\ws\lib\websocket.js:909:35)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

Nothing suspicious.
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 10
 - VS Code version: 1.61.1
 - Extension version: 8.21.0
 - TeX distribution version: TeX Live 2019

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

I think the code is building the path in a weird way. The path should not contain the "/./" that appears on the LatexWorkshop log.

**Comment by jlelong** [comment]
The problem is not with the extra `/./` but that `Matemática Estatística` is turned into `Matem?tica Estat?stica`. I would say that this is because the encoding of your filesystem is not properly detected. I do not think we can do much about it.

**Comment by tamuratak** [comment]
Added the following encodings:

> IBM codepages: 437, 737, 775, 808, 850, 852, 855-858, 860-866, 869, 922, 1046, 1124, 1125, 1129, 1133, 1161-1163 (aliases cpXXX, ibmXXX)

- https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings

CP850 and CP860 covers  Portuguese.

- https://en.wikipedia.org/wiki/Code_page_850
- https://en.wikipedia.org/wiki/Code_page_860
