### ISSUE TITLE
"ReadableStream is not defined" Error when trying to build a recipe under WSL

### ISSUE THREAD

**Issue by jfeldma** [James-Yu/LaTeX-Workshop#3076]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes
Only "Remote Development" and LaTeX Workshop are enabled.

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

I created a simple main.tex with a minimal working example, which can be compiled with pdflatex without problems.

## Describe the bug [Required]

I have problems getting LaTeX Workshop to do something at all, running under WSL (tried both WSL 1 and WSL 2).
I have a fresh installed Ubuntu WSL with only TexLive related things installed.
Installed the above-mentioned Extensions in VSCode and tried to Compile a tex document.

When invoking a build command in LaTeX Workshop I get very little output on the "LaTex Workshop" and "LaTex Compiler" log.
After invoking a build the build also can't be aborted since "Terminate current compilation" gives an error too.
The Developer Console gives a `ReadableStream is not defined` error which is also reported under "Runtime Status" of LaTeX Workshop.
See the logs below for more details.

### To Reproduce

1. ...
2. Click build (with recipe)
3. See error

### Expected behavior

LaTeX Workshop starting the expected tools to compile the document.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[13:55:28] Initializing LaTeX Workshop.
[13:55:28] Creating PDF file watcher.
[13:55:28] Creating LaTeX Workshop http and websocket server.
[13:55:28] LaTeX Workshop initialized.
[13:55:28] Started finding workspace...
[13:55:28] Current workspace folders: ["file:///home/jasmin/latextest"]
[13:55:28] Current workspaceRootDir: /home/jasmin/latextest
[13:55:28] Found root file from active editor: /home/jasmin/latextest/main.tex
[13:55:28] Root file changed: from undefined to /home/jasmin/latextest/main.tex
[13:55:28] Start to find all dependencies.
[13:55:28] Instantiating a new file watcher for /home/jasmin/latextest/main.tex
[13:55:28] Creating Bib file watcher.
[13:55:28] Parsing a file and its subfiles: /home/jasmin/latextest/main.tex
[13:55:28] Parse fls file.
[13:55:28] Cannot find fls file: /home/jasmin/latextest/main.fls
[13:55:28] Server created on 127.0.0.1:36391
[13:55:28] Added to file watcher: /home/jasmin/latextest/main.tex
[13:55:28] Snippet data loaded.
[13:55:28] LaTeX Workshop version: 8.11.1
[13:55:36] BUILD command invoked.
[13:55:36] Started finding workspace...
[13:55:36] Current workspace folders: ["file:///home/jasmin/latextest"]
[13:55:36] Current workspaceRootDir: /home/jasmin/latextest
[13:55:36] Found root file from active editor: /home/jasmin/latextest/main.tex
[13:55:36] Keep using the same root file: /home/jasmin/latextest/main.tex.
[13:55:36] Building root file: /home/jasmin/latextest/main.tex
[13:55:36] Build root file /home/jasmin/latextest/main.tex
[13:59:57] KILL command invoked.
[13:59:57] LaTeX build process to kill is not found.
```

### Developer Tools Console [Required]

```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: ReferenceError: ReadableStream is not defined
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:628
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:628
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
(anonymous) @ browserSocketFactory.ts:230
fire @ event.ts:628
E._fileReader.onload @ browserSocketFactory.ts:91
load (async)
E @ browserSocketFactory.ts:86
create @ browserSocketFactory.ts:203
connect @ browserSocketFactory.ts:277
r @ remoteAgentConnection.ts:193
l @ remoteAgentConnection.ts:234
s @ remoteAgentConnection.ts:321
S @ remoteAgentConnection.ts:363
w @ remoteAgentConnection.ts:433
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
w @ remoteAgentConnection.ts:432
(anonymous) @ remoteExtensionHost.ts:129
processTicksAndRejections @ internal/process/task_queues.js:93
Promise.then (async)
start @ remoteExtensionHost.ts:105
ns @ extensionHostManager.ts:124
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
f @ extensionHostManager.ts:57
(anonymous) @ abstractExtensionService.ts:626
_startExtensionHosts @ abstractExtensionService.ts:625
_initialize @ abstractExtensionService.ts:522
(anonymous) @ extensionService.ts:110
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1148
(anonymous) @ extensionService.ts:109
Promise.then (async)
rc @ extensionService.ts:107
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
acquireInstantiationService @ configurationService.ts:461
(anonymous) @ workbench.ts:214
invokeFunction @ instantiationService.ts:61
initServices @ workbench.ts:208
startup @ workbench.ts:139
open @ desktop.main.ts:115
async function (async)
open @ desktop.main.ts:106
K @ desktop.main.ts:378
m.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:180
i._invokeFactory @ loader.js:1185
i.complete @ loader.js:1195
i._onModuleComplete @ loader.js:1821
i._onModuleComplete @ loader.js:1833
i._resolve @ loader.js:1781
i.defineModule @ loader.js:1424
v @ loader.js:1871
define @ loader.js:1947
(anonymous) @ extensionService.ts:594
(anonymous) @ fake:1
console.ts:137 [Extension Host] stack trace: ReferenceError: ReadableStream is not defined	at MessageHandler.sendWithStream (/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45460:5)	at new PDFWorkerStreamReader (/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45833:45)	at PDFWorkerStream.getFullReader (/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45797:31)	at getPdfManager (/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:306:35)	at setupDoc (/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:457:7)	at wphReady (/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:646:7)	at LoopbackPort.MessageHandler._onComObjOnMessage (/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45410:7)	at /home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.js:2062:18	at Array.forEach (<anonymous>)	at /home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.js:2061:23	at processTicksAndRejections (internal/process/task_queues.js:93:5)
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:628
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:628
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
(anonymous) @ browserSocketFactory.ts:230
fire @ event.ts:628
E._fileReader.onload @ browserSocketFactory.ts:91
load (async)
E @ browserSocketFactory.ts:86
create @ browserSocketFactory.ts:203
connect @ browserSocketFactory.ts:277
r @ remoteAgentConnection.ts:193
l @ remoteAgentConnection.ts:234
s @ remoteAgentConnection.ts:321
S @ remoteAgentConnection.ts:363
w @ remoteAgentConnection.ts:433
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
w @ remoteAgentConnection.ts:432
(anonymous) @ remoteExtensionHost.ts:129
processTicksAndRejections @ internal/process/task_queues.js:93
Promise.then (async)
start @ remoteExtensionHost.ts:105
ns @ extensionHostManager.ts:124
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
f @ extensionHostManager.ts:57
(anonymous) @ abstractExtensionService.ts:626
_startExtensionHosts @ abstractExtensionService.ts:625
_initialize @ abstractExtensionService.ts:522
(anonymous) @ extensionService.ts:110
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1148
(anonymous) @ extensionService.ts:109
Promise.then (async)
rc @ extensionService.ts:107
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
acquireInstantiationService @ configurationService.ts:461
(anonymous) @ workbench.ts:214
invokeFunction @ instantiationService.ts:61
initServices @ workbench.ts:208
startup @ workbench.ts:139
open @ desktop.main.ts:115
async function (async)
open @ desktop.main.ts:106
K @ desktop.main.ts:378
m.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:180
i._invokeFactory @ loader.js:1185
i.complete @ loader.js:1195
i._onModuleComplete @ loader.js:1821
i._onModuleComplete @ loader.js:1833
i._resolve @ loader.js:1781
i.defineModule @ loader.js:1424
v @ loader.js:1871
define @ loader.js:1947
(anonymous) @ extensionService.ts:594
(anonymous) @ fake:1
mainThreadExtensionService.ts:63 [[object Object]]ReadableStream is not defined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:628
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:628
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
(anonymous) @ browserSocketFactory.ts:230
fire @ event.ts:628
E._fileReader.onload @ browserSocketFactory.ts:91
load (async)
E @ browserSocketFactory.ts:86
create @ browserSocketFactory.ts:203
connect @ browserSocketFactory.ts:277
r @ remoteAgentConnection.ts:193
l @ remoteAgentConnection.ts:234
s @ remoteAgentConnection.ts:321
S @ remoteAgentConnection.ts:363
w @ remoteAgentConnection.ts:433
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
w @ remoteAgentConnection.ts:432
(anonymous) @ remoteExtensionHost.ts:129
processTicksAndRejections @ internal/process/task_queues.js:93
Promise.then (async)
start @ remoteExtensionHost.ts:105
ns @ extensionHostManager.ts:124
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
f @ extensionHostManager.ts:57
(anonymous) @ abstractExtensionService.ts:626
_startExtensionHosts @ abstractExtensionService.ts:625
_initialize @ abstractExtensionService.ts:522
(anonymous) @ extensionService.ts:110
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1148
(anonymous) @ extensionService.ts:109
Promise.then (async)
rc @ extensionService.ts:107
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
acquireInstantiationService @ configurationService.ts:461
(anonymous) @ workbench.ts:214
invokeFunction @ instantiationService.ts:61
initServices @ workbench.ts:208
startup @ workbench.ts:139
open @ desktop.main.ts:115
async function (async)
open @ desktop.main.ts:106
K @ desktop.main.ts:378
m.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:180
i._invokeFactory @ loader.js:1185
i.complete @ loader.js:1195
i._onModuleComplete @ loader.js:1821
i._onModuleComplete @ loader.js:1833
i._resolve @ loader.js:1781
i.defineModule @ loader.js:1424
v @ loader.js:1871
define @ loader.js:1947
(anonymous) @ extensionService.ts:594
(anonymous) @ fake:1
mainThreadExtensionService.ts:64 ReferenceError: ReadableStream is not defined
	at MessageHandler.sendWithStream (vscode-file://vscode-app/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45460)
	at new PDFWorkerStreamReader (vscode-file://vscode-app/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45833)
	at PDFWorkerStream.getFullReader (vscode-file://vscode-app/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45797)
	at getPdfManager (vscode-file://vscode-app/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:306)
	at setupDoc (vscode-file://vscode-app/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:457)
	at wphReady (vscode-file://vscode-app/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:646)
	at LoopbackPort.MessageHandler._onComObjOnMessage (vscode-file://vscode-app/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45410)
	at vscode-file://vscode-app/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.js:2062
	at Array.forEach (<anonymous>)
	at vscode-file://vscode-app/home/jasmin/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.js:2061
	at processTicksAndRejections (internal/process/task_queues.js:93)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:628
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:628
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
(anonymous) @ browserSocketFactory.ts:230
fire @ event.ts:628
E._fileReader.onload @ browserSocketFactory.ts:91
load (async)
E @ browserSocketFactory.ts:86
create @ browserSocketFactory.ts:203
connect @ browserSocketFactory.ts:277
r @ remoteAgentConnection.ts:193
l @ remoteAgentConnection.ts:234
s @ remoteAgentConnection.ts:321
S @ remoteAgentConnection.ts:363
w @ remoteAgentConnection.ts:433
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
w @ remoteAgentConnection.ts:432
(anonymous) @ remoteExtensionHost.ts:129
processTicksAndRejections @ internal/process/task_queues.js:93
Promise.then (async)
start @ remoteExtensionHost.ts:105
ns @ extensionHostManager.ts:124
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
f @ extensionHostManager.ts:57
(anonymous) @ abstractExtensionService.ts:626
_startExtensionHosts @ abstractExtensionService.ts:625
_initialize @ abstractExtensionService.ts:522
(anonymous) @ extensionService.ts:110
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1148
(anonymous) @ extensionService.ts:109
Promise.then (async)
rc @ extensionService.ts:107
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
acquireInstantiationService @ configurationService.ts:461
(anonymous) @ workbench.ts:214
invokeFunction @ instantiationService.ts:61
initServices @ workbench.ts:208
startup @ workbench.ts:139
open @ desktop.main.ts:115
async function (async)
open @ desktop.main.ts:106
K @ desktop.main.ts:378
m.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:180
i._invokeFactory @ loader.js:1185
i.complete @ loader.js:1195
i._onModuleComplete @ loader.js:1821
i._onModuleComplete @ loader.js:1833
i._resolve @ loader.js:1781
i.defineModule @ loader.js:1424
v @ loader.js:1871
define @ loader.js:1947
(anonymous) @ extensionService.ts:594
(anonymous) @ fake:1
```

## Desktop [Required]

 - OS: Windows 10 (Windows_NT x64 10.0.19042)
 - VS Code version: 1.64.0
 - Extension version: v8.11.1
 - TeX distribution version: TeX Live 2019 (Ubuntu WSL)

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

Yes

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH
- Remote WSL Version: v0.64.2
- Remote Extension Version: v0.21.0

**Comment by jfeldma** [comment]
Nvm, fixed it myself.
Somehow when searching for tex workshop under extensions a forked version pops up on top which I accidentally installed.
Works like a charm with the right one...
