### ISSUE TITLE
Formatter (latexindent) doesn't behave as expected compared to other plugins or manual use

### ISSUE THREAD

**Issue by apotenza92** [James-Yu/LaTeX-Workshop#3445]
## Preliminary questions [Required]

Formatter within LaTeX Workshop doesn't behave as expected compared to other plugins or manual use of latexindent.

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

LaTeX Workshop indents basically nothing compared to mathematic.vscode-latex or nickfode.latex-formatter plugins if running them as Formatters.

### To Reproduce

1. Run Format Document via LaTeX Workshop
2. Observe that most things aren't indented
3. Run Format Document via one of the other plugins (mathematic.vscode-latex or nickfode.latex-formatter)
4. Observe that most things get properly indented and spaced.

### Expected behavior

A lot more things should get properly indented and spaced like the other plugins do when using latexindent.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[13:55:52] Start formatting with latexindent.
[13:55:52] Format with command: latexindent
[13:55:52] Format with command args: ["-c","%DIR%/","%TMPFILE%","-y=defaultIndent: '%INDENT%'"]
[13:55:53] Formatted c:\Users\apote\AppData\Roaming\pandoc\templates\default.ltx
[13:55:56] onDidSaveTextDocument triggered: file:///c:/Users/apote/AppData/Roaming/pandoc/templates/default.ltx
[13:55:56] Linter for root file started.
[13:55:56] Linter for root command: chktex
[13:55:56] Linter for root command args: ["-wall","-n22","-n30","-e16","-q","-f%f:%l:%c:%d:%k:%n:%m\n","c:\\Users\\apote\\AppData\\Roaming\\pandoc\\templates\\default.ltx"]
[13:55:56] File watcher - file changed: c:\Users\apote\AppData\Roaming\pandoc\templates\default.ltx
[13:55:56] Auto build started detecting the change of a file: c:\Users\apote\AppData\Roaming\pandoc\templates\default.ltx
[13:55:56] BUILD command invoked.
[13:55:56] The document of the active editor: output:extension-output-James-Yu.latex-workshop-%231-LaTeX Workshop
[13:55:56] The languageId of the document: Log
[13:55:56] Cannot find LaTeX root file. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#the-root-file
[13:55:56] Linter for root successfully finished in 0s 767ms
[13:55:56] The .chktexrc file not found.
[13:55:56] Linter log parsed with 509 messages.

```

### Developer Tools Console [Required]

```
 ERR You can't use 'macro parameter character #' in math mode: Error: You can't use 'macro parameter character #' in math mode
    at Object.formatError (c:\Users\apote\.vscode\extensions\james-yu.latex-workshop-8.29.0\out\src\providers\preview\mathjaxpool_worker.js:40:47)
    at TeX.compile (c:\Users\apote\.vscode\extensions\james-yu.latex-workshop-8.29.0\node_modules\mathjax-full\js\input\tex.js:124:33)
    at HTMLMathItem.AbstractMathItem.compile (c:\Users\apote\.vscode\extensions\james-yu.latex-workshop-8.29.0\node_modules\mathjax-full\js\core\MathItem.js:56:39)
    at Object.renderMath (c:\Users\apote\.vscode\extensions\james-yu.latex-workshop-8.29.0\node_modules\mathjax-full\js\core\MathDocument.js:115:65)
    at RenderList.renderConvert (c:\Users\apote\.vscode\extensions\james-yu.latex-workshop-8.29.0\node_modules\mathjax-full\js\core\MathDocument.js:167:35)
    at HTMLMathItem.AbstractMathItem.convert (c:\Users\apote\.vscode\extensions\james-yu.latex-workshop-8.29.0\node_modules\mathjax-full\js\core\MathItem.js:52:32)
    at HTMLDocument.AbstractMathDocument.convert (c:\Users\apote\.vscode\extensions\james-yu.latex-workshop-8.29.0\node_modules\mathjax-full\js\core\MathDocument.js:325:15)
    at Function.typeset (c:\Users\apote\.vscode\extensions\james-yu.latex-workshop-8.29.0\out\src\providers\preview\mathjaxpool_worker.js:60:23)
    at process.<anonymous> (c:\Users\apote\.vscode\extensions\james-yu.latex-workshop-8.29.0\node_modules\workerpool\src\worker.js:125:27)
    at process.emit (node:events:390:28)
```

## Screenshots
Formatted with LaTeX Workshop - essentially flat, very few indents
![formatted with LaTeX Workshop](https://user-images.githubusercontent.com/53612685/187828078-43b97e49-ec16-48b7-ab64-3e5e38b58dc1.png)

Formatted with nickfode.latex-formatter - lots of indents
![formatted with nickfode.latex-formatter](https://user-images.githubusercontent.com/53612685/187828128-7cc7a468-f40a-41b0-b7c9-720c5c0bca09.png)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 11
 - VS Code version: 1.70.2
 - Extension version: 8.29.0
 - TeX distribution version: TeX Live 2022

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by James-Yu** [comment]
I don't see an issue or a bug in the log. Please provide a minimal working example and the expected (but not achieved) result.

**Comment by apotenza92** [comment]
I can provide another screenshot? I'm not totally sure if the default command given to latexindent by LaTeX Workshop is just different to the other two plugins I cited? I can't get LW to produce a formatted output similar to those plugins. I'd really like it to so I don't need to keep other plugins around just for formatting.

**Comment by James-Yu** [comment]
Screenshot won't work.

**Comment by apotenza92** [comment]
If I format in VS Code using the extension I should get the same output as when I run latexindent manually via a perl command line. The logs I attached earlier are the only things shown when running latexindent via formatter within VS Code. 

[formatted using latex workshop.txt](https://github.com/James-Yu/LaTeX-Workshop/files/9467259/formatted.using.latex.workshop.txt)

[formatted using latexindent in command line.txt](https://github.com/James-Yu/LaTeX-Workshop/files/9467260/formatted.using.latexindent.in.command.line.txt)

**Comment by apotenza92** [comment]
Ok thanks, I see that as .tex the output is the same. 
However, I was dealing with .ltx files originally, I only converted them to .txt to send via GitHub. 
As .ltx everything I showed earlier still applies. Does this extension not format .ltx files?

**Comment by James-Yu** [comment]
This is why we (and almost all devs in the Internet) ask for minimal working example. Otherwise your issue cannot be handled.

**Comment by apotenza92** [comment]
Apologies, couldn't send .ltx with GitHub. Here are 3 files of no indents, extension indents, and latexindent.pl indents to compare.
[files](https://1drv.ms/u/s!Ak4Fv91yV9h3jJA3FDdSQ33fRaSGmw?e=1epKi1)
