### ISSUE TITLE
Error: Illegal control sequence name for \renewcommand

### ISSUE THREAD

**Issue by NikitaIT** [James-Yu/LaTeX-Workshop#3519]
## Fix

Set
https://github.com/jlelong/LaTeX-Workshop-wiki/blob/master/Hover.md#latex-workshophoverpreviewnewcommandparseTeXFileenabled

```
  "latex-workshop.hover.preview.newcommand.parseTeXFile.enabled": false
```

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Maybe it's MathJax issue.

[11:25:03] Error: Illegal control sequence name for \renewcommand

Formula not rendered on hover

### To Reproduce

1. Hover on formula

### LaTeX Workshop Output [Required]
```
...
\afterpage{\tocheader}
\fi}{}}\newcommand{\basegostsectionfont}{\fontsize{14pt}{16pt}\selectfont\bfseries}\def\zz{\ifx\[$\else\aftergroup\zzz\fi}\renewcommand{\lstlistingname}{Листинг}\renewcommand{\le}{\ensuremath{\leqslant}}\renewcommand{\leq}{\ensuremath{\leqslant}}\renewcommand{\ge}{\ensuremath{\geqslant}}\renewcommand{\geq}{\ensuremath{\geqslant}}\renewcommand{\emptyset}{\varnothing}\renewcommand{\tan}{\operatorname{tg}}\renewcommand{\cot}{\operatorname{ctg}}\renewcommand{\csc}{\operatorname{cosec}}\renewcommand{\epsilon}{\ensuremath{\upvarepsilon}}\renewcommand{\phi}{\ensuremath{\upvarphi}}\renewcommand{\alpha}{\upalpha}\renewcommand{\beta}{\upbeta}\renewcommand{\gamma}{\upgamma}\renewcommand{\delta}{\updelta}\renewcommand{\varepsilon}{\upvarepsilon}\renewcommand{\zeta}{\upzeta}\renewcommand{\eta}{\upeta}\renewcommand{\theta}{\uptheta}\renewcommand{\vartheta}{\upvartheta}\renewcommand{\iota}{\upiota}\renewcommand{\kappa}{\upkappa}\renewcommand{\lambda}{\uplambda}\renewcommand{\mu}{\upmu}\renewcommand{\nu}{\upnu}\renewcommand{\xi}{\upxi}\renewcommand{\pi}{\uppi}\renewcommand{\varpi}{\upvarpi}\renewcommand{\rho}{\uprho}\renewcommand{\sigma}{\upsigma}\renewcommand{\tau}{\uptau}\renewcommand{\upsilon}{\upupsilon}\renewcommand{\varphi}{\upvarphi}\renewcommand{\chi}{\upchi}\renewcommand{\psi}{\uppsi}\renewcommand{\omega}{\upomega}\newcommand{\autocite}[1]{}\def\oldcite{}\def\bibcite{\stepcounter{citenum}\oldcite}\renewcommand{\revsdnamepunct}{\addcomma}}{}\renewcommand{\newblockpunct}{\addperiod\addnbspace\cyrdash\space\bibsentence}\def\bibdaterangesep{\bibrangedash}\def\bibdaterangesep{\bibrangedash}\renewcommand{\contentsname}{Оглавление}\renewcommand{\figurename}{Рисунок}\renewcommand{\tablename}{Таблица}\renewcommand{\listfigurename}{Список рисунков}\renewcommand{\listtablename}{Список таблиц}\renewcommand{\bibname}{\bibtitlefull}\renewcommand{\nomname}{Список сокращений и условных обозначений}\renewcommand{\eqdeclaration}[1]{, см.~ (#1)}\renewcommand{\pagedeclaration}[1]{, стр.~#1}\renewcommand{\nomAname}{Латинские буквы}\renewcommand{\nomGname}{Греческие буквы}\renewcommand{\nomXname}{Верхние индексы}\renewcommand{\nomZname}{Индексы}\newcommand{\actuality}{}\newcommand{\progress}{}\newcommand{\aim}{{\textbf\aimTXT}}\newcommand{\tasks}{\textbf{\tasksTXT}}\newcommand{\novelty}{\textbf{\noveltyTXT}}\newcommand{\influence}{\textbf{\influenceTXT}}\newcommand{\methods}{\textbf{\methodsTXT}}\newcommand{\defpositions}{\textbf{\defpositionsTXT}}\newcommand{\reliability}{\textbf{\reliabilityTXT}}\newcommand{\probation}{\textbf{\probationTXT}}\newcommand{\contribution}{\textbf{\contributionTXT}}\newcommand{\publications}{\textbf{\publicationsTXT}}\renewcommand{\arraystretch}{1.6}\renewcommand{\arraystretch}{0.9}\begin{equation}
    
    MHT: \left(\{0,1\}^*\right)^n \rightarrow \{0,1\}^{2\lambda}
\end{equation}
[11:25:03] Illegal control sequence name for \renewcommand
[11:25:03] Error: Illegal control sequence name for \renewcommand
    at Object.formatError (/Users/nikitafedorov/.vscode/extensions/james-yu.latex-workshop-8.29.0/out/src/providers/preview/mathjaxpool_worker.js:40:47)
    at TeX.compile (/Users/nikitafedorov/.vscode/extensions/james-yu.latex-workshop-8.29.0/node_modules/mathjax-full/js/input/tex.js:124:33)
    at AbstractMathItem.compile (/Users/nikitafedorov/.vscode/extensions/james-yu.latex-workshop-8.29.0/node_modules/mathjax-full/js/core/MathItem.js:56:39)
    at Object.renderMath (/Users/nikitafedorov/.vscode/extensions/james-yu.latex-workshop-8.29.0/node_modules/mathjax-full/js/core/MathDocument.js:115:65)
    at RenderList.renderConvert (/Users/nikitafedorov/.vscode/extensions/james-yu.latex-workshop-8.29.0/node_modules/mathjax-full/js/core/MathDocument.js:167:35)
    at AbstractMathItem.convert (/Users/nikitafedorov/.vscode/extensions/james-yu.latex-workshop-8.29.0/node_modules/mathjax-full/js/core/MathItem.js:52:32)
    at AbstractMathDocument.convert (/Users/nikitafedorov/.vscode/extensions/james-yu.latex-workshop-8.29.0/node_modules/mathjax-full/js/core/MathDocument.js:325:15)
    at Function.typeset (/Users/nikitafedorov/.vscode/extensions/james-yu.latex-workshop-8.29.0/out/src/providers/preview/mathjaxpool_worker.js:60:23)
    at process.<anonymous> (/Users/nikitafedorov/.vscode/extensions/james-yu.latex-workshop-8.29.0/node_modules/workerpool/src/worker.js:125:27)
    at process.emit (node:events:526:28)
[11:25:03] Error when MathJax is rendering 
\renewcommand{\@ cref}[2]{
```

### Developer Tools Console [Required]

Not related.
```
mainThreadExtensionService.ts:79 [[object Object]]Cannot read properties of undefined (reading 'document')
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
mainThreadExtensionService.ts:80 TypeError: Cannot read properties of undefined (reading 'document')
	at vscode-file://vscode-app/Users/nikitafedorov/.vscode/extensions/arjun.swagger-viewer-3.1.2/out/preview/client.js:170:63
	at p.invoke (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at b.fire (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at D.$acceptDirtyStateChanged (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:12289)
	at D.$acceptModelSaved (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:12032)
	at i._doInvokeHandler (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:13680)
	at i._invokeHandler (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:13362)
	at i._receiveRequest (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:12132)
	at i._receiveOneMessage (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:10834)
	at vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:8941
	at p.invoke (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at b.fire (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.fire (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:19049)
	at vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:17106
	at p.invoke (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at b.fire (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.fire (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:19049)
	at s._receiveMessage (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:23861)
	at vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:21304
	at p.invoke (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at b.fire (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at b.acceptChunk (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:15880)
	at vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:15010
	at Socket.d (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:27128)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: MacoS
 - VS Code version: last
 - Extension version: last
 - TeX distribution version: MacTex

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by James-Yu** [comment]
Can you please provide a minimal working example on this bug? Thanks!
