### ISSUE TITLE
ENOTDIR error when building

### ISSUE THREAD

**Issue by moxxio** [James-Yu/LaTeX-Workshop#3555]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]
When I try to compile a tex file, vsc notifies me that "a system error occurred (spawn ENOTDIR)".

### To Reproduce

I installed the extension, set the path variable (I had texlive already installed) and tried to build.

### Expected behavior
No error.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[03:06:14] Initializing LaTeX Workshop.
[03:06:14] Extension root: /home/moxx/.vscode/extensions/james-yu.latex-workshop-9.0.1
[03:06:14] $PATH: /home/moxx/.local/bin:/home/moxx/.opam/compilation/bin:/home/moxx/anaconda3/bin:/home/moxx/anaconda3/condabin:/home/moxx/anaconda3/bin:/home/moxx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/bin/latex
[03:06:14] $SHELL: /bin/bash
[03:06:14] $LANG: en_US.UTF-8
[03:06:14] $LC_ALL: undefined
[03:06:14] process.platform: linux
[03:06:14] process.arch: x64
[03:06:14] vscode.env.appName: Visual Studio Code
[03:06:14] vscode.env.remoteName: undefined
[03:06:14] vscode.env.uiKind: 1
[03:06:14] Configuration for workspace: file:///home/moxx/Rheya/beruf/cv
[03:06:14] editor.acceptSuggestionOnEnter: "on"
[03:06:14] latex-workshop.bind.enter.key: true
[03:06:14] latex-workshop.docker.enabled: false
[03:06:14] latex-workshop.docker.image.latex: ""
[03:06:14] latex-workshop.hover.preview.mathjax.extensions: []
[03:06:14] latex-workshop.intellisense.package.enabled: true
[03:06:14] latex-workshop.intellisense.update.aggressive.enabled: false
[03:06:14] latex-workshop.intellisense.update.delay: 1000
[03:06:14] latex-workshop.latex.autoBuild.run: "onFileChange"
[03:06:14] latex-workshop.latex.build.forceRecipeUsage: true
[03:06:14] latex-workshop.latex.outDir: "%DIR%"
[03:06:14] latex-workshop.latex.recipes: [
 {
  "name": "latexmk 🔃",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmk (latexmkrc)",
  "tools": [
   "latexmk_rconly"
  ]
 },
 {
  "name": "latexmk (lualatex)",
  "tools": [
   "lualatexmk"
  ]
 },
 {
  "name": "latexmk (xelatex)",
  "tools": [
   "xelatexmk"
  ]
 },
 {
  "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
  "tools": [
   "pdflatex",
   "bibtex",
   "pdflatex",
   "pdflatex"
  ]
 },
 {
  "name": "Compile Rnw files",
  "tools": [
   "rnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Jnw files",
  "tools": [
   "jnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "tectonic",
  "tools": [
   "tectonic"
  ]
 }
]
[03:06:14] latex-workshop.latex.tools: [
 {
  "name": "latexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-pdf",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "lualatexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-lualatex",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "xelatexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-xelatex",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "latexmk_rconly",
  "command": "latexmk",
  "args": [
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "pdflatex",
  "command": "pdflatex",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "bibtex",
  "command": "bibtex",
  "args": [
   "%DOCFILE%"
  ],
  "env": {}
 },
 {
  "name": "rnw2tex",
  "command": "Rscript",
  "args": [
   "-e",
   "knitr::opts_knit$set(concordance = TRUE); knitr::knit('%DOCFILE_EXT%')"
  ],
  "env": {}
 },
 {
  "name": "jnw2tex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"tex\")"
  ],
  "env": {}
 },
 {
  "name": "jnw2texmintex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"texminted\")"
  ],
  "env": {}
 },
 {
  "name": "tectonic",
  "command": "tectonic",
  "args": [
   "--synctex",
   "--keep-logs",
   "%DOC%.tex"
  ],
  "env": {}
 }
]
[03:06:14] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto"
[03:06:14] Creating a new file watcher.
[03:06:14] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[03:06:14] Creating PDF file watcher.
[03:06:14] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[03:06:14] Creating Bib file watcher.
[03:06:14] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[03:06:14] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[03:06:14] [Server] Creating LaTeX Workshop http and websocket server.
[03:06:14] LaTeX Workshop initialized.
[03:06:14] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[03:06:14] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[03:06:14] Current workspace folders: ["file:///home/moxx/Rheya/beruf/cv"]
[03:06:14] Found root file from active editor: /home/moxx/Rheya/beruf/cv/cv.tex
[03:06:14] Root file changed: from undefined to /home/moxx/Rheya/beruf/cv/cv.tex
[03:06:14] Start to find all dependencies.
[03:06:14] Root file languageId: latex
[03:06:14] Reset file watcher.
[03:06:14] Parsing a file and its subfiles: /home/moxx/Rheya/beruf/cv/cv.tex
[03:06:14] Parse fls file.
[03:06:14] Cannot find fls file: /home/moxx/Rheya/beruf/cv/cv.fls
[03:06:14] [Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":36031}
[03:06:14] Added to file watcher: /home/moxx/Rheya/beruf/cv/cv.tex
[03:06:14] Snippet data loaded.
[03:06:14] [Server] valdOrigin is http://127.0.0.1:36031
[03:06:15] Checking for duplicate labels: /home/moxx/Rheya/beruf/cv/cv.tex.
[03:06:16] Manager.fileWatcher.getWatched: {"/home/moxx/Rheya/beruf/cv":["cv.tex"]}
[03:06:16] Manager.filesWatched: ["/home/moxx/Rheya/beruf/cv/cv.tex"]
[03:06:16] BibWatcher.bibWatcher.getWatched: {}
[03:06:16] BibWatcher.bibsWatched: []
[03:06:16] PdfWatcher.pdfWatcher.getWatched: {}
[03:06:16] PdfWatcher.pdfsWatched: []
[03:06:16] PdfWatcher.watchedPdfVirtualUris: []
[03:06:16] PdfWatcher.ignoredPdfUris: []
[03:06:17] BUILD command invoked.
[03:06:17] The document of the active editor: file:///home/moxx/Rheya/beruf/cv/cv.tex
[03:06:17] The languageId of the document: latex
[03:06:17] Current workspace folders: ["file:///home/moxx/Rheya/beruf/cv"]
[03:06:17] Found root file from active editor: /home/moxx/Rheya/beruf/cv/cv.tex
[03:06:17] Keep using the same root file: /home/moxx/Rheya/beruf/cv/cv.tex
[03:06:17] Building root file: /home/moxx/Rheya/beruf/cv/cv.tex
[03:06:17] Build root file /home/moxx/Rheya/beruf/cv/cv.tex
[03:06:17] outDir: /home/moxx/Rheya/beruf/cv
[03:06:17] Recipe step 1: latexmk
[03:06:17] Recipe step 1 args: ["-synctex=1","-interaction=nonstopmode","-file-line-error","-pdf","-outdir=/home/moxx/Rheya/beruf/cv","/home/moxx/Rheya/beruf/cv/cv"]
[03:06:17] Recipe step env: {}
[03:06:17] Recipe step root file: /home/moxx/Rheya/beruf/cv/cv.tex
[03:06:17] cwd: /home/moxx/Rheya/beruf/cv

```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

workbench.desktop.main.js:820 Error: A system error occurred (spawn ENOTDIR)
	at s._executeContributedCommand (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:111561)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
onDidChangeNotification @ workbench.desktop.main.js:820
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/6261075646f055b99068d3688932416f2346dd3b/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

```

### Extension Host
I add the extension host log as it might be of interest.

```
2022-11-24 03:06:17.494 [error] Error: spawn ENOTDIR
	at ChildProcess.spawn (node:internal/child_process:413:11)
	at Object.spawn (node:child_process:720:9)
	at Object.spawn [as default] (/home/moxx/.vscode/extensions/james-yu.latex-workshop-9.0.1/node_modules/cross-spawn/index.js:12:24)
	at Builder.spawnProcess (/home/moxx/.vscode/extensions/james-yu.latex-workshop-9.0.1/out/src/components/builder.js:247:31)
	at Builder.buildLoop (/home/moxx/.vscode/extensions/james-yu.latex-workshop-9.0.1/out/src/components/builder.js:190:30)
	at Builder.build (/home/moxx/.vscode/extensions/james-yu.latex-workshop-9.0.1/out/src/components/builder.js:165:20)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Commander.build (/home/moxx/.vscode/extensions/james-yu.latex-workshop-9.0.1/out/src/commander.js:120:9)
	at async s._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:111367) latex-workshop.build {"value":"James-Yu.latex-workshop","_lower":"james-yu.latex-workshop"}
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Ubuntu 22.04.1 LTS
 - VS Code version: 1.73.1
 - Extension version: 9.0.1
 - TeX distribution version: TeX Live 2022

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by moxxio** [comment]
Apparently, this error occurs if you do not have  `latexmk` installed.
