### ISSUE TITLE
PDF viewer won't refresh or jump after returning from suspend

### ISSUE THREAD

**Issue by edemaine** [James-Yu/LaTeX-Workshop#3591]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: n/a

## Describe the bug [Required]

Just like #1804 and #1304, the connection to the PDF viewer seems to be broken after my Windows 11 machine comes back from suspend state. When the PDF changes (e.g. from building in LaTeX Workshop), the PDF window does not refresh. SyncTeX jumping doesn't work in either direction.

The logs below show that LaTeX Workshop attempts to reconnect, but fails.

### To Reproduce

1. Open a LaTeX project and PDF file.
2. Suspend machine (probably needs to be Windows).
3. Modify LaTeX and build PDF.

### Expected behavior

I expect the PDF window to stay up-to-date with the PDF file.

### Workarounds

Closing and re-opening the PDF window causes it to start working again.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

In the logs below, the wake-from-suspend occurs at 14:30. The logs beforehand are likely not relevant, but included for completeness.

My project path within my home directory has been abbreviated to `...` for security.

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[13:25:29] Initializing LaTeX Workshop.
[13:25:29] Extension root: c:\Users\edemaine\.vscode\extensions\james-yu.latex-workshop-9.1.1
[13:25:29] $PATH: C:\Users\edemaine\.meteor;C:\Users\edemaine\.yarn\bin;C:\Users\edemaine\.config\yarn\global\node_modules\.bin;C:\Users\edemaine\csail\bin;C:\Users\edemaine\.local\bin;C:\cygwin64\usr\local\bin;C:\cygwin64\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\libnvvp;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files\Python310\Scripts;C:\Program Files\Python310;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\dotnet;C:\Program Files\PuTTY;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Inkscape\bin;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.1.1;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\GitHub CLI;C:\Users\edemaine\AppData\Local\pnpm;C:\Users\edemaine\AppData\Local\.meteor;C:\Users\edemaine\AppData\Roaming\npm;C:\Users\edemaine\AppData\Roaming\npm\node_modules\meteor\node_modules\.bin;C:\Users\edemaine\AppData\Roaming\npm\node_modules\.bin;C:\Users\edemaine\AppData\Roaming\node_modules\.bin;C:\Users\edemaine\AppData\node_modules\.bin;C:\Users\edemaine\node_modules\.bin;C:\Users\node_modules\.bin;C:\node_modules\.bin;C:\Users\edemaine\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\run-script\lib\node-gyp-bin;C:\Users\edemaine\.meteor;C:\Users\edemaine\.yarn\bin;C:\Users\edemaine\.config\yarn\global\node_modules\.bin;C:\Users\edemaine\csail\bin;C:\Users\edemaine\.local\bin;C:\cygwin64\usr\local\bin;C:\cygwin64\bin;C:\Windows\System32;C:\Users\edemaine\AppData\Local\Microsoft\WindowsApps;C:\Users\edemaine\AppData\Local\Programs\Microsoft VS Code;C:\Users\edemaine\AppData\Local\Programs\Microsoft VS Code\bin
[13:25:29] $SHELL: /usr/bin/zsh
[13:25:29] $LANG: undefined
[13:25:29] $LC_ALL: undefined
[13:25:29] process.platform: win32
[13:25:29] process.arch: x64
[13:25:29] vscode.env.appName: Visual Studio Code
[13:25:29] vscode.env.remoteName: undefined
[13:25:29] vscode.env.uiKind: 1
[13:25:29] Configuration for workspace: file:///c:/Users/edemaine/...
[13:25:29] editor.acceptSuggestionOnEnter: "off"
[13:25:29] latex-workshop.bind.enter.key: true
[13:25:29] latex-workshop.docker.enabled: false
[13:25:29] latex-workshop.docker.image.latex: ""
[13:25:29] latex-workshop.hover.preview.mathjax.extensions: []
[13:25:29] latex-workshop.intellisense.package.enabled: true
[13:25:29] latex-workshop.intellisense.update.aggressive.enabled: false
[13:25:29] latex-workshop.intellisense.update.delay: 1000
[13:25:29] latex-workshop.latex.autoBuild.run: "onFileChange"
[13:25:29] latex-workshop.latex.build.forceRecipeUsage: true
[13:25:29] latex-workshop.latex.outDir: "%DIR%"
[13:25:29] latex-workshop.latex.recipes: [
 {
  "name": "latexmk 🔃",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmk (latexmkrc)",
  "tools": [
   "latexmk_rconly"
  ]
 },
 {
  "name": "latexmk (lualatex)",
  "tools": [
   "lualatexmk"
  ]
 },
 {
  "name": "latexmk (xelatex)",
  "tools": [
   "xelatexmk"
  ]
 },
 {
  "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
  "tools": [
   "pdflatex",
   "bibtex",
   "pdflatex",
   "pdflatex"
  ]
 },
 {
  "name": "Compile Rnw files",
  "tools": [
   "rnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Jnw files",
  "tools": [
   "jnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "tectonic",
  "tools": [
   "tectonic"
  ]
 }
]
[13:25:29] latex-workshop.latex.tools: [
 {
  "name": "latexmk",
  "command": "bash",
  "args": [
   "-c",
   "latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=\"`cygpath \"%OUTDIR%\"`\" \"`cygpath -u \"%DOC%\"`\" | sed 's#/cygdrive/\\([a-zA-Z]\\)/#\\1:/#g' && (gunzip -kf %DOCFILE%.synctex.gz && sed 's#/cygdrive/\\([a-zA-Z]\\)/#\\1:/#g' <%DOCFILE%.synctex | gzip -c - >%DOCFILE%.synctex.gz ; rm -f %DOCFILE%.synctex)"
  ],
  "env": {}
 },
 {
  "name": "lualatexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-lualatex",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "latexmk_rconly",
  "command": "latexmk",
  "args": [
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "pdflatex",
  "command": "pdflatex",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "bibtex",
  "command": "bibtex",
  "args": [
   "%DOCFILE%"
  ],
  "env": {}
 },
 {
  "name": "rnw2tex",
  "command": "Rscript",
  "args": [
   "-e",
   "knitr::opts_knit$set(concordance = TRUE); knitr::knit('%DOCFILE_EXT%')"
  ],
  "env": {}
 },
 {
  "name": "jnw2tex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"tex\")"
  ],
  "env": {}
 },
 {
  "name": "jnw2texmintex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"texminted\")"
  ],
  "env": {}
 },
 {
  "name": "tectonic",
  "command": "tectonic",
  "args": [
   "--synctex",
   "--keep-logs",
   "%DOC%.tex"
  ],
  "env": {}
 }
]
[13:25:29] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto"
[13:25:29] Creating a new file watcher.
[13:25:29] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[13:25:29] Creating PDF file watcher.
[13:25:29] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[13:25:29] Creating Bib file watcher.
[13:25:29] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[13:25:29] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[13:25:29] Cannot run pdflatex to determine if we are using MiKTeX
[13:25:29] [Server] Creating LaTeX Workshop http and websocket server.
[13:25:29] LaTeX Workshop initialized.
[13:25:29] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[13:25:29] Bibtex format config: {"tab":"    ","case":"UPPERCASE","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[13:25:29] Current workspace folders: ["file:///c:/Users/edemaine/..."]
[13:25:29] Current workspaceRootDir: file:///c:/Users/edemaine/...
[13:25:29] [Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":56792}
[13:25:29] Snippet data loaded.
[13:25:30] [Server] valdOrigin is http://127.0.0.1:56792
[13:25:30] Restoring the PDF viewer at the column 1 from the state: {"type":"state","state":{"pdfFileUri":"file:///c:/Users/edemaine/.../main.pdf","scale":"2.1","scrollMode":0,"spreadMode":0,"scrollTop":43356.921875,"scrollLeft":364.6153869628906,"trim":0,"synctexEnabled":true,"autoReloadEnabled":true}}
[13:25:30] The internal PDF viewer url: http://127.0.0.1:56792/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRmMlM0ElMkZVc2VycyUyRmVkZW1haW5lJTJGY3NhaWwlMkZQYXBlcnMlMkZSZWRCbHVlJTJGRml4ZWRBbmdsZSUyRm1haW4ucGRm
[13:25:30] Added to PDF file watcher: file:///c:/Users/edemaine/.../main.pdf
[13:25:30] Cannot find fls file: c:\Users\edemaine\...\main.fls
[13:25:30] Cannot find fls file: c:\Users\edemaine\...\cgt_sample_article.fls
[13:25:30] Found files that might be root, choose the first one: c:\Users\edemaine\...\main.tex,c:\Users\edemaine\...\cgt_sample_article.tex
[13:25:30] Root file changed: from undefined to c:\Users\edemaine\...\main.tex
[13:25:30] Start to find all dependencies.
[13:25:30] Root file languageId: latex
[13:25:30] Reset file watcher.
[13:25:30] Parsing a file and its subfiles: c:\Users\edemaine\...\main.tex
[13:25:30] Found .bib file: c:\Users\edemaine\...\main.bib
[13:25:30] Added to bib file watcher: c:\Users\edemaine\...\main.bib
[13:25:30] Parsing .bib entries from c:\Users\edemaine\...\main.bib
[13:25:30] Added to file watcher: c:\Users\edemaine\...\main.tex
[13:25:31] Parsed 10 bib entries from c:\Users\edemaine\...\main.bib.
[13:25:31] Parse fls file.
[13:25:31] Cannot find fls file: c:\Users\edemaine\...\main.fls
[13:25:31] Handle data type: open
[13:25:31] Preview PDF file: file:///c:/Users/edemaine/.../main.pdf
[13:25:31] Checking for duplicate labels: c:\Users\edemaine\...\main.tex.
[13:25:31] Handle data type: loaded
[13:25:33] Manager.fileWatcher.getWatched: {"c:\\Users\\edemaine\\...":["main.tex"]}
[13:25:33] Manager.filesWatched: ["c:\\Users\\edemaine\\...\\main.tex"]
[13:25:33] BibWatcher.bibWatcher.getWatched: {"c:\\Users\\edemaine\\...":["main.bib"]}
[13:25:33] BibWatcher.bibsWatched: ["c:\\Users\\edemaine\\...\\main.bib"]
[13:25:33] PdfWatcher.pdfWatcher.getWatched: {"c:\\Users\\edemaine\\...":["main.pdf"]}
[13:25:33] PdfWatcher.pdfsWatched: ["c:\\Users\\edemaine\\...\\main.pdf"]
[13:25:33] PdfWatcher.watchedPdfVirtualUris: []
[13:25:33] PdfWatcher.ignoredPdfUris: []
[13:25:37] Current workspace folders: ["file:///c:/Users/edemaine/..."]
[13:25:37] Found root file from active editor: c:\Users\edemaine\...\main.tex
[13:25:37] Keep using the same root file: c:\Users\edemaine\...\main.tex
[13:26:19] onDidSaveTextDocument triggered: file:///c:/Users/edemaine/.../main.tex
[13:26:19] File watcher - file changed: c:\Users\edemaine\...\main.tex
[13:26:19] Parsing a file and its subfiles: c:\Users\edemaine\...\main.tex
[13:26:19] Found .bib file: c:\Users\edemaine\...\main.bib
[13:26:20] Checking for duplicate labels: c:\Users\edemaine\...\main.tex.
[13:26:20] Auto build started detecting the change of a file: c:\Users\edemaine\...\main.tex
[13:26:20] BUILD command invoked.
[13:26:20] The document of the active editor: file:///c:/Users/edemaine/.../main.tex
[13:26:20] The languageId of the document: latex
[13:26:20] Building root file: c:\Users\edemaine\...\main.tex
[13:26:20] Build root file c:\Users\edemaine\...\main.tex
[13:26:20] outDir: c:/Users/edemaine/...
[13:26:20] Preparing to run recipe: latexmk 🔃
[13:26:20] Recipe step 1: bash
[13:26:20] Recipe step 1 args: ["-c","latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=\"`cygpath \"c:/Users/edemaine/...\"`\" \"`cygpath -u \"c:/Users/edemaine/.../main\"`\" | sed 's#/cygdrive/\\([a-zA-Z]\\)/#\\1:/#g' && (gunzip -kf main.synctex.gz && sed 's#/cygdrive/\\([a-zA-Z]\\)/#\\1:/#g' <main.synctex | gzip -c - >main.synctex.gz ; rm -f main.synctex)"]
[13:26:20] Recipe step env: {}
[13:26:20] Recipe step root file: c:\Users\edemaine\...\main.tex
[13:26:20] cwd: c:\Users\edemaine\...
[13:26:20] LaTeX build process spawned. PID: 48552.
[13:26:27] BibTeX log parsed with 0 messages.
[13:26:27] LaTeX log parsed with 15 messages.
[13:26:27] A step in recipe finished. PID: 48552.
[13:26:27] Successfully built c:\Users\edemaine\...\main.tex.
[13:26:27] Call refreshExistingViewer: {"sourceFile":"c:\\Users\\edemaine\\...\\main.tex"}
[13:26:27] Refresh PDF viewer: file:///c%3A/Users/edemaine/.../main.pdf
[13:26:27] Parse fls file.
[13:26:27] Fls file found: c:\Users\edemaine\...\main.fls
[13:26:27] Parse aux file: c:\Users\edemaine\...\main.aux
[13:26:27] Found .bib file: c:\Users\edemaine\...\main.bib
[13:26:27] Auto Clean invoked.
[13:26:27] Clean glob matched files: {"globs":["*.blg","*.out","*.acn","*.acr","*.alg","*.glg","*.glo","*.gls","*.fls","*.fdb_latexmk","*.snm","*.synctex(busy)","*.synctex.gz(busy)","*.nav"],"outdir":"c:\\Users\\edemaine\\..."}
[13:26:27] Ignore folder glob patterns with globstar: 
[13:26:27] Cleaning file: c:\Users\edemaine\...\main.out
[13:26:27] Cleaning file: c:\Users\edemaine\...\main.fls
[13:26:27] Cleaning file: c:\Users\edemaine\...\main.fdb_latexmk
[13:26:27] Cleaning file: c:\Users\edemaine\...\main.blg
[13:26:27] Preview PDF file: file:///c:/Users/edemaine/.../main.pdf
[13:26:27] Handle data type: loaded
[13:26:27] Added to file watcher: c:\Users\edemaine\...\orcid.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\cgt-logo.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\sat.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\cross.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\compgeomtop.cls
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\spiral-analysis.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\cc-by.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\frame-loop.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\linked-3sat.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\clause-fail.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\insulation.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\clause.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\clause3.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\spiral.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\hook.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\variable.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\clause-force.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\hook2.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\sample.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\frame.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\frame_square.pdf
[13:26:27] Added to file watcher: c:\Users\edemaine\...\figures\hook-fail.pdf
[13:30:47] onDidSaveTextDocument triggered: file:///c:/Users/edemaine/.../main.tex
[13:30:47] File watcher - file changed: c:\Users\edemaine\...\main.tex
[13:30:47] Parsing a file and its subfiles: c:\Users\edemaine\...\main.tex
[13:30:47] Found .bib file: c:\Users\edemaine\...\main.bib
[13:30:48] Checking for duplicate labels: c:\Users\edemaine\...\main.tex.
[13:30:48] Auto build started detecting the change of a file: c:\Users\edemaine\...\main.tex
[13:30:48] BUILD command invoked.
[13:30:48] The document of the active editor: file:///c:/Users/edemaine/.../main.tex
[13:30:48] The languageId of the document: latex
[13:30:48] Building root file: c:\Users\edemaine\...\main.tex
[13:30:48] Build root file c:\Users\edemaine\...\main.tex
[13:30:48] outDir: c:/Users/edemaine/...
[13:30:48] Preparing to run recipe: latexmk 🔃
[13:30:48] Recipe step 1: bash
[13:30:48] Recipe step 1 args: ["-c","latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=\"`cygpath \"c:/Users/edemaine/...\"`\" \"`cygpath -u \"c:/Users/edemaine/.../main\"`\" | sed 's#/cygdrive/\\([a-zA-Z]\\)/#\\1:/#g' && (gunzip -kf main.synctex.gz && sed 's#/cygdrive/\\([a-zA-Z]\\)/#\\1:/#g' <main.synctex | gzip -c - >main.synctex.gz ; rm -f main.synctex)"]
[13:30:48] Recipe step env: {}
[13:30:48] Recipe step root file: c:\Users\edemaine\...\main.tex
[13:30:48] cwd: c:\Users\edemaine\...
[13:30:48] LaTeX build process spawned. PID: 34276.
[13:30:55] BibTeX log parsed with 0 messages.
[13:30:55] LaTeX log parsed with 15 messages.
[13:30:55] A step in recipe finished. PID: 34276.
[13:30:55] Successfully built c:\Users\edemaine\...\main.tex.
[13:30:55] Call refreshExistingViewer: {"sourceFile":"c:\\Users\\edemaine\\...\\main.tex"}
[13:30:55] Refresh PDF viewer: file:///c%3A/Users/edemaine/.../main.pdf
[13:30:55] Parse fls file.
[13:30:55] Fls file found: c:\Users\edemaine\...\main.fls
[13:30:55] Parse aux file: c:\Users\edemaine\...\main.aux
[13:30:55] Found .bib file: c:\Users\edemaine\...\main.bib
[13:30:55] Auto Clean invoked.
[13:30:55] Clean glob matched files: {"globs":["*.blg","*.out","*.acn","*.acr","*.alg","*.glg","*.glo","*.gls","*.fls","*.fdb_latexmk","*.snm","*.synctex(busy)","*.synctex.gz(busy)","*.nav"],"outdir":"c:\\Users\\edemaine\\..."}
[13:30:55] Ignore folder glob patterns with globstar: 
[13:30:55] Cleaning file: c:\Users\edemaine\...\main.out
[13:30:55] Cleaning file: c:\Users\edemaine\...\main.fls
[13:30:55] Cleaning file: c:\Users\edemaine\...\main.fdb_latexmk
[13:30:55] Cleaning file: c:\Users\edemaine\...\main.blg
[13:30:55] Preview PDF file: file:///c:/Users/edemaine/.../main.pdf
[13:30:55] Handle data type: loaded
[14:40:19] Current workspace folders: ["file:///c:/Users/edemaine/..."]
[14:40:19] Found root file from active editor: c:\Users\edemaine\...\main.tex
[14:40:19] Keep using the same root file: c:\Users\edemaine\...\main.tex
[14:40:54] Current workspace folders: ["file:///c:/Users/edemaine/..."]
[14:40:54] Found root file from active editor: c:\Users\edemaine\...\main.tex
[14:40:54] Keep using the same root file: c:\Users\edemaine\...\main.tex
[14:40:59] onDidSaveTextDocument triggered: file:///c:/Users/edemaine/.../main.tex
[14:40:59] File watcher - file changed: c:\Users\edemaine\...\main.tex
[14:40:59] Parsing a file and its subfiles: c:\Users\edemaine\...\main.tex
[14:40:59] Found .bib file: c:\Users\edemaine\...\main.bib
[14:41:00] Checking for duplicate labels: c:\Users\edemaine\...\main.tex.
[14:41:00] Auto build started detecting the change of a file: c:\Users\edemaine\...\main.tex
[14:41:00] BUILD command invoked.
[14:41:00] The document of the active editor: file:///c:/Users/edemaine/.../main.tex
[14:41:00] The languageId of the document: latex
[14:41:00] Building root file: c:\Users\edemaine\...\main.tex
[14:41:00] Build root file c:\Users\edemaine\...\main.tex
[14:41:00] outDir: c:/Users/edemaine/...
[14:41:00] Preparing to run recipe: latexmk 🔃
[14:41:00] Recipe step 1: bash
[14:41:00] Recipe step 1 args: ["-c","latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=\"`cygpath \"c:/Users/edemaine/...\"`\" \"`cygpath -u \"c:/Users/edemaine/.../main\"`\" | sed 's#/cygdrive/\\([a-zA-Z]\\)/#\\1:/#g' && (gunzip -kf main.synctex.gz && sed 's#/cygdrive/\\([a-zA-Z]\\)/#\\1:/#g' <main.synctex | gzip -c - >main.synctex.gz ; rm -f main.synctex)"]
[14:41:00] Recipe step env: {}
[14:41:00] Recipe step root file: c:\Users\edemaine\...\main.tex
[14:41:00] cwd: c:\Users\edemaine\...
[14:41:00] LaTeX build process spawned. PID: 18448.
[14:41:07] BibTeX log parsed with 0 messages.
[14:41:07] LaTeX log parsed with 15 messages.
[14:41:07] A step in recipe finished. PID: 18448.
[14:41:07] Successfully built c:\Users\edemaine\...\main.tex.
[14:41:07] Call refreshExistingViewer: {"sourceFile":"c:\\Users\\edemaine\\...\\main.tex"}
[14:41:07] Refresh PDF viewer: file:///c%3A/Users/edemaine/.../main.pdf
[14:41:07] Parse fls file.
[14:41:07] Fls file found: c:\Users\edemaine\...\main.fls
[14:41:07] Parse aux file: c:\Users\edemaine\...\main.aux
[14:41:07] Found .bib file: c:\Users\edemaine\...\main.bib
[14:41:07] Auto Clean invoked.
[14:41:07] Clean glob matched files: {"globs":["*.blg","*.out","*.acn","*.acr","*.alg","*.glg","*.glo","*.gls","*.fls","*.fdb_latexmk","*.snm","*.synctex(busy)","*.synctex.gz(busy)","*.nav"],"outdir":"c:\\Users\\edemaine\\..."}
[14:41:07] Ignore folder glob patterns with globstar: 
[14:41:07] Cleaning file: c:\Users\edemaine\...\main.out
[14:41:07] Cleaning file: c:\Users\edemaine\...\main.fls
[14:41:07] Cleaning file: c:\Users\edemaine\...\main.fdb_latexmk
[14:41:07] Cleaning file: c:\Users\edemaine\...\main.blg
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

PDF a70334172472ba836652263cfbaad98c [1.5 pdfTeX-1.40.24 / LaTeX with compgeomtop.cls] (PDF.js: 3.0.279 [d0823066c])
viewer.js:2237 PDF b7cc5733868adcba271f9b82c885aaf7 [1.5 pdfTeX-1.40.24 / LaTeX with compgeomtop.cls] (PDF.js: 3.0.279 [d0823066c])
latexworkshop.js:370 Closed: WebScocket to LaTeX Workshop.
latexworkshop.js:374 Try to reconnect to LaTeX Workshop.
connection.js:11 WebSocket connection to 'ws://127.0.0.1:56792/' failed: 
(anonymous) @ connection.js:11
2connection.js:15 Uncaught (in promise) Error: Failed to connect to ws://127.0.0.1:56792
    at WebSocket.<anonymous> (connection.js:15:57)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: getaddrinfo ENOTFOUND default.exp-tas.com
E @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
E @ console.ts:137
log.ts:316   ERR getaddrinfo ENOTFOUND default.exp-tas.com: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
9connection.js:15 Uncaught (in promise) Error: Failed to connect to ws://127.0.0.1:56792
    at WebSocket.<anonymous> (connection.js:15:57)
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/latexworkshop.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/build/pdf.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/connection.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/synctex.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/pagetrimmer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/externalpromise.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/utils.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/viewerhistory.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/viewer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/build/pdf.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
connection.js:30 Uncaught (in promise) Error: Failed to connect to ws://127.0.0.1:56792
    at WebSocket.<anonymous> (connection.js:15:57)
send @ connection.js:30
await in send (async)
(anonymous) @ connection.js:22
```

## Screenshots

n/a

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 11, build 22621
 - VS Code version: 1.74.2
 - Extension version: 9.1.1
 - TeX distribution version: TeX Live 2022/Cygwin

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by James-Yu** [comment]
It's possible. Suspending system may sometimes break existing network connections, on which the pdf features of the extension relies on. Unfortunately I don't think it is possible to persist the connection from the extension side.

**Comment by edemaine** [comment]
I thought #1813 attempted to reconnect the network connection in this case. And the logs show that this is attempted, but fails. Any idea why?

```
latexworkshop.js:370 Closed: WebScocket to LaTeX Workshop.
latexworkshop.js:374 Try to reconnect to LaTeX Workshop.
connection.js:11 WebSocket connection to 'ws://127.0.0.1:56792/' failed: 
(anonymous) @ connection.js:11
2connection.js:15 Uncaught (in promise) Error: Failed to connect to ws://127.0.0.1:56792
    at WebSocket.<anonymous> (connection.js:15:57)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: getaddrinfo ENOTFOUND default.exp-tas.com
E @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
E @ console.ts:137
log.ts:316   ERR getaddrinfo ENOTFOUND default.exp-tas.com: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
9connection.js:15 Uncaught (in promise) Error: Failed to connect to ws://127.0.0.1:56792
    at WebSocket.<anonymous> (connection.js:15:57)
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/latexworkshop.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/build/pdf.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/connection.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/synctex.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/pagetrimmer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/externalpromise.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/utils.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/out/viewer/components/viewerhistory.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/viewer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:56792/build/pdf.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
connection.js:30 Uncaught (in promise) Error: Failed to connect to ws://127.0.0.1:56792
    at WebSocket.<anonymous> (connection.js:15:57)
send @ connection.js:30
await in send (async)
(anonymous) @ connection.js:22
```
