### ISSUE TITLE
The `SyncTex from Cursor` option does not work anymore

### ISSUE THREAD

**Issue by basavyr** [James-Yu/LaTeX-Workshop#3637]
## Preliminary questions [Required]

You still see this issue?: Yes
You visited the wiki?: Yes
You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Starting with version `9.4.0` of the extension, the `SyncTex from Cursor` feature does not work anymore. 

### To Reproduce

1. Have both a `.tex` file and the generated `.pdf` file by the building process opened side-by-side. ![image](https://user-images.githubusercontent.com/18283620/211261424-a27a7d5b-5580-4a57-8d9a-5b384acca4d8.png)
2. Open the Command Pallet in VS Code (`cmd` + `shift` + `p` on macOS)
3. Click on `SyncTex from Cursor` ![image](https://user-images.githubusercontent.com/18283620/211261623-ab5ca5ae-e317-4e64-8920-ce5bdeceafdb.png)
4. Nothing happens...

### Expected behavior

The feature should navigate within the `.pdf` file at the specific location where the cursor was positioned in the `.tex` file

### LaTeX Workshop Output [Required]

This is the log generated when using the latest version of this extension

```
[04:52:53][Logger] New log placeholder %WS1% registered for /Users/basavyr/Desktop/pure .
[04:52:53][Config] Configuration for workspace: file://%WS1% .
[04:52:53][Config] editor.acceptSuggestionOnEnter: "on" .
[04:52:53][Config] latex-workshop.bind.enter.key: true .
[04:52:53][Config] latex-workshop.docker.enabled: false .
[04:52:53][Config] latex-workshop.docker.image.latex: "" .
[04:52:53][Config] latex-workshop.hover.preview.mathjax.extensions: [] .
[04:52:53][Config] latex-workshop.intellisense.package.enabled: true .
[04:52:53][Config] latex-workshop.intellisense.update.aggressive.enabled: false .
[04:52:53][Config] latex-workshop.intellisense.update.delay: 1000 .
[04:52:53][Config] latex-workshop.latex.autoBuild.run: "onFileChange" .
[04:52:53][Config] latex-workshop.latex.build.forceRecipeUsage: true .
[04:52:53][Config] latex-workshop.latex.outDir: "%DIR%" .
[04:52:53][Config] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto" .
[04:52:53][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[04:52:53][Server] Creating LaTeX Workshop http and websocket server.
[04:52:53][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":52585}
[04:52:53][Server] valdOrigin is http://127.0.0.1:52585
[04:52:53][Extension] Initializing LaTeX Workshop.
[04:52:53][Extension] Extension root: /Users/basavyr/.vscode/extensions/james-yu.latex-workshop-9.4.3
[04:52:53][Extension] $PATH: /Users/basavyr/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/basavyr/.pyenv/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
[04:52:53][Extension] $SHELL: /bin/zsh
[04:52:53][Extension] $LANG: undefined
[04:52:53][Extension] $LC_ALL: undefined
[04:52:53][Extension] process.platform: darwin
[04:52:53][Extension] process.arch: arm64
[04:52:53][Extension] vscode.env.appName: Visual Studio Code
[04:52:53][Extension] vscode.env.remoteName: undefined
[04:52:53][Extension] vscode.env.uiKind: 1
[04:52:53][Extension] LaTeX Workshop initialized.
[04:52:53][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[04:52:53][] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[04:52:53][Manager] Current workspace folders: ["file://%WS1%"]
[04:52:53][Manager] Found root file from active editor: %WS1%/example_file.tex
[04:52:53][Manager] Root file changed: from undefined to %WS1%/example_file.tex
[04:52:53][Manager] Start to find all dependencies.
[04:52:53][Manager] Root file languageId: latex
[04:52:53][Cacher][Watcher] Reset.
[04:52:53][Cacher] Adding %WS1%/example_file.tex .
[04:52:53][Cacher] Caching %WS1%/example_file.tex .
[04:52:53][Cacher] Updated inputs of %WS1%/example_file.tex .
[04:52:53][Cacher][Watcher] Watched %WS1%/example_file.tex .
[04:52:53][DupLabel] Checking for duplicate labels: %WS1%/example_file.tex .
[04:52:53][Cacher] Updated elements of %WS1%/example_file.tex .
[04:52:53][Cacher] Updated bibs of %WS1%/example_file.tex .
[04:52:53][Cacher] Cached %WS1%/example_file.tex .
[04:52:53][Cacher] Parsing .fls %WS1%/example_file.fls .
[04:52:53][Cacher] Found .aux %WS1%/example_file.tex from .fls %WS1%/example_file.fls , parsing.
[04:52:53][Cacher] Parsed .aux %WS1%/example_file.tex .
[04:52:53][Cacher] Parsed .fls %WS1%/example_file.fls .
[04:52:55][Commander] SHOWLOG command invoked: default
[04:53:12][Manager] Current workspace folders: ["file://%WS1%"]
[04:53:12][Manager] Found root file from active editor: %WS1%/example_file.tex
[04:53:12][Manager] Keep using the same root file: %WS1%/example_file.tex
[04:53:17][] onDidSaveTextDocument triggered: file://%WS1%/example_file.tex
[04:53:17][Cacher] Caching %WS1%/example_file.tex .
[04:53:17][Cacher] Updated inputs of %WS1%/example_file.tex .
[04:53:17][Builder] Auto build started detecting the change of a file: %WS1%/example_file.tex .
[04:53:17][Commander] BUILD command invoked.
[04:53:17][Commander] The document of the active editor: file://%WS1%/example_file.tex
[04:53:17][Commander] The languageId of the document: latex
[04:53:17][Commander] Building root file: %WS1%/example_file.tex
[04:53:17][Builder] Build root file %WS1%/example_file.tex
[04:53:17][Cacher][Watcher] Changed %WS1%/example_file.tex .
[04:53:17][DupLabel] Checking for duplicate labels: %WS1%/example_file.tex .
[04:53:17][Cacher] Updated elements of %WS1%/example_file.tex .
[04:53:17][Cacher] Updated bibs of %WS1%/example_file.tex .
[04:53:17][Cacher] Cached %WS1%/example_file.tex .
[04:53:17][Builder] outDir: %WS1% .
[04:53:17][Builder] Preparing to run recipe: latexmk.
[04:53:17][Builder] Recipe step 1 The command is latexmk:["-synctex=1","-interaction=nonstopmode","-file-line-error","-pdf","-outdir=%WS1%","%WS1%/example_file"].
[04:53:17][Builder] env: {}
[04:53:17][Builder] root: %WS1%/example_file.tex
[04:53:17][Builder] cwd: %WS1%
[04:53:17][Builder] LaTeX build process spawned with PID 53328.
[04:53:17][Builder] Finished a step in recipe with PID 53328.
[04:53:17][Builder] Successfully built %WS1%/example_file.tex .
[04:53:24][Commander] VIEW command invoked.
[04:53:24][Manager] Current workspace folders: ["file://%WS1%"]
[04:53:24][Manager] Found root file from active editor: %WS1%/example_file.tex
[04:53:24][Manager] Keep using the same root file: %WS1%/example_file.tex
[04:53:24][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:52585/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRlVzZXJzJTJGYmFzYXZ5ciUyRkRlc2t0b3AlMkZwdXJlJTJGZXhhbXBsZV9maWxlLnBkZg .
[04:53:24][Cacher][PDF] Watched file://%WS1%/example_file.pdf .
[04:53:24][Viewer] Open PDF tab for file://%WS1%/example_file.pdf
[04:53:24][Viewer] Handle data type: open
[04:53:24][Server] Preview PDF file: file://%WS1%/example_file.pdf
[04:53:24][Viewer] Handle data type: loaded
[04:53:25][Manager] Current workspace folders: ["file://%WS1%"]
[04:53:25][Manager] Found root file from active editor: %WS1%/example_file.tex
[04:53:25][Manager] Keep using the same root file: %WS1%/example_file.tex
[04:53:32][Commander] SYNCTEX command invoked.
[04:53:32][Locator] Forward from %WS1%/example_file.tex to %WS1%/example_file.pdf on line 3.
[04:53:32][SyncTeX] Failed parsing .synctex %WS1%/example_file.synctex , using .synctex.gz. Error: ENOENT: no such file or directory, open '%WS1%/example_file.synctex'
[04:53:32]Error: ENOENT: no such file or directory, open '%WS1%/example_file.synctex'
	at Object.openSync (node:fs:585:3)
	at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
	at Object.readFileSync (node:fs:453:35)
	at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
	at SyncTexJs.parseSyncTexForPdf (/Users/basavyr/.vscode/extensions/james-yu.latex-workshop-9.4.3/out/src/components/locatorlib/synctex.js:92:26)
	at SyncTexJs.syncTexJsForward (/Users/basavyr/.vscode/extensions/james-yu.latex-workshop-9.4.3/out/src/components/locatorlib/synctex.js:136:41)
	at Locator.syncTeX (/Users/basavyr/.vscode/extensions/james-yu.latex-workshop-9.4.3/out/src/components/locator.js:160:52)
	at Object.synctex (/Users/basavyr/.vscode/extensions/james-yu.latex-workshop-9.4.3/out/src/commander.js:183:16)
	at /Users/basavyr/.vscode/extensions/james-yu.latex-workshop-9.4.3/out/src/main.js:128:953
	at s.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:107622)
	at s.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:108311)
	at u.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:11208)
	at u.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10926)
	at u.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10019)
	at u.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:9000)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:7788
	at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at w.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at h.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:15804
	at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at w.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at h.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
	at c.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:17324)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:15795
	at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at w.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at g.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:12045)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:11332
	at Socket.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:19792)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[04:53:32][Viewer] Try to synctex %WS1%/example_file.pdf
```

## Desktop [Required]

 - OS: macOS Ventura `13.1 (22C65)`
 - VS Code version: November 2022 (version 1.74)
 - Extension version: `9.4.0`
 - TeX distribution version: Tex Live 2022

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

Building the tex project does generate the `synctex` file as usual:
![image](https://user-images.githubusercontent.com/18283620/211452854-a38d1df9-58d4-49f8-86df-f71545549320.png)

Reverting back to version `9.3.0` of the extension makes everything work as usual. See log below:
```
[04:55:18] Initializing LaTeX Workshop.
[04:55:18] Extension root: /Users/basavyr/.vscode/extensions/james-yu.latex-workshop-9.3.0
[04:55:18] $PATH: /Users/basavyr/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/basavyr/.pyenv/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
[04:55:18] $SHELL: /bin/zsh
[04:55:18] $LANG: undefined
[04:55:18] $LC_ALL: undefined
[04:55:18] process.platform: darwin
[04:55:18] process.arch: arm64
[04:55:18] vscode.env.appName: Visual Studio Code
[04:55:18] vscode.env.remoteName: undefined
[04:55:18] vscode.env.uiKind: 1
[04:55:18] Configuration for workspace: file:///Users/basavyr/Desktop/pure
[04:55:18] editor.acceptSuggestionOnEnter: "on"
[04:55:18] latex-workshop.bind.enter.key: true
[04:55:18] latex-workshop.docker.enabled: false
[04:55:18] latex-workshop.docker.image.latex: ""
[04:55:18] latex-workshop.hover.preview.mathjax.extensions: []
[04:55:18] latex-workshop.intellisense.package.enabled: true
[04:55:18] latex-workshop.intellisense.update.aggressive.enabled: false
[04:55:18] latex-workshop.intellisense.update.delay: 1000
[04:55:18] latex-workshop.latex.autoBuild.run: "onFileChange"
[04:55:18] latex-workshop.latex.build.forceRecipeUsage: true
[04:55:18] latex-workshop.latex.outDir: "%DIR%"
[04:55:18] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto"
[04:55:18] Creating a new file watcher.
[04:55:18] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[04:55:18] Creating PDF file watcher.
[04:55:18] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[04:55:18] Creating Bib file watcher.
[04:55:18] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[04:55:18] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[04:55:18] [Server] Creating LaTeX Workshop http and websocket server.
[04:55:18] LaTeX Workshop initialized.
[04:55:18] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[04:55:18] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[04:55:18] Current workspace folders: ["file:///Users/basavyr/Desktop/pure"]
[04:55:18] Found root file from active editor: /Users/basavyr/Desktop/pure/example_file.tex
[04:55:18] Root file changed: from undefined to /Users/basavyr/Desktop/pure/example_file.tex
[04:55:18] Start to find all dependencies.
[04:55:18] Root file languageId: latex
[04:55:18] Reset file watcher.
[04:55:18] Parsing a file and its subfiles: /Users/basavyr/Desktop/pure/example_file.tex
[04:55:18] Parse fls file.
[04:55:18] Fls file found: /Users/basavyr/Desktop/pure/example_file.fls
[04:55:18] Parse aux file: /Users/basavyr/Desktop/pure/example_file.aux
[04:55:18] [Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":52688}
[04:55:18] Added to file watcher: /Users/basavyr/Desktop/pure/example_file.tex
[04:55:18] Snippet data loaded.
[04:55:18] [Server] valdOrigin is http://127.0.0.1:52688
[04:55:18] Restoring the PDF viewer at the column 1 from the state: {"type":"state","state":{"pdfFileUri":"file:///Users/basavyr/Desktop/pure/example_file.pdf","scale":"auto","scrollMode":0,"spreadMode":0,"scrollTop":71,"scrollLeft":0,"trim":0,"synctexEnabled":true,"autoReloadEnabled":true}}
[04:55:18] The internal PDF viewer url: http://127.0.0.1:52688/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRlVzZXJzJTJGYmFzYXZ5ciUyRkRlc2t0b3AlMkZwdXJlJTJGZXhhbXBsZV9maWxlLnBkZg
[04:55:18] Added to PDF file watcher: file:///Users/basavyr/Desktop/pure/example_file.pdf
[04:55:18] Checking for duplicate labels: /Users/basavyr/Desktop/pure/example_file.tex.
[04:55:19] Handle data type: open
[04:55:19] Preview PDF file: file:///Users/basavyr/Desktop/pure/example_file.pdf
[04:55:19] Handle data type: loaded
[04:55:20] Manager.fileWatcher.getWatched: {"/Users/basavyr/Desktop/pure":["example_file.tex"]}
[04:55:20] Manager.filesWatched: ["/Users/basavyr/Desktop/pure/example_file.tex"]
[04:55:20] BibWatcher.bibWatcher.getWatched: {}
[04:55:20] BibWatcher.bibsWatched: []
[04:55:20] PdfWatcher.pdfWatcher.getWatched: {"/Users/basavyr/Desktop/pure":["example_file.pdf"]}
[04:55:20] PdfWatcher.pdfsWatched: ["/Users/basavyr/Desktop/pure/example_file.pdf"]
[04:55:20] PdfWatcher.watchedPdfVirtualUris: []
[04:55:20] PdfWatcher.ignoredPdfUris: []
[04:55:22] onDidSaveTextDocument triggered: file:///Users/basavyr/Desktop/pure/example_file.tex
[04:55:22] File watcher - file changed: /Users/basavyr/Desktop/pure/example_file.tex
[04:55:22] Parsing a file and its subfiles: /Users/basavyr/Desktop/pure/example_file.tex
[04:55:22] Checking for duplicate labels: /Users/basavyr/Desktop/pure/example_file.tex.
[04:55:22] Auto build started detecting the change of a file: /Users/basavyr/Desktop/pure/example_file.tex
[04:55:22] BUILD command invoked.
[04:55:22] The document of the active editor: file:///Users/basavyr/Desktop/pure/example_file.tex
[04:55:22] The languageId of the document: latex
[04:55:22] Building root file: /Users/basavyr/Desktop/pure/example_file.tex
[04:55:22] Build root file /Users/basavyr/Desktop/pure/example_file.tex
[04:55:22] outDir: /Users/basavyr/Desktop/pure
[04:55:22] Preparing to run recipe: latexmk
[04:55:22] Recipe step 1: latexmk
[04:55:22] Recipe step 1 args: ["-synctex=1","-interaction=nonstopmode","-file-line-error","-pdf","-outdir=/Users/basavyr/Desktop/pure","/Users/basavyr/Desktop/pure/example_file"]
[04:55:22] Recipe step env: {}
[04:55:22] Recipe step root file: /Users/basavyr/Desktop/pure/example_file.tex
[04:55:22] cwd: /Users/basavyr/Desktop/pure
[04:55:22] LaTeX build process spawned. PID: 53419.
[04:55:22] A step in recipe finished. PID: 53419.
[04:55:22] Successfully built /Users/basavyr/Desktop/pure/example_file.tex.
[04:55:25] SYNCTEX command invoked.
[04:55:25] [SyncTexJs] Execute syncTexJsForward: {"pdfFile":"/Users/basavyr/Desktop/pure/example_file.pdf","filePath":"/Users/basavyr/Desktop/pure/example_file.tex","line":3}
[04:55:25] Try to synctex /Users/basavyr/Desktop/pure/example_file.pdf
```

The *key difference* that I notice in the newest version is the `'%WS1%` prefix, which is present in the workspace path. Moreover, if you try to clean the auxiliary files, everything gets deleted **except** for the `synctex.gz` file.

**Comment by James-Yu** [comment]
#3631 If not released in latest, I will do so shortly.
