### ISSUE TITLE
PDF viewer doesn't work

### ISSUE THREAD

**Issue by nidrissi** [James-Yu/LaTeX-Workshop#3664]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

The PDF viewer does not work. The internal webview is empty. Opening the URL of the viewer in an external browser produces a `ERR_CONNECTION_REFUSED` error.

### To Reproduce

1. Compile any document.
2. Click on "View PDF".
3. The webview is empty.

### Expected behavior

I should be able to see the PDF.

### LaTeX Workshop Output [Required]

```
[09:37:45][Logger] New log placeholder %WS1% registered for /home/najib/tmp .
[09:37:45][Config] Configuration for workspace: file://%WS1% .
[09:37:45][Config] editor.acceptSuggestionOnEnter: "on" .
[09:37:45][Config] latex-workshop.bind.enter.key: false .
[09:37:45][Config] latex-workshop.docker.enabled: false .
[09:37:45][Config] latex-workshop.docker.image.latex: "" .
[09:37:45][Config] latex-workshop.hover.preview.mathjax.extensions: [] .
[09:37:45][Config] latex-workshop.intellisense.package.enabled: true .
[09:37:45][Config] latex-workshop.intellisense.update.aggressive.enabled: false .
[09:37:45][Config] latex-workshop.intellisense.update.delay: 1000 .
[09:37:45][Config] latex-workshop.latex.autoBuild.run: "never" .
[09:37:45][Config] latex-workshop.latex.build.forceRecipeUsage: true .
[09:37:45][Config] latex-workshop.latex.outDir: "%DIR%" .
[09:37:45][Config] latex-workshop.latex.recipes: [
 {
  "name": "latexmk",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmk (latexmkrc)",
  "tools": [
   "latexmk_rconly"
  ]
 },
 {
  "name": "latexmk (lualatex)",
  "tools": [
   "lualatexmk"
  ]
 },
 {
  "name": "latexmk (xelatex)",
  "tools": [
   "xelatexmk"
  ]
 },
 {
  "name": "pdflatex -> bibtex -> pdflatex * 2",
  "tools": [
   "pdflatex",
   "bibtex",
   "pdflatex",
   "pdflatex"
  ]
 },
 {
  "name": "Compile Rnw files",
  "tools": [
   "rnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Jnw files",
  "tools": [
   "jnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Pnw files",
  "tools": [
   "pnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "tectonic",
  "tools": [
   "tectonic"
  ]
 }
] .
[09:37:45][Config] latex-workshop.latex.tools: [
 {
  "name": "latexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-pdf",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "lualatexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-lualatex",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 }
] .
[09:37:45][Config] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto" .
[09:37:45][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[09:37:46][Server] Creating LaTeX Workshop http and websocket server.
[09:37:47][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":42847}
[09:37:47][Extension] Initializing LaTeX Workshop.
[09:37:47][Extension] Extension root: /home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0
[09:37:47][Extension] $PATH: /home/najib/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/bin/remote-cli:/home/najib/.config/nvm/versions/node/v19.4.0/bin:/home/najib/.texlive2022/bin/x86_64-linux:/home/najib/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/home/najib/.local/bin:/usr/local/bin:/usr/bin:/bin:/home/najib/.dotnet/tools
[09:37:47][Extension] $SHELL: /bin/zsh
[09:37:47][Extension] $LANG: en_US.UTF-8
[09:37:47][Extension] $LC_ALL: undefined
[09:37:47][Extension] process.platform: linux
[09:37:47][Extension] process.arch: x64
[09:37:47][Extension] vscode.env.appName: Visual Studio Code
[09:37:47][Extension] vscode.env.remoteName: wsl
[09:37:47][Extension] vscode.env.uiKind: 1
[09:37:47][Extension] LaTeX Workshop initialized.
[09:37:47][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":true,"sort":["key"],"alignOnEqual":true,"sortFields":true,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[09:37:47][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[09:37:47][Manager] Current workspace folders: ["file://%WS1%"]
[09:37:47][Manager] Found root file from active editor: %WS1%/main.tex
[09:37:47][Manager] Root file changed: from undefined to %WS1%/main.tex
[09:37:47][Manager] Start to find all dependencies.
[09:37:47][Manager] Root file languageId: latex
[09:37:47][Cacher][Watcher] Reset.
[09:37:47][Cacher] Adding %WS1%/main.tex .
[09:37:47][Cacher] Caching %WS1%/main.tex .
[09:37:47][Cacher] Updated inputs of %WS1%/main.tex .
[09:37:47][Server] valdOrigin is http://127.0.0.1:42847
[09:37:47][Cacher][Watcher] Watched %WS1%/main.tex .
[09:37:47][DupLabel] Checking for duplicate labels: %WS1%/main.tex .
[09:37:47][Cacher] Updated elements of %WS1%/main.tex .
[09:37:47][Cacher] Updated bibs of %WS1%/main.tex .
[09:37:47][Cacher] Cached %WS1%/main.tex .
[09:37:47][Cacher] Parsing .fls %WS1%/main.fls .
[09:37:47][Cacher] Adding /home/najib/.texlive2022/texmf.cnf .
[09:37:47][Cacher] Adding /home/najib/.texlive2022/texmf-dist/web2c/texmf.cnf .
[09:37:47][Cacher] Adding /home/najib/.texlive2022/texmf-var/web2c/pdftex/pdflatex.fmt .
[09:37:47][Cacher] Adding /home/najib/.texlive2022/texmf-dist/tex/latex/base/article.cls .
[09:37:47][Cacher] Adding /home/najib/.texlive2022/texmf-dist/tex/latex/base/size10.clo .
[09:37:47][Cacher] Adding /home/najib/.texlive2022/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def .
[09:37:47][Cacher] Adding /home/najib/.texlive2022/texmf-var/fonts/map/pdftex/updmap/pdftex.map .
[09:37:47][Cacher] Adding /home/najib/.texlive2022/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb .
[09:37:47][Cacher] Found .aux %WS1%/main.tex from .fls %WS1%/main.fls , parsing.
[09:37:47][Cacher] Parsed .aux %WS1%/main.tex .
[09:37:47][Cacher] Parsed .fls %WS1%/main.fls .
[09:37:47][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf.cnf .
[09:37:47][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-var/web2c/pdftex/pdflatex.fmt .
[09:37:47][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-dist/web2c/texmf.cnf .
[09:37:47][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-dist/tex/latex/base/article.cls .
[09:37:47][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-dist/tex/latex/base/size10.clo .
[09:37:47][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def .
[09:37:47][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-var/fonts/map/pdftex/updmap/pdftex.map .
[09:37:47][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb .
```

### Developer Tools Console [Required]

```
 INFO [attempt 1] Invoking resolveAuthority(wsl)
log.ts:304  INFO [attempt 1] resolveAuthority(wsl) returned '127.0.0.1:54454' after 558 ms
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///c%3A/Users/najib/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bopensuse-tumbleweed/home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///c%3A/Users/najib/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bopensuse-tumbleweed/home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///c%3A/Users/najib/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bopensuse-tumbleweed/home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/Bibtex.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///c%3A/Users/najib/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bopensuse-tumbleweed/home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/markdown-latex-combined.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///c%3A/Users/najib/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bopensuse-tumbleweed/home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/cpp-grammar-bailout.tmLanguage.json
register @ TMScopeRegistry.ts:47
log.ts:316   ERR Cannot read properties of undefined (reading 'state'): TypeError: Cannot read properties of undefined (reading 'state')
	at PdfViewerPanelSerializer.deserializeWebviewPanel (/home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/out/src/components/viewerlib/pdfviewerpanel.js:61:98)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c.$deserializeWebviewPanel (/home/najib/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:96:172352)
log.ts:304  INFO [perf] Render performance baseline is 33ms
```

## Screenshots

![image](https://user-images.githubusercontent.com/16067652/214246208-b63e41af-ef4c-4c6f-8b3e-7287ecd47e48.png)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 11
 - VS Code version: 1.74.3
 - Extension version: 9.5.0
 - TeX distribution version: texlive 2022

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

Yes

- Remote WSL
- Remote Extension Version: 0.72.0

**Comment by James-Yu** [comment]
You can close all editor, restart vscode, and work as usual.

**Comment by nidrissi** [comment]
@James-Yu I had already tried that several times. Would you like me to capture a video of my desktop closing and reopening vscode several times to prove it?

**Comment by James-Yu** [comment]
You do not have a log message says `VIEW command invoked`. Debugging is not possible without it.

**Comment by nidrissi** [comment]
Okay, there you go.

```
[10:21:43][Logger] New log placeholder %WS1% registered for /home/najib/tmp .
[10:21:43][Config] Configuration for workspace: file://%WS1% .
[10:21:43][Config] editor.acceptSuggestionOnEnter: "on" .
[10:21:43][Config] latex-workshop.bind.enter.key: false .
[10:21:43][Config] latex-workshop.docker.enabled: false .
[10:21:43][Config] latex-workshop.docker.image.latex: "" .
[10:21:43][Config] latex-workshop.hover.preview.mathjax.extensions: [] .
[10:21:43][Config] latex-workshop.intellisense.package.enabled: true .
[10:21:43][Config] latex-workshop.intellisense.update.aggressive.enabled: false .
[10:21:43][Config] latex-workshop.intellisense.update.delay: 1000 .
[10:21:43][Config] latex-workshop.latex.autoBuild.run: "never" .
[10:21:43][Config] latex-workshop.latex.build.forceRecipeUsage: true .
[10:21:43][Config] latex-workshop.latex.outDir: "%DIR%" .
[10:21:43][Config] latex-workshop.latex.recipes: [
 {
  "name": "latexmk",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmk (latexmkrc)",
  "tools": [
   "latexmk_rconly"
  ]
 },
 {
  "name": "latexmk (lualatex)",
  "tools": [
   "lualatexmk"
  ]
 },
 {
  "name": "latexmk (xelatex)",
  "tools": [
   "xelatexmk"
  ]
 },
 {
  "name": "pdflatex -> bibtex -> pdflatex * 2",
  "tools": [
   "pdflatex",
   "bibtex",
   "pdflatex",
   "pdflatex"
  ]
 },
 {
  "name": "Compile Rnw files",
  "tools": [
   "rnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Jnw files",
  "tools": [
   "jnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Pnw files",
  "tools": [
   "pnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "tectonic",
  "tools": [
   "tectonic"
  ]
 }
] .
[10:21:43][Config] latex-workshop.latex.tools: [
 {
  "name": "latexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-pdf",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "lualatexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-lualatex",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 }
] .
[10:21:43][Config] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto" .
[10:21:43][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[10:21:44][Server] Creating LaTeX Workshop http and websocket server.
[10:21:45][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":32787}
[10:21:45][Server] valdOrigin is http://127.0.0.1:32787
[10:21:45][Extension] Initializing LaTeX Workshop.
[10:21:45][Extension] Extension root: /home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0
[10:21:45][Extension] $PATH: /home/najib/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/bin/remote-cli:/home/najib/.texlive2022/bin/x86_64-linux:/home/najib/.local/bin:/home/najib/.config/nvm/versions/node/v19.4.0/bin:/home/najib/.texlive2022/bin/x86_64-linux:/home/najib/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/home/najib/.local/bin:/usr/local/bin:/usr/bin:/bin:/home/najib/.dotnet/tools
[10:21:45][Extension] $SHELL: /bin/zsh
[10:21:45][Extension] $LANG: en_US.UTF-8
[10:21:45][Extension] $LC_ALL: undefined
[10:21:45][Extension] process.platform: linux
[10:21:45][Extension] process.arch: x64
[10:21:45][Extension] vscode.env.appName: Visual Studio Code
[10:21:45][Extension] vscode.env.remoteName: wsl
[10:21:45][Extension] vscode.env.uiKind: 1
[10:21:45][Extension] LaTeX Workshop initialized.
[10:21:45][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":true,"sort":["key"],"alignOnEqual":true,"sortFields":true,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[10:21:45][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[10:21:45][Manager] Current workspace folders: ["file://%WS1%"]
[10:21:45][Manager] Found root file from active editor: %WS1%/main.tex
[10:21:45][Manager] Root file changed: from undefined to %WS1%/main.tex
[10:21:45][Manager] Start to find all dependencies.
[10:21:45][Manager] Root file languageId: latex
[10:21:45][Cacher][Watcher] Reset.
[10:21:45][Cacher] Adding %WS1%/main.tex .
[10:21:45][Cacher] Caching %WS1%/main.tex .
[10:21:45][Cacher] Updated inputs of %WS1%/main.tex .
[10:21:45][Cacher][Watcher] Watched %WS1%/main.tex .
[10:21:45][DupLabel] Checking for duplicate labels: %WS1%/main.tex .
[10:21:45][Cacher] Updated elements of %WS1%/main.tex .
[10:21:45][Cacher] Updated bibs of %WS1%/main.tex .
[10:21:45][Cacher] Cached %WS1%/main.tex .
[10:21:45][Cacher] Parsing .fls %WS1%/main.fls .
[10:21:45][Cacher] Adding /home/najib/.texlive2022/texmf.cnf .
[10:21:45][Cacher] Adding /home/najib/.texlive2022/texmf-dist/web2c/texmf.cnf .
[10:21:45][Cacher] Adding /home/najib/.texlive2022/texmf-var/web2c/pdftex/pdflatex.fmt .
[10:21:45][Cacher] Adding /home/najib/.texlive2022/texmf-dist/tex/latex/base/article.cls .
[10:21:45][Cacher] Adding /home/najib/.texlive2022/texmf-dist/tex/latex/base/size10.clo .
[10:21:45][Cacher] Adding /home/najib/.texlive2022/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def .
[10:21:45][Cacher] Adding /home/najib/.texlive2022/texmf-var/fonts/map/pdftex/updmap/pdftex.map .
[10:21:45][Cacher] Adding /home/najib/.texlive2022/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb .
[10:21:45][Cacher] Found .aux %WS1%/main.tex from .fls %WS1%/main.fls , parsing.
[10:21:45][Cacher] Parsed .aux %WS1%/main.tex .
[10:21:45][Cacher] Parsed .fls %WS1%/main.fls .
[10:21:46][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf.cnf .
[10:21:46][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-dist/web2c/texmf.cnf .
[10:21:46][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-var/web2c/pdftex/pdflatex.fmt .
[10:21:46][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-dist/tex/latex/base/article.cls .
[10:21:46][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-dist/tex/latex/base/size10.clo .
[10:21:46][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def .
[10:21:46][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-var/fonts/map/pdftex/updmap/pdftex.map .
[10:21:46][Cacher][Watcher] Watched /home/najib/.texlive2022/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb .
[10:21:49][Commander] VIEW command invoked with mode: file://%WS1%/main.tex.
[10:21:49][Manager] Current workspace folders: ["file://%WS1%"]
[10:21:49][Manager] Found root file from active editor: %WS1%/main.tex
[10:21:49][Manager] Keep using the same root file: %WS1%/main.tex
[10:21:50][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:32787/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRmhvbWUlMkZuYWppYiUyRnRtcCUyRm1haW4ucGRm .
[10:21:50][Cacher][PDF] Watched file://%WS1%/main.pdf .
[10:21:50][Viewer] Open PDF tab for file://%WS1%/main.pdf
```

![image](https://user-images.githubusercontent.com/16067652/214254538-1f5a1b33-8894-4e86-9969-ab2b27a9b7ad.png)

**Comment by James-Yu** [comment]
What's in developer tools console?

**Comment by nidrissi** [comment]
```
workbench.desktop.main.js:sourcemap:616  INFO [attempt 1] Invoking resolveAuthority(wsl)
workbench.desktop.main.js:sourcemap:616  INFO [attempt 1] resolveAuthority(wsl) returned '127.0.0.1:52501' after 377 ms
workbench.desktop.main.js:sourcemap:616  WARN [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
workbench.desktop.main.js:sourcemap:2053 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///c%3A/Users/najib/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bopensuse-tumbleweed/home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/TeX.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:2053
workbench.desktop.main.js:sourcemap:2053 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///c%3A/Users/najib/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bopensuse-tumbleweed/home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/LaTeX.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:2053
workbench.desktop.main.js:sourcemap:2053 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///c%3A/Users/najib/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bopensuse-tumbleweed/home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/Bibtex.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:2053
workbench.desktop.main.js:sourcemap:2053 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///c%3A/Users/najib/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bopensuse-tumbleweed/home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/markdown-latex-combined.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:2053
workbench.desktop.main.js:sourcemap:2053 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///c%3A/Users/najib/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bopensuse-tumbleweed/home/najib/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/cpp-grammar-bailout.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:2053
workbench.desktop.main.js:sourcemap:616  INFO [perf] Render performance baseline is 57ms
```

**Comment by James-Yu** [comment]
No. That is not "same as before". The only error message disappeared, which is caused by not closing and reopening the tab.

I will try reproduce the issue on my side.

**Comment by nidrissi** [comment]
That's true, the previous log had been obtained after reloading vscode several times.

Here's the latex document if you want to reproduce:

```
\documentclass{article}
\begin{document}
Hello.
\end{document}
```

**Comment by nidrissi** [comment]
My local network is ok. I can run an http server (e.g. using python's `http.server` or node's `serve`) in WSL and access it from Windows just fine. I can see (with `ss -tlnp`) that something is listening on the port, and if I use e.g. curl from inside WSL with the given address, I get the viewer. What kind of server/mechanism does the extension use to listen on the port?

**Comment by nidrissi** [comment]
@James-Yu Okay, I found the issue is. The extension's server listen on `127.0.0.1:PORT` only. It should listen on any address (`*:PORT`) for the port forwarding to work reliably.
