### ISSUE TITLE
PDF viewer suddenly stops working.

### ISSUE THREAD

**Issue by zhxchd** [James-Yu/LaTeX-Workshop#3668]
## Preliminary questions [Required]
PDF rendering stops working while other external PDF viewers can still read the file. 

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

My issue is not with compiling a document.

## Describe the bug [Required]

When opening a PDF file in VS code (not necessarily a PDF file compiled from LaTeX, just any PDF file as I've set the default PDF viewer to be LaTeX-Workshop), a new tab opens but it is blank. Sometimes it says "An error occurred while loading view: latex-workshop-pdf" on the top of the tab. But sometimes it does not.

This happens overnight, everything was fine yesterday and suddenly it does not work today. I've tried setting the watch delay but there's no luck. I've tried deleting the extension (from `~/.vscode-server/extensions`) and re-install it and the issue is still there. I've also tried rebooting both Windows and WSL.

### To Reproduce

1. Open a PDF file in VS code while LaTeX-Workshop is set to be the default PDF viewer.
2. PDF tab opens but it is blank.

### Expected behavior

The PDF should have been displayed.

### LaTeX Workshop Output [Required]

```
[14:19:55][Logger] New log placeholder %WS1% registered for ************ [REDACTED]
[14:19:55][Config] Configuration for workspace: file://%WS1% .
[14:19:55][Config] editor.acceptSuggestionOnEnter: "off" .
[14:19:55][Config] latex-workshop.bind.enter.key: true .
[14:19:55][Config] latex-workshop.docker.enabled: false .
[14:19:55][Config] latex-workshop.docker.image.latex: "" .
[14:19:55][Config] latex-workshop.hover.preview.mathjax.extensions: [] .
[14:19:55][Config] latex-workshop.intellisense.package.enabled: true .
[14:19:55][Config] latex-workshop.intellisense.update.aggressive.enabled: false .
[14:19:55][Config] latex-workshop.intellisense.update.delay: 1000 .
[14:19:55][Config] latex-workshop.latex.autoBuild.run: "onFileChange" .
[14:19:55][Config] latex-workshop.latex.build.forceRecipeUsage: false .
[14:19:55][Config] latex-workshop.latex.outDir: "%DIR%" .
[14:19:55][Config] latex-workshop.latex.recipes: [
 {
  "name": "latexmk",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmk (latexmkrc)",
  "tools": [
   "latexmk_rconly"
  ]
 },
 {
  "name": "latexmk (lualatex)",
  "tools": [
   "lualatexmk"
  ]
 },
 {
  "name": "latexmk (xelatex)",
  "tools": [
   "xelatexmk"
  ]
 },
 {
  "name": "pdflatex -> bibtex -> pdflatex * 2",
  "tools": [
   "pdflatex",
   "bibtex",
   "pdflatex",
   "pdflatex"
  ]
 },
 {
  "name": "Compile Rnw files",
  "tools": [
   "rnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Jnw files",
  "tools": [
   "jnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Pnw files",
  "tools": [
   "pnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "tectonic",
  "tools": [
   "tectonic"
  ]
 }
] .
[14:19:55][Config] latex-workshop.latex.tools: [
 {
  "name": "latexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-pdf",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "lualatexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-lualatex",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "xelatexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-xelatex",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "latexmk_rconly",
  "command": "latexmk",
  "args": [
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "pdflatex",
  "command": "pdflatex",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "bibtex",
  "command": "bibtex",
  "args": [
   "%DOCFILE%"
  ],
  "env": {}
 },
 {
  "name": "rnw2tex",
  "command": "Rscript",
  "args": [
   "-e",
   "knitr::opts_knit$set(concordance = TRUE); knitr::knit('%DOCFILE_EXT%')"
  ],
  "env": {}
 },
 {
  "name": "jnw2tex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"tex\")"
  ],
  "env": {}
 },
 {
  "name": "jnw2texminted",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"texminted\")"
  ],
  "env": {}
 },
 {
  "name": "pnw2tex",
  "command": "pweave",
  "args": [
   "-f",
   "tex",
   "%DOC_EXT%"
  ],
  "env": {}
 },
 {
  "name": "pnw2texminted",
  "command": "pweave",
  "args": [
   "-f",
   "texminted",
   "%DOC_EXT%"
  ],
  "env": {}
 },
 {
  "name": "tectonic",
  "command": "tectonic",
  "args": [
   "--synctex",
   "--keep-logs",
   "%DOC%.tex"
  ],
  "env": {}
 }
] .
[14:19:55][Config] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto" .
[14:19:55][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[14:19:55][Server] Creating LaTeX Workshop http and websocket server.
[14:19:55][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":32961}
[14:19:55][Extension] Initializing LaTeX Workshop.
[14:19:55][Extension] Extension root: /home/xczhu/.vscode-server/extensions/james-yu.latex-workshop-9.5.0
[14:19:55][Extension] $PATH: /home/xczhu/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/bin/remote-cli:/usr/local/texlive/2022/bin/x86_64-linux:/home/xczhu/.local/bin:/home/xczhu/perl5/bin:/home/xczhu/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/bin:/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/libnvvp:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Git/cmd:/mnt/c/Strawberry/c/bin:/mnt/c/Strawberry/perl/site/bin:/mnt/c/Strawberry/perl/bin:/mnt/c/Program Files/NVIDIA Corporation/Nsight Compute 2020.3.1/:/mnt/c/Program Files/MATLAB/R2022a/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Users/zhuxi/AppData/Local/Programs/Python/Python310/Scripts/:/mnt/c/Users/zhuxi/AppData/Local/Programs/Python/Python310/:/mnt/c/Users/zhuxi/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/zhuxi/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/zhuxi/AppData/Local/Programs/MiKTeX/miktex/bin/x64/:/mnt/c/Users/zhuxi/AppData/Local/JetBrains/Toolbox/scripts:/snap/bin:/home/xczhu/hadoop-3.3.0/bin
[14:19:55][Extension] $SHELL: /usr/bin/bash
[14:19:55][Extension] $LANG: C.UTF-8
[14:19:55][Extension] $LC_ALL: undefined
[14:19:55][Extension] process.platform: linux
[14:19:55][Extension] process.arch: x64
[14:19:55][Extension] vscode.env.appName: Visual Studio Code
[14:19:55][Extension] vscode.env.remoteName: wsl
[14:19:55][Extension] vscode.env.uiKind: 1
[14:19:55][Extension] LaTeX Workshop initialized.
[14:19:55][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[14:19:55][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[14:19:55][Manager] Current workspace folders: ["file://%WS1%"]
[14:19:55][Manager] Current workspaceRootDir: file://%WS1%
[14:19:55][Server] valdOrigin is http://127.0.0.1:32961
[14:19:55][Cacher][Path] Non-existent .fls for %WS1%/main.tex .
[14:19:55][Cacher] Caching %WS1%/main.tex .
[14:19:55][Cacher] Input %WS1%/src/00-abstract.tex from %WS1%/main.tex .
[14:19:55][Cacher] Adding %WS1%/src/00-abstract.tex .
[14:19:55][Cacher] Caching %WS1%/src/00-abstract.tex .
[14:19:55][Cacher] Updated inputs of %WS1%/src/00-abstract.tex .
[14:19:55][Cacher] Input %WS1%/src/01-intro.tex from %WS1%/main.tex .
[14:19:55][Cacher] Adding %WS1%/src/01-intro.tex .
[14:19:55][Cacher] Caching %WS1%/src/01-intro.tex .
[14:19:55][Cacher] Updated inputs of %WS1%/src/01-intro.tex .
[14:19:55][Cacher] Input %WS1%/src/02-preliminaries.tex from %WS1%/main.tex .
[14:19:55][Cacher] Adding %WS1%/src/02-preliminaries.tex .
[14:19:55][Cacher] Caching %WS1%/src/02-preliminaries.tex .
[14:19:55][Cacher] Updated inputs of %WS1%/src/02-preliminaries.tex .
[14:19:55][Cacher] Input %WS1%/src/03-statement.tex from %WS1%/main.tex .
[14:19:55][Cacher] Adding %WS1%/src/03-statement.tex .
[14:19:55][Cacher] Caching %WS1%/src/03-statement.tex .
[14:19:55][Cacher] Updated inputs of %WS1%/src/03-statement.tex .
[14:19:55][Cacher] Input %WS1%/src/04-approach.tex from %WS1%/main.tex .
[14:19:55][Cacher] Adding %WS1%/src/04-approach.tex .
[14:19:55][Cacher] Caching %WS1%/src/04-approach.tex .
[14:19:55][Cacher] Updated inputs of %WS1%/src/04-approach.tex .
[14:19:55][Cacher] Input %WS1%/src/05-experiments.tex from %WS1%/main.tex .
[14:19:55][Cacher] Adding %WS1%/src/05-experiments.tex .
[14:19:55][Cacher] Caching %WS1%/src/05-experiments.tex .
[14:19:55][Cacher] Updated inputs of %WS1%/src/05-experiments.tex .
[14:19:55][Cacher] Input %WS1%/src/06-related.tex from %WS1%/main.tex .
[14:19:55][Cacher] Adding %WS1%/src/06-related.tex .
[14:19:55][Cacher] Caching %WS1%/src/06-related.tex .
[14:19:55][Cacher] Updated inputs of %WS1%/src/06-related.tex .
[14:19:55][Cacher] Input %WS1%/src/07-conclusion.tex from %WS1%/main.tex .
[14:19:55][Cacher] Adding %WS1%/src/07-conclusion.tex .
[14:19:55][Cacher] Caching %WS1%/src/07-conclusion.tex .
[14:19:55][Cacher] Updated inputs of %WS1%/src/07-conclusion.tex .
[14:19:55][Cacher] Updated inputs of %WS1%/main.tex .
[14:19:55][Cacher][Watcher] Watched %WS1%/src/00-abstract.tex .
[14:19:55][Cacher][Watcher] Watched %WS1%/src/01-intro.tex .
[14:19:55][Cacher][Watcher] Watched %WS1%/src/02-preliminaries.tex .
[14:19:55][Cacher][Watcher] Watched %WS1%/src/03-statement.tex .
[14:19:55][Cacher][Watcher] Watched %WS1%/src/04-approach.tex .
[14:19:55][Cacher][Watcher] Watched %WS1%/src/05-experiments.tex .
[14:19:55][Cacher][Watcher] Watched %WS1%/src/06-related.tex .
[14:19:55][Cacher][Watcher] Watched %WS1%/src/07-conclusion.tex .
[14:19:55][DupLabel] Checking for duplicate labels: %WS1%/src/00-abstract.tex .
[14:19:55][Cacher] Updated elements of %WS1%/src/00-abstract.tex .
[14:19:55][Cacher] Updated bibs of %WS1%/src/00-abstract.tex .
[14:19:55][Cacher] Cached %WS1%/src/00-abstract.tex .
[14:19:55][DupLabel] Checking for duplicate labels: %WS1%/src/01-intro.tex .
[14:19:55][Cacher] Updated elements of %WS1%/src/01-intro.tex .
[14:19:55][Cacher] Updated bibs of %WS1%/src/01-intro.tex .
[14:19:55][Cacher] Cached %WS1%/src/01-intro.tex .
[14:19:55][DupLabel] Checking for duplicate labels: %WS1%/src/02-preliminaries.tex .
[14:19:55][Cacher] Updated elements of %WS1%/src/02-preliminaries.tex .
[14:19:55][Cacher] Updated bibs of %WS1%/src/02-preliminaries.tex .
[14:19:55][Cacher] Cached %WS1%/src/02-preliminaries.tex .
[14:19:55][DupLabel] Checking for duplicate labels: %WS1%/src/03-statement.tex .
[14:19:55][Cacher] Updated elements of %WS1%/src/03-statement.tex .
[14:19:55][Cacher] Updated bibs of %WS1%/src/03-statement.tex .
[14:19:55][Cacher] Cached %WS1%/src/03-statement.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/04-approach.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/04-approach.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/04-approach.tex .
[14:19:56][Cacher] Cached %WS1%/src/04-approach.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/05-experiments.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/05-experiments.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/05-experiments.tex .
[14:19:56][Cacher] Cached %WS1%/src/05-experiments.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/06-related.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/06-related.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/06-related.tex .
[14:19:56][Cacher] Cached %WS1%/src/06-related.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/07-conclusion.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/07-conclusion.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/07-conclusion.tex .
[14:19:56][Cacher] Cached %WS1%/src/07-conclusion.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/main.tex .
[14:19:56][Cacher] Updated elements of %WS1%/main.tex .
[14:19:56][Cacher] Bib %WS1%/ref.bib from %WS1%/main.tex .
[14:19:56][Cacher][Bib] File watched %WS1%/ref.bib .
[14:19:56][Intelli][Citation] Parsing .bib entries from %WS1%/ref.bib
[14:19:56][Intelli][Citation] Parsed 57 bib entries from %WS1%/ref.bib .
[14:19:56][Cacher] Updated bibs of %WS1%/main.tex .
[14:19:56][Cacher] Cached %WS1%/main.tex .
[14:19:56][Cacher][Path] Non-existent .fls for %WS1%/src/00-abstract.tex .
[14:19:56][Cacher][Path] Non-existent .fls for %WS1%/src/04-approach.tex .
[14:19:56][Cacher][Path] Non-existent .fls for %WS1%/src/03-statement.tex .
[14:19:56][Cacher][Path] Non-existent .fls for %WS1%/src/01-intro.tex .
[14:19:56][Cacher][Path] Non-existent .fls for %WS1%/src/05-experiments.tex .
[14:19:56][Cacher][Path] Non-existent .fls for %WS1%/src/02-preliminaries.tex .
[14:19:56][Cacher][Path] Non-existent .fls for %WS1%/src/06-related.tex .
[14:19:56][Cacher][Path] Non-existent .fls for %WS1%/src/07-conclusion.tex .
[14:19:56][Manager] Found files that might be root, choose the first one: %WS1%/main.tex
[14:19:56][Manager] Root file changed: from undefined to %WS1%/main.tex
[14:19:56][Manager] Start to find all dependencies.
[14:19:56][Manager] Root file languageId: latex
[14:19:56][Cacher][Watcher] Reset.
[14:19:56][Cacher] Adding %WS1%/main.tex .
[14:19:56][Cacher] Caching %WS1%/main.tex .
[14:19:56][Cacher] Input %WS1%/src/00-abstract.tex from %WS1%/main.tex .
[14:19:56][Cacher] Adding %WS1%/src/00-abstract.tex .
[14:19:56][Cacher] Caching %WS1%/src/00-abstract.tex .
[14:19:56][Cacher] Updated inputs of %WS1%/src/00-abstract.tex .
[14:19:56][Cacher] Input %WS1%/src/01-intro.tex from %WS1%/main.tex .
[14:19:56][Cacher] Adding %WS1%/src/01-intro.tex .
[14:19:56][Cacher] Caching %WS1%/src/01-intro.tex .
[14:19:56][Cacher] Updated inputs of %WS1%/src/01-intro.tex .
[14:19:56][Cacher] Input %WS1%/src/02-preliminaries.tex from %WS1%/main.tex .
[14:19:56][Cacher] Adding %WS1%/src/02-preliminaries.tex .
[14:19:56][Cacher] Caching %WS1%/src/02-preliminaries.tex .
[14:19:56][Cacher] Updated inputs of %WS1%/src/02-preliminaries.tex .
[14:19:56][Cacher] Input %WS1%/src/03-statement.tex from %WS1%/main.tex .
[14:19:56][Cacher] Adding %WS1%/src/03-statement.tex .
[14:19:56][Cacher] Caching %WS1%/src/03-statement.tex .
[14:19:56][Cacher] Updated inputs of %WS1%/src/03-statement.tex .
[14:19:56][Cacher] Input %WS1%/src/04-approach.tex from %WS1%/main.tex .
[14:19:56][Cacher] Adding %WS1%/src/04-approach.tex .
[14:19:56][Cacher] Caching %WS1%/src/04-approach.tex .
[14:19:56][Cacher] Updated inputs of %WS1%/src/04-approach.tex .
[14:19:56][Cacher] Input %WS1%/src/05-experiments.tex from %WS1%/main.tex .
[14:19:56][Cacher] Adding %WS1%/src/05-experiments.tex .
[14:19:56][Cacher] Caching %WS1%/src/05-experiments.tex .
[14:19:56][Cacher] Updated inputs of %WS1%/src/05-experiments.tex .
[14:19:56][Cacher] Input %WS1%/src/06-related.tex from %WS1%/main.tex .
[14:19:56][Cacher] Adding %WS1%/src/06-related.tex .
[14:19:56][Cacher] Caching %WS1%/src/06-related.tex .
[14:19:56][Cacher] Updated inputs of %WS1%/src/06-related.tex .
[14:19:56][Cacher] Input %WS1%/src/07-conclusion.tex from %WS1%/main.tex .
[14:19:56][Cacher] Adding %WS1%/src/07-conclusion.tex .
[14:19:56][Cacher] Caching %WS1%/src/07-conclusion.tex .
[14:19:56][Cacher] Updated inputs of %WS1%/src/07-conclusion.tex .
[14:19:56][Cacher] Updated inputs of %WS1%/main.tex .
[14:19:56][Cacher][Watcher] Watched %WS1%/main.tex .
[14:19:56][Cacher][Watcher] Watched %WS1%/src/00-abstract.tex .
[14:19:56][Cacher][Watcher] Watched %WS1%/src/01-intro.tex .
[14:19:56][Cacher][Watcher] Watched %WS1%/src/02-preliminaries.tex .
[14:19:56][Cacher][Watcher] Watched %WS1%/src/03-statement.tex .
[14:19:56][Cacher][Watcher] Watched %WS1%/src/04-approach.tex .
[14:19:56][Cacher][Watcher] Watched %WS1%/src/05-experiments.tex .
[14:19:56][Cacher][Watcher] Watched %WS1%/src/06-related.tex .
[14:19:56][Cacher][Watcher] Watched %WS1%/src/07-conclusion.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/00-abstract.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/00-abstract.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/00-abstract.tex .
[14:19:56][Cacher] Cached %WS1%/src/00-abstract.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/01-intro.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/01-intro.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/01-intro.tex .
[14:19:56][Cacher] Cached %WS1%/src/01-intro.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/02-preliminaries.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/02-preliminaries.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/02-preliminaries.tex .
[14:19:56][Cacher] Cached %WS1%/src/02-preliminaries.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/03-statement.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/03-statement.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/03-statement.tex .
[14:19:56][Cacher] Cached %WS1%/src/03-statement.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/04-approach.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/04-approach.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/04-approach.tex .
[14:19:56][Cacher] Cached %WS1%/src/04-approach.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/05-experiments.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/05-experiments.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/05-experiments.tex .
[14:19:56][Cacher] Cached %WS1%/src/05-experiments.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/06-related.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/06-related.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/06-related.tex .
[14:19:56][Cacher] Cached %WS1%/src/06-related.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/src/07-conclusion.tex .
[14:19:56][Cacher] Updated elements of %WS1%/src/07-conclusion.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/src/07-conclusion.tex .
[14:19:56][Cacher] Cached %WS1%/src/07-conclusion.tex .
[14:19:56][DupLabel] Checking for duplicate labels: %WS1%/main.tex .
[14:19:56][Cacher] Updated elements of %WS1%/main.tex .
[14:19:56][Cacher] Bib %WS1%/ref.bib from %WS1%/main.tex .
[14:19:56][Cacher] Updated bibs of %WS1%/main.tex .
[14:19:56][Cacher] Cached %WS1%/main.tex .
[14:19:56][Cacher][Path] Non-existent .fls for %WS1%/main.tex .
[14:20:39][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:32961/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRmhvbWUlMkZ4Y3podSUyRmRvYyUyRnBhcGVycyUyRmtkZC1sbGRwZ25uJTJGbWFpbi5wZGY .
[14:20:39][Cacher][PDF] Watched file://%WS1%/main.pdf .
[14:20:39][Viewer] Open PDF tab for file://%WS1%/main.pdf
[14:25:13][Commander] SHOWLOG command invoked: default
[14:25:17][Commander] SHOWLOG command invoked: default
```

### Developer Tools Console [Required]

```
log.ts:304  INFO Electron sandbox mode is enabled!
log.ts:304  INFO [attempt 1] Invoking resolveAuthority(wsl)
log.ts:304  INFO [attempt 1] resolveAuthority(wsl) returned '127.0.0.1:10826' after 552 ms
log.ts:310  WARN [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///c%3A/Users/zhuxi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/xczhu/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///c%3A/Users/zhuxi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/xczhu/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///c%3A/Users/zhuxi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/xczhu/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/Bibtex.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///c%3A/Users/zhuxi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/xczhu/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/markdown-latex-combined.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///c%3A/Users/zhuxi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/xczhu/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/syntax/cpp-grammar-bailout.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.macro.
Old grammar file: file:///c%3A/Users/zhuxi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/cpp/syntaxes/cpp.embedded.macro.tmLanguage.json.
New grammar file: file:///c%3A/Users/zhuxi/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.17.2/autogenerated/cpp.embedded.macro.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.cpp.
Old grammar file: file:///c%3A/Users/zhuxi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/cpp/syntaxes/cpp.tmLanguage.json.
New grammar file: file:///c%3A/Users/zhuxi/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.17.2/autogenerated/cpp.tmLanguage.json
register @ TMScopeRegistry.ts:47
log.ts:316   ERR Cannot read properties of undefined (reading 'state'): TypeError: Cannot read properties of undefined (reading 'state')
	at PdfViewerPanelSerializer.deserializeWebviewPanel (/home/xczhu/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/out/src/components/viewerlib/pdfviewerpanel.js:61:98)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c.$deserializeWebviewPanel (/home/xczhu/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:96:172352)
log.ts:304  INFO [perf] Render performance baseline is 25ms
```

There's an error about PDF veiwer.

## Screenshots

<img width="1920" alt="Screenshot 2023-01-25 143210" src="https://user-images.githubusercontent.com/42903201/214496722-51f7d2cd-59a7-4aad-9f3b-50325a9ad186.png">

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Ubuntu 20.04 [WSL 2]
 - VS Code version: 1.74.3
 - Extension version: 9.5.0
 - TeX distribution version: not relevant

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

Yes.

- Remote WSL
- Remote Extension Version: 0.72.0

### Additional context

NA.

**Comment by nidrissi** [comment]
Looks similar to my issue #3664 that the developers didn't care to fix.

**Comment by James-Yu** [comment]
See #3665 and #1267. Configure your firewall to allow for the port.

**Comment by nidrissi** [comment]
@James-Yu I think you misunderstood my comment from yesterday. Opening the firewall is not at all the solution. I was trying to explain that your argument for not listening on "*:PORT" rather than "127.0.0.1:PORT" made no sense.

**Comment by AxiomOfChoices** [comment]
> See #3665 and #1267. Configure your firewall to allow for the port.

Could you kindly explain how to do this step. As far as I know my firewall hasn't changed at all and yet PDF preview suddenly stopped working and I cannot find any guide online that explains how to do this.

**Comment by SherAndrei** [comment]
I figured out, that there are two directories referring to `vscode-server` on my WSL in `$HOME` directroy: `vscode-server` and `vscode-server-server`. I don't know how this happened, but after deleting both of them, reinstalling vscode-server (it's done automatically by `vscode`) and reinstalling the exstention bug disappeared.

**Comment by zhxchd** [comment]
Just an update on this issue. I wasn't able to fix this when I posted the issue, and use the extension in Windows VS Code instead. Just now I try again in WSL VS code remote, it's working right now. I'm not sure whether it is a firewall issue or not, but I don't think I've ever changed my firewall config since then.
