### ISSUE TITLE
I still can't see my pdf file in vscode at 1.1.2 wsl2 and 9.7.0 LW

### ISSUE THREAD

**Issue by syvshc** [James-Yu/LaTeX-Workshop#3721]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ ] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 11
- Visual Studio Code Version: 1.75.1
- LaTeX Workshop Version: 9.7.0
- TeX Distribution Version: TeXLive 2022

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using WSL2 whose version is 1.1.2.0

## The Issue*

as #3670 said, I have tried the `3.6.1` artifact, and the `3.7.0`  version in VSCode, both of them led to the same issue

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[11:29:48][Logger] New log placeholder %WS1% registered for /home/syvshclily/test .
[11:29:48][Config] Configuration for workspace: file://%WS1% .
[11:29:48][Config] editor.acceptSuggestionOnEnter: "on" .
[11:29:48][Config] latex-workshop.bind.enter.key: true .
[11:29:48][Config] latex-workshop.docker.enabled: false .
[11:29:48][Config] latex-workshop.docker.image.latex: "" .
[11:29:48][Config] latex-workshop.hover.preview.mathjax.extensions: [] .
[11:29:48][Config] latex-workshop.intellisense.package.enabled: true .
[11:29:48][Config] latex-workshop.intellisense.update.aggressive.enabled: false .
[11:29:48][Config] latex-workshop.intellisense.update.delay: 1000 .
[11:29:48][Config] latex-workshop.latex.autoBuild.run: "never" .
[11:29:48][Config] latex-workshop.latex.build.forceRecipeUsage: false .
[11:29:48][Config] latex-workshop.latex.outDir: "%DIR%" .
[11:29:48][Config] latex-workshop.latex.recipes: [
 {
  "name": "pdflatex",
  "tools": [
   "pdflatex"
  ]
 },
 {
  "name": "latexmk",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmkpdf",
  "tools": [
   "latexmkpdf"
  ]
 },
 {
  "name": "latexmkxe",
  "tools": [
   "latexmkxe"
  ]
 },
 {
  "name": "xelatex",
  "tools": [
   "xelatex"
  ]
 },
 {
  "name": "lualatex",
  "tools": [
   "lualatex"
  ]
 },
 {
  "name": "bibtex",
  "tools": [
   "bibtex"
  ]
 },
 {
  "name": "biber",
  "tools": [
   "biber"
  ]
 }
] .
[11:29:48][Config] latex-workshop.latex.tools: [
 {
  "name": "latexmk",
  "command": "latexmk",
  "args": [
   "-pvc-",
   "%DOCFILE%"
  ]
 },
 {
  "name": "latexmkpdf",
  "command": "latexmk",
  "args": [
   "-shell-escape",
   "-synctex=1",
   "-interaction=nonstopmode",
   "-halt-on-error",
   "-file-line-error",
   "-pdf",
   "-pv",
   "%DOCFILE%"
  ]
 },
 {
  "name": "latexmkxe",
  "command": "latexmk",
  "args": [
   "-xelatex",
   "-shell-escape",
   "-synctex=1",
   "-interaction=nonstopmode",
   "-halt-on-error",
   "-file-line-error",
   "-pv",
   "%DOCFILE%"
  ]
 },
 {
  "name": "xelatex",
  "command": "xelatex",
  "args": [
   "-shell-escape",
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-pdf",
   "%DOCFILE%"
  ]
 },
 {
  "name": "lualatex",
  "command": "lualatex",
  "args": [
   "-shell-escape",
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-pdf",
   "%DOCFILE%"
  ]
 },
 {
  "name": "pdflatex",
  "command": "pdflatex",
  "args": [
   "-shell-escape",
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "%DOCFILE%"
  ]
 },
 {
  "name": "bibtex",
  "command": "bibtex",
  "args": [
   "%DOCFILE%"
  ]
 },
 {
  "name": "biber",
  "command": "biber",
  "args": [
   "%DOCFILE%"
  ]
 }
] .
[11:29:48][Config] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto" .
[11:29:48][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[11:29:48][Server] Creating LaTeX Workshop http and websocket server.
[11:29:48][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":45451} .
[11:29:48][Extension] Initializing LaTeX Workshop.
[11:29:48][Extension] Extension root: /home/syvshclily/.vscode-server/extensions/james-yu.latex-workshop-9.6.1
[11:29:48][Extension] $PATH: /home/syvshclily/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli:/home/syvshclily/git/petsc/petsc-latest/arch-linux-c-debug/bin:/home/syvshclily/git/petsc/petsc-latest/lib/petsc/bin:/home/syvshclily/texlive/2022/bin/x86_64-linux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/Razer Chroma SDK/bin:/mnt/c/Program Files/Razer Chroma SDK/bin:/mnt/c/Program Files (x86)/Razer/ChromaBroadcast/bin:/mnt/c/Program Files/Razer/ChromaBroadcast/bin:/mnt/c/Program Files/Python310/Scripts/:/mnt/c/Program Files/Python310/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/texlive/2022/bin/win32:/mnt/c/texlive/2020/bin/win32:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Bandizip/:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files/gnuplot/bin:/mnt/c/Strawberry/c/bin:/mnt/c/Strawberry/perl/site/bin:/mnt/c/Strawberry/perl/bin:/mnt/c/WINDOWS/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/syvshc-lily/AppData/Local/Microsoft/WindowsApps:/mnt/d/vscode/bin:/mnt/c/Users/syvshc-lily/AppData/Roaming/Python/Python310/Scripts:/mnt/c/Users/syvshc-lily/AppData/Roaming/npm:/mnt/c/Users/syvshc-lily/AppData/Local/Pandoc/:/mnt/c/tools/neovim/Neovim/bin:/mnt/c/Program Files/dotnet/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/d/OneDrive/wogs/Code/python:/mnt/c/tools/winfetch:/mnt/d/Program Files/MATLAB/R2022b/runtime/win64:/mnt/d/Program Files/MATLAB/R2022b/bin:/mnt/c/Program Files/PowerShell/7/:/mnt/c/ProgramData/syvshc-lily/GitHubDesktop/bin:/mnt/c/Users/syvshc-lily/AppData/Local/GitHubDesktop/bin:/mnt/d/Arch:/mnt/c/Users/syvshc-lily/AppData/Local/Programs/oh-my-posh/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[11:29:48][Extension] $SHELL: /usr/bin/zsh
[11:29:48][Extension] $LANG: en_US.UTF-8
[11:29:48][Extension] $LC_ALL: undefined
[11:29:48][Extension] process.platform: linux
[11:29:48][Extension] process.arch: x64
[11:29:48][Extension] vscode.env.appName: Visual Studio Code
[11:29:48][Extension] vscode.env.remoteName: wsl
[11:29:48][Extension] vscode.env.uiKind: 1
[11:29:48][Extension] LaTeX Workshop initialized.
[11:29:48][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[11:29:48][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[11:29:48][Manager] Current workspace folders: ["file://%WS1%"]
[11:29:48][Manager] Current workspaceRootDir: file://%WS1%
[11:29:48][Server] valdOrigin is http://127.0.0.1:45451
[11:29:49][Cacher][Path] Non-existent .fls for %WS1%/main.tex .
[11:29:49][Cacher] Cache not finished on %WS1%/main.tex when getting its children.
[11:29:49][Cacher] Caching %WS1%/main.tex .
[11:29:49][Cacher] Updated inputs of %WS1%/main.tex .
[11:29:49][DupLabel] Checking for duplicate labels: %WS1%/main.tex .
[11:29:49][Cacher] Updated elements of %WS1%/main.tex .
[11:29:49][Cacher] Updated bibs of %WS1%/main.tex .
[11:29:49][Cacher] Cached %WS1%/main.tex .
[11:29:49][Structure] Structure cleared on undefined root.
[11:29:49][Manager] Found files that might be root, choose the first one: %WS1%/main.tex
[11:29:49][Manager] Root file changed: from undefined to %WS1%/main.tex
[11:29:49][Manager] Start to find all dependencies.
[11:29:49][Manager] Root file languageId: latex
[11:29:49][Cacher][Watcher] Reset.
[11:29:49][Cacher] Adding %WS1%/main.tex .
[11:29:49][Cacher][Watcher] Watched %WS1%/main.tex with a new watcher on %WS1% .
[11:29:49][Cacher] Caching %WS1%/main.tex .
[11:29:49][Cacher] Updated inputs of %WS1%/main.tex .
[11:29:49][DupLabel] Checking for duplicate labels: %WS1%/main.tex .
[11:29:49][Cacher] Updated elements of %WS1%/main.tex .
[11:29:49][Cacher] Updated bibs of %WS1%/main.tex .
[11:29:49][Cacher] Cached %WS1%/main.tex .
[11:29:49][Cacher][Path] Non-existent .fls for %WS1%/main.tex .
[11:29:49][Structure] Structure force updated with 0 root sections for %WS1%/main.tex .
[11:30:01][Manager] Current workspace folders: ["file://%WS1%"]
[11:30:01][Manager] Found root file from active editor: %WS1%/main.tex
[11:30:01][Manager] Keep using the same root file: %WS1%/main.tex
[11:30:01][Structure] Structure updated with 0 root sections for %WS1%/main.tex .
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
 WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'commentsResolvedState' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:sourcemap:90 [Extension Host] ApplicationInsights:An invalid instrumentation key was provided. There may be resulting telemetry loss Array(1)
I @ workbench.desktop.main.js:sourcemap:90
workbench.desktop.main.js:sourcemap:616  INFO Invoking resolveAuthority(wsl)...
workbench.desktop.main.js:sourcemap:616  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] obtaining proxy...
workbench.desktop.main.js:sourcemap:616  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] invoking...
workbench.desktop.main.js:sourcemap:616  INFO [LocalProcess0][resolveAuthority(wsl,1)][471ms] returned 127.0.0.1:2987
workbench.desktop.main.js:sourcemap:616  INFO resolveAuthority(wsl) returned '127.0.0.1:2987' after 472 ms
workbench.desktop.main.js:sourcemap:616  INFO Creating a socket (renderer-Management-4e0854b3-2db2-40cb-ba74-6675cdaf4400)...
workbench.desktop.main.js:sourcemap:616  INFO Creating a socket (renderer-ExtensionHost-9149fb7c-d80a-4db3-92ee-9b6a7e3a3ce4)...
workbench.desktop.main.js:sourcemap:616  INFO Creating a socket (renderer-Management-4e0854b3-2db2-40cb-ba74-6675cdaf4400) was successful after 128 ms.
workbench.desktop.main.js:sourcemap:616  INFO Creating a socket (renderer-ExtensionHost-9149fb7c-d80a-4db3-92ee-9b6a7e3a3ce4) was successful after 310 ms.
workbench.desktop.main.js:sourcemap:616  WARN [twxs.cmake]: 无法注册“cmake.cmakePath”。此属性已注册。
workbench.desktop.main.js:sourcemap:616  WARN No search provider registered for scheme: vscode-remote, waiting
workbench.desktop.main.js:sourcemap:616   ERR Cannot get default system shell when there is no backend for remote authority 'wsl+Arch': Error: Cannot get default system shell when there is no backend for remote authority 'wsl+Arch'
    at Object.getDefaultSystemShell (vscode-file://vscode-app/d:/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1704:6413)
    at async i.v (vscode-file://vscode-app/d:/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:18560)
    at async i.r (vscode-file://vscode-app/d:/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:17823)
    at async i.getDefaultProfile (vscode-file://vscode-app/d:/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:17154)
    at async Promise.all (index 0)
    at async r.y (vscode-file://vscode-app/d:/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1696:50610)
workbench.desktop.main.js:sourcemap:1920 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///d%3A/vscode/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Barch/home/syvshclily/.vscode-server/extensions/james-yu.latex-workshop-9.6.1/syntax/TeX.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1920
workbench.desktop.main.js:sourcemap:1920 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///d%3A/vscode/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Barch/home/syvshclily/.vscode-server/extensions/james-yu.latex-workshop-9.6.1/syntax/LaTeX.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1920
workbench.desktop.main.js:sourcemap:1920 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///d%3A/vscode/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Barch/home/syvshclily/.vscode-server/extensions/james-yu.latex-workshop-9.6.1/syntax/Bibtex.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1920
workbench.desktop.main.js:sourcemap:1920 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///d%3A/vscode/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Barch/home/syvshclily/.vscode-server/extensions/james-yu.latex-workshop-9.6.1/syntax/markdown-latex-combined.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1920
workbench.desktop.main.js:sourcemap:1920 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///d%3A/vscode/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Barch/home/syvshclily/.vscode-server/extensions/james-yu.latex-workshop-9.6.1/syntax/cpp-grammar-bailout.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1920
workbench.desktop.main.js:sourcemap:616   ERR Cannot get default system shell when there is no backend for remote authority 'wsl+Arch': Error: Cannot get default system shell when there is no backend for remote authority 'wsl+Arch'
    at Object.getDefaultSystemShell (vscode-file://vscode-app/d:/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1704:6413)
    at async i.v (vscode-file://vscode-app/d:/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:18560)
    at async i.r (vscode-file://vscode-app/d:/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:17823)
    at async i.getDefaultProfile (vscode-file://vscode-app/d:/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:17154)
    at async i.o (vscode-file://vscode-app/d:/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:15865)
workbench.desktop.main.js:sourcemap:616   ERR Cannot read properties of undefined (reading 'state'): TypeError: Cannot read properties of undefined (reading 'state')
	at PdfViewerPanelSerializer.deserializeWebviewPanel (/home/syvshclily/.vscode-server/extensions/james-yu.latex-workshop-9.6.1/out/src/components/viewerlib/pdfviewerpanel.js:60:98)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async s.$deserializeWebviewPanel (/home/syvshclily/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/workbench/api/node/extensionHostProcess.js:98:174638)
workbench.desktop.main.js:sourcemap:605 [vs-picgo]: 无法找到键 ext.keywords 的消息。
w @ workbench.desktop.main.js:sourcemap:605
workbench.desktop.main.js:sourcemap:616  INFO [perf] Render performance baseline is 29ms
workbench.desktop.main.js:sourcemap:2020 Activating extension 'ms-vscode-remote.remote-containers' failed: connect ETIMEDOUT 185.199.110.153:443.
$onExtensionActivationError @ workbench.desktop.main.js:sourcemap:2020
```

**Comment by James-Yu** [comment]
Did you try the new host name command? If it won’t work, there’s nothing can be done from the extension side.

**Comment by syvshc** [comment]
> Did you try the new host name command? If it won’t work, there’s nothing can be done from the extension side.

Sorry, I didn't know what the new host name is. Is it something described in this issue? https://github.com/microsoft/terminal/issues/11795

**Comment by James-Yu** [comment]
https://github.com/James-Yu/LaTeX-Workshop/blob/master/CHANGELOG.md#970---2023-02-14
