### ISSUE TITLE
Building one LaTeX file breaks the extension until I restart VSCode

### ISSUE THREAD

**Issue by HarrisonWilde** [James-Yu/LaTeX-Workshop#3742]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Mac OS 13.2.1
- Visual Studio Code Version: 1.75.1
- LaTeX Workshop Version: 9.7.0
- TeX Distribution Version: TeX Live 2022

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- Building seems to stop working after I try building another file after first building a different one
- I see an error pop up in the bottom right that says "Cannot read properties of undefined (reading 'children')"

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Install LaTeX Workshop
2. Disable all other extensions etc.
3. Build document after opening application, works fine
4. Build another document in a different folder in the same workspace, observe error mentioned above
5. No longer works for either

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- For the build to happen

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._

N/A

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
log.ts:398  WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'commentsResolvedState' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///Users/harrisonwilde/.vscode/extensions/james-yu.latex-workshop-9.7.0/syntax/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///Users/harrisonwilde/.vscode/extensions/james-yu.latex-workshop-9.7.0/syntax/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///Users/harrisonwilde/.vscode/extensions/james-yu.latex-workshop-9.7.0/syntax/Bibtex.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///Users/harrisonwilde/.vscode/extensions/james-yu.latex-workshop-9.7.0/syntax/markdown-latex-combined.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///Users/harrisonwilde/.vscode/extensions/james-yu.latex-workshop-9.7.0/syntax/cpp-grammar-bailout.tmLanguage.json
register @ TMScopeRegistry.ts:47
log.ts:392  INFO [perf] Render performance baseline is 20ms
5viewer.js:1909 The `PDFViewerApplication.open` signature was updated, please use an object instead.
open @ viewer.js:1909
log.ts:392  INFO Settings Sync: Updated current session d828ee35a4a2272
viewer.js:1909 The `PDFViewerApplication.open` signature was updated, please use an object instead.
open @ viewer.js:1909
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'children')
I @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'children')
	at Cacher.loadFlsFile (/Users/harrisonwilde/.vscode/extensions/james-yu.latex-workshop-9.7.0/out/src/components/cacher.js:274:39)
	at async /Users/harrisonwilde/.vscode/extensions/james-yu.latex-workshop-9.7.0/out/src/components/manager.js:280:21
I @ console.ts:137
mainThreadExtensionService.ts:79 [[object Object]]Cannot read properties of undefined (reading 'children')
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
mainThreadExtensionService.ts:80 TypeError: Cannot read properties of undefined (reading 'children')
	at Cacher.loadFlsFile (vscode-file://vscode-app/Users/harrisonwilde/.vscode/extensions/james-yu.latex-workshop-9.7.0/out/src/components/cacher.js:274:39)
	at async vscode-file://vscode-app/Users/harrisonwilde/.vscode/extensions/james-yu.latex-workshop-9.7.0/out/src/components/manager.js:280:21
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
notificationsAlerts.ts:40 Error: Cannot read properties of undefined (reading 'children')
	at s.h (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:108192)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
c @ notificationsAlerts.ts:40
DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-cdn.net/Users/harrisonwilde/.vscode/extensions/james-yu.latex-workshop-9.7.0/node_modules/pdfjs-dist/build/pdf.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://127.0.0.1:55081/out/viewer/latexworkshop.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:55081/build/pdf.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:55081/out/viewer/components/connection.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:55081/out/viewer/components/synctex.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:55081/out/viewer/components/htmleditor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:55081/out/viewer/components/pagetrimmer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:55081/out/viewer/components/externalpromise.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:55081/out/viewer/components/utils.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:55081/out/viewer/components/viewerhistory.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:55081/viewer/viewer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not parse content for vscode-webview://06p2kc05klhgoph7c0pdcgobi4n516mptp7vpdu792t76v0adklb/pdf.worker.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for http://127.0.0.1:55081/build/pdf.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
```

## Anything Else?
> _Add any other context about the problem below._
- N/A

**Comment by James-Yu** [comment]
Extension logs please.

Also, I cannot reproduce the problem. Please provide a minimal working example if possible.
