### ISSUE TITLE
Use Docker and pdflatex to typeset.

### ISSUE THREAD

**Issue by SubtleMuffin** [James-Yu/LaTeX-Workshop#3745]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 11
- Visual Studio Code Version: 1.75.1
- LaTeX Workshop Version: [v9.7.0](https://github.com/James-Yu/LaTeX-Workshop/releases/tag/v9.7.0)
- TeX Distribution Version: Docker, image: subtlemuffin/latex:latest

## The Issue*
> _Please briefly describe the issue you come across._
- Cannot typeset a document with `Docker` and `pdflatex`, due to [this line](https://github.com/James-Yu/LaTeX-Workshop/blob/a53711a631c000d63815c5d4b60019deb90acd62/src/components/builder.ts#L508). I confirm `latexmk` works fine.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Open any document
2. Typeset using the `pdflatex` recipe:
```json
"latex-workshop.latex.recipes": [
        {
            "name": "latexmk",
            "tools": [
                "latexmk"
            ]
        },
        {
            "name": "pdflatex",
            "tools": [
                "pdflatex"
            ]
        },
    ]
```
3. Builder complains `[Builder] Do not use Docker to invoke the command: pdflatex.`.

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- Successfully typeset the document with `pdflatex` and `Docker`.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[10:09:43][Commander] RECIPES command invoked.
[10:09:43][Commander] BUILD command invoked.
[10:09:43][Commander] The document of the active editor: file:///c:/Users/[redacted]/[redacted].tex
[10:09:43][Commander] The languageId of the document: latex
[10:09:43][Manager] Current workspace folders: ["file:///c:/Users/[redacted]/"]
[10:09:43][Manager] Found root file from active editor: %WS1%\[redacted].tex
[10:09:43][Manager] Keep using the same root file: %WS1%\[redacted].tex
[10:09:43][Structure] Structure updated with 7 root sections for %WS1%\[redacted].tex .
[10:09:43][Commander] Building root file: %WS1%\[redacted].tex
[10:09:43][Builder] Build root file %WS1%\[redacted].tex
[10:09:43][Builder] outDir: %WS1% .
[10:09:43][Builder] Preparing to run recipe: pdflatex.
[10:09:43][Builder] Prepared 1 tools.
[10:09:43][Builder] Do not use Docker to invoke the command: pdflatex.
[10:09:43][Builder] Recipe step 1 The command is pdflatex:["-synctex=1","-interaction=nonstopmode","-file-line-error","-shell-escape","[redacted]"].
[10:09:43][Builder] env: undefined
[10:09:43][Builder] root: %WS1%\[redacted].tex
[10:09:43][Builder] cwd: %WS1%
[10:09:44][Builder] LaTeX build process spawned with PID 2732.
[10:09:44][Structure] Structure updated with 7 root sections for %WS1%\[redacted].tex .
[10:09:44][Builder] LaTeX fatal error on PID 2732. Error: spawn pdflatex ENOENT
[10:09:44]Error: spawn pdflatex ENOENT
	at notFoundError (c:\Users\[redacted]\.vscode\extensions\james-yu.latex-workshop-9.7.0\node_modules\cross-spawn\lib\enoent.js:6:26)
	at verifyENOENT (c:\Users\[redacted]\.vscode\extensions\james-yu.latex-workshop-9.7.0\node_modules\cross-spawn\lib\enoent.js:40:16)
	at cp.emit (c:\Users\[redacted]\.vscode\extensions\james-yu.latex-workshop-9.7.0\node_modules\cross-spawn\lib\enoent.js:27:25)
	at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[10:09:44][Builder] Does the executable exist? $PATH: undefined, $Path: [redacted]
[10:09:44][Builder] 'pdflatex' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by James-Yu** [comment]
Note that the extension do not support docker officially. We do not handle related issues.
