### ISSUE TITLE
LaTeX-Workshop internal Preview renders colored content in black

### ISSUE THREAD

**Issue by mw88-personal** [James-Yu/LaTeX-Workshop#3861]
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: Windows 11 22HS (Build 22621.1555)
- Visual Studio Code Version:  1.77.3
- LaTeX Workshop Version: 9.8.2
- TeX Distribution Version: TeX Live 2022

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using WSL2 whose version is ``WSL-Version: 1.2.5.0``

## The Issue*
When I preview PDFs using the internal PDF preview of LaTeX-Workshop in vscode, many colored objects are instead displayed in black.
The exact same PDF is displayed in correct colors, when displayed in another PDF reader, e.g. Sumatra PDF.

### Reproduction Steps
1.  Compile the MWE:
~~~latex
\documentclass{article}
\usepackage{xcolor}
\usepackage{tikz}


\begin{document}
A red line:
\begin{tikzpicture}
	\draw[draw=red] (0,0) -- (1, 1);
\end{tikzpicture}

{
\color{red}
This text should be red.
}

\end{document}
~~~
2. Preview in internal PDF preview of vscode
3.  Compare to display in external PDF viewer (Sumatra PDF).

### Expected Behavior
I expect colors to appear the same in the internal preview nd the external viewer.

### LaTeX Workshop Output*
Log not relevant to the problem. Compilation is succesfull.

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:421  INFO Invoking resolveAuthority(wsl)...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] obtaining proxy...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] invoking...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][612ms] returned 127.0.0.1:65163
log.ts:421  INFO resolveAuthority(wsl) returned '127.0.0.1:65163' after 613 ms
log.ts:421  INFO Creating a socket (renderer-Management-b6b451b3-5786-445f-b8b4-c743d4d193ca)...
log.ts:421  INFO Creating a socket (renderer-ExtensionHost-c484da36-cbbe-4676-8433-a1821d99a723)...
log.ts:421  INFO Creating a socket (renderer-Management-b6b451b3-5786-445f-b8b4-c743d4d193ca) was successful after 100 ms.
log.ts:421  INFO Creating a socket (renderer-ExtensionHost-c484da36-cbbe-4676-8433-a1821d99a723) was successful after 293 ms.
log.ts:441   ERR Error: Decryption failed.
2log.ts:441   ERR SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at C.$getPassword (mainThreadSecretState.ts:70:24)
log.ts:421  INFO [perf] Render performance baseline is 28ms
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bdebian/home/marc/.vscode-server/extensions/james-yu.latex-workshop-9.8.2/syntax/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bdebian/home/marc/.vscode-server/extensions/james-yu.latex-workshop-9.8.2/syntax/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bdebian/home/marc/.vscode-server/extensions/james-yu.latex-workshop-9.8.2/syntax/Bibtex.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bdebian/home/marc/.vscode-server/extensions/james-yu.latex-workshop-9.8.2/syntax/markdown-latex-combined.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bdebian/home/marc/.vscode-server/extensions/james-yu.latex-workshop-9.8.2/syntax/cpp-grammar-bailout.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: vscode-remote://wsl%2Bdebian/home/marc/.vscode-server/extensions/james-yu.latex-workshop-9.8.2/syntax/TeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/Marc/.vscode/extensions/vomout.latex-syntax-0.0.7/syntaxes/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: vscode-remote://wsl%2Bdebian/home/marc/.vscode-server/extensions/james-yu.latex-workshop-9.8.2/syntax/LaTeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/Marc/.vscode/extensions/vomout.latex-syntax-0.0.7/syntaxes/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:45
log.ts:441   ERR Unable to load and parse grammar for scope markdown.latex.codeblock from file:///c%3A/Users/Marc/.vscode/extensions/vomout.latex-syntax-0.0.7/syntax/latexblock.json Error: Unable to read file 'c:\Users\Marc\.vscode\extensions\vomout.latex-syntax-0.0.7\syntax\latexblock.json' (Error: Unable to resolve nonexistent file 'c:\Users\Marc\.vscode\extensions\vomout.latex-syntax-0.0.7\syntax\latexblock.json')
    at r.w (fileService.ts:584:10)
    at r.v (fileService.ts:569:15)
    at async r.u (fileService.ts:481:18)
    at async S.readExtensionResource (extensionResourceLoaderService.ts:36:18)
    at async Object.loadGrammar (TMGrammarFactory.ts:54:22)
    at async t.Registry._doLoadSingleGrammar (main.js:85:15)
    at async Promise.all (index 58)
    at async t.Registry._loadGrammar (main.js:72:47)
    at async L.createGrammar (TMGrammarFactory.ts:141:14)
    at async k.L (textMateTokenizationFeatureImpl.ts:270:14)
    at async R.i (tokenizationRegistry.ts:148:17)
    at async L.getOrCreate (tokenizationRegistry.ts:76:3)
DevTools failed to load source map: Could not load content for http://127.0.0.1:36015/out/viewer/latexworkshop.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:36015/out/viewer/components/connection.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:36015/out/viewer/components/htmleditor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:36015/out/viewer/components/synctex.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:36015/build/pdf.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:36015/out/viewer/components/pagetrimmer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:36015/out/viewer/components/externalpromise.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:36015/out/viewer/components/utils.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:36015/out/viewer/components/viewerhistory.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:36015/viewer/viewer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:36015/build/pdf.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
```

## Anything else
See screenshots for problem clarification:
![image](https://user-images.githubusercontent.com/1152984/234841580-7c331ff5-e616-4d5c-aeb1-d9c772319f19.png)
![image](https://user-images.githubusercontent.com/1152984/234841673-ca2510f2-cc04-46cd-ab60-f74f730527ad.png)

**Comment by James-Yu** [comment]
On my side:
<img width="1440" alt="Screenshot 2023-04-27 at 19 13 25" src="https://user-images.githubusercontent.com/4210342/234845832-78d07970-b428-418e-b942-65fff0c1eaaa.png">

Log is indeed relevant. You may also instead check your config.

**Comment by mw88-personal** [comment]
I updated the LaTeX-Workshop console output. Perhaps I could not spot a relevant line but you will.

Moreover, I repeated the process with the following settings set to default:
* User Settings
* Workspace Settings
* Profile Settings
* Remote Settings (WSL Debian)

I repeated the same experiment with a freshly downloaded (zipped) copy of VSCode **without** WSL, just LaTeX-Workshop installed (same versions of windows, vscode, LaTeX-Workshop).

None of these changed the output on my side.

**Comment by James-Yu** [comment]
The added is not the complete log as per instruction.

You issue is a local problem. I am sorry that I can’t help you.

**Comment by mw88-personal** [comment]
I was able to resolve it. For future reference, here is what solved it. However, while it was a local problem, as described, it could arise in more than just my setup and could be resolved globally.

Question 1 (to improve my future bug reports): Can you extend the instructions for bug reports on how to get the full log then? In the *Output* panel, after selecting *LaTeX Workshop* in the dropdown, the paseted log messages were all that was written there. In particular, it didn't start with `New log placeholder %WS1% registered`.

My Workaround: After applying a different visual style   (defaslt dark) to windows, and reopening the PDF preview, the colors  displayed correctly with the internal PDF preview. Returning to a custom visal style made them appear black again. I conclude, that the PDF preview uses system colors, instead of colors set by vscode or LaTeX-Workshop.

Once I set in *User Settings*:
~~~JSON
{
    "latex-workshop.view.pdf.color.dark.backgroundColor": "0",
    "latex-workshop.view.pdf.color.dark.pageColorsForeground": "0",
    "latex-workshop.view.pdf.color.dark.pageBorderColor": "0",
    "latex-workshop.view.pdf.color.light.backgroundColor": "0",
    "latex-workshop.view.pdf.color.light.pageColorsForeground": "0",
    "latex-workshop.view.pdf.color.light.pageBorderColor": "0",
}
~~~
some default colors are applied and colors are rendered correctly. It does **only** work with setting an **invalid value**, e.g. "0", not with an empty string. If I set **any valid** color value for any of the properties in group *dark* or *light*, it overrides the respective property.

I concede, that this is not to be viewed as a bug anymore, but the same behaviour might arise on different configurations. My workaround works sufficiently, but it might be more useful to provide a default configuration for PDF.js which does not use system colors.
