### ISSUE TITLE
outline/structure is missing while using WSL

### ISSUE THREAD

**Issue by eqol-fomi** [James-Yu/LaTeX-Workshop#3897]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System:  Windows 11
- Visual Studio Code Version: 1.78.2
- LaTeX Workshop Version: 9.11.4
- TeX Distribution Version: TeX Live 2022

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using WSL: Ubuntu whose version is Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220)

## The Issue*
> _Please briefly describe the issue you come across._
- there is nothing in the outline/structure
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/102793631/c63b87fa-4702-4b92-852c-763d02079ef5)

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Just open the file. 

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- outline/structure works normally.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[22:30:41][Logger] New log placeholder %WS1% registered for /home/fomi/Papers/VM5aR_TEX .
[22:30:41][Config] latex-workshop.latex.recipes: [{"name":"XeLaTeX","tools":["xelatex"]},{"name":"PDFLaTeX","tools":["pdflatex"]},{"name":"BibTeX","tools":["bibtex"]},{"name":"LaTeXmk","tools":["latexmk"]},{"name":"xelatex -> bibtex -> xelatex*2","tools":["xelatex","bibtex","xelatex","xelatex"]},{"name":"pdflatex -> bibtex -> pdflatex*2","tools":["pdflatex","bibtex","pdflatex","pdflatex"]}] .
[22:30:41][Config] latex-workshop.latex.recipe.default: "lastUsed" .
[22:30:41][Config] latex-workshop.latex.tools: [{"name":"xelatex","command":"xelatex","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","%DOCFILE%"]},{"name":"pdflatex","command":"pdflatex","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","%DOCFILE%"]},{"name":"latexmk","command":"latexmk","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","-pdf","-outdir=%OUTDIR%","%DOCFILE%"]},{"name":"bibtex","command":"bibtex","args":["%DOCFILE%"]}] .
[22:30:41][Config] latex-workshop.kpsewhich.enabled: true .
[22:30:41][Config] latex-workshop.latex.autoBuild.run: "never" .
[22:30:41][Config] latex-workshop.latex.autoClean.run: "onFailed" .
[22:30:41][Config] latex-workshop.latex.clean.fileTypes: ["*.aux","*.bbl","*.blg","*.idx","*.ind","*.lof","*.lot","*.out","*.toc","*.acn","*.acr","*.alg","*.glg","*.glo","*.gls","*.ist","*.fls","*.log","*.fdb_latexmk"] .
[22:30:41][Config] latex-workshop.view.outline.commands: [] .
[22:30:41][Config] latex-workshop.view.outline.floats.enabled: false .
[22:30:41][Config] latex-workshop.view.pdf.internal.synctex.keybinding: "double-click" .
[22:30:41][Config] latex-workshop.intellisense.unimathsymbols.enabled: true .
[22:30:41][Config] latex-workshop.message.warning.show: false .
[22:30:41][Config] latex-workshop.showContextMenu: true .
[22:30:41][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[22:30:41][Server] Creating LaTeX Workshop http and websocket server.
[22:30:41][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":33597} .
[22:30:41][Extension] Initializing LaTeX Workshop.
[22:30:41][Extension] Extension root: /home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4
[22:30:41][Extension] $PATH: /home/fomi/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/Intel/oneAPI/mpi/latest/bin/:/mnt/c/Program Files (x86)/Intel/oneAPI/mpi/latest/bin/release/:/mnt/c/Program Files (x86)/Intel/oneAPI/mpi/latest/libfabric/bin/:/mnt/c/Program Files (x86)/Intel/oneAPI/mpi/latest/libfabric/bin/utils/:/mnt/c/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/redist/intel64_win/compiler:/mnt/c/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/redist/ia32_win/compiler:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Wolfram Research/WolframScript/:/mnt/d/Program Files/gmt6/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/mingw64/bin:/mnt/c/texlive/2021/bin/win64:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/dotnet/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/texlive/2022/bin/win32:/mnt/d/Program Files/MATLAB/R2023a/bin:/mnt/c/Users/fomi/AppData/Local/Programs/Python/Python310/Scripts/:/mnt/c/Users/fomi/AppData/Local/Programs/Python/Python310/:/mnt/c/Users/fomi/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/fomi/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/Julia-1.7.3/bin:/mnt/c/Users/fomi/AppData/Local/Pandoc/:/snap/bin
[22:30:41][Extension] $SHELL: /bin/bash
[22:30:41][Extension] $LANG: C.UTF-8
[22:30:41][Extension] $LC_ALL: undefined
[22:30:41][Extension] process.platform: linux
[22:30:41][Extension] process.arch: x64
[22:30:41][Extension] vscode.env.appName: Visual Studio Code
[22:30:41][Extension] vscode.env.remoteName: wsl
[22:30:41][Extension] vscode.env.uiKind: 1
[22:30:41][Extension] LaTeX Workshop initialized.
[22:30:41][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[22:30:41][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[22:30:41][Manager] Current workspace folders: ["file://%WS1%"]
[22:30:41][Manager] Found root file from active editor: %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex
[22:30:42][Manager] Root file changed: from undefined to %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex
[22:30:42][Manager] Start to find all dependencies.
[22:30:42][Manager] Root file languageId: latex
[22:30:42][Event] ROOT_FILE_CHANGED: "%WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex"
[22:30:42][Cacher][Watcher] Reset.
[22:30:42][Cacher] Adding %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex .
[22:30:42][Cacher][Watcher] Watched %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex with a new watcher on %WS1% .
[22:30:42][Event] FILE_WATCHED: "%WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex"
[22:30:42][Cacher] Caching %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex .
[22:30:42][Cacher] Updated inputs of %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex .
[22:30:42][Cacher] Parse LaTeX AST with fast-parse: %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex .
[22:30:42][Event] ROOT_FILE_SEARCHED
[22:30:42][Server] valdOrigin is http://127.0.0.1:33597
[22:30:43][Cacher] Parsed LaTeX AST: %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex .
[22:30:43][DupLabel] Checking for duplicate labels: %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex .
[22:30:43][Cacher] Updated elements of %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex .
[22:30:43][Cacher] Bib %WS1%/VM5aR.bib from %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex .
[22:30:43][Intelli][Citation] Parsing .bib entries from %WS1%/VM5aR.bib
[22:30:43][Intelli][Citation] Parse BibTeX AST from %WS1%/VM5aR.bib .
[22:30:43][Cacher][Watcher] Watched %WS1%/VM5aR.bib with a new watcher on %WS1% .
[22:30:43][Event] FILE_WATCHED: "%WS1%/VM5aR.bib"
[22:30:43][Cacher] Updated bibs of %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex .
[22:30:43][Cacher] Cached %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex .
[22:30:43][Event] FILE_PARSED: "%WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex"
[22:30:43][Cacher][Path] Non-existent .fls for %WS1%/Manuscript-GPS_ICE-6G_D_VM5aR.tex .
[22:30:43][Intelli][Citation] Parsed 90 bib entries from %WS1%/VM5aR.bib .
[22:30:43][Event] FILE_PARSED: "%WS1%/VM5aR.bib"
[22:33:31][Commander] SHOWLOG command invoked: default
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:421  INFO Invoking resolveAuthority(wsl)...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] obtaining proxy...
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] invoking...
default.exp-tas.com/vscode/ab:1          Failed to load resource: net::ERR_CONNECTION_CLOSED
log.ts:421  INFO [LocalProcess0][resolveAuthority(wsl,1)][796ms] returned 127.0.0.1:3511
log.ts:421  INFO resolveAuthority(wsl) returned '127.0.0.1:3511' after 797 ms
log.ts:421  INFO Creating a socket (renderer-Management-82589d60-7fa3-46ee-a944-d91c27919b78)...
log.ts:421  INFO Creating a socket (renderer-ExtensionHost-9903ede7-3a36-45b4-8e61-048f32a04fd0)...
log.ts:421  INFO Creating a socket (renderer-Management-82589d60-7fa3-46ee-a944-d91c27919b78) was successful after 178 ms.
log.ts:421  INFO Creating a socket (renderer-ExtensionHost-9903ede7-3a36-45b4-8e61-048f32a04fd0) was successful after 360 ms.
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///c%3A/Users/fomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/syntax/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///c%3A/Users/fomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/syntax/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///c%3A/Users/fomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/syntax/Bibtex.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///c%3A/Users/fomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/syntax/markdown-latex-combined.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///c%3A/Users/fomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/syntax/cpp-grammar-bailout.tmLanguage.json
register @ TMScopeRegistry.ts:45
log.ts:421  INFO [perf] Render performance baseline is 34ms
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1          Failed to load resource: net::ERR_CONNECTION_CLOSED
vscodeexperiments.azureedge.net/experiments/vscode-experiments.json:1          Failed to load resource: net::ERR_CONNECTION_CLOSED
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'toString')
I @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'toString')
	at addSectionNumber (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:374:52)
	at construct (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:52:18)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async StructureView.build (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:104:34)
	at async StructureView.reconstruct (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:116:26)
I @ console.ts:137
mainThreadExtensionService.ts:80 [James-Yu.latex-workshop]Cannot read properties of undefined (reading 'toString')
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
mainThreadExtensionService.ts:81 TypeError: Cannot read properties of undefined (reading 'toString')
	at addSectionNumber (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:374:52)
	at construct (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:52:18)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async StructureView.build (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:104:34)
	at async StructureView.reconstruct (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:116:26)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'toString')
I @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'toString')
	at addSectionNumber (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:374:52)
	at construct (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:52:18)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async StructureView.build (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:104:34)
	at async StructureView.reconstruct (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:116:26)
I @ console.ts:137
mainThreadExtensionService.ts:80 [James-Yu.latex-workshop]Cannot read properties of undefined (reading 'toString')
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
mainThreadExtensionService.ts:81 TypeError: Cannot read properties of undefined (reading 'toString')
	at addSectionNumber (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:374:52)
	at construct (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:52:18)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async StructureView.build (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:104:34)
	at async StructureView.reconstruct (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:116:26)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
notificationsAlerts.ts:40 TypeError: Cannot read properties of undefined (reading 'toString')
	at addSectionNumber (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:374:52)
	at construct (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:52:18)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async StructureView.build (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:104:34)
	at async StructureView.refresh (/home/fomi/.vscode-server/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:122:26)
	at async y.R (/home/fomi/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:99:65144)
	at async y.getChildren (/home/fomi/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:99:61563)
c @ notificationsAlerts.ts:40
```

## Anything Else?
> _Add any other context about the problem below._
- outline/structure works normally, when the files are directly opened in the Windows.

**Comment by James-Yu** [comment]
Please provide a minimal working example.

**Comment by eqol-fomi** [comment]
```
\documentclass{article}

\usepackage[english]{babel}

\title{Your Paper}
\author{You}

\begin{document}

\section*{A}

\end{document}
```

After testing, I found that the problem occurred when using the commands with * (like \section*{})

I tried to modify latex-workshop.view.outline.sections, add section|*.
The error report disappears but the outline/structure is still blank.
