### ISSUE TITLE
Structure not building for no-number sections 

### ISSUE THREAD

**Issue by wduminy** [James-Yu/LaTeX-Workshop#3904]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: MacOS
- Visual Studio Code Version: 1.78.2 
- LaTeX Workshop Version: v9.11.4
- TeX Distribution Version: TeX Live 2023

## The Issue*
The outline/structure does not render

### Reproduction Steps
Try this example.  Remove the `*` then it works as expected.
```
\documentclass{article}
\begin{document}
\section*{About the world}
\end{document}
```

## Logs
```
2023-05-29 14:52:27.494 [error] TypeError: Cannot read properties of undefined (reading 'toString')
	at addSectionNumber ([snipped]/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:374:52)
	at construct ([snipped]/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:52:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async StructureView.build ([snipped]/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:104:34)
	at async StructureView.reconstruct ([snipped]/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:116:26)
```

**Comment by James-Yu** [comment]
#3897
