### ISSUE TITLE
Citation hover, browser, etc. broken with `\DeclareMathOperator` + `\mathbb`

### ISSUE THREAD

**Issue by YDX-2147483647** [James-Yu/LaTeX-Workshop#3957]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*

> _Please change the following `[ ]` to `[x]` for confirmation._

- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code. (Note: except the language pack)
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*

> _Please write exact version numbers instead of descriptors such as `latest`._

- Operating System: Windows 10
- Visual Studio Code Version: 1.80.0
- LaTeX Workshop Version: 9.12.2
- TeX Distribution Version: TeX Live 2023

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._

(nothing)

## The Issue*

> _Please briefly describe the issue you come across._

- If I `\DeclareMathOperator` with `\mathbb`, then command _LaTeX Workshop: Open citation browser_ will be empty.
- Also, hovering on `\cite{…}` won't show anything.

_Note_: If I remove `\DeclareMathOperator` and build again, then citation browser and hovering work fine. However if I add it back and build one more time, then citation browser becomes empty but the hovering still works.

### Reproduction Steps

> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._

1. `main.tex`

   ```latex
   \documentclass{book}
   \title{Notes}
   \author{me}
   
   \usepackage{biblatex}
   
   \addbibresource{simple.bib}
   
   \usepackage{amsopn}
   \DeclareMathOperator*{\whatever}{\mathbb{E}}
   
   \begin{document}
   \cite{Macdonald2022Jun}
   \end{document}
   ```

2. `simple.bib`

   ```latex
   @article{Macdonald2022Jun,
     author    = {Macdonald, Lewis and Taylor, Gillian C. and Brisbane, Jennifer Margaret and Christodoulou, Ersi and Scott, Lucy and von Kriegsheim, Alex and Rossant, Janet and Gu, Bin and Wood, Andrew J.},
     title     = {{Rapid and specific degradation of endogenous proteins in mouse models using auxin-inducible degrons}},
     journal   = {eLife},
     year      = {2022},
     month     = jun,
     publisher = {eLife Sciences Publications, Ltd},
     url       = {https://elifesciences.org/articles/77987#content},
     doi       = {10.7554/eLife.77987},
   }
   ```

3. Build.

4. Hover on `\cite{Macdonald2022Jun}`, nothing happens.

5. <kbd>F1</kbd>, *LaTeX Workshop: Open citation browser*. It says “Press ENTER to insert citation key at cursor”, but nothing is available.

### Expected Behavior

> _What were you expecting to see? Include any relevant examples or documentation links._

- Citation browser and hover works with `\DeclareMathOperator*{\whatever}{\mathbb{E}}`.

### LaTeX Workshop Output*

> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._

```
[17:28:39.241][Logger] New log placeholder %WS1% registered for d:\DevelopProjects\temp\test-citation .
[17:28:39.241][Config] latex-workshop.latex.recipes: [{"name":"latexmk 🔃","tools":["latexmk"]},{"name":"SVG 🎨","tools":["latexmk-no-pdf","dvisvgm"]}] .
[17:28:39.330][Config] latex-workshop.latex.recipe.default: "lastUsed" .
[17:28:39.332][Config] latex-workshop.latex.tools: [{"name":"latexmk","command":"latexmk","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","-xelatex","-shell-escape","-outdir=%OUTDIR%","-cd","%DOC%"],"env":{}},{"name":"latexmk-no-pdf","command":"latexmk","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","-xelatex","-shell-escape","-outdir=%OUTDIR%","-cd","-pdf-","%DOC%"],"env":{}},{"name":"dvisvgm","command":"dvisvgm","args":["--font-format=woff","%DOC%.dvi","--output=%DOC%.svg"]}] .
[17:28:39.351][Config] latex-workshop.latex.autoBuild.run: "onSave" .
[17:28:39.393][Config] latex-workshop.synctex.afterBuild.enabled: true .
[17:28:39.444][Config] latex-workshop.message.warning.show: false .
[17:28:39.445][Config] latex-workshop.message.error.show: false .
[17:28:39.466][Config] latex-workshop.bibtex-format.trailingComma: true .
[17:28:39.470][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[17:28:39.965][Server] Creating LaTeX Workshop http and websocket server.
[17:28:40.109][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":59922} .
[17:28:40.115][Extension] Initializing LaTeX Workshop.
[17:28:40.116][Extension] Extension root: c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2
[17:28:40.116][Extension] $PATH: C:\Program Files\PowerShell\7;C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\mingw-w64\x86_64-8.1.0-release-posix-seh-rt_v6-rev0\mingw64\bin;C:\Program Files\Wolfram Research\WolframScript\;C:\Program Files\dotnet\;C:\Program Files\opencv\build\x64\vc15\bin;C:\Program Files\opencv\build\x64\mingw\bin;C:\Program Files\MATLAB\R2020b\bin;C:\Users\bjalp\AppData\Roaming\Python\Python310\Scripts;D:\ProgramFiles\Neovim\bin;D:\ProgramFiles\nvm;D:\ProgramFiles\nodejs;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;D:\ProgramFiles\Gpg4win\..\GnuPG\bin;C:\Program Files\Pandoc\;C:\Program Files\Go\bin;C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\Program Files\PowerShell\7\;C:\Users\bjalp\scoop\apps\gsudo\current;C:\Users\bjalp\AppData\Local\pnpm;C:\Users\bjalp\scoop\shims;D:\ProgramFiles\Ruby31-x64\bin;C:\Users\bjalp\.cargo\bin;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Users\bjalp\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\Users\bjalp\.dotnet\tools;C:\Users\bjalp\AppData\Roaming\Python\Scripts;C:\Users\bjalp\AppData\Roaming\Pub\Cache\bin;D:\ProgramFiles\nvm;D:\ProgramHome\go\bin;c:\users\bjalp\.local\bin;D:\ProgramFiles\Fiddler;C:\Users\bjalp\go\bin;D:\ProgramFiles\texlive\2023\bin\windows;D:\ProgramFiles\Neovim\bin;D:\ProgramFiles\nvm;D:\ProgramFiles\nodejs;C:\Users\bjalp\go\bin;C:\Users\bjalp\go\bin
[17:28:40.117][Extension] $SHELL: undefined
[17:28:40.117][Extension] $LANG: zh_CN.UTF-8
[17:28:40.118][Extension] $LC_ALL: undefined
[17:28:40.118][Extension] process.platform: win32
[17:28:40.119][Extension] process.arch: x64
[17:28:40.119][Extension] vscode.env.appName: Visual Studio Code
[17:28:40.120][Extension] vscode.env.remoteName: undefined
[17:28:40.120][Extension] vscode.env.uiKind: 1
[17:28:40.121][Extension] LaTeX Workshop initialized.
[17:28:40.129][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":true,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[17:28:40.134][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[17:28:40.139][Manager] Current workspace folders: ["file:///d:/DevelopProjects/temp/test-citation"]
[17:28:40.140][Manager] Found root file from active editor: %WS1%\main.tex
[17:28:40.141][Manager] Root file changed: from undefined to %WS1%\main.tex
[17:28:40.142][Manager] Start to find all dependencies.
[17:28:40.143][Manager] Root file languageId: latex
[17:28:40.144][Event] ROOT_FILE_CHANGED: "d:\\DevelopProjects\\temp\\test-citation\\main.tex"
[17:28:40.146][Cacher][Watcher] Reset.
[17:28:40.159][Cacher] Adding %WS1%\main.tex .
[17:28:40.162][Cacher][Watcher] Watched %WS1%\main.tex with a new watcher on %WS1% .
[17:28:40.164][Event] FILE_WATCHED: "d:\\DevelopProjects\\temp\\test-citation\\main.tex"
[17:28:40.176][Cacher] Caching %WS1%\main.tex .
[17:28:40.178][Cacher] Updated inputs of %WS1%\main.tex .
[17:28:40.179][Cacher] Parse LaTeX AST: %WS1%\main.tex .
[17:28:40.179][Event] ROOT_FILE_SEARCHED
[17:28:40.223][Server] valdOrigin is http://127.0.0.1:59922
[17:28:40.280][Cacher] Parsed LaTeX AST: %WS1%\main.tex .
[17:28:40.284][Event] FILE_PARSED: "d:\\DevelopProjects\\temp\\test-citation\\main.tex"
[17:28:40.293][Structure] Structure force updated with 0 root sections for %WS1%\main.tex .
[17:28:40.294][Event] STRUCTURE_UPDATED
[17:28:49.874][Commander] CITATION command invoked.
```

### Developer Tools Console

> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._

Here are the errors.

```javascript
[James-Yu.latex-workshop]Cannot read properties of undefined (reading 'content')
$onExtensionRuntimeError @ workbench.desktop.main.js:1962
workbench.desktop.main.js:1962 TypeError: Cannot read properties of undefined (reading 'content')
	at Command.parseAst (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\providers\completer\command.js:192:31)
	at Command.parseAst (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\providers\completer\command.js:224:42)
	at Command.parse (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\providers\completer\command.js:176:43)
	at Cacher.updateElements (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\components\cacher.js:207:30)
	at c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\components\cacher.js:131:18
$onExtensionRuntimeError @ workbench.desktop.main.js:1962
```

The following is the full log

```javascript
workbench.desktop.main.js:sourcemap:1842 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/bjalp/.vscode/extensions/james-yu.latex-workshop-9.12.2/syntax/TeX.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1842
workbench.desktop.main.js:sourcemap:1842 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/bjalp/.vscode/extensions/james-yu.latex-workshop-9.12.2/syntax/LaTeX.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1842
workbench.desktop.main.js:sourcemap:1842 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///c%3A/Users/bjalp/.vscode/extensions/james-yu.latex-workshop-9.12.2/syntax/Bibtex.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1842
workbench.desktop.main.js:sourcemap:1842 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///c%3A/Users/bjalp/.vscode/extensions/james-yu.latex-workshop-9.12.2/syntax/markdown-latex-combined.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1842
workbench.desktop.main.js:sourcemap:1842 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///c%3A/Users/bjalp/.vscode/extensions/james-yu.latex-workshop-9.12.2/syntax/cpp-grammar-bailout.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1842
workbench.desktop.main.js:sourcemap:131 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'content')
v @ workbench.desktop.main.js:sourcemap:131
workbench.desktop.main.js:sourcemap:131 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'content')
	at Command.parseAst (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\providers\completer\command.js:192:31)
	at Command.parseAst (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\providers\completer\command.js:224:42)
	at Command.parse (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\providers\completer\command.js:176:43)
	at Cacher.updateElements (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\components\cacher.js:207:30)
	at c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\components\cacher.js:131:18
v @ workbench.desktop.main.js:sourcemap:131
workbench.desktop.main.js:sourcemap:1962 [James-Yu.latex-workshop]Cannot read properties of undefined (reading 'content')
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:1962
workbench.desktop.main.js:sourcemap:1962 TypeError: Cannot read properties of undefined (reading 'content')
	at Command.parseAst (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\providers\completer\command.js:192:31)
	at Command.parseAst (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\providers\completer\command.js:224:42)
	at Command.parse (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\providers\completer\command.js:176:43)
	at Cacher.updateElements (c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\components\cacher.js:207:30)
	at c:\Users\bjalp\.vscode\extensions\james-yu.latex-workshop-9.12.2\out\src\components\cacher.js:131:18
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:1962
workbench.desktop.main.js:sourcemap:627  INFO [perf] Render performance baseline is 154ms
```

## Anything Else?

> _Add any other context about the problem below._

I have a temporary workaround: Add a pair of bracket to `\mathbb{E}`.

```latex
\DeclareMathOperator*{\whatever}{{\mathbb{E}}}
```

Besides, the MWE is from #3346.

**Comment by James-Yu** [comment]
This bug was fixed in a previous commit.

<img width="345" alt="Screenshot 2023-07-07 at 21 17 04" src="https://github.com/James-Yu/LaTeX-Workshop/assets/4210342/69dd77d3-c4ca-45bc-bdd8-51ae4e981b0d">

**Comment by YDX-2147483647** [comment]
Thanks for your quick response! I'll wait for the next release.
