### ISSUE TITLE
Build not terminated in force mode

### ISSUE THREAD

**Issue by modaresimr** [James-Yu/LaTeX-Workshop#4000]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [e.g. Windows 10]: linux
- Visual Studio Code Version: [e.g. 1.41.0]: 1.80.2
- LaTeX Workshop Version: [e.g. 8.5.0]: 9.13.4
- TeX Distribution Version: [e.g. TeX Live 2019 / MiKTeX 2.9.7250]: 

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ
Visual Studio Code v4.16.1
## The Issue*
> _Please briefly describe the issue you come across._
The problem is that whenever the latex workshop encountered with an error, the icon on the status bar is showing building (even it is not running) and even the terminate current build process won't work.
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/9498182/14fc0894-c70c-40e9-acf3-15453ba086a6)

```
[13:33:08.375][Commander] KILL command invoked.
[13:33:08.376][Builder] Kill child processes of the current process with PID 50379.
[13:33:08.397][Builder] Failed killing child processes of the current process. Error: Command failed: pkill -P 50379
[13:33:08.398]Error: Command failed: pkill -P 50379
	at checkExecSyncError (node:child_process:826:11)
	at Object.execSync (node:child_process:900:15)
	at Builder.kill (/config/extensions/james-yu.latex-workshop-9.13.3-universal/out/src/components/builder.js:80:20)
	at Object.kill (/config/extensions/james-yu.latex-workshop-9.13.3-universal/out/src/commander.js:144:16)
	at /config/extensions/james-yu.latex-workshop-9.13.3-universal/out/src/main.js:135:865
	at e.$wL.h (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:99:64085)
	at e.$wL.$executeContributedCommand (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:99:64959)
	at t.N (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:111:11199)
	at t.M (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:111:10965)
	at t.H (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:111:10046)
	at t.G (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:111:9122)
	at i.value (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:111:7952)
	at v.w (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at v.fire (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at fire (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:13931)
	at i.value (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:127:30923)
	at v.w (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at v.fire (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at fire (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:13931)
	at s.z (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:16976)
	at i.value (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:15428)
	at v.w (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at v.fire (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at i.acceptChunk (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:11705)
	at i.value (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:10992)
	at v.w (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at v.fire (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at v.u (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:127:19064)
[13:33:08.399][Builder] Killed the current process with PID 50379

```

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. add "-f" in latexmk argument
2. have an error in latex file
3.  build

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- It should finish building in any case when there is an error

**Comment by modaresimr** [comment]
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/9498182/b8f752e7-7e61-4a0d-8a4f-d0fd61f3ef3a)

The problem also exist in vscode windows

**Comment by modaresimr** [comment]
The error happens with:
```
[James-Yu.latex-workshop]message must be set
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
w @ event.ts:1088
fire @ event.ts:1119
fire @ ipc.net.ts:650
z @ ipc.net.ts:1015
(anonymous) @ ipc.net.ts:875
w @ event.ts:1088
fire @ event.ts:1119
acceptChunk @ ipc.net.ts:394
(anonymous) @ ipc.net.ts:350
(anonymous) @ browserSocketFactory.ts:230
w @ event.ts:1088
fire @ event.ts:1119
i.onload @ browserSocketFactory.ts:91
mainThreadExtensionService.ts:82  TypeError: message must be set
	at new e.$pJ (/app/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:95:15446)
	at showCompilerDiagnostics (/config/extensions/james-yu.latex-workshop-9.13.4-universal/out/src/components/parserlib/parserutils.js:74:22)
	at Object.showLog (/config/extensions/james-yu.latex-workshop-9.13.4-universal/out/src/components/parserlib/bibtexlog.js:45:47)
	at Object.parseLog (/config/extensions/james-yu.latex-workshop-9.13.4-universal/out/src/components/parser.js:82:37)
	at ChildProcess.<anonymous> (/config/extensions/james-yu.latex-workshop-9.13.4-universal/out/src/components/builder.js:337:51)
	at ChildProcess.emit (node:events:390:28)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
w @ event.ts:1088
fire @ event.ts:1119
fire @ ipc.net.ts:650
z @ ipc.net.ts:1015
(anonymous) @ ipc.net.ts:875
w @ event.ts:1088
fire @ event.ts:1119
acceptChunk @ ipc.net.ts:394
(anonymous) @ ipc.net.ts:350
(anonymous) @ browserSocketFactory.ts:230
w @ event.ts:1088
fire @ event.ts:1119
i.onload @ browserSocketFactory.ts:91
```


after i add try catch in `parser.js` file the problem seems to be resolved

**Comment by James-Yu** [comment]
Finally got some time to look into this issue.

Your issue is because that the extension relies on os level `pkill` or `taskkill` to terminate latex processes, which may fail due to reasons beyond the control of this extension. On this issue, we cannot do more than what os provides.

For the status bar icon. It gets updates when os tells the extension that the latex process is terminated/killed/returned, which obviously is not this case. I thought of change the icon on failed termination, but that will cause bigger problem as there are orphaned latex process leftover without any visual indicator to users.

Please comment if you have any suggestions on how this may be resolved under the limit of os.
