### ISSUE TITLE
encounter ENOENT error but xelatex.exe do exists in $Path

### ISSUE THREAD

**Issue by Orrinn** [James-Yu/LaTeX-Workshop#4013]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ ] The issue has not been reported in this repository.
- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [*] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ ] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 11
- Visual Studio Code Version: 1.81.1
- LaTeX Workshop Version: 9.13.4
- TeX Distribution Version: Tex Live 2022

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- just under the windows 11 enviroment.

## The Issue*
> _Please briefly describe the issue you come across._
- cannot compile the .tex file, but I do confirm that xelatex exists in $Path

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. write a .tex file
2. compile

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[19:07:02.067][Commander] Building root file: %WS1%\sample-sigplan.tex
[19:07:02.067][Builder] Build root file %WS1%\sample-sigplan.tex
[19:07:02.069][Builder] outDir: %WS1%\output .
[19:07:02.070][Builder] Preparing to run recipe: xe->bib->xe->xe.
[19:07:02.070][Builder] Prepared 4 tools.
[19:07:07.874][Builder] LaTeX fatal error on PID 27264. Error: spawn xelatex -output-directory=./output ENOENT
[19:07:07.874]Error: spawn xelatex -output-directory=./output ENOENT
    at notFoundError (c:\Users\jiang\.vscode\extensions\james-yu.latex-workshop-9.13.4\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (c:\Users\jiang\.vscode\extensions\james-yu.latex-workshop-9.13.4\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (c:\Users\jiang\.vscode\extensions\james-yu.latex-workshop-9.13.4\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
[19:07:07.874][Builder] Does the executable exist? $PATH: undefined, $Path: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\texlive\2022\bin\win32;C:\Program Files\MATLAB\R2022b\runtime\win64;C:\Program Files\MATLAB\R2022b\bin;C:\Users\jiang\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\jiang\AppData\Local\Programs\Python\Python37-32\;C:\Users\jiang\AppData\Local\Microsoft\WindowsApps;C:\texlive\2022\bin\win32;, $SHELL: undefined
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
workbench.desktop.main.js:1846 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/jiang/.vscode/extensions/james-yu.latex-workshop-9.13.4/syntax/TeX.tmLanguage.json
register @ workbench.desktop.main.js:1846
workbench.desktop.main.js:1846 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/jiang/.vscode/extensions/james-yu.latex-workshop-9.13.4/syntax/LaTeX.tmLanguage.json
register @ workbench.desktop.main.js:1846
workbench.desktop.main.js:1846 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///c%3A/Users/jiang/.vscode/extensions/james-yu.latex-workshop-9.13.4/syntax/Bibtex.tmLanguage.json
register @ workbench.desktop.main.js:1846
workbench.desktop.main.js:1846 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///c%3A/Users/jiang/.vscode/extensions/james-yu.latex-workshop-9.13.4/syntax/markdown-latex-combined.tmLanguage.json
register @ workbench.desktop.main.js:1846
workbench.desktop.main.js:1846 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///c%3A/Users/jiang/.vscode/extensions/james-yu.latex-workshop-9.13.4/syntax/cpp-grammar-bailout.tmLanguage.json
register @ workbench.desktop.main.js:1846
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/jiang/.vscode/extensions/james-yu.latex-workshop-9.13.4/syntax/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/jiang/.vscode/extensions/james-yu.latex-workshop-9.13.4/syntax/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///c%3A/Users/jiang/.vscode/extensions/james-yu.latex-workshop-9.13.4/syntax/Bibtex.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///c%3A/Users/jiang/.vscode/extensions/james-yu.latex-workshop-9.13.4/syntax/markdown-latex-combined.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///c%3A/Users/jiang/.vscode/extensions/james-yu.latex-workshop-9.13.4/syntax/cpp-grammar-bailout.tmLanguage.json
register @ TMScopeRegistry.ts:46
workbench.desktop.main.js:129 [Extension Host] Initializing tunnel extension
workbench.desktop.main.js:627  INFO [perf] Render performance baseline is 22ms
workbench.desktop.main.js:762 Recipe terminated with fatal error: spawn xelatex -output-directory=./output ENOENT.
c @ workbench.desktop.main.js:762
4workbench.desktop.main.js:627  WARN Settings pattern "application.*" doesn't match any settings
```

## Anything Else?
> _Add any other context about the problem below._
- using xelatex --version in Power shell can get the correct output:
```
PS C:\Users\jiang> xelatex --version
XeTeX 3.141592653-2.6-0.999994 (TeX Live 2022)
kpathsea version 6.3.4
Copyright 2022 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 70.1; using 70.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.11.1; using 2.11.1
Compiled with Graphite2 version 1.3.14; using 1.3.14
Compiled with HarfBuzz version 3.4.0; using 3.4.0
Compiled with libpng version 1.6.37; using 1.6.37
Compiled with pplib version v2.05 less toxic i hope
Compiled with fontconfig version 2.13.96; using 2.13.96
```
it there any way to solve this problem?

**Comment by James-Yu** [comment]
Please search the past issues.
