### ISSUE TITLE
[Bug] Can't show the preview window

### ISSUE THREAD

**Issue by unprintable123** [James-Yu/LaTeX-Workshop#4026]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System:  Windows 11
- Visual Studio Code Version: 1.82.2
- LaTeX Workshop Version: 9.14.0
- TeX Distribution Version:  TeX Live 2021

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._

## The Issue*
> _Please briefly describe the issue you come across._
- Can't show the preview of code

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Create a file with the following code,
```latex
\documentclass{article}

\newcommand{\itembegin}{\begin{itemize}
}

\newcommand{\itemend}{\end{itemize}
}


\begin{document}

$111$

\itembegin
\item 123
\itemend

\end{document}
```
It can be correctly compiled.
2. when you hover at `111` it won't show the preview

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- code be correctly previewed.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[20:08:56.788][Preview][Math] Failed rendering MathJax 
\newcommand{\itembegin}{\begin{itemize}\newcommand{\itemend}{\end{itemize}111 . Error: Missing close brace
[20:08:56.789]Error: Missing close brace
    at Object.formatError (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\out\src\providers\preview\mathjaxpool_worker.js:39:47)
    at TeX.compile (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\input\tex.js:127:33)
    at AbstractMathItem.compile (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\core\MathItem.js:56:39)
    at Object.renderMath (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\core\MathDocument.js:119:65)
    at RenderList.renderConvert (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\core\MathDocument.js:171:35)
    at AbstractMathItem.convert (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\core\MathItem.js:52:32)
    at AbstractMathDocument.convert (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\core\MathDocument.js:329:15)
    at Function.typeset (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\out\src\providers\preview\mathjaxpool_worker.js:58:23)
    at process.<anonymous> (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\workerpool\src\worker.js:157:27)
    at process.emit (node:events:513:28)
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
 ERR Missing close brace: Error: Missing close brace
    at Object.formatError (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\out\src\providers\preview\mathjaxpool_worker.js:39:47)
    at TeX.compile (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\input\tex.js:127:33)
    at AbstractMathItem.compile (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\core\MathItem.js:56:39)
    at Object.renderMath (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\core\MathDocument.js:119:65)
    at RenderList.renderConvert (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\core\MathDocument.js:171:35)
    at AbstractMathItem.convert (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\core\MathItem.js:52:32)
    at AbstractMathDocument.convert (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\mathjax-full\js\core\MathDocument.js:329:15)
    at Function.typeset (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\out\src\providers\preview\mathjaxpool_worker.js:58:23)
    at process.<anonymous> (c:\Users\123\.vscode\extensions\james-yu.latex-workshop-9.14.0\node_modules\workerpool\src\worker.js:157:27)
    at process.emit (node:events:513:28)
```

## Anything Else?
> _Add any other context about the problem below._
- It seems that both close brace at the new line are ignored. To trigger this bug `\begin` or `\end` is needed.
- The following code also has this bug,
```latex
\documentclass{article}

\newcommand{\itemaaa}{\begin{itemize}\item 111
\end{itemize}}


\begin{document}

$111$

\itemaaa

\end{document}
```
with log `\newcommand{\itemaaa}{\begin{itemize}111 . Error: Missing close brace`

**Comment by unprintable123** [comment]
https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#hover-preview-fails-to-render-math-equation-with-errors

**Comment by TamotsuTokazu** [comment]
Actually, I think this is still a bug, or at least, it's a feature removed. The reason is that the `\newcommand` contains multiple lines and thus the regex failed.
