### ISSUE TITLE
Build command fails because VSCode cannot make subdirectories

### ISSUE THREAD

**Issue by phdcybersec** [James-Yu/LaTeX-Workshop#4048]
## Pre-checks

- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment

- Operating System: MacOS Sonoma 14.1 (23B73)
- Visual Studio Code Version: 1.81.1
- LaTeX Workshop Version: v9.14.1
- TeX Distribution Version: TeX 3.141592653 (TeX Live 2022/nixos.org)

## The Issue

- I am using a custom build command that uses Nix ([nixos.org](https://nixos.org)) to enable full reproducibility of my builds. 
- Builds are actually run by a daemon and the build output is symlinked to the current directory as `./result/...`. 
- The build outputs are not own by the current user, and therefore one cannot write files or create directories in the `./result/` symlink.
- I defined `./result` as output directory with `"latex-workshop.latex.outDir": "%WORKSPACE_FOLDER%/result"` so that the PDF created inside it is recognized.
- On build, the LaTeX-Workshop first creates `%OUTDIR%` **and subfolders** if they don't exist (see [source](https://github.com/James-Yu/LaTeX-Workshop/blob/dac0ee527ce0241f295ae74ebf38b89c7d1b5a41/src/components/builder.ts#L669)), which fails in my case with an expected "permission denied" error.

### Reproduction Steps

1. Install Nix,
2. Make a derivation to build a LaTeX document (I can provide one if needed, but the problem seems quite staightforward).
3. Setup LaTeX-Workshop to use `nix build`
4. Run "build latex"

### Expected Behavior

Either:
- the ability to disable folder creation;
- the ability to point the viewer to the correct PDF (with auto reload) without setting `%OUTDIR%`;
- anything else?

### LaTeX Workshop Output

```
[17:02:38.934][Event] STRUCTURE_UPDATED
[17:02:40.728][Extension] onDidSaveTextDocument triggered: file://%WS1%/src/document.tex
[17:02:40.728][Builder] Auto build started on saving file: %WS1%/src/document.tex .
[17:02:40.728][Event] AUTO_BUILD_INITIATED: {"type":"onSave","file":"%WS1%/src/document.tex"}
[17:02:40.728][Commander] BUILD command invoked.
[17:02:40.729][Commander] The document of the active editor: file://%WS1%/src/document.tex
[17:02:40.729][Commander] The languageId of the document: latex
[17:02:40.729][Commander] Building root file: %WS1%/src/document.tex
[17:02:40.729][Builder] Build root file %WS1%/src/document.tex
[17:02:40.730][Builder] outDir: %WS1%/result .
[17:02:40.730][Builder] Unexpected Error: please see the console log of the Developer Tools of VS Code.
```

### Developer Tools Console

```
Error: EACCES: permission denied, mkdir '/Users/leo/Workspace/imta/demo-paper/result/resources'
    at Object.mkdirSync (node:fs:1388:3)
    at /Users/leo/.vscode/extensions/james-yu.latex-workshop-9.14.1/out/src/components/builder.js:660:24
    at Array.forEach (<anonymous>)
    at Builder.createOuputSubFolders (/Users/leo/.vscode/extensions/james-yu.latex-workshop-9.14.1/out/src/components/builder.js:654:48)
    at Builder.build (/Users/leo/.vscode/extensions/james-yu.latex-workshop-9.14.1/out/src/components/builder.js:174:14)
    at Object.build (/Users/leo/.vscode/extensions/james-yu.latex-workshop-9.14.1/out/src/commander.js:68:5)
```

**Comment by phdcybersec** [comment]
Weirdly enough, using the `"latex-workshop.latex.external.build.*"` settings seems to bypass (?) the subfolder creation, whereas the recipe system does not. This will work in my case for now, but the issue is still relevant.

**Comment by James-Yu** [comment]
The extension cannot elevate itself beyond vscode's permission. I'm afraid there is nothing can be done from the extension side.

**Comment by James-Yu** [comment]
I don't think your log says everything. Why there is a subfolder called "resources" inside "result"?

**Comment by phdcybersec** [comment]
Sorry for the downtime. The `resources` subfolder is actually inside the `src` folder, in which I have my LaTeX file. What happens (from what I understand) is that the extension tries to recursively create folders in the output directory according to the ones in `src`. Since the `results` directory is owned by root, it cannot. However, I fail to understand why the extension would need to create folders *recursively*?

**Comment by James-Yu** [comment]
I see your use case. I do think I have a more elegant solution to the problem. Pending.

**Comment by phdcybersec** [comment]
Great! Thank you very much!
