### ISSUE TITLE
Hover over equation does not show preview. Vol. 2.

### ISSUE THREAD

**Issue by davidzanger** [James-Yu/LaTeX-Workshop#4105]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: Windows 10
- Visual Studio Code Version: 1.85.1
- LaTeX Workshop Version: 9.16.1
- TeX Distribution Version: MikTex 23.5

## The Issue

When hovering over a equation it does not show a preview anymore. 

### Reproduction Steps
This is my main.tex:

```latex
\documentclass[a4paper]{scrbook}

\usepackage{amsmath}

\begin{document}

% From: https://tex.stackexchange.com/questions/2705/typesetting-column-vector
\newcount\colveccount
\newcommand*\colvec[1]{
\global\colveccount#1
    \begin{pmatrix}
        \colvecnext
        }
\def\colvecnext#1{
#1
        \global\advance\colveccount-1
        \ifnum\colveccount>0
        \\
        \expandafter\colvecnext
        \else
    \end{pmatrix}
    \fi
}

\begin{equation}
    \colvec{5}{a}{b}{c}{d}{e}
\end{equation}

\end{document}

```

### LaTeX Workshop Output*

```
[10:51:45.904][Logger] New log placeholder %WS1% registered for c:\Users\zang_da\Documents\programming\trial_document .
[10:51:45.904][Extension] Initializing LaTeX Workshop.
[10:51:46.207][Build][Recipe] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[10:51:46.328][Server] Creating LaTeX Workshop http and websocket server.
[10:51:46.457][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[10:51:46.552][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":57533} .
[10:51:46.566][Extension] Extension root: c:\Users\zang_da\.vscode\extensions\james-yu.latex-workshop-9.16.1
[10:51:46.567][Extension] $SHELL: undefined
[10:51:46.567][Extension] $LANG: undefined
[10:51:46.567][Extension] $LC_ALL: undefined
[10:51:46.568][Extension] process.platform: win32
[10:51:46.568][Extension] process.arch: x64
[10:51:46.569][Extension] vscode.env.appName: Visual Studio Code
[10:51:46.569][Extension] vscode.env.remoteName: undefined
[10:51:46.569][Extension] vscode.env.uiKind: 1
[10:51:46.656][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[10:51:46.659][Root] Current workspace folders: ["file:///c:/Users/zang_da/Documents/programming/trial_document"]
[10:51:46.660][Extension] LaTeX Workshop initialized.
[10:51:46.662][Root] Found root file from active editor: %WS1%\main.tex
[10:51:46.662][Root] Root file changed: from %WS1%\main.tex to %WS1%\main.tex, langID latex . Refresh dependencies
[10:51:46.662][Event] ROOT_FILE_CHANGED: "c:\\Users\\zang_da\\Documents\\programming\\trial_document\\main.tex"
[10:51:46.663][Cacher][Watcher] Reset.
[10:51:46.663][Cacher][Watcher] Reset.
[10:51:46.664][Cacher][Watcher] Reset.
[10:51:46.668][Cacher] Adding %WS1%\main.tex .
[10:51:46.669][Cacher][Watcher] Watched %WS1%\main.tex with a new watcher on %WS1% .
[10:51:46.669][Event] FILE_WATCHED: "c:\\Users\\zang_da\\Documents\\programming\\trial_document\\main.tex"
[10:51:46.671][Cacher] Caching %WS1%\main.tex .
[10:51:46.672][Cacher] Updated inputs of %WS1%\main.tex .
[10:51:46.672][Cacher] Parse LaTeX AST: %WS1%\main.tex .
[10:51:46.672][Event] ROOT_FILE_SEARCHED
[10:51:46.687][Server] valdOrigin is http://127.0.0.1:57533
[10:51:46.761][Cacher] Parsed LaTeX AST: %WS1%\main.tex .
[10:51:46.762][File] Calling kpsewhich to resolve scrbook.cls .
[10:51:47.600][Cacher] Updated elements in 838.53 ms: %WS1%\main.tex .
[10:51:47.601][Event] FILE_PARSED: "c:\\Users\\zang_da\\Documents\\programming\\trial_document\\main.tex"
[10:51:47.604][Cacher] Parsing .fls %WS1%\main.fls .
[10:51:47.611][Cacher] Found .aux %WS1%\main.tex from .fls %WS1%\main.fls , parsing.
[10:51:47.612][Cacher] Parsed .aux %WS1%\main.tex .
[10:51:47.612][Cacher] Parsed .fls %WS1%\main.fls .
[10:51:47.613][Structure] Structure force updated with 0 root sections for %WS1%\main.tex .
[10:51:47.614][Event] STRUCTURE_UPDATED
[10:51:53.309][Preview][Math] Failed rendering MathJax \newcommand{\Trial}{\mathrm{trial}}
\newcommand*\colvec[1]{
\global\colveccount#1
    \begin{pmatrix}
        \colvecnext
        }
\begin{equation}
    \colvec{5}{a}{b}{c}{d}{e}
\end{equation} . Error: You can't use 'macro parameter character #' in math mode
[10:51:53.310]Error: You can't use 'macro parameter character #' in math mode
    at Object.formatError (c:\Users\zang_da\.vscode\extensions\james-yu.latex-workshop-9.16.1\out\src\preview\math\mathjax.js:39:47)
    at TeX.compile (c:\Users\zang_da\.vscode\extensions\james-yu.latex-workshop-9.16.1\node_modules\mathjax-full\js\input\tex.js:127:33)
    at AbstractMathItem.compile (c:\Users\zang_da\.vscode\extensions\james-yu.latex-workshop-9.16.1\node_modules\mathjax-full\js\core\MathItem.js:56:39)
    at Object.renderMath (c:\Users\zang_da\.vscode\extensions\james-yu.latex-workshop-9.16.1\node_modules\mathjax-full\js\core\MathDocument.js:119:65)
    at RenderList.renderConvert (c:\Users\zang_da\.vscode\extensions\james-yu.latex-workshop-9.16.1\node_modules\mathjax-full\js\core\MathDocument.js:171:35)
    at AbstractMathItem.convert (c:\Users\zang_da\.vscode\extensions\james-yu.latex-workshop-9.16.1\node_modules\mathjax-full\js\core\MathItem.js:52:32)
    at AbstractMathDocument.convert (c:\Users\zang_da\.vscode\extensions\james-yu.latex-workshop-9.16.1\node_modules\mathjax-full\js\core\MathDocument.js:329:15)
    at Function.typeset (c:\Users\zang_da\.vscode\extensions\james-yu.latex-workshop-9.16.1\out\src\preview\math\mathjax.js:58:23)
    at process.<anonymous> (c:\Users\zang_da\.vscode\extensions\james-yu.latex-workshop-9.16.1\node_modules\workerpool\src\worker.js:150:27)
    at process.emit (node:events:513:28)
```

**Comment by James-Yu** [comment]
I wonder if this new command can correctly render with previous versions?

**Comment by James-Yu** [comment]
From the log you may see that it is MathJaX which cannot handle this type of macro. This retry commit is the best thing we can do from the extension side.

**Comment by davidzanger** [comment]
> I wonder if this new command can correctly render with previous versions?

I tried other older versions but it never seemed to work. However, as long as all other formulas render I am satisfied. Thank you very much!
