### ISSUE TITLE
File found error when viewing pdf file

### ISSUE THREAD

**Issue by jsrdcht** [James-Yu/LaTeX-Workshop#4125]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: MAC OS 14
- Visual Studio Code Version: 1.85.1
- LaTeX Workshop Version: v9.17.0
- TeX Distribution Version: TeX 3.141592653 (TeX Live 2022) kpathsea version 6.3.4

## The Issue*
> _Please briefly describe the issue you come across._
When I click on any of the sub-items under "view PDF", nothing happens. So I checked the output of the LaTeX workshop and it seems like the program cannot find the correct path for the PDF.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._

Click on any sub-item of the "view latex PDF" of the "latex workshop" extension on the left sidebar, such as clicking on "view in vscode tab".

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._

I expect that when I click "view pdf," the program can correctly pop up a preview window.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% 

registered`._
```
[19:15:16.879][Logger] New log placeholder %WS1% registered for /Users/chentuo/Seafile/main-repo/AcademicRepo/latex/FormattingGuidelines-IJCAI-23 .
[19:15:16.879][Extension] Initializing LaTeX Workshop.
[19:15:16.982][Build][Recipe] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[19:15:17.027][Server] Creating LaTeX Workshop http and websocket server.
[19:15:17.145][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[19:15:17.170][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":58914} .
[19:15:17.175][Extension] Extension root: /Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0
[19:15:17.176][Extension] $PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/Users/chentuo/opt/anaconda3/bin:/Users/chentuo/opt/anaconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin:/Users/chentuo/Library/Application Support/JetBrains/Toolbox/scriptseval
[19:15:17.176][Extension] $SHELL: /bin/zsh
[19:15:17.176][Extension] $LANG: undefined
[19:15:17.176][Extension] $LC_ALL: undefined
[19:15:17.176][Extension] process.platform: darwin
[19:15:17.176][Extension] process.arch: arm64
[19:15:17.176][Extension] vscode.env.appName: Visual Studio Code
[19:15:17.176][Extension] vscode.env.remoteName: undefined
[19:15:17.176][Extension] vscode.env.uiKind: 1
[19:15:17.177][Config] latex-workshop.latex.recipes: [{"name":"XeLaTeX","tools":["xelatex"]},{"name":"PDFLaTeX","tools":["pdflatex"]},{"name":"BibTeX","tools":["bibtex"]},{"name":"LaTeXmk","tools":["latexmk"]},{"name":"xelatex -> bibtex -> xelatex*2","tools":["xelatex","bibtex","xelatex","xelatex"]},{"name":"pdflatex -> bibtex -> pdflatex*2","tools":["pdflatex","bibtex","pdflatex","pdflatex"]}] .
[19:15:17.177][Config] latex-workshop.latex.recipe.default: "lastUsed" .
[19:15:17.177][Config] latex-workshop.latex.tools: [{"name":"pdflatex","command":"pdflatex","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","%DOCFILE%"]},{"name":"xelatex","command":"xelatex","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","-pdf","%DOCFILE%"]},{"name":"latexmk","command":"latexmk","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","-pdf","-outdir=%OUTDIR%","%DOCFILE%"]},{"name":"bibtex","command":"bibtex","args":["%DOCFILE%"]}] .
[19:15:17.177][Config] latex-workshop.latex.outDir: "build" .
[19:15:17.178][Config] latex-workshop.latex.autoBuild.run: "onSave" .
[19:15:17.178][Config] latex-workshop.latex.autoClean.run: "onFailed" .
[19:15:17.178][Config] latex-workshop.latex.clean.fileTypes: ["*.aux","*.bbl","*.blg","*.idx","*.ind","*.lof","*.lot","*.out","*.toc","*.acn","*.acr","*.alg","*.glg","*.glo","*.gls","*.ist","*.fls","*.log","*.fdb_latexmk"] .
[19:15:17.179][Config] latex-workshop.view.pdf.viewer: "external" .
[19:15:17.179][Config] latex-workshop.view.pdf.external.viewer.command: "/Applications/Google Chrome.app" .
[19:15:17.187][Config] latex-workshop.message.warning.show: false .
[19:15:17.187][Config] latex-workshop.message.error.show: false .
[19:15:17.188][Config] latex-workshop.showContextMenu: true .
[19:15:17.199][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[19:15:17.200][Root] Current workspace folders: ["file://%WS1%"]
[19:15:17.200][Extension] LaTeX Workshop initialized.
[19:15:17.201][Root] Current workspaceRootDir: file://%WS1% .
[19:15:17.208][Server] valdOrigin is http://127.0.0.1:58914
[19:15:17.220][Root] Found files that might be root, choose the first one: %WS1%/ijcai23.tex .
[19:15:17.220][Root] Root file changed: from %WS1%/ijcai23.tex to %WS1%/ijcai23.tex, langID latex . Refresh dependencies
[19:15:17.220][Event] ROOT_FILE_CHANGED: "%WS1%/ijcai23.tex"
[19:15:17.221][Cacher][Watcher] Reset.
[19:15:17.221][Cacher][Watcher] Reset.
[19:15:17.221][Cacher][Watcher] Reset.
[19:15:17.222][Cacher] Adding %WS1%/ijcai23.tex .
[19:15:17.222][Cacher][Watcher] Watched %WS1%/ijcai23.tex with a new watcher on %WS1% .
[19:15:17.223][Event] FILE_WATCHED: "%WS1%/ijcai23.tex"
[19:15:17.224][Cacher] Caching %WS1%/ijcai23.tex .
[19:15:17.224][Cacher] Updated inputs of %WS1%/ijcai23.tex .
[19:15:17.225][Cacher] Parse LaTeX AST: %WS1%/ijcai23.tex .
[19:15:17.225][Event] ROOT_FILE_SEARCHED
[19:15:17.286][Root] Current workspace folders: ["file://%WS1%"]
[19:15:17.291][Root] Found root file from active editor: %WS1%/ijcai23.tex
[19:15:17.295][Root] Keep using the same root file: %WS1%/ijcai23.tex
[19:15:17.296][Event] ROOT_FILE_SEARCHED
[19:15:17.583][Cacher] Parsed LaTeX AST: %WS1%/ijcai23.tex .
[19:15:17.583][File] Calling kpsewhich to resolve article.cls .
[19:15:17.739][Cacher] Bib %WS1%/zotero.bib from %WS1%/ijcai23.tex .
[19:15:17.740][Intelli][Citation] Parsing .bib entries from %WS1%/zotero.bib
[19:15:17.742][Intelli][Citation] Parse BibTeX AST from %WS1%/zotero.bib .
[19:15:17.743][Cacher][Watcher] Watched %WS1%/zotero.bib with a new watcher on %WS1% .
[19:15:17.743][Event] FILE_WATCHED: "%WS1%/zotero.bib"
[19:15:17.743][Cacher] Updated elements in 160.28 ms: %WS1%/ijcai23.tex .
[19:15:17.744][Event] FILE_PARSED: "%WS1%/ijcai23.tex"
[19:15:17.750][Structure] Structure force updated with 0 root sections for %WS1%/ijcai23.tex .
[19:15:17.750][Event] STRUCTURE_UPDATED
[19:15:17.750][Structure] Structure updated with 6 root sections for %WS1%/ijcai23.tex .
[19:15:17.751][Structure] Structure updated with 6 root sections for %WS1%/ijcai23.tex .
[19:15:17.751][Event] STRUCTURE_UPDATED
[19:15:17.752][Event] STRUCTURE_UPDATED
[19:15:17.976][Intelli][Citation] Parsed 1053 bib entries from %WS1%/zotero.bib .
[19:15:17.977][Event] FILE_PARSED: "%WS1%/zotero.bib"
[19:15:17.978][Structure] Structure force updated with 6 root sections for %WS1%/ijcai23.tex .
[19:15:17.979][Event] STRUCTURE_UPDATED
[19:15:21.750][Commander] VIEW command invoked with mode: file://%WS1%/ijcai23.tex.
[19:15:21.750][Root] Current workspace folders: ["file://%WS1%"]
[19:15:21.751][Root] Found root file from active editor: %WS1%/ijcai23.tex
[19:15:21.751][Root] Keep using the same root file: %WS1%/ijcai23.tex
[19:15:21.751][Event] ROOT_FILE_SEARCHED
[19:15:21.751][Event] STRUCTURE_UPDATED
[19:15:21.752][Viewer] Open external viewer for %WS1%/build/ijcai23.pdf
[19:15:21.752][Viewer] Execute the external PDF viewer command The command is /Applications/Google Chrome.app:["%WS1%/build/ijcai23.pdf"].
[19:15:21.753][Viewer] The external PDF viewer stdout: 
[19:15:21.753][Viewer] The external PDF viewer stderr: 
[19:15:28.909][Event] STRUCTURE_UPDATED
[19:15:35.319][Event] STRUCTURE_UPDATED
[19:15:42.694][Commander] VIEW command invoked with mode: tab.
[19:15:42.695][Commander] Active document is not a TeX file.
[19:15:46.464][Event] STRUCTURE_UPDATED
[19:15:49.062][Commander] VIEW command invoked with mode: tab.
[19:15:49.062][Root] Current workspace folders: ["file://%WS1%"]
[19:15:49.063][Root] Found root file from active editor: %WS1%/ijcai23.tex
[19:15:49.063][Root] Keep using the same root file: %WS1%/ijcai23.tex
[19:15:49.063][Event] ROOT_FILE_SEARCHED
[19:15:49.064][Event] STRUCTURE_UPDATED
[19:15:49.064][Viewer] Cannot find PDF file file://%WS1%/build/ijcai23.pdf
[19:15:58.405][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:58914/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyNXdzMSUyNSUyRiUyNVdTMSUyNSUyRmJ1aWxkJTJGaWpjYWkyMy5wZGY .
[19:15:58.406][Cacher][Watcher] Watched //%WS1%/%WS1%/build/ijcai23.pdf with a new watcher on //%WS1%/%WS1%/build .
[19:15:58.406][Event] FILE_WATCHED: "//%WS1%/%WS1%/build/ijcai23.pdf"
[19:15:58.407][Viewer] Open PDF tab for file://%ws1%/%WS1%/build/ijcai23.pdf
[19:15:58.563][Viewer] Handle data type: open
[19:15:58.660][Server] Error reading PDF file://%ws1%/%WS1%/build/ijcai23.pdf EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
[19:15:58.661]EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
    at Function.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:26791)
    at Object.readFile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:25177)
    at handler (/Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/out/src/preview/server.js:201:37)
[19:16:07.717][Viewer] Handle data type: open
[19:16:07.877][Server] Error reading PDF file://%ws1%/%WS1%/build/ijcai23.pdf EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
[19:16:07.878]EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
    at Function.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:26791)
    at Object.readFile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:25177)
    at handler (/Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/out/src/preview/server.js:201:37)
[19:16:13.957][Viewer] Handle data type: open
[19:16:14.031][Server] Error reading PDF file://%ws1%/%WS1%/build/ijcai23.pdf EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
[19:16:14.032]EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
    at Function.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:26791)
    at Object.readFile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:25177)
    at handler (/Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/out/src/preview/server.js:201:37)
[19:16:26.595][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:58914/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRlVzZXJzJTJGY2hlbnR1byUyRlNlYWZpbGUlMkZtYWluLXJlcG8lMkZBY2FkZW1pY1JlcG8lMkZsYXRleCUyRkZvcm1hdHRpbmdHdWlkZWxpbmVzLUlKQ0FJLTIzJTJGaWpjYWkyMy5wZGY .
[19:16:26.595][Cacher][Watcher] Watched %WS1%/ijcai23.pdf with a new watcher on %WS1% .
[19:16:26.596][Event] FILE_WATCHED: "%WS1%/ijcai23.pdf"
[19:16:26.596][Viewer] Open PDF tab for file://%WS1%/ijcai23.pdf
[19:16:26.718][Viewer] Handle data type: open
[19:16:26.760][Server] Preview PDF file: file://%WS1%/ijcai23.pdf
[19:16:26.900][Viewer] Handle data type: loaded
[19:16:26.900][Event] VIEWER_PAGE_LOADED
[19:16:28.787][Event] STRUCTURE_UPDATED
[19:16:34.271][Commander] VIEW command invoked with mode: browser.
[19:16:34.271][Root] Current workspace folders: ["file://%WS1%"]
[19:16:34.273][Root] Found root file from active editor: %WS1%/ijcai23.tex
[19:16:34.273][Root] Keep using the same root file: %WS1%/ijcai23.tex
[19:16:34.273][Event] ROOT_FILE_SEARCHED
[19:16:34.273][Event] STRUCTURE_UPDATED
[19:16:34.274][Viewer] Cannot find PDF file file://%WS1%/build/ijcai23.pdf
[19:18:23.244][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:58914/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyNXdzMSUyNSUyRiUyNVdTMSUyNSUyRmJ1aWxkJTJGaWpjYWkyMy5wZGY .
[19:18:23.246][Cacher][Watcher] Watched //%WS1%/%WS1%/build/ijcai23.pdf .
[19:18:23.246][Event] FILE_WATCHED: "//%WS1%/%WS1%/build/ijcai23.pdf"
[19:18:23.246][Viewer] Open PDF tab for file://%ws1%/%WS1%/build/ijcai23.pdf
[19:18:23.325][Viewer] Handle data type: open
[19:18:23.375][Server] Error reading PDF file://%ws1%/%WS1%/build/ijcai23.pdf EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
[19:18:23.375]EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
    at Function.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:26791)
    at Object.readFile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:25177)
    at handler (/Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/out/src/preview/server.js:201:37)
[19:19:53.725][Commander] VIEW command invoked with mode: tab.
[19:19:53.726][Commander] Active document is not a TeX file.
[19:20:02.580][Event] STRUCTURE_UPDATED
[19:20:06.476][Commander] VIEW command invoked with mode: tab.
[19:20:06.476][Root] Current workspace folders: ["file://%WS1%"]
[19:20:06.479][Root] Found root file from active editor: %WS1%/ijcai23.tex
[19:20:06.479][Root] Keep using the same root file: %WS1%/ijcai23.tex
[19:20:06.479][Event] ROOT_FILE_SEARCHED
[19:20:06.480][Event] STRUCTURE_UPDATED
[19:20:06.482][Viewer] Cannot find PDF file file://%WS1%/build/ijcai23.pdf
[19:24:03.408][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:58914/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyNXdzMSUyNSUyRiUyNVdTMSUyNSUyRmJ1aWxkJTJGaWpjYWkyMy5wZGY .
[19:24:03.409][Cacher][Watcher] Watched //%WS1%/%WS1%/build/ijcai23.pdf .
[19:24:03.409][Event] FILE_WATCHED: "//%WS1%/%WS1%/build/ijcai23.pdf"
[19:24:03.410][Viewer] Open PDF tab for file://%ws1%/%WS1%/build/ijcai23.pdf
[19:24:03.521][Viewer] Handle data type: open
[19:24:03.553][Server] Error reading PDF file://%ws1%/%WS1%/build/ijcai23.pdf EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
[19:24:03.554]EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
    at Function.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:26791)
    at Object.readFile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:25177)
    at handler (/Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/out/src/preview/server.js:201:37)
[19:26:48.689][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:58914/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyNXdzMSUyNSUyRiUyNVdTMSUyNSUyRmJ1aWxkJTJGaWpjYWkyMy5wZGY .
[19:26:48.689][Cacher][Watcher] Watched //%WS1%/%WS1%/build/ijcai23.pdf .
[19:26:48.689][Event] FILE_WATCHED: "//%WS1%/%WS1%/build/ijcai23.pdf"
[19:26:48.690][Viewer] Open PDF tab for file://%ws1%/%WS1%/build/ijcai23.pdf
[19:26:48.778][Viewer] Handle data type: open
[19:26:48.818][Server] Error reading PDF file://%ws1%/%WS1%/build/ijcai23.pdf EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
[19:26:48.818]EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/%ws1%/%WS1%/build/ijcai23.pdf'
    at Function.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:26791)
    at Object.readFile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:25177)
    at handler (/Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/out/src/preview/server.js:201:37)
[19:32:30.367][Commander] VIEW command invoked.
[19:32:30.367][Commander] Active document is not a TeX file.

```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
workbench.desktop.main.js:sourcemap:643  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'registerIssueDataProvider' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:sourcemap:643  INFO Started local extension host with pid 77344.
workbench.desktop.main.js:sourcemap:643  WARN No search provider registered for scheme: file, waiting
workbench.desktop.main.js:sourcemap:643  INFO [perf] Render performance baseline is 22ms
workbench.desktop.main.js:sourcemap:1897 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/syntax/TeX.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1897
workbench.desktop.main.js:sourcemap:1897 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/syntax/LaTeX.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1897
workbench.desktop.main.js:sourcemap:1897 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/syntax/Bibtex.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1897
workbench.desktop.main.js:sourcemap:1897 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/syntax/markdown-latex-combined.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1897
workbench.desktop.main.js:sourcemap:1897 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/syntax/cpp-grammar-bailout.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1897
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/syntax/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/syntax/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/syntax/Bibtex.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/syntax/markdown-latex-combined.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/syntax/cpp-grammar-bailout.tmLanguage.json
register @ TMScopeRegistry.ts:46
7An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
workbench.desktop.main.js:sourcemap:643   ERR Error: 此文件未显示在文本编辑器中，因为它是一个目录。
    at k (workbench.desktop.main.js:sourcemap:148:781)
    at ee (workbench.desktop.main.js:sourcemap:769:59199)
    at M.fc (workbench.desktop.main.js:sourcemap:2148:24758)
    at M.setInput (workbench.desktop.main.js:sourcemap:2148:24179)
    at async b.S (workbench.desktop.main.js:sourcemap:2146:23046)
    at async b.L (workbench.desktop.main.js:sourcemap:2146:21637)
    at async b.openEditor (workbench.desktop.main.js:sourcemap:2146:20603)
    at async workbench.desktop.main.js:sourcemap:2275:23005
    at async v.M (workbench.desktop.main.js:sourcemap:1184:80268)
    at async v.openCodeEditor (workbench.desktop.main.js:sourcemap:720:4538)
    at async o.open (workbench.desktop.main.js:sourcemap:645:43427)
    at async f.open (workbench.desktop.main.js:sourcemap:645:44557)
127.0.0.1:58914/pdf..ZmlsZSUzQSUyRiUyRiUyNXdzMSUyNSUyRiUyNVdTMSUyNSUyRmJ1aWxkJTJGaWpjYWkyMy5wZGY:1     Failed to load resource: the server responded with a status of 404 (Not Found)
workbench.desktop.main.js:sourcemap:643   ERR Error: 此文件未显示在文本编辑器中，因为它是一个目录。
    at k (workbench.desktop.main.js:sourcemap:148:781)
    at ee (workbench.desktop.main.js:sourcemap:769:59199)
    at M.fc (workbench.desktop.main.js:sourcemap:2148:24758)
    at M.setInput (workbench.desktop.main.js:sourcemap:2148:24179)
    at async b.S (workbench.desktop.main.js:sourcemap:2146:23046)
    at async b.L (workbench.desktop.main.js:sourcemap:2146:21637)
    at async b.openEditor (workbench.desktop.main.js:sourcemap:2146:20603)
    at async workbench.desktop.main.js:sourcemap:2275:23005
    at async v.M (workbench.desktop.main.js:sourcemap:1184:80268)
    at async v.openCodeEditor (workbench.desktop.main.js:sourcemap:720:4538)
    at async o.open (workbench.desktop.main.js:sourcemap:645:43427)
    at async f.open (workbench.desktop.main.js:sourcemap:645:44557)
127.0.0.1:58914/pdf..ZmlsZSUzQSUyRiUyRiUyNXdzMSUyNSUyRiUyNVdTMSUyNSUyRmJ1aWxkJTJGaWpjYWkyMy5wZGY:1     Failed to load resource: the server responded with a status of 404 (Not Found)
127.0.0.1:58914/pdf..ZmlsZSUzQSUyRiUyRiUyNXdzMSUyNSUyRiUyNVdTMSUyNSUyRmJ1aWxkJTJGaWpjYWkyMy5wZGY:1     Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load source map: Could not load content for vscode-webview://1lk23sua5m1teos86lblhvsvkkhsfhv3pvutv7t724lb2ojb8u39/pdf.worker.mjs.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for http://127.0.0.1:58914/build/pdf.worker.mjs.map: Fetch through target failed: Target not supported; Fallback: Unknown error
DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-cdn.net/Users/chentuo/.vscode/extensions/james-yu.latex-workshop-9.17.0/node_modules/pdfjs-dist/build/pdf.mjs.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
```

## Anything Else?
> _Add any other context about the problem below._

Clicking on this address, vscode took me to the root directory of my MAC.

[19:20:06.476][Root] Current workspace folders: ["file://%WS1%"]

**Comment by James-Yu** [comment]
Sorry but your log did not reflect useful information. You may check your actions before each `[Viewer][Panel] Internal PDF viewer at` entry. It is at these times when `%WS1%/build/ijcai23.pdf` became `//%WS1%/%WS1%/build/ijcai23.pdf`. The extension does not do that.
