### ISSUE TITLE
Backward SyncTeX failed on non-existent

### ISSUE THREAD

**Issue by Cold-Stars** [James-Yu/LaTeX-Workshop#4239]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ ] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [Windows 11]
- Visual Studio Code Version: [1.88.1(system step)]
- LaTeX Workshop Version: [9.20.0]
- TeX Distribution Version: [TeX Live 2024]

## The Issue*
- Error when using vscode built-in pdf preview for reverse search
- settings.json：
```json
{
    "latex-workshop.latex.autoBuild.run": "onFileChange",
    "latex-workshop.showContextMenu": true,
    "latex-workshop.intellisense.package.enabled": true,
    "latex-workshop.message.error.show": false,
    "latex-workshop.message.warning.show": false,
    "latex-workshop.latex.tools": [
        {
            "name": "xelatex",
            "command": "xelatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOCFILE%"
            ]
        },
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOCFILE%"
            ]
        },
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "-outdir=%OUTDIR%",
                "%DOCFILE%"
            ]
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        }
    ],
    "latex-workshop.latex.recipes": [
        {
            "name": "XeLaTeX",
            "tools": [
                "xelatex"
            ]
        },
        {
            "name": "PDFLaTeX",
            "tools": [
                "pdflatex"
            ]
        },
        {
            "name": "BibTeX",
            "tools": [
                "bibtex"
            ]
        },
        {
            "name": "LaTeXmk",
            "tools": [
                "latexmk"
            ]
        },
        {
            "name": "xelatex -> bibtex -> xelatex*2",
            "tools": [
                "xelatex",
                "bibtex",
                "xelatex",
                "xelatex"
            ]
        },
        {
            "name": "pdflatex -> bibtex -> pdflatex*2",
            "tools": [
                "pdflatex",
                "bibtex",
                "pdflatex",
                "pdflatex"
            ]
        }
    ],
    "latex-workshop.latex.clean.fileTypes": [
        "*.aux",
        "*.bbl",
        "*.blg",
        "*.idx",
        "*.ind",
        "*.lof",
        "*.lot",
        "*.out",
        "*.toc",
        "*.acn",
        "*.acr",
        "*.alg",
        "*.glg",
        "*.glo",
        "*.gls",
        "*.ist",
        "*.fls",
        "*.log",
        "*.fdb_latexmk"
    ],
    "latex-workshop.latex.autoClean.run": "onFailed",
    "latex-workshop.latex.recipe.default": "lastUsed",
    "latex-workshop.view.pdf.internal.synctex.keybinding": "double-click"
}
```
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/113192545/d195f592-4119-4de4-a913-25bd878bd2f9)

### LaTeX Workshop Output*
```
[21:05:44.566][Viewer] Handle data type: reverse_synctex
[21:05:44.567][Locator] Backward from %WS1%\1.pdf at x=202.9159577677225, y=251.09929110105583 on page 1.
[21:05:44.640][Locator] Backward SyncTeX failed on isSameRealPath() with d:/yan/�ҵ�/����/С����/latex/./1.tex and %WS1%\1.tex . Error: ENOENT: no such file or directory, lstat 'd:\yan\�ҵ�'
[21:05:44.640]Error: ENOENT: no such file or directory, lstat 'd:\yan\�ҵ�'
	at Object.realpathSync (node:fs:2676:7)
	at Object.<anonymous> (node:electron/js2c/node_init:2:5352)
	at isSameRealPath (c:\Users\19731\.vscode\extensions\james-yu.latex-workshop-9.20.0\out\src\utils\pathnormalize.js:39:28)
	at Object.toTeX (c:\Users\19731\.vscode\extensions\james-yu.latex-workshop-9.20.0\out\src\locate\synctex.js:435:52)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[21:05:44.641][Locator] Backward SyncTeX failed on non-existent d:\yan\�ҵ�\����\С����\latex\1.tex .
```

**Comment by James-Yu** [comment]
Please provide a full log.

**Comment by Cold-Stars** [comment]
> Please provide a full log.
> 
> edit: please also provide the full path to your tex file.

I have updated the log. My tex path is D:\yan\my\paper\small paper\latex\1.tex

**Comment by James-Yu** [comment]
Did you encounter the same issue with all English paths?

**Comment by Cold-Stars** [comment]
> Did you encounter the same issue with all English paths?

There are no issues under the English path.

**Comment by James-Yu** [comment]
Please provide the synctex.gz file under CJK path for debug. It is highly like to be a SyncTeX issue.

**Comment by James-Yu** [comment]
It is always recommended to use ASCII paths. This commit may fix issues related to synctex binary (as we don't use it now), but the general TeX system works poorly under non-ASCII paths.
