### ISSUE TITLE
No bibliography suggestions when ``bibtex`` file are mal-parsed

### ISSUE THREAD

**Issue by Badr-MOUFAD** [James-Yu/LaTeX-Workshop#4335]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*

- Operating system: MacOS Sonoma v14.5
- VS code version: v1.92.1
- LaTeX Workshop: v10.1.0
- TeX Distribution: TeX Live 2024

## The Issue*

When a bibtex file mistakenly contain a syntax error, no errors/warnings are being raised and more importantly bibliography suggestions no longer show up.

### Reproduction Steps

Here is a minimal directory to reproduce.
Notice, the second bib entry intentionally contains a syntax error.

```
—— ./
 └——— main.tex
 └——— biblio.tex
```

<details>
  <summary>Content of <code>main.tex</code> </summary>

```tex
\documentclass{article}

\begin{document}

    A sample sentence with a citation \cite{badr2024check}.

    % --- try to cite something else after


    \bibliographystyle{unsrtnat}
    \bibliography{biblio.bib}

\end{document}
```

</details>

<details>
  <summary>Content of <code>biblio.bib</code></summary>

```bibtex
@inproceedings{badr2024check,
  title     = {Sanity check},
  author    = {Moufad, Badr and Janati, Yazif},
  booktitle = {LaTeX-Workshop},
  year      = {2024}
}

@article{badr2024-expo-inve{s},
  title   = {Exposing a bug in Latex citation: investigation},
  author  = {Moufad, Badr and Janati, Yazif},
  journal = {LaTeX-Workshop},
  year    = {2024}
}

@article{badr2024invoked,
  title   = {This will be invoked to reproduce the bug},
  author  = {Moufad, Badr and Janati, Yazif},
  journal = {LaTeX-Workshop},
  year    = {2024}
}
```

</details>

Upon compiling the project, no error/warning will be shown.
Besides, citation suggestions will no longer show up.

### Expected Behavior

Raise and error or a warning to signal the problem.

In large project, it is hard to spot errors.
These syntax error might be introduced after copying a bib entry from google scholar or arxiv.

## Logs

<details>
  <summary>LaTeX Workshop Output</summary>

```txt
[15:02:34.068][Logger] New log placeholder %WS1% registered for /Users/badrmoufad/gh-repos/others/vs-latex-bug .
[15:02:34.068][Extension] Initializing LaTeX Workshop.
[15:02:34.098][Build][Recipe] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[15:02:34.098][Build][Recipe] Set $LATEXWORKSHOP_DOCKER_PATH: "docker"
[15:02:34.108][Server] Creating LaTeX Workshop http and websocket server.
[15:02:34.125][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[15:02:34.135][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":49508} .
[15:02:34.151][Extension] Extension root: /Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0
[15:02:34.151][Extension] $PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin:/opt/homebrew/Caskroom/miniforge/base/bin:/opt/homebrew/Caskroom/miniforge/base/condabin:/opt/homebrew/bin:/opt/homebrew/sbin
[15:02:34.151][Extension] $SHELL: /bin/zsh
[15:02:34.151][Extension] $LANG: en_US.UTF-8
[15:02:34.151][Extension] $LC_ALL: undefined
[15:02:34.151][Extension] process.platform: darwin
[15:02:34.151][Extension] process.arch: arm64
[15:02:34.151][Extension] vscode.env.appName: Visual Studio Code
[15:02:34.151][Extension] vscode.env.remoteName: undefined
[15:02:34.151][Extension] vscode.env.uiKind: 1
[15:02:34.163][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{","}"]
[15:02:34.164][Root] Current workspace folders: ["file://%WS1%"]
[15:02:34.164][Extension] LaTeX Workshop initialized.
[15:02:34.164][Root] Current workspaceRootDir: file://%WS1% .
[15:02:34.165][Server] valdOrigin is http://127.0.0.1:49508
[15:02:34.186][Root] Found files that might be root, choose the first one: %WS1%/main.tex .
[15:02:34.186][Root] Root file changed: from %WS1%/main.tex to %WS1%/main.tex, langID latex . Refresh dependencies
[15:02:34.186][Event] ROOT_FILE_CHANGED: "%WS1%/main.tex"
[15:02:34.186][Cacher][Watcher] Reset.
[15:02:34.186][Cacher][Watcher] Reset.
[15:02:34.187][Cacher] Adding %WS1%/main.tex .
[15:02:34.187][Cacher][Watcher] Watched %WS1%/main.tex with a new .* watcher on %WS1% .
[15:02:34.187][Event] FILE_WATCHED: "%WS1%/main.tex"
[15:02:34.187][Cacher] Caching %WS1%/main.tex .
[15:02:34.188][Event] ROOT_FILE_SEARCHED
[15:02:34.189][Cacher] Updated inputs of %WS1%/main.tex .
[15:02:34.189][Cacher] Parse LaTeX AST: %WS1%/main.tex .
[15:02:34.194][Cacher] Parsed LaTeX AST in 4.99 ms: %WS1%/main.tex .
[15:02:34.195][File] Calling kpsewhich to resolve article.cls .
[15:02:34.274][File] kpsewhich returned with '/usr/local/texlive/2024/texmf-dist/tex/latex/base/article.cls'.
[15:02:34.274][Cacher] Bib %WS1%/biblio.bib from %WS1%/main.tex .
[15:02:34.275][Intelli][Citation] Parsing .bib entries from %WS1%/biblio.bib
[15:02:34.275][Intelli][Citation] Parse BibTeX AST from %WS1%/biblio.bib .
[15:02:34.275][Cacher][Watcher] Watched %WS1%/biblio.bib with a new .bib watcher on %WS1% .
[15:02:34.275][Event] FILE_WATCHED: "%WS1%/biblio.bib"
[15:02:34.275][Cacher] Updated elements in 80.39 ms: %WS1%/main.tex .
[15:02:34.275][Event] FILE_PARSED: "%WS1%/main.tex"
[15:02:34.275][Structure][BibTeX] Parse active BibTeX document for AST.
[15:02:34.281][Cacher] Parsing .fls %WS1%/main.fls .
[15:02:34.339][Cacher] Found .aux %WS1%/main.aux from .fls %WS1%/main.fls , parsing.
[15:02:34.358][Cacher] Parsed .aux %WS1%/main.aux .
[15:02:34.358][Cacher] Parsed .fls %WS1%/main.fls .
[15:02:34.588][Structure][BibTeX] Parse active BibTeX document for AST.
[15:02:36.817][Structure][BibTeX] Parse active BibTeX document for AST.
```

</details>

<details>
  <summary>Developer Tools Console</summary>

```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: SyntaxError: Expected ",", "=", [ \t\r\n], or [^%@={}()"#, \t\r\n] but "{" found.
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] stack trace: SyntaxError: Expected ",", "=", [ \t\r\n], or [^%@={}()"#, \t\r\n] but "{" found.
    at new peg$SyntaxError (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:14:20)
    at peg$buildStructuredError (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:446:12)
    at Object.peg$parse [as parse] (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:1982:11)
    at Object.parse (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser.js:36:30)
    at Function.parseBibTeX (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/out/src/parse/parser/unified.js:46:42)
    at MessagePort.<anonymous> (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/node_modules/workerpool/src/worker.js:150:27)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:825:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
log.ts:439   ERR Expected ",", "=", [ \t\r\n], or [^%@={}()"#, \t\r\n] but "{" found.: SyntaxError: Expected ",", "=", [ \t\r\n], or [^%@={}()"#, \t\r\n] but "{" found.
    at new peg$SyntaxError (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:14:20)
    at peg$buildStructuredError (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:446:12)
    at Object.peg$parse [as parse] (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:1982:11)
    at Object.parse (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/node_modules/latex-utensils/out/src/bibtex/bibtex_parser.js:36:30)
    at Function.parseBibTeX (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/out/src/parse/parser/unified.js:46:42)
    at MessagePort.<anonymous> (/Users/badrmoufad/.vscode/extensions/james-yu.latex-workshop-10.1.0/node_modules/workerpool/src/worker.js:150:27)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:825:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
```
</details>

## Anything Else?

Inspecting the logs, it apprease that this problem happens because of an unhandeled error in the parsing Promise.

I would be happy to make a PR, follow along with you, to fix this problem.

Also pining @YazidJanati

**Comment by James-Yu** [comment]
You may refer to https://github.com/tamuratak/latex-utensils for bibtex parsing problem.

**Comment by jlelong** [comment]
I do not think there is an issue with the parsing of the bibtex file. Curly braces are not accepted as parts of bibtex keys, which breaks the parsing. The question seems to be rather related to the lack of notification of a parsing failure to the user.

First, note that the syntax highlighting detects the issue
<img width="483" alt="Capture d’écran 2024-08-13 à 11 44 49" src="https://github.com/user-attachments/assets/cf9f0782-2229-4d23-bae7-532faace7eae">

Then, what about putting https://github.com/James-Yu/LaTeX-Workshop/blob/614eec118aa95a390237d0ec60fd15d7edb2b18d/src/completion/completer/citation.ts#L250 inside a `try...catch` block to log the parsing failure even though we will not be able to precisely locate the error?
