### ISSUE TITLE
Support watching files on virtual file systems

### ISSUE THREAD

**Issue by msujew** [James-Yu/LaTeX-Workshop#4357]
## Pre-checks
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment
- Operating System: Windows 11
- Visual Studio Code Version: 1.92.2
- LaTeX Workshop Version: 10.2.1
- TeX Distribution Version: TeX Live 2020

## The Issue

We're building a VS Code extension to do collaboration/pair-programming, similar to MS live-share. When a guest joins a room, all files in VS Code are handled through a virtual file system using the `oct` URI scheme. We were made aware of https://github.com/TypeFox/open-collaboration-tools/issues/61. It seems like file reloads aren't correctly handled - file changes are correctly registered (see log below), but the extension attempts to reload the file from disk. This fails, as the file only exists within a virtual in-memory file system (see extension host logs below).

### Reproduction Steps
1. Create a room with the [open collaboration tools](https://marketplace.visualstudio.com/items?itemName=typefox.open-collaboration-tools) extension.
2. Create a second VS Code instance and join that newly created room
3. In that second instance (i.e. the guest instance) open a pdf file
4. In the host instance, recompile the pdf file
5. The file is updated in the host instance but not in the guest instance

### Expected Behavior
The pdf file is also updated on the guest instance

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[01:38:55.538][Logger] New log placeholder %WS1% registered for \Extras\Extras .
[01:38:55.538][Extension] Initializing LaTeX Workshop.
[01:38:55.668][Build][Recipe] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[01:38:55.668][Build][Recipe] Set $LATEXWORKSHOP_DOCKER_PATH: "docker"
[01:38:55.735][Server] Creating LaTeX Workshop http and websocket server.
[01:38:55.821][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[01:38:55.877][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":56706} .
[01:38:55.881][Extension] Extension root: c:\Users\Mark\.vscode\extensions\james-yu.latex-workshop-10.1.0
[01:38:55.882][Extension] process.platform: win32
[01:38:55.882][Extension] process.arch: x64
[01:38:55.882][Extension] vscode.env.appName: Visual Studio Code
[01:38:55.882][Extension] vscode.env.remoteName: undefined
[01:38:55.882][Extension] vscode.env.uiKind: 1
[01:38:55.885][Config] latex-workshop.latex.external.build.command: "npm run build" .
[01:38:55.926][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{","}"]
[01:38:55.927][Root] Current workspace folders: ["oct:/Workspace/Workspace"]
[01:38:55.927][Extension] LaTeX Workshop initialized.
[01:38:55.928][Root] Current workspaceRootDir: oct:/Workspace/Workspace.
[01:38:55.929][Server] valdOrigin is http://127.0.0.1:56706
[01:38:55.938][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:56706/viewer.html?file=pdf..b2N0JTNBJTJGRXh0cmFzJTJGRXh0cmFzJTJGOTktYXVmZ2FiZW4ucGRm .
[01:38:55.939][Cacher][Watcher] Watched %WS1%\thesis.pdf with a new .pdf watcher on %WS1% .
[01:38:55.939][Event] FILE_WATCHED: "\\Workspace\\Workspace\\thesis.pdf"
[01:38:56.290][Viewer] Handle data type: open
[01:38:58.092][Server] Preview PDF file: oct:/Workspace/Workspace/thesis.pdf
[01:38:58.217][Viewer] Handle data type: loaded
[01:38:58.217][Event] VIEWER_PAGE_LOADED
```

### Extension Host Log Output
```
2024-09-01 01:39:16.790 [error] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'C:\Workspace\Workspace\thesis.pdf'
    at Function.e (c:\Users\Mark\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:6206)
    at stat (c:\Users\Mark\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:3977)
    at Watcher.initiatePolling (c:\Users\Mark\.vscode\extensions\james-yu.latex-workshop-10.1.0\out\src\core\watcher.js:157:23)
    at Watcher.onDidChange (c:\Users\Mark\.vscode\extensions\james-yu.latex-workshop-10.1.0\out\src\core\watcher.js:128:13)
```

**Comment by James-Yu** [comment]
It’s not possible: we cannot infer the uri scheme from path `[01:38:55.939][Event] FILE_WATCHED: "\\Workspace\\Workspace\\thesis.pdf" `

**Comment by msujew** [comment]
@James-Yu I guess that's correct, but only because the code strips the URI scheme before doing anything else. If we keep it around, things start working as expected, see https://github.com/James-Yu/LaTeX-Workshop/pull/4359 :)
