### ISSUE TITLE
No editor sticky scroll

### ISSUE THREAD

**Issue by JRodez** [James-Yu/LaTeX-Workshop#4389]
## Pre-checks*
- [*] The issue has not been reported in this repository.
- [*] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [*] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [*] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: NixOS with packages from 24.05 channel (https://github.com/NixOS/nixpkgs/commit/8f7492cce28977fbf8bd12c72af08b1f6c7c3e49)
- Visual Studio Code Version: 1.93.0
- LaTeX Workshop Version: v10.3.2
- TeX Distribution Version: TeX 3.141592653 (TeX Live 2023/nixos.org)

## The Issue*
- Sticky scroll is not working but disabling LM "solves" the issue
- window log shows a maybe related error :
```log
2024-09-16 16:29:36.978 [error] Illegal value for lineNumber: Error: Illegal value for lineNumber
    at K.getLineMaxColumn (vscode-file://vscode-app/nix/store/pxy4dndr8z74lc7iza7m691sv62bzsv0-vscode-1.93.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:769:160)
    at V.getBottomForLineNumber (vscode-file://vscode-app/nix/store/pxy4dndr8z74lc7iza7m691sv62bzsv0-vscode-1.93.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:782:1682)
    at I.findScrollWidgetState (vscode-file://vscode-app/nix/store/pxy4dndr8z74lc7iza7m691sv62bzsv0-vscode-1.93.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:808:13719)
    at I.cb (vscode-file://vscode-app/nix/store/pxy4dndr8z74lc7iza7m691sv62bzsv0-vscode-1.93.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:808:12947)
    at async I.ab (vscode-file://vscode-app/nix/store/pxy4dndr8z74lc7iza7m691sv62bzsv0-vscode-1.93.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:808:12429)
```

### Reproduction Steps
1. disable all extensions but LW
2. open a Latex file
3. observe that there is no sticky scroll and window log is going crazy

### Expected Behavior
- having sticky scroll
- no error on window log 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[16:53:30.534][Root] Current workspace folders: ["file://%WS1%"]
[16:53:30.534][Root] Try finding root from magic comment.
[16:53:30.542][Root] Try finding root from active editor.
[16:53:30.543][Root] Try finding root from current root.
[16:53:30.543][Root] Keep using the same root file: %WS1%/src/main.tex
[16:53:30.543][Event] ROOT_FILE_SEARCHED
[16:53:30.543][Event] STRUCTURE_UPDATED
[16:53:30.543][Event] STRUCTURE_UPDATED
[16:53:31.294][Root] Current workspace folders: ["file://%WS1%"]
[16:53:31.294][Root] Try finding root from magic comment.
[16:53:31.304][Root] Try finding root from active editor.
[16:53:31.305][Root] Try finding root from current root.
[16:53:31.306][Root] Keep using the same root file: %WS1%/src/main.tex
[16:53:31.306][Event] ROOT_FILE_SEARCHED
[16:53:31.306][Event] STRUCTURE_UPDATED
[16:53:31.307][Event] STRUCTURE_UPDATED
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
log.ts:439   ERR Illegal value for lineNumber: Error: Illegal value for lineNumber
    at K.getLineMaxColumn (vscode-file://vscode-app/nix/store/pxy4dndr8z74lc7iza7m691sv62bzsv0-vscode-1.93.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:769:160)
    at V.getBottomForLineNumber (vscode-file://vscode-app/nix/store/pxy4dndr8z74lc7iza7m691sv62bzsv0-vscode-1.93.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:782:1682)
    at I.findScrollWidgetState (vscode-file://vscode-app/nix/store/pxy4dndr8z74lc7iza7m691sv62bzsv0-vscode-1.93.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:808:13719)
    at I.cb (vscode-file://vscode-app/nix/store/pxy4dndr8z74lc7iza7m691sv62bzsv0-vscode-1.93.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:808:12947)
    at async I.ab (vscode-file://vscode-app/nix/store/pxy4dndr8z74lc7iza7m691sv62bzsv0-vscode-1.93.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:808:12429)
```

## Anything Else?
- no

**Comment by James-Yu** [comment]
Not related to this extension. You may report to vscode’s repo.

**Comment by JRodez** [comment]
> Not related to this extension. You may report to vscode’s repo.

The sticky scroll works on LaTeX files without Latex Workshop, and sticky scroll  works fine with other LaTeX extensions.

**Comment by James-Yu** [comment]
The extension does nothing to sticky scroll. Indeed, I am not aware of API for extension to mess with that.
