### ISSUE TITLE
fail to load the extension

### ISSUE THREAD

**Issue by chantisnake** [James-Yu/LaTeX-Workshop#474]
### Description

The extension would not load on start of the editor. reinstalling the editor, and reinstalling the extension both do not work.

### Log messages

```
[4424:0318/153250.862:INFO:CONSOLE(4183)] "Activating extension `James-Yu.latex-workshop` failed: Cannot find module 'opn'.", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (4183)
```

I am not sure if the following log is useful:
```
[4424:0318/153251.001:INFO:CONSOLE(1306)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1306)
[4424:0318/153251.001:INFO:CONSOLE(1306)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1306)
[4424:0318/153251.006:INFO:CONSOLE(253)] "%c[Extension Host] %cWARNING: Promise with no error callback:8 %c(at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:848)", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (253)
[4424:0318/153251.029:INFO:CONSOLE(253)] "%c[Extension Host]%", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (253)
[4424:0318/153251.030:INFO:CONSOLE(253)] "%c[Extension Host] %cTypeError: Cannot read property 'map' of undefined
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:582:153
    at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:68:868)
    at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:153)
    at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:970)
    at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:411)
    at e.resolveOk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:524:491)
    at e._receiveReply (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:584:316)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:583:678)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:582:671
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:585:523
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:459
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:729)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:146:633)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20) %c(at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:937)", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (253)
[4424:0318/153251.051:INFO:CONSOLE(253)] "%c[Extension Host] %cWARNING: Promise with no error callback:9 %c(at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:848)", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (253)
[4424:0318/153251.051:INFO:CONSOLE(1306)] "%c  ERR", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1306)
[4424:0318/153251.054:INFO:CONSOLE(253)] "%c[Extension Host]%", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (253)
[4424:0318/153251.084:INFO:CONSOLE(253)] "%c[Extension Host] %cTypeError: Cannot read property 'map' of undefined
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:582:153
    at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:68:868)
    at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:153)
    at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:970)
    at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:411)
    at e.resolveOk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:524:491)
    at e._receiveReply (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:584:316)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:583:678)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:582:671
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:585:523
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:459
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:729)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:146:633)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20) %c(at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:937)", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (253)
```

**Comment by chantisnake** [comment]
temp solution:
```shell
cd "~\.vscode\extensions\James-Yu.latex-workshop-3.14.0"
npm install
```

**Comment by James-Yu** [comment]
It should be a bug related to the marketplace. I will soon make a new release. Please check if that still won't work.

A good solution is to uninstall the extension -> close vscode completely -> reopen and install extension.

**Comment by Issacwww** [comment]
I had this problem in vs code 1.31.0 and when I open any .tex file, the vs code will alert an error: "Extension host terminated unexpectedly." I have tried to reinstall the extension, but after installing it, when I just click the icon of the extension in the slide bar, the same error will be alerted, I cannot build any .tex file anymore.

**Comment by tamuratak** [comment]
See Microsoft/vscode/issues/67999. Please disable extensions, Live Server and Ftp-Simple.

**Comment by kerukukku1** [comment]
@tamuratak 
I tried it, but it still crashes.

**Comment by tamuratak** [comment]
See #1164 and [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#The-directory-node_modules-may-cause-errors). The directory `~/node_modules/` in the home directory may cause errors on Mac and Linux on VSCode 1.31.0.

If you still see this issue, please create a new issue.

**Comment by kerukukku1** [comment]
@tamuratak 
thanks!!!
my solution : 
```
rm -rf ~/node_modules
```

**Comment by tamuratak** [comment]
Great. You're welcome.
