### ISSUE TITLE
"Cannot find module 'async-each'"

### ISSUE THREAD

**Issue by oerpli** [James-Yu/LaTeX-Workshop#510]
### Description
Since updating to the newest version the extension cannot be activated anymore. 
I've had no problems last week but today it does not work any more.
Also: when I use the current master branch and compile it myself it seems to work just fine in the debugging instance of VS Code. 
But in the normal environment I get `Cannot find module 'async-each'` in the dev tool console. 

### Log messages

```
[Extension Host] Here is the error stack:  Error: Cannot find module 'async-each'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:784)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\...\.vscode\extensions\James-Yu.latex-workshop-5.0.4\node_modules\chokidar\index.js:5:17)
	at Object.<anonymous> (C:\Users\...\.vscode\extensions\James-Yu.latex-workshop-5.0.4\node_modules\chokidar\index.js:718:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
```

**Comment by James-Yu** [comment]
Can you please try uninstall the extension then close and reopen vscode, finally reinstall the extension?

**Comment by oerpli** [comment]
I think I did this before and it didn't help. This time I deleted the extension folder manually and then reinstalled the extension and it worked.

**Comment by James-Yu** [comment]
It should be a vscode issue.
