### ISSUE TITLE
Build command not working for non-root files used via \import

### ISSUE THREAD

**Issue by jsdeguzman6** [James-Yu/LaTeX-Workshop#751]
### Description

When I use a non-root file via `\import{path_to_file/}{file.tex}`, the build command doesn't work

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

This pops up every time I save/build (the non-root file is TrueorFalse.tex, the root file is Math17Exam4.tex).

```
[00:09:47] Auto-build c:\Users\jeremiah\Documents\math-exams-answers\Math17\4th\Solutions\TrueorFalse.tex upon save.
[00:09:47] BUILD command invoked.
[00:09:47] Parsing c:\Users\jeremiah\Documents\math-exams-answers\Math17\4th\Math17Exam4.tex for outline
[00:09:47] Linter for active file started.
[00:09:47] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[00:09:47] Try root file in root directory: c:\Users\jeremiah\Documents\math-exams-answers\Math17\4th\Math17Exam4.tex
[00:09:47] Parsing c:\Users\jeremiah\Documents\math-exams-answers\Math17\4th\Math17Exam4.tex
[00:09:47] Cannot find LaTeX root file.
```

</details>

<details>
<summary>Developer Tools Console</summary>

This pops up every time I save/build

```
/C:/Users/jeremiah/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1398
ERR Path must be a string. Received null: TypeError: Path must be a string. Received null
	at assertPath (path.js:28:11)
	at Object.extname (path.js:922:5)
	at SectionNodeProvider.buildModel (C:\Users\jeremiah\.vscode\extensions\james-yu.latex-workshop-5.8.2\out\src\providers\outline.js:159:26)
	at SectionNodeProvider.refresh (C:\Users\jeremiah\.vscode\extensions\james-yu.latex-workshop-5.8.2\out\src\providers\outline.js:48:28)
	at context.subscriptions.push.vscode.workspace.onDidSaveTextDocument (C:\Users\jeremiah\.vscode\extensions\james-yu.latex-workshop-5.8.2\out\src\main.js:161:40)
	at e.fire (c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:218)
	at e.$acceptModelSaved (c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:728:141)
	at e._doInvokeHandler (c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:983)
	at e._invokeHandler (c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:701)
	at e._receiveRequest (c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:767)
	at e._receiveOneMessage (c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:536)
	at c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:669:452
	at c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:672:575
	at c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:903
	at e.fire (c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:218)
	at a (c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:713)
	at Socket._socketDataListener (c:\Users\jeremiah\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

</details>

### How to reproduce

1. Create a root file, and a non-root file to be imported in the root file.
2. Use the non-root file in the root file's document, by `\import{path_to_non_root/}{non_root.tex}
3. Save/build on the non-root file

### Expected behavior

The root file should be saved, and re-built/compiled as well.

### Actual behavior

The root file was not re-built. In addition, according to the output, the root file wasn't found.

### Additional Information

I tried using `\input{path_to_non_root/non_root.tex}`, oddly enough, it works.

Also, maybe it's related to this update: https://github.com/James-Yu/LaTeX-Workshop/commit/d64a8c90c4ac91bd4cbc0dfe95ac8bb4f740df7e

In addition, here's the configuration settings edited, at least the ones that are related to LaTeX workshop:
```json
{
    "latex-workshop.chktex.enabled": true,
    "latex-workshop.intellisense.surroundCommand.enabled": true,
    "latex-workshop.latex.clean.enabled": true,
    "latex-workshop.latex.magic.args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-shell-escape",
        "%DOC%"
    ],
    "latex-workshop.synctex.afterBuild.enabled": true,
    "latex-workshop.view.pdf.viewer": "tab",
}
```

**Comment by jlelong** [comment]
It sounds like you are using `\import` with a relative path, whereas the [documentation of the **import** pakage](http://ctan.uib.no/macros/latex/contrib/import/import.pdf) clearly says that `\import` expects a full path. For relative paths, the `\subimport` command should be used.

Please confirm that everything works fine using the correct command.
