### ISSUE TITLE
latex-outline not working for files with \input command

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#752]
### Description

Latex outline not getting populated for files having `\input` command at the beginning

### Log messages

<details>
<summary>Developer Tools Console</summary>
```
Error: Path must be a string. Received null
	at assertPath (path.js:28:11)
	at Object.extname (path.js:1471:5)
	at SectionNodeProvider.buildModel (/home/varun/.vscode/extensions/james-yu.latex-workshop-5.8.2/out/src/providers/outline.js:159:26)
	at SectionNodeProvider.refresh (/home/varun/.vscode/extensions/james-yu.latex-workshop-5.8.2/out/src/providers/outline.js:48:28)
	at SectionNodeProvider.getChildren (/home/varun/.vscode/extensions/james-yu.latex-workshop-5.8.2/out/src/providers/outline.js:192:41)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:509:807
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:110:323
	at new n.Class.derive._oncancel (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:84:776)
	at Object.t.asWinJsPromise (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:110:286)
	at t.fetchChildrenNodes (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:509:759)
	at t.getChildren (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:507:263)
	at e.$getChildren (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:504:844)
	at e._doInvokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
	at e._invokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
	at e._receiveRequest (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
	at e._receiveOneMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
	at e.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
	at a (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
	at Socket._socketDataListener (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```
</details>

### How to reproduce

1. Start vscode
2. Open a latex file which adds another file's context using `\input` (say, file-1)
3. Open a latex file which does not have `\input`(say, file-2)

### Expected behavior

The latex-outline should get populated in both the cases

### Actual behavior

The latex-outline does not get populated for file-2 and shows `Path must be a string. Received null` notification

**Comment by iFailatGitHub** [comment]
it's related to #751, except I used `\import`.

**Comment by werunom** [comment]
I have been using `\input{filename}`. 

Let me know if you want me try something else...

**Comment by jlelong** [comment]
Can you give me an example of a file breaking the outline? It looks like the regex does not work properly.

**Comment by jlelong** [comment]
Just to summarize a bit:
- Item 3 is just fine.
- Item 1 is also fine because everything coming after the first `\end{document}` is ignored. So only the content of `RoughNoInput.tex` is considered via the `\input` command and the rest of the `RoughInput` file ignored.
- Item 2 clearly shows an error occurring when a full path is given to `\input`. I am on it.

**Comment by werunom** [comment]
@jlelong  - Thanks! 

Just to clarify - I was not suggesting that the outline of `RoughInput.tex` should consists of the outline of `RoughNoInput.tex` just because I have included the second file using an `input{}` command. (I used the second file in the input command so as to reduce the number of test latex files required to demonstrate the problem.) Given this, I wanted to highlight **item 1** to point that the latex-outline is not getting refreshed depending the file which is in focus. And thought of pointing out **item 3** to indicate that the issue observed in **item 2** is not observed in this case. But as you clearly mention, the root cause of all these is **item 2**. Thanks for fixing this!
