### ISSUE TITLE
Build on Save not working

### ISSUE THREAD

**Issue by Gliptal** [James-Yu/LaTeX-Workshop#797]
### Description

Saving does not trigger the file build anymore.

### How to reproduce

1.  Save

### Expected behavior

The project is built.

### Actual behavior

The project is _not_ built.

**Comment by James-Yu** [comment]
Cannot reproduce.

**Comment by thatRobR** [comment]
I'm having the same issue after updating to version 5.10.0, tried reinstalling LaTeX Workshop but with no luck.

I'm using macOS 10.13.6 with newest version of VSC.

**Comment by James-Yu** [comment]
Please provide log messages.

**Comment by Gliptal** [comment]
```
[2018-09-14 17:43:01.238] [renderer1] [error] Cannot read property 'depth' of undefined: TypeError: Cannot read property 'depth' of undefined
	at SectionNodeProvider.buildModel (C:\Users\Utente\.vscode\extensions\james-yu.latex-workshop-5.10.0\out\src\providers\structure.js:113:170)
	at SectionNodeProvider.buildModel (C:\Users\Utente\.vscode\extensions\james-yu.latex-workshop-5.10.0\out\src\providers\structure.js:190:22)
	at SectionNodeProvider.refresh (C:\Users\Utente\.vscode\extensions\james-yu.latex-workshop-5.10.0\out\src\providers\structure.js:48:28)
	at context.subscriptions.push.vscode.workspace.onDidSaveTextDocument (C:\Users\Utente\.vscode\extensions\james-yu.latex-workshop-5.10.0\out\src\main.js:126:45)
	at e.fire (c:\Program Files (x86)\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at e.$acceptModelSaved (c:\Program Files (x86)\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:741:914)
	at e._doInvokeHandler (c:\Program Files (x86)\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:309)
	at e._invokeHandler (c:\Program Files (x86)\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:27)
	at e._receiveRequest (c:\Program Files (x86)\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:802)
	at e._receiveOneMessage (c:\Program Files (x86)\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:993)
	at c:\Program Files (x86)\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
	at c:\Program Files (x86)\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
	at e.fire (c:\Program Files (x86)\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at a (c:\Program Files (x86)\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
	at Socket._socketDataListener (c:\Program Files (x86)\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by James-Yu** [comment]
Quite useful. Will look into it soon.

**Comment by Xunnamius** [comment]
I'm still experiencing this error from time to time.

**Comment by tamuratak** [comment]
Please open a new issue filling out all the information required in the issue template.
