### ISSUE TITLE
[Bug?] Completions not active.

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#840]
### Log messages

<details>
<summary>LaTeX Workshop Output</summary>
[08:36:22] Initializing LaTeX Workshop.
[08:36:22] Creating LaTeX Workshop http and websocket server.
[08:36:22] LaTeX Workshop initialized.
[08:36:22] Linter for root file started.
[08:36:23] Found root file from active editor: c:\redacted\file.tex
[08:36:23] Root file changed from: undefined. Find all dependencies.
[08:36:23] Instatiating new file watcher for c:\redacted\file.tex
[08:36:23] Parsing c:\redacted\file.tex
[08:36:23] Server created on 127.0.0.1:6971
[08:36:23] LaTeX Workshop version: 5.10.2
[08:36:23] Error reading data: SyntaxError: Unexpected token } in JSON at position 11370.
[08:36:23] Parsing c:\redacted\file.tex for outline
[08:37:10] Parsing c:\redacted\file.tex for outline
[08:37:13] Found root file from active editor: c:\redacted\file.tex
[08:37:13] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:13] Found root file from active editor: c:\redacted\file.tex
[08:37:13] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:14] Found root file from active editor: c:\redacted\file.tex
[08:37:14] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:14] Found root file from active editor: c:\redacted\file.tex
[08:37:14] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:14] Found root file from active editor: c:\redacted\file.tex
[08:37:14] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:14] Parsing c:\redacted\file.tex for outline
[08:37:14] Parsing c:\redacted\file.tex for outline
[08:37:15] Linter for active file started.
[08:37:15] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[08:37:15] Found root file from active editor: c:\redacted\file.tex
[08:37:15] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:15] Parsing c:\redacted\file.tex for outline
[08:37:15] Linter for active file successfully finished in 0s 414ms
[08:37:15] Linter log parsed with 117 messages.
[08:37:15] Linter for active file started.
[08:37:15] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[08:37:15] Linter for active file successfully finished in 0s 376ms
[08:37:15] Linter log parsed with 117 messages.
[08:37:16] VIEW command invoked.
[08:37:16] Found root file from active editor: c:\redacted\file.tex
[08:37:16] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:16] No PDF viewer connected for c:\redacted\MATH1012 Notes.pdf
[08:37:16] Serving PDF file at http://127.0.0.1:6971/viewer.html?file=/pdf:c%253A%255CUsers%255CTEC%255CGoogle%2520Drive%2520(tecosaur%2540gmail.com)%255CTEC%255CUWA%2520Notes%255CMathematics%255CMATH1012%255CMATH1012%2520Notes.pdf
[08:37:16] Open PDF tab for c:\redacted\MATH1012 Notes.pdf
[08:37:18] Preview PDF file: c:\redacted\MATH1012 Notes.pdf
[08:37:20] Parsing c:\redacted\file.tex for outline
[08:37:20] SYNCTEX command invoked.
[08:37:20] Found root file from active editor: c:\redacted\file.tex
[08:37:20] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:20] Executing synctex with args view,-i,1638:14:c:\redacted\file.tex,-o,c:\redacted\MATH1012 Notes.pdf
[08:37:21] Try to synctex c:\redacted\MATH1012 Notes.pdf
[08:37:31] Found root file from active editor: c:\redacted\file.tex
[08:37:31] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:31] Found root file from active editor: c:\redacted\file.tex
[08:37:31] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:31] Found root file from active editor: c:\redacted\file.tex
[08:37:31] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:31] Parsing c:\redacted\file.tex for outline
[08:37:31] Found root file from active editor: c:\redacted\file.tex
[08:37:31] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:31] Parsing c:\redacted\file.tex for outline
[08:37:32] Linter for active file started.
[08:37:32] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[08:37:32] Found root file from active editor: c:\redacted\file.tex
[08:37:32] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:32] Parsing c:\redacted\file.tex for outline
[08:37:32] Found root file from active editor: c:\redacted\file.tex
[08:37:32] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:32] Linter for active file successfully finished in 0s 484ms
[08:37:32] Linter log parsed with 117 messages.
[08:37:32] Found root file from active editor: c:\redacted\file.tex
[08:37:32] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:32] Parsing c:\redacted\file.tex for outline
[08:37:33] Found root file from active editor: c:\redacted\file.tex
[08:37:33] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:33] Found root file from active editor: c:\redacted\file.tex
[08:37:33] Root file remains unchanged from: c:\redacted\file.tex.
[08:37:33] Parsing c:\redacted\file.tex for outline
[08:37:33] Parsing c:\redacted\file.tex for outline
[08:37:33] Linter for active file started.
[08:37:33] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[08:37:33] Linter for active file successfully finished in 0s 376ms
[08:37:33] Linter log parsed with 117 messages.
[08:37:38] Parsing c:\redacted\file.tex for outline
[08:43:45] Linter for active file started.
[08:43:45] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[08:43:45] Linter for active file successfully finished in 0s 422ms
[08:43:45] Linter log parsed with 117 messages.
[08:43:48] Linter for active file started.
[08:43:48] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[08:43:48] Linter for active file successfully finished in 0s 389ms
[08:43:48] Linter log parsed with 117 messages.
[08:44:11] Linter for active file started.
[08:44:11] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[08:44:11] Linter for active file started.
[08:44:11] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[08:44:11] Linter for active file failed with exit code null and error:
[08:47:18] Linter log parsed with 0 messages.
[08:47:18] Parsing c:\redacted\file.tex for outline
[08:47:18] Linter for active file successfully finished in 0s 423ms
[08:47:18] Linter log parsed with 117 messages.
</details>

<details>
<summary>Developer Tools Console</summary>

```javascript
[Extension Host] Found no documents
2webviewElement.ts:130 [Embedded Page] #document_outline is undefined.
2webviewElement.ts:130 [Embedded Page] #document_outline_label is undefined.
2webviewElement.ts:130 [Embedded Page] #page is undefined.
2webviewElement.ts:130 [Embedded Page] #print_progress_message is undefined.
2webviewElement.ts:130 [Embedded Page] #print_progress_percent is undefined.
2webviewElement.ts:130 [Embedded Page] #print_progress_close is undefined.
2webviewElement.ts:130 [Embedded Page] #of_pages is undefined.
webviewElement.ts:130 [Embedded Page] PDF 64aeb4b153c84209813790a2540d0dd3 [1.5 pdfTeX-1.40.19 / LaTeX with hyperref package] (PDF.js: 1.10.97)
log.ts:171   ERR Cannot read property 'hasOwnProperty' of undefined: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Promise (C:\Users\TEC\.vscode\extensions\james-yu.latex-workshop-5.10.2\out\src\providers\completion.js:47:46)
    at new Promise (<anonymous>)
    at Completer.provideCompletionItems (C:\Users\TEC\.vscode\extensions\james-yu.latex-workshop-5.10.2\out\src\providers\completion.js:40:16)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:755:678
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:466
    at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:86:460)
    at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:431)
    at e.provideCompletionItems (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:755:632)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:767:852
    at e._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:91)
    at e.$provideCompletionItems (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:767:814)
    at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:309)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:27)
    at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:802)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:993)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
    at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
    at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```
</details>

### How to reproduce

To be honest, I'm not quite sure how to reproduce, this just started happening all or a sudden for no apparent reason.

### Expected behavior

Things like `\centre`, `\begin` etc. should have associated completion items.

### Actual behavior

They don't
![image](https://user-images.githubusercontent.com/20903656/46384283-a43ce780-c6e7-11e8-8aa8-c86b4d7d19fb.png)
_suggested text from vs codes default sugestions_

### Additional Information

Tried:
 - Disabling All Extensions
 - Uninstalling This Extension
 - Reload vs code
 - Re-Installing this extension
 - Reload vs code
Same behaviour.

**Comment by tecosaur** [comment]
Update: I reinstalled VS Code, which seems to have fixed it. I'll leave this here though since I've no idea what went wrong.
